### ISSUE TITLE
Error Strict Notice: Non-static method

### ISSUE THREAD

**Issue by lucianoalbis** [stavarengo/php-sigep#100]
Olá,

alguém já passou por esse erro?

Strict Notice: Non-static method PhpSigep\Services\SoapClient\Real::solicitaEtiquetas() should not be called statically, assuming $this from incompatible context  in ...

Obs: O estranho é que somente as vezes ocorre o erro, o sistema já está em produção e rodando bacana, porém algumas vezes ele trava.

att,

**Comment by stavarengo** [comment]
@lucianoalbis conseguiu resolver?
