### ISSUE TITLE
Guia Técnico Correios

### ISSUE THREAD

**Issue by IuryChristmas** [stavarengo/php-sigep#101]
![etiqueta correios](https://cloud.githubusercontent.com/assets/11336127/21776922/8d418a6c-d67b-11e6-9669-98f1ce6ebdac.jpg)

Boa tarde galera, recentemente topei na internet com um guia técnico que os correios liberaram com recomendações para a criação das etiquetas, essa da imagem é o exemplo da etiqueta 4 rótulos por folha, andei olhando a etiqueta gerada pelo phpsigep e vi que ela possuí algumas diferenças, acham que pode dar algum tipo de problema futuramente não seguir as recomendações? Caso tenham curiosidade, vou anexar o guia de onde retirei a imagem.

[Guia Tecnico - Embalagens RPC_v1.1.pdf](https://github.com/stavarengo/php-sigep/files/694259/Guia.Tecnico.-.Embalagens.RPC_v1.1.pdf)

**Comment by andersonls** [comment]
@IuryChristmas Acho difícil que se a etiqueta esteja fora do padrão gere problemas. No pior dos casos não vai passar nas máquinas de triagem deles e o processamento vai ser manual.

Comigo quando implantei o webservice aconteceu até do pessoal da agência da minha cidade pedir para colocar informação a mais que não estava no modelo padrão da etiqueta.

Outro problema é que eles não tem um mecanismo de divulgar essas alterações de layout para os clientes, esse que você achou provavelmente fizeram para algum evento dos correios com alguns clientes e ficou por aí.

Levante a mão quem aqui já recebeu alguma notificação dos correios de alteração de layout ou até alteração do webservice hehe

**Comment by IuryChristmas** [comment]
Ok, sendo assim vou fechar aqui a issue... Obrigado @andersonls
