### ISSUE TITLE
Problema para obter serviçoes disponíveis

### ISSUE THREAD

**Issue by davidalves1** [stavarengo/php-sigep#104]
Boa tarde. Estou passando o dados do contrato para obter os serviços disponíveis no ambiente de produção, porém a sincronização não funciona. Com o usuário de teste no ambiente de homologação está funcionando. Alguém está passando por esse problema?

**Comment by stavarengo** [comment]
@davidalves1 nos passe mais informações, como por exemplo, o erro que acontece quando a requisição falha.
