### ISSUE TITLE
Gerar vários itens em uma unica PLP

### ISSUE THREAD

**Issue by tarcisiotr** [stavarengo/php-sigep#108]
Não estou conseguindo o parâmetro certo para gerar a PLP para vários pedidos, com uma unidade funciona normal.

Eu ja tentei alterar diversos itens porem, não funciona. tem algum macete para isto ? ou melo menos um XML exemplo para eu me basear?

Obrigado

**Comment by IuryChristmas** [comment]
$bootstrap = new \PhpSigep\Bootstrap();

            $bootstrap::start($this->getConfig());
            //$logofile = 'media/logo-etiqueta.png';
            $objetoPostal = array();

            foreach ($dados as $dado) {
                $objetoPostal[] = $this->getObjetoPostal($dado);
            }

            $plp = $this->getPreListaPostagem($this->getAccessData(), $objetoPostal);
            $pdf = new \PhpSigep\Pdf\ListaDePostagem($plp, $idPlp);

            $pdf->render();

pra gerar vários itens, eu fiz algo mais ou menos assim, onde o getObjetoPostal() é onde monto a estrutura que ele pede, informando dados do destinatário, peso, dimensões do objeto, essas coisas

**Comment by tarcisiotr** [comment]
Eu fiz algum semelhante mas ele esta pedindo para alterar o arquivo FecharPreListaDePostagem.php esta dizendo que estou enviando mais de um argumento. Esse arquivo ja esta preparado para mais de um pedido ou eu to fazendo coisa errada? 

Estou enviando isto: levar em consideração que estou apenas replicando o pedido ao invés de mandar um item diferente.


$encomendas = array();
        $pedidos = 0;

        while($pedidos < 3){
            
        $encomenda = new \PhpSigep\Model\ObjetoPostal();
        $encomenda->setServicosAdicionais($cdServicosAdicionais);
        $encomenda->setDestinatario($destinatario);
        $encomenda->setDestino($destino);
        $encomenda->setDimensao($dimensao);
        $encomenda->setEtiqueta($etiquetasSemDv[0]);
        $encomenda->setPeso($peso);
        $encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem($cdServicoDePostagem));

         $encomenda = new \PhpSigep\Model\ObjetoPostal();

        $encomenda->setServicosAdicionais($cdServicosAdicionais);
        $encomenda->setDestinatario($destinatario);
        $encomenda->setDestino($destino);
        $encomenda->setDimensao($dimensao);
        $encomenda->setEtiqueta($etiquetasSemDv[0]);
        $encomenda->setPeso($peso);
        $encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem($cdServicoDePostagem));

        
        $pedidos = $pedidos + 1;
        $encomendas[] = $encomenda;
        }

**Comment by IuryChristmas** [comment]
Certo, primeiro... Por que você tá instanciando duas vezes o ObjetoPostal? Uma única vez bastaria, como ele está dentro do while você sempre vai criar um novo objeto na próxima iteração, mas caso seja preciso instanciar duas vezes, troca a variável, porque dessa forma eu acredito que a última vai sobrescrever a primeira e no fim vai ter só um item.
Quanto ao erro de FecharPreListaDePostagem, faz o seguinte... Testa primeiro só ele e vê se retornar o id da plp e também testa separado o de imprimir a plp e coloca como id da plp, um número qualquer só pra tu testar mesmo, se o FecharPreListaDePostagem retornar o id da plp, então ele tá funcionando correto e você tá passando os parâmetros certo, e testando a impressão separada, você já vai descobrindo se passou alguma coisa que não deveria e não perde tempo, precisando consultar o ws dos correios pra ele te retornar um id, gera um id você mesmo só pra ficar testando, usa a função time() ou gera um número aleatório.
