### ISSUE TITLE
Download das Etiquetas

### ISSUE THREAD

**Issue by IuryChristmas** [stavarengo/php-sigep#110]
Fala galera, seguinte... Consigo gerar as etiquetas pro browser desktop sem problema, ela aparece em outra página pra visualização e lá ele pode fazer o download ou imprimir como desejar, mas quando tento fazer no mobile, não funciona... Ele abre uma nova aba, mas informa que o navegador não permite a visualização do pdf, pensei então em forçar o download, notei que no método $pdf->render();
posso passar dois parâmetros, o nome da etiqueta e uma letra que não sei o significado: $pdf->render('F', 'etiquetas.pdf')
Ele faz o download, mas ele salva direto na minha pasta html e queria que ele perguntasse o local de download, como posso fazer isso? Já existe uma maneira implementada de se fazer?

**Comment by stavarengo** [comment]
@IuryChristmas Isso não é algo específico do celular?

**Comment by IuryChristmas** [comment]
@stavarengo sim, no caso o problema só ocorre no celular, a ideia que me deram seria no momento do clique, forçar o navegador a fazer o download, mas aceito sugestões rs

**Comment by andersonls** [comment]
@IuryChristmas o método $pdf->render simplesmente repassa os parâmetros para o fpdf. O significado da letra são os seguintes (não lembro se todas estão tratadas no método render:

I: Mostra o pdf no navegador (se não suportar deve fazer download)
D: Força o download
F: Salva em arquivo
S: Retorna em string

Sobre salvar direto ou mostrar a janela pedindo onde salvar é configuração do navegador, acho que não tem o que fazer do lado PHP com relação a isso.

**Comment by IuryChristmas** [comment]
@andersonls obrigado cara, consegui forçar o download, mas o arquivo corrompe no celular quando realiza o download, é como se ele não baixasse o arquivo todo... Vou tentar resolver isso, fazer alguns testes e ver se resolvo isso. Vou tentar salvar o arquivo no servidor mesmo e depois realizar o download pra ver se ele consegue fazer isso sem corromper.

**Comment by andersonls** [comment]
@IuryChristmas Nesse ponto não posso ajudar, pq não trabalho com mobile. Mas por curiosidade, qual o motivo de baixar no celular? Você tem alguma aplicação pra isso (tipo ele imprime pelo celular) ou é sõ pra vizualização mesmo?

**Comment by IuryChristmas** [comment]
@andersonls é só pra visualização mesmo, meu chefe havia testado a visualização no smartphone dele e não funcionou, eu testei então no meu e no de outro desenvolvedor aqui e também não funcionou.
