### ISSUE TITLE
Como imprimir 4 etiquetas na mesma pagina

### ISSUE THREAD

**Issue by mozgbrasil** [stavarengo/php-sigep#111]
Ola

Boa Noite meus amigos

Tenho a necessidade de imprimir 4 etiquetas na mesma pagina

Cheguei a ler esse mesmo questionamento em

https://github.com/stavarengo/php-sigep/issues/63

https://github.com/stavarengo/php-sigep/issues/47

Que é informado para configurar na hora da impressão para imprimir X páginas por folha

Veja nas imagens a seguir que no processo para impressão não tenho essa possibilidade

![captura de tela de 2017-02-10 20-13-03](https://cloud.githubusercontent.com/assets/17202780/22846170/5f2359b0-efcd-11e6-8658-d39eb31b8ba5.png)
![captura de tela de 2017-02-10 20-13-05](https://cloud.githubusercontent.com/assets/17202780/22846172/5f4a5290-efcd-11e6-81b7-239258d66a40.png)
![captura de tela de 2017-02-10 20-13-07](https://cloud.githubusercontent.com/assets/17202780/22846173/5f645f96-efcd-11e6-9181-d0a303bb352d.png)

Efetuando pesquisa pelo termo "imprimir varias folhas por pagina"

Encontrei o seguinte documento do Acrobat Reader, mencionando esse recurso

https://helpx.adobe.com/pt/acrobat/kb/print-multiple-pages-per-sheet.html

Como é nativo do Ubuntu o leitor de PDF Evince é provável que o mesmo não tenha esse recurso

Acabo de instalar o Adobe Acrobat e vemos que temos essa possibilidade conforme a documentação do Acrobat, conforme imagem

![captura de tela de 2017-02-10 21-14-49](https://cloud.githubusercontent.com/assets/17202780/22847732/2d26630e-efd6-11e6-97f4-a8e0b7274d26.png)

**Comment by andersonls** [comment]
Boa noite @mozgbrasil, eu estou fazendo da seguinte forma

    $pdf = new \Sigep\PDF\ImprovedFPDF('P', 'mm', 'Letter' );
    
    $pageCount = $pdf->setSourceFile($fileName);
    
    $pdf->AddPage();
    $pdf->SetFillColor(0,0,0);
    $pdf->SetFont('Arial','B',16);
    
    for($i=1;$i<=$pageCount;$i++) {
        $tplIdx = $pdf->importPage($i, '/MediaBox');
    
        $mod = $i % 4;
    
        switch ($mod) {
            case 0:
                //A4: 210(x) × 297(y)
                //Letter: 216 (x) × 279 (y)
                $pdf->useTemplate($tplIdx, 110, 145, 105, 138, true);
    
                if ($i !== $pageCount) {
                    $pdf->AddPage();
                    $pdf->SetFillColor(0,0,0);
                    $pdf->SetFont('Arial','B',16);
                }
                break;
            case 1:
                $pdf->useTemplate($tplIdx, 10, 10, 105, 138, true);
                break;
            case 2:
                $pdf->useTemplate($tplIdx, 110, 10, 105, 138, true);
                break;
            case 3:
                $pdf->useTemplate($tplIdx, 10, 145, 105, 138, true);
                break;
        }
    
    }

Onde $fileName é o nome do arquivo com as etiquetas, uma por página (você precisa salvar em arquivo). Se tiver mais de um arquivo é só repetir o trecho de código.

Pra usar isso você precisa da biblioteca [FPDI](https://www.setasign.com/products/fpdi/about/) e alterar a tua classe \Sigep\PDF\ImprovedFPDF faz extender a FPDI ao invés da FPDF (a FPDI extende a FPDF e apenas adiociona alguns recursos a mais como esse).

**Comment by mozgbrasil** [comment]
Boa Noite @andersonls

Muito obrigado pela contribuição

**Comment by IuryChristmas** [comment]
Boa tarde @andersonls fiquei com dúvida no código, mais precisamente onde devo colocar ele... Esse trecho teria de ser inserido após o arquivo ter sido gerado pelo método _render ou devo colocar isso direto na classe ImprovedFPDF e lá criar um método que execute o código?

**Comment by andersonls** [comment]
@IuryChristmas Agora que você mencionou, pode não ser uma má idéia colocar dentro da classe ImprovedFPDF, se o @stavarengo gostar da idéia podemos fazer um método alternativo que já retorna nesse template de 4 etiquetas por página.

No meu caso, como eu uso isso pra outras coisas, eu fiz em uma classe separada para não ter código duplicado. Nesse caso você pode fazer da seguinte forma:

// ... Codigo para gerar as etiquetas

$fileName = 'exemplo.pdf';
$improvedFpdf->render($fileName, 'F'); //Salva em arquivo

// ... Codigo o trecho de código do outro comentário

**Comment by stavarengo** [comment]
Por mim tudo bem.

**Comment by jdgrieco** [comment]
+1

**Comment by IuryChristmas** [comment]
Só passando pra avisar que consegui fazer o lance com as 4 etiquetas por folha @andersonls e se eu tiver um tempinho nesse final de semana, posso tentar fazer esse lance de colocar pra ele imprimir nesse template de 4 etiquetas... Acho que seria válido também, tentar criar um de 6 por folha... Meu cliente falou que é bem comum eles usarem pra imprimir 6 etiquetas de uma vez na mesma folha.

**Comment by andersonls** [comment]
Legal @IuryChristmas, se você conseguir fazer um PR com isso eu agradeço, aqui tá um pouco corrido e eu to tentando começar um projetinho pra imprimir as etiquetas em impressoras de etiquetas (Zebra, Bematech, etc).

**Comment by dehdocs** [comment]
@andersonls eu fiz um pull com as informações acima muito obrigado pela dica.. vai ajudar muita gente!
👍

**Comment by gustvao** [comment]
@andersonls conseguiu fazer funcionar em zebra?

**Comment by andersonls** [comment]
@gustvao Não tive tempo nem inspiração ainda.

**Comment by gustvao** [comment]
@IuryChristmas deu certo o PR?
