### ISSUE TITLE
Código CEPNet (Postnet)

### ISSUE THREAD

**Issue by carlosfilho88** [stavarengo/php-sigep#112]
Segundo [esse manual dos Correios](https://www.correios.com.br/para-sua-empresa/servicos-para-o-seu-contrato/guias/enderecamento/enderecamento-de-correspondencias/arquivos/Guia_Tnico_CepNet_e_2D_Triagem_Endereamento_20_04_16.pdf
), é possível gerar códigos no formato CEPNet para padronizar a leitura de CEPs nas máquinas deles, alguém já viu ou implementou essa solução em qualquer linguagem?

**Comment by carlosfilho88** [comment]
Encontrei a resposta, a classe Zend_Barcode_Object_Postnet já faz isso.

**Comment by stavarengo** [comment]
Pode fechar o issue?

**Comment by carlosfilho88** [comment]
Sim @stavarengo, por favor.
