### ISSUE TITLE
Gerar Etiqueta sem correios

### ISSUE THREAD

**Issue by danilopimenta** [stavarengo/php-sigep#116]
É possível utilizar o modulo de Etiqueta sem o contrato dos Correios?

**Comment by andersonls** [comment]
Atualmente não. Como seria o layout da etiqueta que você quer gerar?

Sem o contrato e integração com os correios ficaria somente a parte dos endereços conforme a imagem abaixo.
![screenshot from 2017-03-30 08 43 42](https://cloud.githubusercontent.com/assets/1561038/24502628/0c72842a-1525-11e7-9e57-83248a2a29e2.png)

**Comment by stavarengo** [comment]
@andersonls se tiver tudo ok, feche o issue por favor.

**Comment by danilopimenta** [comment]
Bom, obrigado pelo feedback, a princípio não utilizarei a lib, irei gerar o pdf da etiqueta manualmente
