### ISSUE TITLE
PHPSigep Erros Diversos [Laravel]

### ISSUE THREAD

**Issue by pedro-santiago** [stavarengo/php-sigep#120]
Pessoal. Tô tendo um monte de erro pra inserir a biblioteca num projeto de um cliente. Tô consertando um a um e devo subir um PR pra aprovação. 

O caso é que como são muitas modificações, será que vale a pena criar um projeto wrapper e colocar essa lib como dependency ou daria pra colocar alguns arquivos direto nela, e assim facilitar a vida de quem usa o Laravel.

E também, se alguém já portou isso aqui pra Laravel, dá o ar da graça aí pq né?
Abs

**Comment by stavarengo** [comment]
Oi @pedro-santiago . 
Eu sou fã da reutilização de códigos, então a ideia de ter um wrapper não me parece legal, pois nesse caso teríamos dois repositórios e isso pode confundir novos usuários da biblioteca.

Alem disso, ter dois repositórios sempre causa um delay de atualização entre um e outro, ou seja, um grupo dos nossos usuários teriam a versão mais nova em quanto que o outro grupo ainda teria que esperar até que o repositórios que ele usam seja atualizado tbm.

Explica  com um pouco mais de detalhes o que vc está alterando e porque. Assim podemos tentar te ajudar a encontrar uma saída.

**Comment by pedro-santiago** [comment]
Boa! Seria massa se a gente fizesse funcionar ;) Minhas alterações seriam:

- Adicionar uma Facade pro Sigep em geral, abstraindo as funções pra métodos simples, mas que por debaixo dos panos ainda fizessem uso de todos os métodos anteriores, porém portados para a síntaxe do Laravel.
- Migrar todas as configurações possíveis para um arquivo separado, de forma que ao rodar o `php artisan vendor:publish` tenhamos um arquivo `sigep.php` com um array de configurações e parâmetros.
- No FPDF, o primeiro método construtor é uma função com o mesmo nome da classe. No PHP 7+ isso foi removido, então precisaremos trocar por __construct() **(sooner or later)**
- Os métodos para render() da PLP e da lista de etiquetas poderiam ter a mesma síntaxe, aceitar talvez os mesmos parâmetros, pra facilitar o entendimento.
- Criar um ServiceProvider pra instanciar as configurações, de modo que ao chamarmos a Facade `Sigep`, consigamos instanciar o AccessData e o ambiente necessário.
- Adicionar instruções no Readme e Documentar.

Tentei ser pontual, mas queria ver se isso de alguma forma ajudaria outros usuários, portanto antes de botar a mão na massa queria abrir o tópico pra discussão.
Abraços!

**Comment by stavarengo** [comment]
Vamos lá @pedro-santiago. Segue minhas considerações na ordem em que vc listou.

Já vou adiantar que curti todas as ideias, com uma única ressalva: retro-compatibilidade. Seja lá o que a gente escolher fazer, não podemos quebrar a compatibilidade com as versões anteriores.

1. **_Adicionar uma Facade pro Sigep em geral_**   
Acho ótimo. Se você não tiver nada contra, vamos usar a [PSR-11](https://github.com/php-fig/container) para isso. Todos os maiores frameworks e bibliotecas usam ela.

2. **_Migrar todas as configurações possíveis para um arquivo separado_**   
Na verdade tive a impressão que esta tarefa é uma consequência da tarefa 1. Para não quebrar a compatibilidade acho que devemos continuar usando a classe [`PhpSigep\Config`], ou seja, a gente cria sim o arquivo de configuração, mas internamente o PhpSigep instância uma [`PhpSigep\Config`] com as configurações que ele encontrar nos arquivos.

3. **_No FPDF, o primeiro método construtor é uma função com o mesmo nome da classe_**   
Está valendo, desde não quebre a compatibilidade com os nosso usuários que já usam a PHPSigep.

4. **_Os métodos para render() da PLP e da lista de etiquetas poderiam ter a mesma síntaxe_**   
Essa não entendi. Eles já não são iguais hoje? De qualquer maneira, acho que vale criar uma `interface` para as classes de relatórios sim.

5. **_Criar um ServiceProvider pra instanciar as configurações_**   
Acho que esta tarefa é uma consequência das tarefas 1 e 2. Eu sugiro que o [`\PhpSigep\Model\AccessData`] tenha sua própria factory configurada no container de serviços. Para isso o [`\PhpSigep\Model\AccessData`] iria precisar de uma `interface`, como já é feito com qualquer serviço que esteja disponível no container de serviços.

6. **_Adicionar instruções no Readme e Documentar_**    
Essa é parte mais bonita de todas e eu posso ajudar aqui :grinning:

Agora uma sugestão minha: que a gente passe usar a [PSR-3](https://github.com/php-fig/log) para mensagens de log.


[`PhpSigep\Config`]: https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Config.php
[`\PhpSigep\Model\AccessData`]: https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Model/AccessData.php

**Comment by stavarengo** [comment]
@pedro-santiago ?

**Comment by dehdocs** [comment]
estou usando a library no laravel há alguns meses até o momento sem problema nenhum, apenas importei via composer e utilizo os metodos puxando tudo pelos namespaces. 

Não sei se é a melhor maneira de utiliza-lo por lá, mais funciona perfeitamente!

**Comment by stavarengo** [comment]
Fechando pq @pedro-santiago parou de responder :(
