### ISSUE TITLE
Versionamento dos pull requests

### ISSUE THREAD

**Issue by willian-rosa** [stavarengo/php-sigep#121]
Pessoal precisamos controlar os pull requests com versões, sei que mais burocrático mas essencial para o projeto. E com isso controlar a versão no packagist.

Falo isso porque deu problema, nosso servidor de produção, na geração de pdf por causa das ultimas atualizações feitas recentemente. Por tanto é muito mais rápido voltar uma versão no composer.json do que o processo de pull request.

**Comment by stavarengo** [comment]
@willian-rosa concordo. Começarei a fazer isso a partir de agora.
