### ISSUE TITLE
Fatal error: Class 'FPDF' not found in vendor/setasign/fpdi/fpdi_bridge.php on line 24

### ISSUE THREAD

**Issue by mozgbrasil** [stavarengo/php-sigep#122]
Ola

Boa Tarde

Veja que ao editar o arquivo 

/vendor/stavarengo/php-sigep/exemplos/bootstrap-exemplos.php

e comentar o trecho 

	/*if (!class_exists('PhpSigepFPDF')) {
	    throw new RuntimeException(
	        'Não encontrei a classe PhpSigepFPDF. Execute "php composer.phar install" ou baixe o projeto ' .
	        'https://github.com/stavarengo/php-sigep-fpdf manualmente e adicione a classe no seu path.'
	    );
	}*/

é exibido o erro

Fatal error: Class 'FPDF' not found in vendor/setasign/fpdi/fpdi_bridge.php on line 24

Alguém sabe informar o motivo do disparo desse erro

Esse erro começou a ser disparado após o commit https://github.com/stavarengo/php-sigep/commit/6062794fb069ef8e6c89fb0a5315d6b583e912fc 

http://imgur.com/a/Us9dt

**Comment by stavarengo** [comment]
@dehdocs consegue ajudar a gente nessa?
Precisamos mesmo deste setasign/fpdi?

**Comment by andersonls** [comment]
@stavarengo @mozgbrasil Essa alteração foi referente a issue #111. Pra solução que eu postei lá funcionar é necessário a classe FPDI.

Olhando o commit agora, acho que o correto seria:

1. Manter  class ImprovedFPDF extends \PhpSigepFPDF (em src/PhpSigep/Pdf/ImprovedFPDF.php )
2. Retirar "setasign/fpdi": "1.6.1" (em composer.json)
3. No repositório php-sigep-fpdf incluir os arquivos da biblioteca FPDI e alterar o arquivo PhpSigepFPDF.php para:

require_once \_\_DIR__ . '/fpdi.php';

class PhpSigepFPDF extends FPDI
{
}

Alguém consegue testar se essas alterações resolvem o problema?

**Comment by stavarengo** [comment]
@andersonls consegue corrigir e subir pra gente?

**Comment by andersonls** [comment]
@stavarengo Feito! Fiz um PR no php-sigep-pdf também.

**Comment by GlauberMosche** [comment]
Bom dia

Estou com o seguinte erro, podem me ajudar?

Fatal error: Uncaught RuntimeException: Não encontrei a classe PhpSigepFPDF.

**Comment by relpcam** [comment]
Também estou tendo o mesmo problema

**Comment by igassis** [comment]
Fatal error: Uncaught Error: Class 'FPDF' not found  Tambem estou com o mesmo problema

**Comment by relpcam** [comment]
> Fatal error: Uncaught Error: Class 'FPDF' not found Tambem estou com o mesmo problema

@igassis  você está tendo esse no momento de gerar um etiqueta? Caso sim, tente incluir essa linha

require __DIR__ . '/src/php-sigep-fpdf/fpdf.php';
