### ISSUE TITLE
Warning: include(PhpSigep\Pdf\ImprovedFPDF.php): failed to open stream: No such file or directory  in magento-1.9.3.1-dev34/root/lib/Varien/Autoload.php on line 94

### ISSUE THREAD

**Issue by mozgbrasil** [stavarengo/php-sigep#123]
Ola

Boa Tarde

Após o commit https://github.com/stavarengo/php-sigep/commit/6062794fb069ef8e6c89fb0a5315d6b583e912fc

Começou a ser disparado o seguinte erro no Magento 

	Warning: include(PhpSigep\Pdf\ImprovedFPDF.php): failed to open stream: No such file or directory  in magento-1.9.3.1-dev34/root/lib/Varien/Autoload.php on line 94

Vejo que foi editado o arquivo

/vendor/stavarengo/php-sigep/src/PhpSigep/Pdf/ImprovedFPDF.php

Para

	class ImprovedFPDF extends \FPDI

Caso eu retorne para o modelo que estava há 8 dias atras funciona

	class ImprovedFPDF extends \PhpSigepFPDF

Alguém sabe informar o motivo do disparo desse erro

http://imgur.com/a/KBw3c

**Comment by mozgbrasil** [comment]
Ola 

Boa Tarde

@dehdocs consegue ajudar a gente nessa?

Precisamos mesmo deste setasign/fpdi?

Após essa alteração já relatei 2 erros

**Comment by andersonls** [comment]
Coloquei a resposta na issue #122.

**Comment by stavarengo** [comment]
@mozgbrasil se tiver tudo ok, fecha esse issue por favor.
