### ISSUE TITLE
Remover codigo de rastreio

### ISSUE THREAD

**Issue by gheeenrique** [stavarengo/php-sigep#124]
Olá, gostaria de remover o código de rastreio do pdf para criar etiquetas, existe algum lugar do código que eu removo para não gerar o pdf com o código de rastreio?
Uma segunda dúvida, eu consigo salvar o código de rastreio no banco de dados? Alguém tem alguma ideia de como fazer? Obrigado!

**Comment by andersonls** [comment]
Sem fazer alterações no código não é possível. 

Para salvar as etiquetas no BD é do lado da tua aplicação, a biblioteca não trabalha com BD. Você pode ver em exemplos/solicitarEtiquetas.php como solicitar os códigos de rastreios.

**Comment by gheeenrique** [comment]
@andersonls consegui resolver, muito obrigado pela ajuda, adaptei meu código ao sigep.
Agora estou com o seguinte erro ao tentar fazer o fechamento da plp:
Array
(
    [*isSoapFault] => 
    [*errorCode] => 
    [*errorMsg] => 
    [*result] => PhpSigep\Model\FechaPlpVariosServicosRetorno Object
        (
            [idPlp:protected] => 74389313
            [_failIfAtributeNotExiste:protected] => 1
        )

    [*soapFault] => 
    [*_failIfAtributeNotExiste] => 1
)

Alguém já passou por isso?

**Comment by stavarengo** [comment]
@gheeenrique isso não parece ser um erro. Vc conseguiu resolver aí?
