### ISSUE TITLE
Erro 'JBAS014580' ao tentar gerar a PLP

### ISSUE THREAD

**Issue by davidalves1** [stavarengo/php-sigep#125]
Bom dia. No nosso sistema a geração de PLP estava funcionando normalmente, mas recentemente começou a dar erro. Nos nossos testes encontramos o seguinte erro: 
![error_sigep](https://cloud.githubusercontent.com/assets/12610236/24657076/5f867d66-191b-11e7-975e-a636cf6f2635.jpg)
Alguém mais está passando por esse problema?

**Comment by stavarengo** [comment]
@davidalves1 não tenho ideia do que pode ser. Mas vc já procurou no manual do Correios?

**Comment by davidalves1** [comment]
Opa, realizamos vários testes aqui e foi verificado que era problema nos correios mesmo. Depois de um tempo voltou a funcionar normalmente. Obrigado.
