### ISSUE TITLE
Erro ao gerar plp

### ISSUE THREAD

**Issue by gheeenrique** [stavarengo/php-sigep#126]
Olá, quero agradecer o projeto e contribuição de todos.
Estou com seguinte erro ao fechar PLP, se eu coloco um código de rastreio que já foi fechado consigo um erro de que já existe, mas se gero uma etiqueta e coloco obtenho o seguinte erro: 
Array
(
[*isSoapFault] =>
[*errorCode] =>
[*errorMsg] =>
[*result] => PhpSigep\Model\FechaPlpVariosServicosRetorno Object
(
[idPlp:protected] => 74389313
[_failIfAtributeNotExiste:protected] => 1
)

[*soapFault] => 
[*_failIfAtributeNotExiste] => 1
)

**Comment by gheeenrique** [comment]
Aproveitando a colaboração de vocês, quando eu utilizo os código sem nenhuma modificação apenas colocando minhas credencias eu obtenho o seguinte erro:
Array
(
    [*isSoapFault] => 1
    [*errorCode] => 0
    [*errorMsg] => [SG] A etiqueta PN825215874BR está fora do padrão esperado.
    [*result] => 
    [*soapFault] => 
    [*_failIfAtributeNotExiste] => 1
)

**Comment by andersonls** [comment]
Esse erro é pq o webservice está esperando etiqueta sem DV e vc está
enviando com (ou vice versa).

**Comment by stavarengo** [comment]
deu certo @gheeenrique ?

**Comment by gheeenrique** [comment]
@stavarengo deu certo sim, muito obrigado!
Agora estou com um erro que acredito que seja o último hehe, o solicitaetiqueta está vindo mas com 8 digitos apenas... Tem algum modo que faço para receber os 9 digitos? Abraços

**Comment by andersonls** [comment]
@gheeenrique O webservice sempre vai retornar com apenas 8 digitos (sem o DV). O que você pode fazer é utilizar a classe PhpSigep\Model\Etiqueta e chamar os métodos: 

setEtiquetaSemDv($etiquetaCom8Digitos);
$etiquetaCom9Digitos = getEtiquetaComDv();

**Comment by gheeenrique** [comment]
@andersonls amigo, não entendi muito bem, tem como você colocar no código para eu vê como ficaria? 
Obrigado!

**Comment by stavarengo** [comment]
@gheeenrique tudo que vc precisa estão nestes exemplos:

- [geraDigitoVerificadorEtiquetas](https://github.com/stavarengo/php-sigep/blob/master/exemplos/geraDigitoVerificadorEtiquetas.php)
- [solicitarEtiquetas](https://github.com/stavarengo/php-sigep/blob/master/exemplos/solicitarEtiquetas.php)
