### ISSUE TITLE
Sobre modelo da etiqueta

### ISSUE THREAD

**Issue by mozgbrasil** [stavarengo/php-sigep#128]
Bom dia

Sobre a biblioteca

Vemos a diferença entre a etiqueta da biblioteca e o modelo do Correios, presente no Manual

http://www.correios.com.br/para-voce/correios-de-a-a-z/embalagens-recomendadas-pelos-correios/arquivos/GuiaTcnicoEmbalagensRPC.pdf

Enquanto na etiqueta da biblioteca usa diversas chancelas, vemos no Manual que é usado símbolos de encaminhamento de acordo com o serviço do Correios utilizado

Vejo que essa biblioteca foi iniciado em 08/2013 não sei se tem relação isso, talvez na época do desenvolvimento o formato era esse mesmo presente na biblioteca

Sabe me informar porque a etiqueta da biblioteca não tem o mesmo formato e dados conforme o modelo do Correios ?

_

Outra coisa, vejo que até o tamanho a dimensão da etiqueta é diferente, enquanto no Manual vemos que é sugerido o uso 138,11 x 106,36 mm 

Na biblioteca temos a dimensão 100 x 140

Sabe me informar porque a etiqueta da biblioteca não tem o mesmo formato e dados conforme o modelo do Correios ?

_

![captura de tela de 2017-04-05 18-07-34](https://cloud.githubusercontent.com/assets/17202780/24727492/98a8fe0e-1a2c-11e7-90ac-f4e18666617c.png)
![captura de tela de 2017-04-05 18-07-37](https://cloud.githubusercontent.com/assets/17202780/24727493/98a94918-1a2c-11e7-9920-d9834c77d6f3.png)

**Comment by mozgbrasil** [comment]
Encontrei link demonstrando o modelo da etiqueta pelo Correios

https://www.correios.com.br/para-voce/correios-de-a-a-z/embalagens-recomendadas-pelos-correios/arquivos/etiqueta-de-enderecamento-automatico-4-rotulos-por-folha-138-11-x-106-36-mm-em-pdf

**Comment by stavarengo** [comment]
@mozgbrasil [nessa página](https://github.com/stavarengo/php-sigep/tree/master/exemplos) tem exemplos com diferentes versões de etiquetas. Veja na imagem abaixo.
![image](https://cloud.githubusercontent.com/assets/816369/24729191/6e72af8e-1a33-11e7-971b-28de4f5c01ec.png)

Observer, por exemplo, que a última etiqueta de 2016 foi criada pelo @andersonls.
Caso o Correios tenha modificado o layout novamente, vamos criar uma nova versão para 2017.

**Comment by andersonls** [comment]
@mozgbrasil Como você chegou nesses link? Acho que o principal motivo de este modelo não estar na biblioteca é pq ninguém tem conhecimento dele.

Como o @stavarengo mencionou, no ano passado eu fiz um PR com uma atualização no modelo das etiquetas, pois foi o modelo que recebi dos correios quando comecei a integração. Mas depois disso nunca recebi nenhum material comentando sobre atualização do layout. Se você souber mecher com o FPDF e fizer um PR com esse layout novo, com certeza o @stavarengo vai fazer merge.

Entretanto, eu pessoalmente, não iria utilizar esse modelo por dois motivos:

1. Não tenho certeza se quem trabalha nas agências e nos centros de distribuição conhecem esse layout (principalmente os símbolos de encaminhamento, Sedex, Pac, etc).
2. Os dois maiores cases de utilização dos webservices dos correios ainda utilizam o modelo gerado no imprimirEtiquetas2016.php, que é o MercadoEnvios e o SigepWeb

O legal seria entrar em contato com alguém dos correios para saber a situação desse layout. Se foi oficializado, se já existe algum case de uso.

**Comment by mozgbrasil** [comment]
Boa Tarde

No manual em 

http://www.corporativo.correios.com.br/encomendas/sigepweb/doc/Manual_de_Implementacao_do_Web_Service_SIGEP_WEB.pdf

Temos o apontamento para

http://www.correios.com.br/para-voce/correios-de-a-a-z/embalagens-recomendadas-pelos-correios/arquivos/GuiaTcnicoEmbalagensRPC.pdf

![captura de tela de 2017-04-06 14-25-28](https://cloud.githubusercontent.com/assets/17202780/24767313/f65be234-1ad4-11e7-8af8-77c378466231.png)
![captura de tela de 2017-04-06 14-25-43](https://cloud.githubusercontent.com/assets/17202780/24767314/f65cdbe4-1ad4-11e7-94c2-4e421a3fbebf.png)

**Comment by stavarengo** [comment]
Vamos fazer esse novo modelo então. Você dá conta @mozgbrasil ?

**Comment by mozgbrasil** [comment]
Bom dia

Acho que podemos deixar em aberto esse assunto para implementação futura

Assim que eu tiver disponibilidade devo entrar em contato com o Correios para saber a situação desse layout se deve ser usado

Se alguém tiver a informação pode contribuir aqui nessa interação

**Comment by stavarengo** [comment]
Ok @mozgbrasil.
Então vou fechar o bug por enquanto. Se precisar a gente re-abre ele.
