### ISSUE TITLE
Envio plp ao correios

### ISSUE THREAD

**Issue by gheeenrique** [stavarengo/php-sigep#129]
Primeiramente, quero parabenizar a todos pelo excelente trabalho, e como faço para contribuir melhor ainda.
Em segunda oportunidade, gostaria de uma ajuda.
Fiz tudo certinho, está em modo produção fiz a mudança no AccessDataHomologacao conforme manual, coloquei os dados dos correios que eles me forneceu, o que ocorre.
Pelo sigep desktop com os mesmo dados eu consigo gerar o código de etiqueta e a plp, fazendo isso levo ao correios e eles valida tudo ok.
Pelo sigep php eu consigo gerar o código de etiquetas 9 digitos e fecho a plp que é me gerado um número com inicio 74. Mas hoje quando levei ao correios recebi o erro que o código era invalido e a plp não havia sido fechada.
Alguém já passou por isso ou sabe o que pode está havendo?
Se necessário envio o relato que o correios me passou e também como estou fechando a plp, a mensagem que apareceu.
Muito obrigado a todos e novamente parabens pelo projeto. 

**Uma dúvida**
Eu tenho que enviar a plp para o correios com o dv ou sem dv? No momento estou enviando com dv porque a mulher do correios pede o cd de rastreio, da ultima vez enviei com 8 dígitos números e ela disse está incorreto.

**Comment by stavarengo** [comment]
Oi @gheeenrique 
Essas são dúvidas muito específicas para o seu caso, por isso, fica difícil te ajudar.

Poste as informações que vc tem para ver se pode te ajudar de alguma forma.

**Comment by gheeenrique** [comment]
O correios recebe a PLP em 8 Digitos, entretanto para nós da comunidade fazemos o rastreio com 9 digitos. Consegui resolver meus problemas, por favor encerrar o chamado, obrigado.
