### ISSUE TITLE
Serviços Adicionais

### ISSUE THREAD

**Issue by gheeenrique** [stavarengo/php-sigep#130]
Olá amigos, essas ultimas semanas estou adaptando o projeto ao um sistema de e-commerce próprio, eu gostaria de saber se esse projeto tem a função AR na impressão de etiquetas, ou deve ser feito.

**Comment by stavarengo** [comment]
Oi @gheeenrique 
Bastar usar o `PhpSigep\Model\ServicoAdicional::SERVICE_AVISO_DE_RECEBIMENTO` como é exibido no exemplo [aqui](https://github.com/stavarengo/php-sigep/blob/6588f0f95bf7615cbbeb0345229cd848c32eeb51/exemplos/helper-criar-pre-lista.php#L35)
