### ISSUE TITLE
Erro ao tentar gerar etiquetas

### ISSUE THREAD

**Issue by andersom-rfd** [stavarengo/php-sigep#132]
`Parse error: Invalid numeric literal in .../vendor/stavarengo/php-sigep/src/PhpSigep/Model/ServicoDePostagem.php:31`

e

`E_COMPILE_ERROR: Cannot redefine class constant PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_CONTRATO_AGENCIA`

**Comment by andersonls** [comment]
@rasnwebdev Teu PR que gerou o erro, consegue ver pra gente?

**Comment by andersom-rfd** [comment]
Pode fechar a issue
