### ISSUE TITLE
Array puro usando metodo método toArray()

### ISSUE THREAD

**Issue by tiagobatistaa** [stavarengo/php-sigep#133]
Estou tentando fazer o result virar array puro com o meto toArray(), não estou conseguindo referenciar a classe DefaultStdClass dentro do exemplo calcPrecoPrazo.php. E mesmo colocando a função dentro desse arquivo o array me retorna sempre em branco array{}

Testei tambem usando o consultaCep = "object(PhpSigep\Services\Result)#12 (6) { ["isSoapFault":protected]=> bool(false) ["errorCode":protected]=> NULL ["errorMsg":protected]=> NULL ["result":protected]=> object(PhpSigep\Model\ConsultaCepResposta)#13 (9) { ["bairro":protected]=> string(7) "Lourdes" ["cep":protected]=> string(8) "30170010" ["cidade":protected]=> string(14) "Belo Horizonte" ["complemento1":protected]=> string(0) "" ["complemento2":protected]=> string(14) "- até 279/280" ["endereco":protected]=> string(19) "Avenida Bias Fortes" ["id":protected]=> int(0) ["uf":protected]=> string(2) "MG" ["_failIfAtributeNotExiste":protected]=> bool(true) } ["soapFault":protected]=> NULL ["_failIfAtributeNotExiste":protected]=> bool(true) } "

não consigo chamar como array sem precisar chamar por objetos  Ex. $result->getResult()[0]->getValor().

**Comment by stavarengo** [comment]
Isso eh pq `result` eh um array, certo? Pq vc não usa o `array_map`?

**Comment by tiagobatistaa** [comment]
Fiz e funcionou, vlw
