### ISSUE TITLE
Problema com os novos códigos de SEDEX e PAC

### ISSUE THREAD

**Issue by Stedile93** [stavarengo/php-sigep#136]
Olá @stavarengo, tudo bom? Primeiramente gostaria de parabenizar pelo projeto e empenho para que o mesmo esteja sempre atualizado e otimizado.

Já tenho usado em produção o php-sigep, porém, uma versão bem antiga. Agora surgiu a necessidade  de disponibilizar os novos códigos de postagem. Após quebrar um pouco a cabeça tentando adaptar a verão em produção, sem sucesso, decidi clonar a versão mais atual do projeto e fazer alguns testes. E realmente os códigos novos não funcionam rsrs, isso acontece contigo também?

( ! ) Fatal error: Uncaught exception 'PhpSigep\Model\Exception' with message 'There is no service with the code "4162".' in C:\wamp64\www\phpsigep\src\PhpSigep\Model\ServicoDePostagem.php on line 84
( ! ) PhpSigep\Model\Exception: There is no service with the code "4162". in C:\wamp64\www\phpsigep\src\PhpSigep\Model\ServicoDePostagem.php on line 84

Parece que o erro ocorre quando o código perde o "0", mas não consegui identificar o motivo.

Obs.: PHP v5.6.25

Na linha 155 do arquivo ..\Services\Real\CalcPrecoPrazo.php: 
'servico'               => new \PhpSigep\Model\ServicoDePostagem($servico->Codigo),

$servico->Codigo que pertence a $r->CalcPrecoPrazoResult->Servicos->cServico, já possui o código como inteiro novamente e sem o 0.

Não consegui identificar em que momento a string é convertida para numérico novamente.

Desde já, agradeço sua atenção!

**Comment by stavarengo** [comment]
Oi @Stedile93.
Não passe números inteiros para ele, ao inves disto passe uma das contantes da classe \PhpSigep\Model\ServicoDePostagem.
Ex: \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_CONTRATO_AGENCIA

**Comment by andersom-rfd** [comment]
@stavarengo antes do PR #135 ao usar a constante como você falou o código **04162** mudava para **2162**, acho que é devido a ser um _octal literal_. No retorno dos Correios para ele mostra: (note o **"Codigo de servico invalido."**)

```json
{"Codigo":2162,"Valor":"0","PrazoEntrega":"0","ValorMaoPropria":"0","ValorAvisoRecebimento":"0","ValorValorDeclarado":"0","EntregaDomiciliar":"","EntregaSabado":"","Erro":"001","MsgErro":"Codigo de servico invalido.","ValorSemAdicionais":"0","obsFim":""}
```

Após o PR temos o retorno com o valor do serviço:

```json
{"Codigo":4162,"Valor":"8,75","PrazoEntrega":"1","ValorMaoPropria":"0,00","ValorAvisoRecebimento":"0,00","ValorValorDeclarado":"0,00","EntregaDomiciliar":"S","EntregaSabado":"S","Erro":"0","MsgErro":"","ValorSemAdicionais":"8,75","obsFim":""}
```

Só que aí dá o erro que o @Stedile93 mencionou, porque se olhar no JSON acima os Correios retorna o código **4162** como inteiro e não **04162**.

**Comment by stavarengo** [comment]
Entendi @andersom-rfd.
Será o caso de mudar o valor de todas as constantes para int?
Se vc concorda, é fácil para vc fazer aí?

**Comment by andersom-rfd** [comment]
@stavarengo mudando para **int** não resolve, veja:

**mantendo os 5 chars**

código 04162
será enviado como 2162
vai retornar _Codigo de servico invalido_

código 04669
deve mudar para outro número também assim como o acima (no php 7 vai dar erro)
vai retornar _Codigo de servico invalido_

**removendo o 0 do início**
código 4162
vai retornar _Codigo de servico invalido_

código 4669
não testei mais deve acontecer o mesmo do 4162

Na documentação do SIGEP mostra que o código do serviço é do tipo numérico com 5 chars ou posições (00000), só que no retorno do cálculo os Correios está retornando o código do serviço como 4162 e não o 04162 que foi passado.

**Comment by andersom-rfd** [comment]
O que eu pensei @stavarengo é no construtor da classe **src/PhpSigep/Model/ServicoDePostagem.php** fazer uma modificação no código do serviço antes de validar e pegar do array $services.

```php
$serviceCode = str_pad($serviceCode, 5, 0, STR_PAD_LEFT);
```
alterado, segue com a execução

ou

```php
$paddedServiceCode = str_pad($serviceCode, 5, 0, STR_PAD_LEFT); // aceito sugestões para o nome

if (!isset(self::$services[$paddedServiceCode])) {
    throw new Exception('There is no service with the code "' . $serviceCode . '".');
}

$service = self::$services[$paddedServiceCode];
parent::__construct(
    array(
        'codigo'    => $paddedServiceCode,
        'nome'      => $service[0],
        'idServico' => $service[1],
    )
);
```
Assim o código do serviço passado se não encontrado, irá ser o mesmo na exception

**Comment by stavarengo** [comment]
Vc está certo @andersom-rfd.
Eu sugiro usar o `sprintf`, pq acho que fica uma leitura mais natural, mas, quem manda é vc :)
Como `sprintf` ficaria assim.
```php
public function __construct($serviceCode)
{
    $normalizedServiceCode = sprintf("%'05s",  $serviceCode);
    if (!isset(self::$services[$normalizedServiceCode])) {
        throw new Exception('There is no service with the code "' . $serviceCode . '".');
    }
    $service = self::$services[$normalizedServiceCode];
    parent::__construct(
        array(
            'codigo'    => $normalizedServiceCode,
            'nome'      => $service[0],
            'idServico' => $service[1],
        )
    );
}
```

**Comment by Stedile93** [comment]
Buenas @stavarengo e @andersom-rfd !!

Não consegui agradecer antes, mas era isso mesmo. Fico feliz que esse projeto conta com pessoas experientes e está sempre sendo atualizado.

Brigadão!! Abraço.

**Comment by nelsoncarvalhosf** [comment]
Comigo aqui não resolveu o problema, deu certo por ai ? Mesmo no ambiente de homologação?
