### ISSUE TITLE
Site fora do ar

### ISSUE THREAD

**Issue by insign** [stavarengo/php-sigep#139]
[Site informado](http://stavarengo.github.io/php-sigep/) na documentação está fora do ar.

**Comment by dehdocs** [comment]
@insign o site continha apenas alguns exemplos da ferramenta funcionando.

**Comment by stavarengo** [comment]
Galera eu parei de pagar este domínio uma semana atrás. O certo era comprar um domínio específico para o PHPSigep. Vamos?

**Comment by stavarengo** [comment]
Pronto. Site está de volta online.

**Comment by gerbesf** [comment]
Novamente offline.

**Comment by stavarengo** [comment]
Boa noticia.
Consegui uma hospedagem no Google Cloud.
O site de demostração está de volta online: http://stavarengo.github.io/php-sigep/.

Se quiser tbm da para rodar a demostração offline com docker, usando `docker run -p 8888:80 stavarengo/php-sigep-demo:latest` e acessar usando `http://localhost:8888`

**Comment by gustvao** [comment]
boa @stavarengo 

fui testar lá pra ver uma etiqueta e aparentemente não funcionou..

nao testei o resto, mas otima noticia o demo ter voltado,

![image](https://user-images.githubusercontent.com/5428331/35107668-b438e5b2-fc58-11e7-984b-44a5a4686e4c.png)

**Comment by stavarengo** [comment]
Valeu @gustvao 
Tudo ok agora.

**Comment by stavarengo** [comment]
To precisando de ajuda pra atualizar esta pagina de documentação.
Se você tiver um tempo, seria d+ @gustvao

**Comment by gustvao** [comment]
fala @stavarengo eu to com o tempo meio zuado também. Mas o que estou fazendo para contribuir é procurando um freela para fazer o padrão novo da etiqueta 2018, pagar por isso, e fazer o PR para ajudar a comunidade ;) te mantenho informado das novidades

**Comment by stavarengo** [comment]
: )
