### ISSUE TITLE
Erro ao tentar sincronizar novos serviços dos correios

### ISSUE THREAD

**Issue by davidalves1** [stavarengo/php-sigep#140]
Estamos com problemas ao tentar sincronizar os serviços marcados em vermelho:  

![erro_php_sigep](https://cloud.githubusercontent.com/assets/12610236/25675591/6d921008-3015-11e7-871c-b762aa468225.JPG)

A mensagem de erro segue abaixo:
```php
#[2017-05-03 14:24:24] lumen.ERROR: exception 'PhpSigep\Model\Exception' with message 'There is no service with the code "4162".' in .../vendor/stavarengo/php-sigep/src/PhpSigep/Model/ServicoDePostagem.php:84
#Stack trace:
#0 .../vendor/stavarengo/php-sigep/src/PhpSigep/Model/SolicitaEtiquetas.php(105): PhpSigep\Model\ServicoDePostagem->__construct(4162)
#1 (meu arquivo que sinvcroniza as etiquetas): PhpSigep\Model\SolicitaEtiquetas->setServicoDePostagem(4162)
#(...)
```
No banco o código está como `string`, mas realizamos o cast para `int` antes de chamar o método SolicitaEtiquetas. Pelo que analisei no model ServicoDePostagem, os dois valores estão com zero a esquerda e ao passar o valor, o mesmo está chegando no model sem o 0 a esquerda e, então, dá uma exception. Por se tratar de um `int` vale deixar esse 0 a esquerda no model?

**Comment by andersonls** [comment]
@davidalves1 Você precisa atualizar o teu código. Se olhar no repositório foi feito a alteração para string de todas as constantes da classe ServiçoDePostagem.

Como o correios adicionou esse 0 a esquerda nos novos códigos, **int** não funciona mais, precisa ser **string**

**Comment by davidalves1** [comment]
Opa, obrigado @andersonls, Verificamos aqui e essa atualização não foi baixada, pois no arquivo composer.json estava configurado para baixar sempre se um commit específico, para, assim, evitar de quebrar a aplicação em produção caso fosse executado o `composer update`.
