### ISSUE TITLE
ErrorException ao verificar propriedade que não existe no objeto

### ISSUE THREAD

**Issue by andersom-rfd** [stavarengo/php-sigep#142]
`exception 'ErrorException' with message 'Undefined property: SoapFault::$CalcPrecoPrazoResult' in .../vendor/stavarengo/php-sigep/src/PhpSigep/Services/Real/CalcPrecoPrazo.php:138`

```
if (is_object($r) && $r->CalcPrecoPrazoResult && is_object($r->CalcPrecoPrazoResult)
    && $r->CalcPrecoPrazoResult->Servicos && is_object($r->CalcPrecoPrazoResult->Servicos) 
)
```

Note que **$r->CalcPrecoPrazoResult** acessa a propriedade para verificar se ela é considerada verdadeira, caso ela não exista, ocorre a Exception.

**Comment by fhferreira** [comment]
message: "Undefined property: SoapFault::$CalcPrecoPrazoResult"

Error: "#0 /application/backend/vendor/stavarengo/php-sigep/src/PhpSigep/Services/Real/CalcPrecoPrazo.php(140): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /application/backend/vendor/stavarengo/php-sigep/src/PhpSigep/Services/SoapClient/Real.php(86): 
PhpSigep\Services\Real\CalcPrecoPrazo->execute()
#2 /application/backend/app/Services/Apps/CorreiosService.php(249): PhpSigep\Services\SoapClient\Real->calcPrecoPrazo()
