### ISSUE TITLE
Demora ao solicitar etiqueta

### ISSUE THREAD

**Issue by IuryChristmas** [stavarengo/php-sigep#144]
Fala galera, eu to com um pequeno problema, é o seguinte... Sempre que vou realizar a primeira solicitação das etiquetas após ligar minha máquina(local) a primeira solicitação demora por volta de 10-20 minutos para me dar algum retorno, mas depois dessa primeira vez, as solicitações duram por volta de 5 segundos, isso acontece ou já aconteceu com mais alguém?

**Comment by andersonls** [comment]
@IuryChristmas Isso acontece comigo também, desde que comecei a fazer a integração aqui na minha empresa, porém apenas no ambiente de produção. No ambiente de homologação nunca tive esse problema (que uso local pra testes). Na verdade o problema não é na solicitação de etiquetas, é na autenticação. Se você chamar outro método do webservice vai notar o mesmo problema. Se ficar sem fazer chamadas pro webservice por algumas horas, depois a primeira chamada volta a demorar também.

Com você está acontecendo com o de homologação? No de produção você notou o problema também?

Já entrei em contato com o representante comercial dos correios que tenho contato, mas nunca me deram um motivo. Sempre falam que vão encaminhar pra área técnica.

**Comment by IuryChristmas** [comment]
Sim, eu notei o mesmo tanto no de homologação como no de produção, mas no de produção ele a demora é menor.
Nesse caso @andersonls não tem nada que possa ser feito? Além de sentar e tomar um cafézinho enquanto espero é claro, rs

**Comment by andersonls** [comment]
Só gambiarra, hehe... Dá pra colocar o cron do servidor pra chamar o webservice no inicio do dia ou no teu caso que é local na quando liga a máquina.

**Comment by IuryChristmas** [comment]
Hm... Gambiarra nossa de cada dia, rs
Obrigado cara, acho que vou fazer essa gambis só no servidor mesmo, me ajudou muito, eu fecho ou deixo aberto até o final do dia, pra ver se mais alguém se manifesta a respeito?

**Comment by willian-rosa** [comment]
Pessoal.
O correios recomenda fazer reserva de etiquetas para diminuir a quantidade de solicitações.

Da para utilizar o método setModoUmaRequisicao para buscar numeros de etiquetas sequenciais.

$params = new \PhpSigep\Model\SolicitaEtiquetas();				$params->setModoUmaRequisicao();

**Comment by IuryChristmas** [comment]
@willian-rosa eu olhei aqui, ele recebe true ou false é isso mesmo? Onde você colocaria a quantidade? Continua sendo no setQuantidade?

**Comment by willian-rosa** [comment]
@IuryChristmas é isso ai, o resto continua o mesmo.
Ai na quantidade será a quantidade de etiquetas que você vai querer deixar reservada.
Vai ter que fazer algo salvar e controlar essas etiquetas que forem sendo usadas que você solicitou.

**Comment by willian-rosa** [comment]
@IuryChristmas é isso ai, o resto continua o mesmo.
Ai na quantidade será a quantidade de etiquetas que você vai querer deixar reservada.
Vai ter que fazer algo salvar e controlar essas etiquetas que forem sendo usadas que você solicitou.
