### ISSUE TITLE
Etiqueta inválida para o cliente

### ISSUE THREAD

**Issue by gt8** [stavarengo/php-sigep#157]
Depois que atualizei a API, não consegui postar encomendas nos Correios. Fui lá e eles me disseram "etiqueta inválida para o cliente". Há alguém passando pelo mesmo problema? Seria problema na API ou com os Correios?
:S

**Comment by gt8** [comment]
acabei de gerar uma nova PLP e fui testar nos Correios, mas o sistema deles deu exatamente este erro: "Etiqueta inválida" e "Objeto postal não pertence ao SIGEP"

**Comment by stavarengo** [comment]
@gt8 vc chegou a enviar a PLP para o sistema deles?
Se não me engano, vc precisa gerar a etiqueta e enviar uma PLP que contenha ela para eles.
É isso mesmo @gustvao ?

**Comment by gt8** [comment]
Eu peguei o sistema já pronto, @stavarengo. Estou estudando ele, tentando entender como o antigo desenvolvedor integrou a biblioteca. Para ter certeza, poderia me confirmar quais são as classes para gerar a etiqueta e enviar a PLP?

**Comment by gt8** [comment]
Conferi por aqui e vi que a etiqueta não era enviada. Corrigi, mas agora, na agência dos Correios, deu outro erro: "1145127 - Serviço não vinculado ao serviço de postagem" :(

**Comment by lularodriguesneto** [comment]
Estou tendo um problema similar:

https://github.com/stavarengo/php-sigep/issues/160

**Comment by stavarengo** [comment]
@gt8 essa mensagem "1145127 - Serviço não vinculado ao serviço de postagem" parece mais com um problema contratual do seu cliente, ou vc pode estar passando o código de serviço que realmente não é permitido para o seu cliente.
Já verificou estes itens?

**Comment by gt8** [comment]
@stavarengo Esse seu último comentário fez toda a diferença. Em contato com o gerente da agência foi verificado que nosso contrato havia mudado. Depois que atualizei para o contrato novo, as etiquetas passaram a funcionar.
