### ISSUE TITLE
Timeout na primeira resposta

### ISSUE THREAD

**Issue by Fertusco** [stavarengo/php-sigep#158]
Prezados, boa noite.

Não é um issue do módulo, mas estou com um problema de uns tempos até agora.

Quando eu faço um request de qualquer método pela primeira vez, o navegador fica em load travado até o timeout do php. Uns 10 minutos após o primeiro request todas as chamadas de métodos voltam a funcionar instantaneamente. Isto ocorre todos os dias, ou após um longo período de inatividade no sigep.

Não sei se é um problema com meus dados de acesso nos Correios e preciso solicitar outra conta, ou se é algum problema nas minhas configurações.

Alguém passa por este mesmo problema e poderia dar uma luz? (obs: isto só ocorre com as credenciais em produção, no ambiente de homologação isto não ocorre)

**Comment by andersonls** [comment]
Você não está sozinho hehe. Dá uma olhada na issue #144.

**Comment by jdgrieco** [comment]
Ativei essa semana (08/06/2017) o 1º ambiente em produção usando o php-sigep e notei o mesmo problema.

Fiz uma rotina que pesquisa os contratos ativos do cliente:
```php
$result = $phpSigep->buscaCliente($accessData);
foreach ($result->getResult()->get('contratos')->cartoesPostagem->servicos as $servico) {
    echo trim($servico->codigo) . ' - ' . trim($servico->descricao) . "\n";
}
```
E seguindo a sugestão do @andersonls na issue https://github.com/stavarengo/php-sigep/issues/144#issuecomment-299955389, coloquei no cron, com a diferença que chamo a rotina a cada hora, tipo um "heartbeat" ou "ping", por enquanto está funcionando e ninguém reclamou de lentidão

Aproveitando, parabéns ao @stavarengo e todos que contribuem (https://github.com/stavarengo/php-sigep/graphs/contributors) com o php-sigep

**Comment by Fertusco** [comment]
Achei que fosse um problema pontual, mas muitos tem o mesmo problema então!

Engraçado que quando acesso pelo aplicativo do Sigep WEB feito pelos Correios, mesmo após longo período de inatividade, a resposta é instantânea.

Hoje mudei o parâmetro Diretoria nos meus dados de acesso, e logo no primeiro request consegui resposta imediata. Vou continuar testando e caso haja alguma novidade, post aqui.

Obrigado a todos pelo retorno.

**Comment by Fertusco** [comment]
Depois de uma semana de testes, parou de travar a primeira requisição.

Nas funções dentre da classe SoapClientFactory, onde existe a variável $param, apenas alterei da seguinte forma:

> $params = array (
>                 'stream_context' => stream_context_create(
>                     array(
>                         'http' => array(
>                             'protocol_version'=>'1.1',
>                             'header' => 'Connection: Close'
>                         )
>                     )
>                 )
>             );

Desta forma, as requisições via Soap estão funcionando perfeitamente!

**Comment by stavarengo** [comment]
@Fertusco acha que valeu um Pull Request?

**Comment by trialforce** [comment]
Olá, acabei de baixar o projeto e tive lentidão ao ponto de não funcionar os exemplos, fazendo essa modificação funcionou 100%.

Notei que não tem um index.php na pasta de exemplos, facilitaria para rodar eles, só comentando.
