### ISSUE TITLE
Rastreamento de objetos

### ISSUE THREAD

**Issue by edsonrodsilva** [stavarengo/php-sigep#159]
Olá pessoal,

Comecei a ter problema ao rastrear objetos usando esta Integração com Web Service do Correios.

Testei o webservice (webservice.correios.com.br/service/rastro/Rastro.wsdl) usando SoapUI (https://www.soapui.org/) e também tem o mesmo problema.

Meu problema é que 
- 1 as consultas estão retornando apenas um objeto mesmo passando vários ar somente retorna o primeiro.
- 2 Mesmo setando o tipo de $tipoResultado = 'T'; esta retornando apenas um eventos do objeto.

Alguém esta passando por isto? esta com este problema?

Valeu.

**Comment by lularodriguesneto** [comment]
sim de um tempo pra cá só está trazendo o primeiro evento... estou com a mesma dificuldade
além disso não conecta mais com o usuário e senha do meu cliente e sim apenas com o usuário e senha padrão dos correios

**Comment by stavarengo** [comment]
@edsonrodsilva ainda está com problemas?

**Comment by edsonrodsilva** [comment]
Olá, stavarengo!
Sim, o problema persiste.
Hoje eu faço rastreamento em massa de milhares de objetos em meu sistema diariamente.
Eu utilizo a senha padrão dos Correios usuário: ECT e senha: SRO. Sei que esta senha é para testes, mas funcionava bem.
Percebi o problema no dia 19 deste mês, antes disto tudo correia bem, exceto a instabilidade do serviço rsrsr. 

Gostaria de saber se que tem contrato esta conseguindo fazer o rastreamento normalmente com o usuário que é fornecido pelo correio.

Valeu!

**Comment by almeida245** [comment]
Mesmo problema aqui. Só funciona com o usuário e senha padrão dos Correios e ainda assim só traz o primeiro evento.

**Comment by IuryChristmas** [comment]
Estou com o mesmo problema, alguém conseguiu uma solução ou uma resposta dos correios?

**Comment by IuryChristmas** [comment]
Boa tarde galera, tenho novidades a respeito desse problema... Consegui contato com um funcionário dos correios e ele me deu a seguinte resposta, que os correios bloquearam TODOS os usuários e senhas dos clientes pra essa parte de rastreamento... O cliente deve entrar em contato com os correios através de um email, enviando as seguintes informações: numero do contrato, cartão, cnpj, razão social... Depois disso eles geram uma nova senha e enviam ao cliente essa senha atrvés de email...
Sendo assim, vão ficar duas senhas, uma pro sro e outra pros outros serviços que já utilizamos normalmente, como solicitação de etiquetas, etc.

**Comment by jdgrieco** [comment]
@IuryChristmas, que porcaria de serviço, não é???

**Comment by edsonrodsilva** [comment]
Consegui contato com os correios e disse que agora os correios bloquearam e restringe o rastreamento através do **WebService**. O cliente deve entrar em contato com os correios através de um email e formalizar o pedido,  através de correspondência, assinada pelo representante, enviando as seguintes informações: numero do contrato e demais dados e eles geram um usuário e senha exclusiva para o SRO.

Com este usuário e senha consegue rastrear e obter todos os  eventos do objeto e também é possível fazer o rastreamento em lote.

Depois de muito luta, tudo funcionando aqui pra mim.
Valeu!!!

**Comment by IuryChristmas** [comment]
Acho que o tópico pode ser encerrado já, então... Se não restarem mais dúvidas :D

**Comment by saulfm08** [comment]
Eu tenho uma duvida com relação ao rastreio mais abri uma nova issue.

**Comment by almeida245** [comment]
Desculpe abrir a issue novamente, mas alguém pode me informar qual o email que tem que enviar para solicitar usuário e senha para SRO? Informei a situação para um de nossos clientes e ele disse que entrou em contato com a gerente do contrato dele com os correios e que ela não sabe de nada dessa nova senha rsrs

**Comment by IuryChristmas** [comment]
@almeida245 mah... esses emails são específicos por diretoria saca... tipo, aqui em fortaleza tem um responsável por isso... em outro estado, é outro responsável... os endereços de email são diferentes pelo que entendi. Esse gerente do contrato dela, é de uma AGF(Agência franqueada) ou ele é dos Correios mesmo?
