### ISSUE TITLE
Correios não aceita a postagem

### ISSUE THREAD

**Issue by leomarques12** [stavarengo/php-sigep#161]
Olá!
Estou desenvolvendo um Marketplace e está gerando a etiqueta normalmente.
IMAGEM: http://www.investidordigital.net/teste/sigep-etiqueta.jpg

Porém, ao tentar postar nos correios, o pacote não foi aceito. Ao passar o leitor do código de barras, apresentou este erro na tela da agência dos correios.
IMAGEM: http://www.investidordigital.net/teste/sigep-erro-correios.jpg

O meu contrato já está atualizado e utilizando os novos códigos de Sedex e PAC.
PAC: 04669
Sedex: 04162

**Comment by IuryChristmas** [comment]
Verificou se não está usando a url de testes por engano?

**Comment by leomarques12** [comment]
@IuryChristmas você se refere a URL minha, da minha loja? ou dos correios?

**Comment by IuryChristmas** [comment]
Do webservice dos correios

**Comment by leomarques12** [comment]
@IuryChristmas onde vejo este parâmetro?

**Comment by IuryChristmas** [comment]
@leomarques12 procura onde tu está fazendo a chamada no teu código do config.php e olha lá se esse método aqui setEnv tá chamando o ENV_PRODUCTION, se não estiver ai tu chama ele

$config->setEnv(\PhpSigep\Config::ENV_PRODUCTION);

**Comment by leomarques12** [comment]
@IuryChristmas Obrigado... vou checar e aviso o resultado...

**Comment by leomarques12** [comment]
@IuryChristmas funcionou! Obrigado!
