### ISSUE TITLE
Consultar valores das postagens

### ISSUE THREAD

**Issue by leomarques12** [stavarengo/php-sigep#162]
Bom dia!
Nesta lib, é possível consultar o valores que o meu contrato está pagando por cada postagem?

Ou seja, seria uma consulta pós-postagem...

**Comment by dehdocs** [comment]
Não,

Até o momento não conheço nenhuma ferramenta capaz de realizar tal consulta.

**Comment by andersonls** [comment]
Bom dia, dá uma olahda na classe php-sigep/src/PhpSigep/Services/Real/SolicitaXmlPlp.php 

Você passa o ID da PLP retornado no método fechaPlPVáriosServiços e ele te retorna um XML no memo formato, mas com as informações de valor cobrado, peso tarifado, etc preenchidos.

**Comment by rodrigojob** [comment]
Olá, lembre-se que o valor pode ser recalculado pelo Correio no momento da postagem quando difere a cubagem

**Comment by brunorthomaz** [comment]
Os elementos que contém <![CDATA[ ]]> no retorno do xml ficam sem valores quando convertidos.

( https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/SolicitaXmlPlp.php#L46 )

Acredito que poderia ser alterado para:

$xml = simplexml_load_string($r->return, 'SimpleXMLElement', LIBXML_NOCDATA);


@andersonls @rodrigojob @stavarengo

**Comment by stavarengo** [comment]
@brunorthomaz se vc testou e deu certo, faz um PR pra gente.
Uma dúvida: é possível trocar o `'SimpleXMLElement'` por `\SimpleXMLElement::class`?

**Comment by brunorthomaz** [comment]
Sim, é possível, testei aqui e funcionou também.
