### ISSUE TITLE
Rastreamento Versão anterior (URL?)

### ISSUE THREAD

**Issue by saulfm08** [stavarengo/php-sigep#163]
Boa tarde!
Eu uso uma versão antiga do código de vocês pra fazer o rastreio, mas não está funcionando.

Creio que o problema esteja no arquivo:
`tcesarpinho/php-sigep/src/PhpSigep/Services/Real`

Verifiquei que o código está usando o link antigo do websro dos correios vejam:
`curl_setopt_array( $ch, array( CURLOPT_URL => 'http://websro.correios.com.br/sro_bin/sroii_xml.eventos', CURLOPT_POST => true, CURLOPT_RETURNTRANSFER => true, CURLOPT_POSTFIELDS => $postContent, CURLOPT_SSL_VERIFYPEER => false, ) );
`
Será que é só mudar para a URL nova dos correios ?
URL Antiga:
http://websro.correios.com.br/sro_bin/sroii_xml.eventos

URL Nova:
http://webservice.correios.com.br/service/rastro/Rastro.wsdl

**Comment by IuryChristmas** [comment]
@saulfm08 isso, troca a url que deve funcionar.

**Comment by saulfm08** [comment]
Não funcionou. A versão antiga é uma das primeiras versões onde a URL estava fora do Config.php que é onde está hoje atualmente....

Esse módulo do SIGEP foi usado como requerimento de um módulo dos Correios para Magento2, no qual não estava funcionando apenas o rastreio.

Eu fiz um fork do projeto desatualizado e estou atualizando apenas o que diz respeito ao rastreio para não afetar o que já está funcionando em minha loja.

Antes nem o exemplo de rastreio, contido na pasta exemplos, funcionava. Agora já consegui fazer funciona e subi aqui pro meu repositório. 

Agora estou tentando entender o seguinte: como o modulo do SIGEP retorna pro Magento2 essa resposta do objeto rastreado.... Substitui os arquivos modificados no Magento mas está dando um erro 500 agora RS

Trabalho de formiga

**Comment by stavarengo** [comment]
Muito tempo sem interação
