### ISSUE TITLE
Confiabilidade na consulta CalcPrecoPrazo

### ISSUE THREAD

**Issue by jdgrieco** [stavarengo/php-sigep#164]
Olá a todos,

Cuido de uma loja virtual para meu cliente e atualmente utilizo a consulta CalcPrecoPrazo somente na parte administrativa do site para que o responsável pelo despacho dos pedidos escolha PAC ou SEDEX.

No checkout utilizo uma rotina baseada em tabelas no banco de dados com os valores para cada região e toda vez que tem alteração de preço, alguma restrição de entrega, etc. tenho que fazer alterações nessa tabelas.

Sei que o ideal é fazer a consulta mas ai fica o meu receio: até que ponto dá para confiar na estabilidade do webservice dos Correios?

O webservice está estável e com desempenho adequado para confiar nele no checkout?

Alguém utiliza na "frente de loja" ou serviço equivalente?

Sei que o assunto é meio OFF-TOPIC, mas seria interessante receber comentários a respeito

**Comment by stavarengo** [comment]
Oi @jdgrieco.
Respondendo: Eu mesmo, quando inicie este projeto.
Inicialmente este projeto foi feito para um E-Commerce e eu consultava os valores toda vez que alguém chegava na página de checkout. 
Eles tinham uma quantidade de visitantes considerável e o webservice era menos confiável do que é hoje em dia. Por conta disto, obviamente que tive alguns problemas, mas depois de implementar o [sistema de cache](https://github.com/stavarengo/php-sigep#cache) das requisições não tive mais problemas.

Essa foi a minha experiência quando desenvolvi o projetos uns 3 anos atras.

**Comment by jdgrieco** [comment]
Olá a todos, estou fechando a "issue".
Acabei implementando com o sistema de cache que o @stavarengo comentou e até agora tem funcionando bem

**Comment by gustvao** [comment]
@jdgrieco eu enfrentei muitos problemas com instabilidade dos servidores dos correios e acabei partindo para uma solução mista na qual, se o webservice dos correios tiver online e com tempo de resposta razoável, pego de lá as informações de valores, caso contrário, uso uma tabela armazenada offline tipo a sua...

os correios ficam isntáveis com frequencia, dependendo do período, chegam a ficar instáveis todos os dias por dezenas de minutos ou às vezes até horas, e tem períodos que ficam 100% funcionando... é complicado.. dado que ele cai relativamente "pouco", apesar de pouco ser bastatne para conversão de um ecommerce, rs, ter uma solução mista me pareceu o ideal.

@stavarengo uma pergunta par você meu amigo. essa sua solução de cache funcionaria para uma combinação de frete nunca feita antes ou nesse caso, se os correios tivessem instáveis, não retornaria nenhum valor de frete, mesmo com o cache ligado?

**Comment by stavarengo** [comment]
@gustvao acho que não entendi sua pergunta direito, mas por definição um cache armazena a resposta da última requisição.
Se não houve a última requisição então tbm não existe cache.
