### ISSUE TITLE
Rastreamento-Retornar Todos os eventos

### ISSUE THREAD

**Issue by IuryChristmas** [stavarengo/php-sigep#165]
Boa tarde, estou tentando através do método "BuscaEventos" para retornar todos os eventos dos objetos

        $params = array(
            'usuario'  => 'ECT',
            'senha'    => 'SRO',
            'tipo'     => 'L',
            'resultado'=> 'T',
            'lingua'   => '101',
            'objetos'  => $objeto,
        );

estou usando os seguintes parâmetros, segundo o manual no index resultado se eu fizer receber "T" ele deveria me retornar uma lista de todos os eventos daquele objeto específico, mas tudo que ele tem me retornado em meus testes é apenas o último evento... Mais alguém está tendo este problema?

**Comment by jdgrieco** [comment]
@IuryChristmas Será que não está relacionado com a issue #159?

**Comment by IuryChristmas** [comment]
Hmm... Verdade, eu esqueci desse detalhe. Estava usando o usuário e senha
padrão, acho que ele só deve retornar todos os eventos se for com um
usuário que não seja o de teste

2017-07-21 9:25 GMT-03:00 jdgrieco <notifications@github.com>:
