### ISSUE TITLE
Qual código envio para o cliente?

### ISSUE THREAD

**Issue by valdeirs2** [stavarengo/php-sigep#166]
Caros,

Poderiam me tiar uma dúvida?

Ao criar o xml para enviar com o método **fechaPlpVariosServicos()**,  eu preciso antes solicitar uma quantidade de etiquetas correspondentes ao número de objetos que vou postar.

Por exemplo: Temos um pedido com 4 itens, que serão despachados juntos em uma única caixa. Sendo assim, tenho que chamar o método **solicitaEtiquetas()**, passando  como argumento, o código do serviço (PAC, Sedex) e a quantidade de etiquetas (4 itens).

Imaginei, que neste caso, precisaria solicitar uma única etiqueta, pois, os 4 itens estarão juntos. Mas, o WebService me retorna uma mensagem dizendo que tenho que solicitar as 4 etiquetas.

Desta forma, não consigo saber qual destes 4 códigos será o que vamos enviar para o cliente.

Alguém consegue me explicar?

**Comment by IuryChristmas** [comment]
Cara, seguinte... Na construção do xml da plp você está informando os 4 objetos pra ele? Se sim, então o WS está entendendo que são 4 objetos(um em cada caixa). Você deve tratar os 4 itens como um único objeto, em outras palavras você vai levar em consideração só a caixa, quantos itens haverão dentro dela "não vão interessar", eles só poderiam ser de algum interesse, caso fossem ser enviados separados, dessa forma você só envia um único código de rastreio, que vai servir pros 4 já que vão estar todos na mesma caixa/embalagem.

**Comment by valdeirs2** [comment]
@IuryChristmas, entedi o que você disse. Imaginei que teria que repetir o item "<objeto_postal>" para produto do pedido. Mas agora ficou claro.

Muito obrigado!

**Comment by IuryChristmas** [comment]
Não, o "<objeto_postal>" só vai ser repetido se houver outra caixa/embalagem a ser enviada... é nesse caso que deve ser solicitado mais uma etiqueta pra nova embalagem e assim em diante.

@valdeirs2 por nada cara, qualquer coisa estamos ai

**Comment by stavarengo** [comment]
Muito tempo sem interação.
