### ISSUE TITLE
múltiplos logins

### ISSUE THREAD

**Issue by rodrigojob** [stavarengo/php-sigep#167]
Olá, eu estou fazendo testes com o sistema php-sigep e passei por uma situação que não percebi se o sistema atende. 
Diferentes usuários e senhas para cada serviço do Correio.
Você acredita que criaram contas diferentes para o rastreamento, solicitação de etiqueta e para outra coisa?
Ainda tem o idCorreios que você pode usar para criar uma senha, achei que poderia ser um single sign-on, mas não é (ainda???). 
Serve para a Logística Reversa.
Alguém já passou por isso? Tem uma solução inteligente? A minha foi porca: criei um controle por tipo de requisição e vários arquivos com as configurações de acesso, que se duplicaram para atender a homologação.

**Comment by jdgrieco** [comment]
@rodrigojob, realmente a consulta do rastreamento está sendo feita por outro usuário e senha, pelo menos no sistema que dou manutenção.
O que eu fiz foi criar o PhpSigep\Model\AccessData com as informações de login para cada serviço, semelhante ao que você fez.

**Comment by stavarengo** [comment]
@rodrigojob @jdgrieco 
Pode fechar o issue?

**Comment by rodrigojob** [comment]
Pode. 
Lamento muitíssimo a demora.
Se eu fizer direito adicionarei ao sistema
