### ISSUE TITLE
Resposta do Correios: Não foi possível obter as etiquetas solicitadas.

### ISSUE THREAD

**Issue by rsurfings** [stavarengo/php-sigep#168]

**Comment by Rwaldrighi** [comment]
Esta usando o exemplo para testes?
Se sim troque a linhas linhas 5, 6, 7 por este:
$cnpjEmpresa = $accessDataDeHomologacao->getCnpjEmpresa();
$usuario = $accessDataDeHomologacao->getUsuario();
$senha = $accessDataDeHomologacao->getSenha()

**Comment by rsurfings** [comment]
Obrigado

PhpSigep\Services\Result Object
(
    [isSoapFault:protected] => 
    [errorCode:protected] => 
    [errorMsg:protected] => 
    [result:protected] => Array
        (
            [0] => PhpSigep\Model\Etiqueta Object
                (
                    [etiquetaComDv:protected] => 
                    [etiquetaSemDv:protected] => SZ24776375BR
                    [dv:protected] => 
                    [_failIfAtributeNotExiste:protected] => 1
                )

        )

    [soapFault:protected] => 
    [_failIfAtributeNotExiste:protected] => 1
)

**Comment by Rwaldrighi** [comment]
Disponha!

**Comment by luiz-merante** [comment]
boa tarde, o meu só está retornando para TODAS as etiquetas, "Não foi possível obter as etiquetas selecionadas"
