### ISSUE TITLE
Problema geração de etiquetas/chancela/plp e outros.

### ISSUE THREAD

**Issue by Rwaldrighi** [stavarengo/php-sigep#169]
Senhores, boa noite.

Primeiramente gostaria de parabenizar o desenvolvimento do php-sigep e o auxilio de todos que contribuem com o projeto. 

Um de meus clientes, fez a migração do PHP 5 para o 7.1, e o módulo começou a apresentar mensagens de erros, na geração de etiquetas, chancelas, plp, tudo que utiliza o fpdf.php ou o semacode, como a mensagem abaixo:

Warning: A non-numeric value encountered in Php-sigep\src\PhpSigep\Pdf\Semacode.php on line 684

Este erro não impossibilita o funcionamento do módulo, mas explode varias linhas com erros como este. O fpdf.php consegui ajustar, mas nunca trabalhei com semacode, cheguei a procurar bibliotecas semacode compatíveis com PHP 7 mas também não tive sucesso. Removi a apresentação de erros mas gostaria de ajustar.

Alguma dica?

Detalhe a equipe de segurança da empresa não autoriza usar o PHP 5 pois diz que tem vulnerabilidades.

**Comment by stavarengo** [comment]
Oi @Rwaldrighi.
Eu executei aqui e removi todos os warnings que apareceram para mim.
Acabei de subir uma nova versão.
Roda no seu projeto `php composer.phar update stavarengo/php-sigep --with-dependencies`
Este comando vai baixar a nova versão do stavarengo/php-sigep e tbm do stavarengo/php-sigep-fpdf

Caso isto não atualize a versão (por conta das usas regras dentro do composer.json) execute os seguintes comandos.
```
php composer.phar remove stavarengo/php-sigep
php composer.phar require stavarengo/php-sigep:^0.0
```

**Comment by Rwaldrighi** [comment]
Bom dia, @stavarengo.

Obrigado pelo retorno! Eu já tinha alterado o fpdf e removido os Warning, mas queria ajustar o código em definitivo. No caso o semacode é o maior problema, por isso perguntei se alguém conhecia uma biblioteca mais recente, pois a que usamos tem mais de 10 anos. Estou trabalhando com por enquanto assim, mas ainda vou achar um substituto para essa biblioteca.

Mais uma vez obrigado.

**Comment by stavarengo** [comment]
Blz. Não precise se preocupar mais. Faça o update como expliquei acima que já deve funcionar (inclusive o semacode).

**Comment by Rwaldrighi** [comment]
Sim, claro. Mas como falei no primeiro post, eu já tinha feito as alterações e estava funcionando, só quero solucionar em definitivo. 

Obrigado.

**Comment by stavarengo** [comment]
@Rwaldrighi acho que vc não está entendendo: eu já solucionei de foram definitiva.
É só fazer o update.

**Comment by Rwaldrighi** [comment]
Fechado, vou testar no projeto local. Obrigado @stavarengo.

**Comment by gustvao** [comment]
@stavarengo reabrir um defunto aqui. Atualizei para o php7.2 e esse warning voltou a explodir.. alguem mais com esse problema na 7.2?

**Comment by gustvao** [comment]
A non-numeric value encountered REMOTE_ADDR: 201.81.168.15 HTTP_X_FWD: Warning on line 439 in file /home/gadolapps/gadolapps.com/shopify-correios/vendor/stavarengo/php-sigep/src/PhpSigep/Pdf/Semacode.php

**Comment by stavarengo** [comment]
Eu olhei o que tem na [linha 684](https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Pdf/Semacode.php#L684) e encontrei isso `$c = $s{$psl};` dentro de um loop, o que não ajuda a entender o problema.

@gustvao você consegue debugar para entender o motivo?

**Comment by gustvao** [comment]
O que está gerando erros são os campos HEXA, ex:

A non-numeric value encountered 

```php
if ($c & 0x80) {
```

Procurei na internet mas não consegui entender muito bem o que a `$var & 0x80` faz e como consertar isso.. tentei fazer o '0x80' como string mas deu erro na geração do sema..

Você saberia o que fazer nesse caso @stavarengo ? se consertar esse caso vai ser só replicar para as outras linhas do arquivo...

**Comment by stavarengo** [comment]
> ```
> if ($c & 0x80) {
> ```

@gustvao 0x80 é o hexadecimal equivalente ao decimal 128.
Eu encontrei quatro links que, eu acredito, vão te ajudar a interpretar essa instrução.
Veja:
 - https://www.php.net/manual/en/language.operators.bitwise.php
 - https://stackoverflow.com/questions/2376348/difference-between-and-in-php
 - https://stackoverflow.com/questions/15005917/bitwise-comparison-in-php
 - https://stackoverflow.com/questions/12480516/how-do-you-bitwise-shift-a-hex-string-which-is-of-data-type-string-in-php

Se conseguir resolver, manda um PR pra gente por favor.

**Comment by gustvao** [comment]
@stavarengo 

achei ;)

https://github.com/stavarengo/php-sigep/pull/372

tem mais um tb aqui:

https://github.com/stavarengo/php-sigep-fpdf/pull/4
