### ISSUE TITLE
Mal formatação na etiqueta

### ISSUE THREAD

**Issue by borger** [stavarengo/php-sigep#17]
Boa noite,

Parabéns pelo projeto, excelente trabalho, estava testando a versão dev-master, porém quando gero a etiqueta (seguindo o exemplo mesmo), a etiqueta sai conforme abaixo:

<img width="618" alt="screen shot 2015-11-24 at 00 53 42" src="https://cloud.githubusercontent.com/assets/5930158/11356561/fce81ab4-9245-11e5-9a43-d65faa2ccb1c.png">

Alguma idéia do que possa ser?

**Comment by stavarengo** [comment]
Isso é provavelmente um mal posicionamento do elemento.
Gostaria de corrigir e compartilhar com a comunidade?

**Comment by rafaelsiqueira** [comment]
Enviei um PR que corrige isso e muda a forma de exibição do Semacode.

**Comment by stavarengo** [comment]
Legal. Vou fazer o merge lah.
Valeu.

On Sunday, December 6, 2015, Rafael Siqueira <notifications@github.com>
wrote:

> Enviei um PR que corrige isso e muda a forma de exibição do Semacode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stavarengo/php-sigep/issues/17#issuecomment-162263950>
> .
>


-- 
*Rafael Stavarengo*
stapi.com.br - Linkedin
<http://br.linkedin.com/pub/rafael-stavarengo/1a/338/2a1/>
Skype: rafael.stavarengo

**Comment by stavarengo** [comment]
Corrigido aqui https://github.com/stavarengo/php-sigep/pull/18
