### ISSUE TITLE
Lentidão nas consultas

### ISSUE THREAD

**Issue by sotnaspina** [stavarengo/php-sigep#170]
Olá, primeiramente gostaria de parabenizar a todos pelo projeto.

As consultas (solicitar etiqueta, ...) estão demorando muito (no minimo uns 2 minutos), é normal isso ou deixei de fazer alguma config?

Erro retornado: "Resposta do Correios: Não foi possível obter as etiquetas solicitadas."

Grato!

**Comment by Rwaldrighi** [comment]
Fiz um teste aqui agora e o retorno é quase que imediato. Como esta fazendo a consulta?

**Comment by sotnaspina** [comment]
Obrigado pela atenção, consegui resolver aqui.
