### ISSUE TITLE
modulo para prestashop

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#171]
Olá estou desenvolvendo uma integração entre o prestashop e o sigep gostaria de obter uma infomação, qual é a ordem dos arquivos que devo montar para a geração da etiqueta?
qual é o fluxo para utilizar essa aplicação.

**Comment by jdgrieco** [comment]
Olá, basicamente você precisa solicitar a quantidade de etiquetas, que no final das contas é o pacote que será enviado, para o serviço escolhido.

O sistema dos Correios vai retornar os códigos de rastreamento, vc terá que armazenar essa informação em algum lugar.

Os Correios utilizam a PLP (Pré lista de postagem), é a lista que você irá transmitir para o webservice e um PDF dela deverá ser entregue a quem fizer a coleta

Para imprimir a etiqueta é necessário "setar" para cada etiqueta a dimensão do pacote, algum serviço adicional, conforme o caso, o endereço do destinatário, que tipo de serviço (PAC, Sedex, etc.) em um ObjetoPostal (\PhpSigep\Model\ObjetoPostal())

Essas etiquetas devem ser "setadas" em uma PLP (\PhpSigep\Model\PreListaDePostagem()) com a informação do remetente.

Ai você consegue usar um dos métodos CartaoDePostagem ou CartaodePostagem2016 para imprimir as etiquetas.

Ainda é necessário fazer o "fechamento da PLP", é nesse instante que a classe transmite a relação de objetos que os Correios irão processar.

Apesar de não haver limite de PLPs que podem ser enviadas no dia, eu ouvi do gerente de contas de um cliente que não é para enviar um monte por dia. Nesse cliente eles coletam 2 vezes por dia então eles geram 2 PLPs por dia, e raramente é necessário gerar mais.

Na pasta manual da classe tem o manual que os Correios disponibilizam para os desenvolvedores e na pasta exemplos tem vários exemplos de códigos que servem para você entender melhor o funcionamento

Para mim, fora um pequeno detalhe ou outro, o manual e os exemplos foram suficientes para eu conseguir montar toda a lógica necessária.

Os contribuidores da classe são bastante prestativos também.

Espero ter ajudado a lhe dar uma direção

**Comment by criacaosites** [comment]
então eu devo:
1 - criar a pre lista de postagem PLP
2 - gerar as etiquetas
3 - fechar a lista de postal PLP 
nessa ordem?

**Comment by jdgrieco** [comment]
Eu gero as etiquetas, associo ao pedido, ai crio uma pré-lista "interna" da plataforma, associo as etiquetas.

Ai o cliente pode imprimir, remiprimir as etiquetas, acrescentar novas etiquetas. Um pouco antes dos Correios fazerem a coleta eles "fecham" a PLP, ai não permito mais mexer nela. 

Entenda, gerar UMA etiqueta é basicamente reservar UM código de rastreamento no sistema dos Correios

**Comment by criacaosites** [comment]
Entendi:
1 - gerar etiquetas, receber e armazenar codigo de rastreio do pedido
2 - gerar pre-lista com os codigos armazenados
3 - fechar plp

**Comment by stavarengo** [comment]
Ótima iniciativa @criacaosites
Quando vc terminar vamos colocar este módulo como open-source tbm?
Poderia ser um repositorio chamado criacaosites/php-sigep-prestashop-module
O que acha?

**Comment by criacaosites** [comment]
Com certeza faço uma versão para quem não pode pagar e outra paga, não vejo problema algum com isso.
Alguem pode me dar uma ajuda para colocar ele para rodar, estou tentando obter retorno do solicitar etiquetas mas não to recebem autorizacao diz que não foi possivel obter as etiquetas, o que estou fazendo errado.
http://wordlx.com/sigep/solicitarEtiquetas.php

**Comment by criacaosites** [comment]
Começei a fuçar o modulo para entender porque não estou conseguindo logar no ambiente producao para solicitar as etiquetas e notei que o /PhpSigep/Model/AccessDataHomologacao.php está com problemas no carregamento do namespace, ele diz que a classe AccessData não foi encontrada, como vocês contornam isso.

**Comment by criacaosites** [comment]
Deu uns includes no accessdata e accessdatahomologacao para o codigo rodar, vou seguir com uns testes aqui

**Comment by criacaosites** [comment]
Pessoal ao solicitar etiquetas estou sempre com o retorno:
 Resposta do Correios: Não foi possível obter as etiquetas solicitadas.

Como posso contornar isso?

**Comment by stavarengo** [comment]
@criacaosites difícil dizer qual o problema só com esta mensagem.
Posta aqui a mensagem de erro completa. Talvez tenha alguma dica.

Sobre o autoload da classe: isso pode ser uma má configuração do seu composer. 
Vc instalou a bilioteca usando composer?

**Comment by criacaosites** [comment]
Instalei via download porque não consegui pelo composer.

**Comment by criacaosites** [comment]
Estou com outro problema também na geracao das etiquetas, imprimir e fechar plp, são problemas de classe ausente. Tem alguma dica de como contornar isso

**Comment by criacaosites** [comment]
Encontrei a solucao aqui:
https://github.com/stavarengo/php-sigep/issues/168

**Comment by criacaosites** [comment]
[modulo sigep prestashop](https://www.youtube.com/watch?v=N4fv8vVw2lc)

**Comment by stavarengo** [comment]
@criacaosites que legal cara.
O que vc acha da gente modificar o nosso README para falar do seu módulo e tbm de como instalar e configurar ele no presta?
