### ISSUE TITLE
fecha varios pedidos 

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#172]
Olá Pessoal instalei o script e ao rodar o arquivo fechavariospedidos ele me acusa essa informacao:
Array
(
    [*isSoapFault] => 1
    [*errorCode] => 0
    [*errorMsg] => A etiqueta PO638201241BR está fora do padrão esperado.
    [*result] => 
    [*soapFault] => 
    [*_failIfAtributeNotExiste] => 1
)

Que padrão é esse que não é comentado por gentileza, como soluciono isso

**Comment by stavarengo** [comment]
Oi @criacaosites .
Esta mensagem foi gerado pelo Correios. Não é uma mensagem nossa.
Pode ser que eles não aceitam mais etiquetas que comecem com PO (apenas um chute).

**Comment by criacaosites** [comment]
Verifiquei o motivo era mesmo esse e o digito verificador que estava presente.
Gostaria de aproveitar e perguntar onde encontro a listagem de Diretoria para criar um form de configuracao

**Comment by rikw22** [comment]
Apenas para futuras referências a listagem das diretorias está no arquivo:
[PhpSigep/Model/Diretoria.php](https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Model/Diretoria.php)
