### ISSUE TITLE
Tempo excedido na consulta do CEP

### ISSUE THREAD

**Issue by matthtavares** [stavarengo/php-sigep#179]
Estava testando o sistema e percebi que a consulta do CEP estava demorando demais, mais de 100 segundos, o que gerava interrupção. Fiz umas mudanças e adaptei um código que já havia utilizado antes com cURL, o que acabou funcionando bem e o tempo reduziu para menos de 10 segundos. Recomendo que revejam essa parte, não sei se foi apenas comigo que ocorreu esse problema.

**Comment by n49suporte** [comment]
Olá Mateus Tavares,

Uma nova conta foi criada para você em nosso sistema de suporte.

Clique na url abaixo para ativar sua conta e escolher uma senha!

http://clientes.n49.com.br/support/#resetpassword/428771:eb475295-e01f-40c7-9515-a331edc45fa4:236094

Se a URL acima não funcionar, tente copiar e colar em seu navegador.

Se você continuar tendo problemas, não hesite em nos contactar.

Abraços,

N49 Suporte
