### ISSUE TITLE
pegar servico de postagem dinamicamente

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#182]
Pessoal, ha alguma maneira dinamica para eu escolher o servico? Eu fiz uma funcao mas ela nao funciona quando eu a aplico para selecionar dinamicamente o servico na hora de solicitar etiquetas:

`
$params->setServicoDePostagem(servicosigep($servico[0]['servico']));	
function servicosigep($service){
		
				if ($service  == 'SERVICE_PAC_41068'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068;
				}  if ($service  == 'SERVICE_PAC_04510'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_04510;
				}  if ($service  == 'SERVICE_PAC_CONTRATO_41211'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_CONTRATO_41211;
				}  if ($service  == 'SERVICE_PAC_GRANDES_FORMATOS'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_REMESSA_AGRUPADA;
				}  if ($service  == 'SERVICE_PAC_REMESSA_AGRUPADA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_REMESSA_AGRUPADA;
				}  if ($service  == 'SERVICE_E_SEDEX_STANDARD'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_E_SEDEX_STANDARD;
				}  if ($service  == 'SERVICE_SEDEX_40096'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_40096;
				}  if ($service  == 'SERVICE_SEDEX_40436'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_40436;
				}  if ($service  == 'SERVICE_SEDEX_40444'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_40444;
				}  if ($service  == 'SERVICE_SEDEX_12'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_12;
				}  if ($service == 'SERVICE_SEDEX_10'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_10;
				}  if ($service  == 'SERVICE_SEDEX_10_PACOTE'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_10_PACOTE;
				}  if ($service  == 'SERVICE_SEDEX_HOJE_40290'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_HOJE_40290;
				}  if ($service  == 'SERVICE_SEDEX_HOJE_40878'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_A_VISTA;
				}  if ($service  == 'SERVICE_SEDEX_A_VISTA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_A_VISTA;
				}  if ($service  == 'SERVICE_SEDEX_VAREJO_A_COBRAR'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_VAREJO_A_COBRAR;
				}  if ($service  == 'SERVICE_SEDEX_AGRUPADO'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_AGRUPADO;
				}  if ($service  == 'SERVICE_SEDEX_REVERSO'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_REVERSO;
				}  if ($service  == 'SERVICE_SEDEX_PAGAMENTO_NA_ENTREGA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_PAGAMENTO_NA_ENTREGA;
				}  if ($service  == 'SERVICE_PAC_PAGAMENTO_NA_ENTREGA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_PAGAMENTO_NA_ENTREGA;
				}  if ($service  == 'SERVICE_CARTA_COMERCIAL_A_FATURAR'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_CARTA_COMERCIAL_A_FATURAR;
				}  if ($service  == 'SERVICE_CARTA_REGISTRADA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_CARTA_REGISTRADA;
				}  if ($service  == 'SERVICE_SEDEX_CONTRATO_AGENCIA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_CONTRATO_AGENCIA;
				}  if ($service  == 'SERVICE_PAC_CONTRATO_AGENCIA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_CONTRATO_AGENCIA;
				}  if ($service  == 'SERVICE_SEDEX_REVERSO_CONTRATO_AGENCIA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_REVERSO_CONTRATO_AGENCIA;
				}  if ($service  == 'SERVICE_PAC_REVERSO_CONTRATO_AGENCIA'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_REVERSO_CONTRATO_AGENCIA;
				}  if ($service  == 'SERVICE_CARTA_COMERCIAL_REGISTRADA_CTR_EP_MAQ_FRAN'){
					$parameters = \PhpSigep\Model\ServicoDePostagem::SERVICE_CARTA_COMERCIAL_REGISTRADA_CTR_EP_MAQ_FRAN;
				}
		
		return $parameters;
	}`

**Comment by stavarengo** [comment]
@criacaosites usa a [constant](http://php.net/manual/en/function.constant.php)

**Comment by criacaosites** [comment]
voce tem um exemplo para me passar por favor?
a no processo de solicitar etiqueta estou recebendo esse retorno: Status de novo pedido inválido o que poderia estar causando isso?

**Comment by stavarengo** [comment]
No link que te mandei tem exemplos
