### ISSUE TITLE
plp fechada e objeto nao encontrado

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#184]
eu acho que o helper-criar-plp esta solicitando em ambiente teste, alguem pode me dar uma luz como eu solicito etiqueta que ja tem?

`  // {@link \PhpSigep\Services\SoapClient\Real::solicitaEtiquetas() } para gerar o número das etiquetas

	$etiqueta = new \PhpSigep\Model\Etiqueta();
	$etiqueta->setEtiquetaSemDv($order['etiquetaSemDv']);`
Seu eu substituo a classe e funcao para
`$etiqueta = new PhpSigep\Services\SoapClient\Real();
	$etiqueta->solicitaEtiquetas();`
O resultado e esse:

> Catchable fatal error: Argument 1 passed to PhpSigep\Services\SoapClient\Real::solicitaEtiquetas() must be an instance of PhpSigep\Model\SolicitaEtiquetas, none given, called in /home/appecas/public_html/modules/fkcorreiosg2cp2/models/helper-criar-pre-lista.php on line 141 and defined in /home/appecas/public_html/modules/fkcorreiosg2cp2/models/PhpSigep/Services/SoapClient/Real.php on line 44

**Comment by stavarengo** [comment]
Olá @criacaosites .

> eu acho que o helper-criar-plp esta solicitando em ambiente teste, alguem pode me dar uma luz como eu solicito etiqueta que ja tem?
O helper-criar-plp é um arquivo apenas para exemplos e não deve ser usado em produção.

> Seu eu substituo a classe e funcao para $etiqueta = new PhpSigep\Services\SoapClient\Real(); $etiqueta->solicitaEtiquetas(); O resultado e esse:
Como a própria mensagem de erro diz, o argumento 1 do método PhpSigep\Services\SoapClient\Real::solicitaEtiquetas() precisa ser uma instancia de PhpSigep\Model\SolicitaEtiquetas. Você não passou nada.

**Comment by criacaosites** [comment]
Mas acho ent'ao que eu nao entendi o fluxograma do projeto:
Porque se eu solicito a etiqueta, entao eu ja tenho ela, porque eu tenho que pedir novamente no helper?

**Comment by criacaosites** [comment]
Eu imprimi uma etiqueta que eu fechei a plp e nos correios nao constou nada, provavelmente foi por conta do helper certo?

**Comment by stavarengo** [comment]
Provavelmente sim @criacaosites

**Comment by criacaosites** [comment]
Stavarengo,

Eu fiquei com uma duvida, o fecha plp executa o comando 
`$params = include __DIR__ . '/helper-criar-pre-lista.php';
//seleciona pedidos com data_criacao e cod rastreio porem sem o id do PLP
			
$phpSigep = new PhpSigep\Services\SoapClient\Real();

try{
	$result = $phpSigep->fechaPlpVariosServicos($params);`
O que significa que ele obtem o codigo da etiqueta a partir do helpe que esta com a configuracao original de 
`$etiqueta = new \PhpSigep\Model\Etiqueta();
	$etiqueta->setEtiquetaSemDv($order['etiquetaSemDv']);`
ou seja ele esta utilizando uma etiqueta ja solicitada pelo solicitar etiquetas, entao porque os correios nao encontraram o objeto no leitor de codigo de barras?

**Comment by criacaosites** [comment]
Fui ate a agencia                        
E verifiquei                        
Aquelas listagens                        
Uma delas deu certo                        
O restante não aparece no sistema                        
O pedido 5406 PLP 1506439378                        
Deu certo                        
Os pedido agrupados 5407 5439 5445 e 5446                        
PLP 1506439360                        
Não deu certo =/
