### ISSUE TITLE
Dados do destino ao rastrear evento

### ISSUE THREAD

**Issue by JeanJantara** [stavarengo/php-sigep#186]
Oi, 
eu verifiquei o model RastrearObjetoEvento e não encontrei um método que retorne o destino do evento.

**Comment by stavarengo** [comment]
Oi @JeanJantara .
Estes modelos contem todas as informações que o WebService do Correios retornava no momento em que eles foram criados.
Caso novo campos tenham sido adicionadas, nos envie o manual documentando os novos campos, ou melhor ainda: Se puder nos envie um PR com com os novos campos.
