### ISSUE TITLE
Preços e prazos de um único serviço

### ISSUE THREAD

**Issue by clodoaldoevangelista** [stavarengo/php-sigep#187]
Olá, estou com uma dúvida:
No exemplo calcPrecoPrazo.php linha 15:
$params->setServicosPostagem(\PhpSigep\Model\ServicoDePostagem::getAll());
o return mostra todos os serviços dos correios, mas eu gostaria de consultar apenas um por vez. Eu substitui a linha 15 por esta, apenas para um teste:
$params->setServicosPostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068);
Evidentemente daria um erro no foreach:
Warning: Invalid argument supplied for foreach() in /home/meuentregador.com/public/servicos/wp-content/plugins/me-sigep/sigep/src/PhpSigep/Services/Real/CalcPrecoPrazo.php on line 71

A pergunta é:
Como eu passo no parâmetro (linha 15) apenas um serviço, em vez de getAll(); para ter um result com apenas aquele serviço consultado?

 Obrigado.

**Comment by JeanJantara** [comment]
Passa um array com os que você deseja.

**Comment by clodoaldoevangelista** [comment]
Este seria o result desejável, ou seja apenas do serviço 41068.

Array
(
    [0] => Array
        (
            [0] => PhpSigep\Model\CalcPrecoPrazoResposta Object
                (
                    [servico:protected] => PhpSigep\Model\ServicoDePostagem Object
                        (
                            [codigo:protected] => 41068
                            [idServico:protected] => 109819
                            [nome:protected] => Pac 41068
                            [_failIfAtributeNotExiste:protected] => 1
                        )

                    [valor:protected] => 19.6
                    [prazoEntrega:protected] => 11
                    [valorMaoPropria:protected] => 0
                    [valorAvisoRecebimento:protected] => 0
                    [valorValorDeclarado:protected] => 0
                    [entregaDomiciliar:protected] => 1
                    [entregaSabado:protected] => 
                    [erroCodigo:protected] => 0
                    [erroMsg:protected] => 
                    [_failIfAtributeNotExiste:protected] => 1
                )

        )

)

**Comment by stavarengo** [comment]
@clodoaldoevangelista substitua `$params->setServicosPostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068);` por `$params->setServicosPostagem([\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068]);`

**Comment by clodoaldoevangelista** [comment]
Obrigado pela resposta, mas não consegui o resultado esperado. 
Fatal error: Call to a member function getCodigo() on string in ...me-sigep/sigep/src/PhpSigep/Services/Real/CalcPrecoPrazo.php on line 73 Call Stack: 0.0012 247240 1. {main}() ../me-sigep/PrecosPrazos/calcPrecoPrazo.php:156 0.1333 5430696 3. PhpSigep\Services\Real\CalcPrecoPrazo->execute() ...me-sigep/sigep/src/PhpSigep/Services/SoapClient/Real.php:98

Eu consegui consultar um único serviço, mas tive que inserir o código diretamente aqui:
//'nCdServico'          => '41068', // também reconheceu variável

Estive olhando para este problema por 2 dias; sem sucesso. Poderia confirmar se a alteração proposta é suficiente?
Obrigado.

**Comment by stavarengo** [comment]
Me desculpa foi erro meu.
Tenta esse aqui agora: `$params->setServicosPostagem([new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068) ]);`

Deve funcionar.
