### ISSUE TITLE
Abrir PI (Pedido de Informação)

### ISSUE THREAD

**Issue by tangoda** [stavarengo/php-sigep#188]
Olá!

Existe algum webservice ou API para automatizar a abertura de PI / Reclamação junto aos Correios?

**Comment by blopa** [comment]
Queria saber também...

**Comment by tangoda** [comment]
Não existe mesmo, infelizmente. Tive um retorno oficial de um funcionário dos Correios.

**Comment by blopa** [comment]
Puts. Vai ter que rolar um javascript então... ¯\_(ツ)_/¯

**Comment by rodrigojob** [comment]
Eu tinha funcionando com javascript e iframe, fiz uma alteração e não consegui mais fazer funcionar.
Parece que agora há uma luz com a alteração que o Correios fez, eles estão usando o webservices para gerar o PI

**Comment by rodrigojob** [comment]
> Parece que agora há uma luz com a alteração que o Correios fez, eles estão usando o webservices para gerar o PI

Abri uma reclamação no sistema do FALA.BR do governo federal. Pois se o Correios tem webservice para postagem também pode ter para reclamação.
