### ISSUE TITLE
Nova etiqueta dos correios

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#190]
Alguem esta sabendo sobre o novo modelo de etiquetas dos correios?

**Comment by stavarengo** [comment]
@criacaosites vc tem a documentação do layout deste novo modelo aí?

**Comment by criacaosites** [comment]
Pior que nao, inclusive no site dos correios, que agora na iminencia da uma possivel privatizacao pintou o frontend de outra cor, nada falam a esse respeito.
