### ISSUE TITLE
PLP fechada porem nao encontrada nos correios

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#191]
Ola,

Depois do periodo de desenvolvimento do modulo para prestashop agora encontrei um problema ao fechar a plp, meu cliente foi ate a loja dos correios e conseguiu passar apenas uma etiqueta das varias que foram fechadas.
Revi a documentacao e nao identifiquei onde eu errei, poderiam me auxiliar?

Encaminhei ao suporte do sigep esse email abaixo porem 1 semana e nada ainda.

Ola,

Meu nome e Bruno Matos, sou desenvolvedor php e estou trabalhando em um projeto de criar uma integracao entre a api sigep dos correios e o prestashop

https://www.youtube.com/watch?v=N4fv8vVw2lc

Ao fechar a PLP os correios nao estao conseguindo encontrar as etiquetas na loja nem a PLP

Imagem inline 1

Poderiam me auxiliar por gentileza? Quais dados estao indo de maneira incorreta? Abaixo esta o exemplo do meu array object

Array
(
    [34] => PhpSigep\Model\ObjetoPostal Object
        (
            [etiqueta:protected] => PhpSigep\Model\Etiqueta Object
                (
                    [etiquetaComDv:protected] => 
                    [etiquetaSemDv:protected] => OA81551943BR
                    [dv:protected] => 
                    [_failIfAtributeNotExiste:protected] => 1
                )

            [servicoDePostagem:protected] => PhpSigep\Model\ServicoDePostagem Object
                (
                    [codigo:protected] => 40096
                    [idServico:protected] => 104625
                    [nome:protected] => Sedex 40096
                    [_failIfAtributeNotExiste:protected] => 1
                )

            [cubagem:protected] => 
            [peso:protected] => 0.000000
            [destinatario:protected] => PhpSigep\Model\Destinatario Object
                (
                    [nome:protected] => Bruno Die mat
                    [telefone:protected] => (21) 98513-7219
                    [celular:protected] => (21) 2233-3663
                    [email:protected] => finan@criacao-sites.com
                    [logradouro:protected] => Rua Carneiro Leão
                    [complemento:protected] =>  Obs:endereço de testes
                    [numero:protected] =>  130
                    [_failIfAtributeNotExiste:protected] => 1
                )

            [destino:protected] => PhpSigep\Model\DestinoNacional Object
                (
                    [bairro:protected] => Santo Cristo
                    [cep:protected] => 20220130
                    [cidade:protected] => Rio de Janeiro
                    [uf:protected] => RJ
                    [numeroPedido:protected] => FAJUZAISY
                    [numeroNotaFiscal:protected] => 34
                    [serieNotaFiscal:protected] => 
                    [valorNotaFiscal:protected] => 29.12
                    [naturezaNotaFiscal:protected] => 
                    [descricaoObjeto:protected] => 
                    [valorACobrar:protected] => 
                    [_failIfAtributeNotExiste:protected] => 1
                )

            [servicosAdicionais:protected] => Array
                (
                    [0] => PhpSigep\Model\ServicoAdicional Object
                        (
                            [codigoServicoAdicional:protected] => 019
                            [valorDeclarado:protected] => 29.12
                            [_failIfAtributeNotExiste:protected] => 1
                        )

                    [1] => PhpSigep\Model\ServicoAdicional Object
                        (
                            [codigoServicoAdicional:protected] => 001
                            [valorDeclarado:protected] => 
                            [_failIfAtributeNotExiste:protected] => 1
                        )

                    [2] => PhpSigep\Model\ServicoAdicional Object
                        (
                            [codigoServicoAdicional:protected] => 002
                            [valorDeclarado:protected] => 
                            [_failIfAtributeNotExiste:protected] => 1
                        )

                )

            [dimensao:protected] => PhpSigep\Model\Dimensao Object
                (
                    [tipo:protected] => 002
                    [altura:protected] => 20
                    [largura:protected] => 20
                    [comprimento:protected] => 20
                    [diametro:protected] => 0
                    [_failIfAtributeNotExiste:protected] => 1
                )

            [_failIfAtributeNotExiste:protected] => 1
        )

)

**Comment by stavarengo** [comment]
Acho pouco provável que eles respondam.
Veja nos seus logs se não houve erros quando as PLPs que faltam foram geradas.

**Comment by criacaosites** [comment]
O que eu encontrei no log foi isso:
[06-Nov-2017 17:57:27 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by stavarengo** [comment]
Está aí. Então vc encontrou.
Estou fechando o issue como este não é um problema relacionado com o php-sigep.
Se achar o contrário pode abrir novamente.

**Comment by criacaosites** [comment]
Stavarengo,

Como eu debugo o xml do helper-list para saber se ha algum erro de
preenchimento?

**Comment by stavarengo** [comment]
Vc tem que validar ele contra o schema.
Eu não tenho eles aqui, mas lembro que quando iniciei esta library o Correios disponibilizava esses arquivos para fazer uma validação local antes de fazer a requisição.
Caso vc encontre, coloque no nosso projeto [nessa pastinha](https://github.com/stavarengo/php-sigep/tree/master/manual) pra ficar mais fácil de encontrar na próxima vez.

**Comment by criacaosites** [comment]
Sobre a Issue https://github.com/stavarengo/php-sigep/issues/206
