### ISSUE TITLE
Postagem de Cartas através do WebService

### ISSUE THREAD

**Issue by andersonls** [stavarengo/php-sigep#192]
Alguém já fez alguma postagem através do WebService com algum tipo de carta entre os objetos da PLP?

Gostaria de saber se é possível fazer isso, pois as cartas comuns não tem objeto de rastreio, que é obrigatório passar na PLP. E mesmo a carta registrada que tem código de rastreio, no momento do envio pra mim está aparecendo a mensagem de etiqueta inválida.

**Comment by stavarengo** [comment]
Acredito que sim @andersonls 
Talvez tenha sido um erro forçar o "objeto de rastreio" ser obrigatório.
Sobre o problema da etiqueta, é bom conferir com os correios qual o tipo de etiqueta correto para cartas comum.

**Comment by andrikmb** [comment]
veja se não está usando o código 10138, em vez de 10065, a 10138 é só para órgãos públicos, pode ser o código do serviço adicional, na carta não é usado o serviço 25, mas acho que é o 24.

**Comment by andersonls** [comment]
@andrikmb Vou verificar! Com relação a carta normal, que não tem código de rastreio, sabes se é possível?

**Comment by andersonls** [comment]
@andrikmb Com o código 10065 consegui enviar a PLP sem erros no ambiente de homologação. Quando tiver uma carta pra postar, vou testar a postagem na agência. 

Obrigado pela ajuda!

**Comment by stavarengo** [comment]
@andrikmb vc parece estar bem informado sobre cada tipo de código.
Vc acha que vale a pena colocar uma comentário nas constantes para explicar melhor quando cada uma deve ser usada? 
Assim agente evita esse tipo de problema como o que aconteceu com o @andersonls.
Talvez podemos até mudar os nomes de algumas constantes para ficar mais intuitivo.
O que vc me diz?
