### ISSUE TITLE
Documentação não dá para acessar

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#194]
Estou tentando acessar a documentação: http://stavarengo.github.io/php-sigep/
e não está funcionando! Agradeço se puder consertar.

-------------------

Outra coisa, estou desenvolvendo junto com um amigo para fins particulares, mas não estou conseguindo fazer a conexão. 

No arquivo **AccessDataHomologacao.php**, o **usuário e senha** é o **Código Administrativo** e a senha são os **8 primeiros digitos do CNPJ**? Eu consigo acessar nesta página: http://www.corporativo.correios.com.br/encomendas/sigepweb/default.cfm?s=true

É o mesmo para configurar esta api?

Obrigado!

**Comment by lucaspaulino** [comment]
Como estou sem manual, eu passei o dia fuçando o código. E no arquivo **AccessDataHomologacao.php** eu alterei para ENV_PRODUCTION.
Só que agora o código passa muito tempo tentando carregar, e está retornando erro 404, mas não diz qual arquivo e nem nada. Estou tentando instalar manualmente, pois é uma hospedagem da hostgator.

Sem manual fica dificil fazer a configuração correta.

OBS.: eu consegui acessar através do aplicativo **SIGEP Cliente** que baixei no site dos correios.

**Comment by andersonls** [comment]
@lucaspaulino No projeto tem uma pasta chamada "exemplos", lá tem exemplos funcionais das principais funções do webservice. Esses exemplos + o manual do webservice dos correios já é suficiente pra colocar a aplicação pra funcionar.

**Comment by lucaspaulino** [comment]
@andersonls como vou saber que a conexão foi efetuada? Pois, exatamente, eu estou usando os códigos de testes e algumas dão certo (consulta de cep, etc)

Os erros que informei foram do teste com o arquivo **verificaDisponibilidadeServico.php**

**Comment by andersonls** [comment]
O resultado deve ser semelhante ao do consultaCep. Se você não tá conseguindo achar o problema pela saída do PHP nem pelos logs do apache, posta aqui que fica mais fácil pra ajudar.

**Comment by lucaspaulino** [comment]
Olha o erro completo: https://pastebin.com/2txDrd3G

Você não quer me ajudar a configurar? Eu te pago

**Comment by andersonls** [comment]
Esse é teu erro: "A autenticacao de USUARIO falhou!"

Olhando melhor, dá pra ver que os valores não estão setados corretamente:

["codAdministrativo"]=> string(8) "COD_ADMINISTRATIVO"
["usuario"]=> string(10) "USUARIO"
["senha"]=> string(6) "SENHA"

Você alterou o AccessDataHomologacao com esses valores?

O que eu faria nesse caso é fazer uma cópia do AccessDataHomologacao, salvar como AccessDataProdução, alterar os dados do contrutor para ficarem de acordo com os dados do teu contrato dos correios e na linha 6 do verificaDisponibilidadeServico alterar para

$params->setAccessData(new \PhpSigep\Model\AccessDataProducao());

Ou a forma mais preguiçosa é apenas alterar os dados do contrato diretamente no AccessDataHomologacao.

**Comment by lucaspaulino** [comment]
Eu consegui fazer a conexão. Mas ainda preciso de umas ajudas, podemos entrar em contato? Eu pago

**Comment by andersonls** [comment]
Ok, acho que pode fechar a issue então.
