### ISSUE TITLE
Problema ao calcular em CEPs de áreas de risco - Magento 2.1

### ISSUE THREAD

**Issue by Renatobdcs** [stavarengo/php-sigep#196]
Estou usando [um módulo no Magento 2.1](https://github.com/Bleez/Bleez-Correios) (plataforma de e-Ecommerce) que usa este código com adaptações e funciona corretamente. Mas quando é para calcular os CEPs de áreas de rico, quando o mesmo no site do Correios retorna a mensagem:

`(6) - O CEP de destino está sujeito a condições especiais de entrega pela ECT e será realizada com o acréscimo de até 7 (sete) dias úteis ao prazo regular.`

.. no modulo do Magento ele informa que não é possível fazer o cálculo e retorna:

`Serviço indisponível para este endereço. Verifique seu endereço.`

então gostaria de saber onde no código eu poderia identificar quando o problema é que o CEP faz parte de uma área de risco e quando realmente não é possível calcular.

**Comment by stavarengo** [comment]
Oi @Renatobdcs .
As classes que fazem consulta a CEPs são estas aqui.
https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/CalcPrecoPrazo.php
https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/ConsultaCep.php

Se encontrar algum problema pode reabrir o issue.
