### ISSUE TITLE
Declaração de conteúdo

### ISSUE THREAD

**Issue by estevaofelipe** [stavarengo/php-sigep#198]
Hoje recebi um aviso de um cliente que comentou sobre a obrigatoriedade de enviar a "Declaração de conteúdo" dos itens junto a etiqueta, mas não achei nada sobre o assunto, alguém sabe de algo sobre isso?

**Comment by jsferr** [comment]
Bom dia,


Em dezembro, os correios fizeram este comunicado.


http://www.correios.com.br/para-voce/avisos/apresentacao-de-nota-fiscal-na-postagem-de-encomendas-1

[http://correios.com.br/logo.png]<http://www.correios.com.br/para-voce/avisos/apresentacao-de-nota-fiscal-na-postagem-de-encomendas-1>

Apresentação de Nota Fiscal na postagem de encomendas ...<http://www.correios.com.br/para-voce/avisos/apresentacao-de-nota-fiscal-na-postagem-de-encomendas-1>
www.correios.com.br
Para cumprir o que determina a legislação tributária, os Correios a partir de 02/01/2018, passarão a exigir no ato da postagem de qualquer encomenda a respectiva ...



abs,



________________________________
De: estevaofelipe <notifications@github.com>
Enviado: terça-feira, 2 de janeiro de 2018 11:09
Para: stavarengo/php-sigep
Cc: Subscribed
Assunto: [stavarengo/php-sigep] Declaração de conteúdo (#198)


Hoje recebi um aviso de um cliente que comentou sobre a obrigatoriedade de enviar a "Declaração de conteúdo" dos itens junto a etiqueta, mas não achei nada sobre o assunto, alguém sabe de algo sobre isso?

**Comment by estevaofelipe** [comment]
@jsferr obrigado pela resposta, vou verificar se meu cliente consegue mandar a NF junto, caso contrário inicio o desenvolvimento da declaração como está saindo no mercado livre. Abç

**Comment by gustvao** [comment]
@estevaofelipe no fim seu cliente optou por mandar as NF junto?

**Comment by estevaofelipe** [comment]
@gustvao sim, o cliente está enviando a NF no pedido. Obrigado.
