### ISSUE TITLE
Ao fazer uso do fechaplpvariosservicos() está retornando esse erro. Não entendi o que seja.

### ISSUE THREAD

**Issue by jaymeproni** [stavarengo/php-sigep#199]
`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <soap:Fault>
            <faultcode>soap:Client</faultcode>
            <faultstring>Unmarshalling Error: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [7,5] </faultstring>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>`

**Comment by stavarengo** [comment]
Oi @jaymeproni.
Isso está me parecendo erro de enconding.
Vc consegue postar o conteúdo do XML que está sendo enviado na requisição?

**Comment by jaymeproni** [comment]
Bom dia @stavarengo 

Tivemos sucesso,mas deixo aqui nossa tratativa e agradecimento.

Segundo o nosso desenvolvedor que entrou em contato direto com a equpe responsável pelo SIGEP WEB, na verdade no manual pede para colocar o CDATA em cada campo.. quando na verdade todo o conteúdo do XML da PLP deve ir dentro de um único CDATA Segue o XML envelopado completo.

[PLP.txt](https://github.com/stavarengo/php-sigep/files/1651650/PLP.txt)

**Comment by stavarengo** [comment]
Obrigado pelo feedback @jaymeproni .

**Comment by leandrolfds** [comment]
Desta forma, funcionou corretamente pra mim.
obrigado

**Comment by catapandanilo** [comment]
Estou tendo o mesmo problema, se alguém puder enviar um exemplo válido seria de muita ajuda!

**Comment by giovannivecchi** [comment]
Tive o mesmo problema mas o modelo enviado pelo @jaymeproni PLP.txt resolveu pra mim.

PS: se alguem tiver utilizando o SoapUI pra teste tem que remover os Enter's, eu não consegui encontrar o motivo disso, mas deixando a requisição tudo em uma única linha resolveu.

Muito Obrigado !

**Comment by marcosgerene** [comment]
> Bom dia @stavarengo
> 
> Tivemos sucesso,mas deixo aqui nossa tratativa e agradecimento.
> 
> Segundo o nosso desenvolvedor, que entrou em contato direto com a equipe responsável pelo SIGEP WEB, na verdade no manual pede para colocar o CDATA em cada campo. Quando na verdade, todo o conteúdo do XML da PLP deve ir dentro de um único CDATA Segue o XML envelopado completo.
> 
> [PLP.txt](https://github.com/stavarengo/php-sigep/files/1651650/PLP.txt)

resolve https://github.com/stavarengo/php-sigep/issues/474
