### ISSUE TITLE
 Warning: include(FPDF/TPL.php): failed to open stream

### ISSUE THREAD

**Issue by albertobraschi** [stavarengo/php-sigep#200]
Boa noite. 

Estou com uma situação.
Não esta pegando alguns arquivos.
Alguem poderia me ajudar?

Log de erros.
https://pastebin.com/gAb2ZGMj

Agradeço desde ja.

**Comment by stavarengo** [comment]
Oi @albertobraschi 
O jeito mais fácil de fazer a instalação é usando o composer.
Segue o passa a passo descrito [aqui](https://github.com/stavarengo/php-sigep#instala%C3%A7%C3%A3o-com-composer-recomendado). Lá vc tbm vai encontrar a explicação de como fazer a instalação manual.
