### ISSUE TITLE
Nova lei dos correios

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#201]
Alguém sabe como faço pros correios aceitarem a postagem?
desde o dia 2 agora, estão exigindo nota fiscal, etc.

Mas não estou entendendo nada!!

O que é necessário pra eles começarem a aceitar minhas postagens? Basta colocar o valor do produto e a descrição do produto?

**Comment by IuryChristmas** [comment]
Boa tarde @lucaspaulino , dá uma olhada nessa [issue 198](https://github.com/stavarengo/php-sigep/issues/198) e vê se te ajuda a resolver esse problema, acredito que seja o mesmo problema

**Comment by lucaspaulino** [comment]
é isso mesmo @IuryChristmas
