### ISSUE TITLE
Problema ao Solicitar Etiquetas

### ISSUE THREAD

**Issue by srdavidsilva** [stavarengo/php-sigep#205]
Ola, 
Acredito ser uma duvida em relaçao ao processo, näo um bug ou algo do tipo.

Nesta chamada, apos definir os seguintes parametros:
```
$accessData = new \PhpSigep\Model\AccessDataHomologacao();
		$accessData->setUsuario('meuuser');
		$accessData->setSenha('minhasenha');
		$accessData->setCnpjEmpresa('meucnpj');
		$params = new \PhpSigep\Model\SolicitaEtiquetas();
		$params->setQtdEtiquetas(1);
		$params->setServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_E_SEDEX_STANDARD);
		$params->setAccessData($accessData);

		$phpSigep = new \PhpSigep\Services\SoapClient\Real();
		$codEtiqueta = $phpSigep->solicitaEtiquetas($params);
		dump($phpSigep);

```
Nao estou tendo retorno nenhum, o Objeto Real volta vazio.

Estou fazendo algo errado?

**Comment by stavarengo** [comment]
@srdavidsilva tente usar o WSDL local.
Siga essas instruções: https://github.com/stavarengo/php-sigep#problemas-com-o-php-53

**Comment by srdavidsilva** [comment]
@stavarengo obrigado pela resposta, pelo visto o WSDL está rodando aqui. 
Estou obtendo este retorno da API:

```

Result {#1353 ▼
  #isSoapFault: true
  #errorCode: 0
  #errorMsg: "Resposta do Correios: Não foi possível obter as etiquetas solicitadas."
  #result: null
  #soapFault: null
  #_failIfAtributeNotExiste: true
}
```

**Comment by srdavidsilva** [comment]
Veja, realmente parece que o problema não é com soap:
```

SoapClient {#1354 ▼
  +"_exceptions": false
  +"_encoding": "ISO-8859-1"
  +"_connection_timeout": 180
  +"_stream_context": stream-context resource @10 ▼
    options: array:1 [▼
      "ssl" => array:2 [▼
        "verify_peer" => false
        "verify_peer_name" => false
      ]
    ]
  }
  +"_soap_version": 1
  +"sdl": SOAP SDL resource @11
}
```
Mas eu não faço a mínima ideia ainda de por que este retorno, engraçado que a chamada para a etiqueta está totalmente de acordo com a documentação deles.

**Comment by andersonls** [comment]
@*srdavidsilva *Veja se o código do serviço que você está solicitando as
etiquetas e os dados do contrato estão corretos.

Quando apareceu essa mensagem para mim, era pq eu estava usando código do
serviço errado.

**Comment by srdavidsilva** [comment]
@andersonls Obrigado pela resposta.

Estou pensando ser isto mesmo, vou baixar o sistema de windows que tem na documentação do Correios para ver se a autenticação funciona.

Engraçado que eu consigo logar no SIGEP por este link:
http://www.corporativo.correios.com.br/encomendas/sigepweb/

**Comment by lucascolette** [comment]
@srdavidsilva conseguiu resolver essa issue? Estou com o mesmo problema.

**Comment by srdavidsilva** [comment]
Consegui sim Lucas!

O problema realmente era autenticação.

Conversei com o cara do Correio e ele me passou os dados certos.


*David Silva*

2018-02-15 16:06 GMT-02:00 Lucas Colette <notifications@github.com>:
