### ISSUE TITLE
Como debugar a solicitacao de etiquetas

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#206]
estou com dificuldade de imprimir o xml para enviar para os correios para identificar o motivo pelo qual eu fecho a plp mas nao entra no sistema dos correios, alguem pode me informar onde no codigo do solicitar etiquetas eu faco isso? ou se eh em outro lugar.

**Comment by stavarengo** [comment]
@criacaosites se não me engano o XML é gerado automaticamente pela classe [\SoapClient](http://php.net/manual/en/class.soapclient.php), por tanto, é provável que vc precise passar algum parâmetro de depuração para ter acesso ao XML gerado por ela.

De qualquer forma, um bom lugar par começar a depurar é aqui https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/SolicitaEtiquetas.php#L121
