### ISSUE TITLE
Demora no rastreamento

### ISSUE THREAD

**Issue by IuryChristmas** [stavarengo/php-sigep#207]
Boa tarde galera, estou com um problema... meus rastreamentos de objetos, demoram em média 4 minutos para serem feitos, mesmo se eu já tiver feito um rastreamento antes, ele continua a demorar o mesmo tempo de antes, já fiz alguns testes e a demora realmente é na espera pela resposta do WS dos correios.
Mas quando testo de forma local isso não acontece, as respostas são rápidas, existe a possibilidade de ser algum problema de configuração no servidor?

**Comment by gustvao** [comment]
@IuryChristmas conseguiu resolver isso?

**Comment by IuryChristmas** [comment]
@gustvao sim, eu precisei criar um cron pra limpar os arquivos de cache gerado pelo Soap na minha pasta tmp/
Depois disso ficou melhor, mas não consegui encontrar nenhuma explicação lógica

**Comment by jonyw4** [comment]
Bom saber disso, aqui acontece o mesmo...

**Comment by gustvao** [comment]
bom, tem alguma coisa no SRO deles que tem algum trigger que o primeiro request demora EXATOS 4 minutos para retornar. Depois disso fica rápido até perder o cache e voltar a ter 4 minutos.

O workaround é deixar um worker que não dá timeout esperando o request voltar depois de 4 minutos mesmo.. Fora isso funciona
