### ISSUE TITLE
Calculo de frete para mais de um produto

### ISSUE THREAD

**Issue by celsomtrindade** [stavarengo/php-sigep#210]
Caso eu tenha mais de um produto, como faço o cálculo do valor de entrega?

Apenas com somatório do peso dos produtos? Segundo informações na página do [_webservice_](http://www.correios.com.br/para-sua-empresa/comercio-eletronico/como-calcular-precos-e-prazos-de-entrega-em-sua-loja-on-line) do correios o cálculo do frete é feito de acordo com o peso cúbico, mas nos exemplos do cálculo existe apenas o campo de peso.

**Comment by jonyw4** [comment]
Aqui eu faço da seguinte forma:

1. Tenho o cadastro de todos os produtos da empresa com suas dimensões e peso
2. Tenho o cadastro de todas caixas disponíveis da empresa, suas dimensões e seu peso

Com isso em mãos eu faço o seguinte:
1. Calculo o volume de todos os itens (para isso multiplique todas dimensões e as quantidades de produto)
2. Calcule o volume de todas as caixas (ou ja deixe guardado) e compare em qual caixa irá caber esses itens
3. Some o peso da caixa com o peso de todos itens

Pronto. Você terá a agora a dimensão da caixa e o peso final estimado para o calculo do frete. Dá um pouquinho de trabalho, mas depois de fazer isso meus problemas aqui se reduziram praticamente a zero. Uso esse esquema para outras transportadoras tbm.

Não sei se essa foi exatamente a duvida mas a dica ta ai.
Abraços
