### ISSUE TITLE
Etiqueta inexistente

### ISSUE THREAD

**Issue by mateusff** [stavarengo/php-sigep#211]
Boa tarde,

Primeiramente agradecer pela criação do projeto. Muito útil e funcional. Com certeza iremos lhe pagar um cafézinho! rsrsrs
Vamos lá. Implantamos para um cliente e depois de mandar a primeira carga para os Correios veja o que nos relataram:

"Ligaram do correio e deu um problema la no importação do SIGEP, A etiqueta deu certo, mas no momento de passar a etiqueta para o sistema dá como não existe."

Vocês já viram algo assim? Tem algum procedimento a ser feito?

**Comment by jdgrieco** [comment]
@mateusff você gerou a PLP? 

Vc tem que gerar as etiquetas, criar uma PLP e transmitir a PLP através do método fechaPlpVariosServicos

**Comment by mateusff** [comment]
Bom dia jdgrieco.

Era isso mesmo. Não estava fechando a mesma. Valeu amigo. Muito obrigado.

**Comment by mateusff** [comment]
@jdgrieco

**Comment by mateusff** [comment]
Pessoal. Deu certo o fechaPlpVariosServicos .. Porém o mesmo tem demorado muito para processar. Segundo o cliente tem travado o sistema na maioria das vezes. Sabem o que pode estar ocorrendo?
