### ISSUE TITLE
Copia de arquivo XML enviado

### ISSUE THREAD

**Issue by micromart** [stavarengo/php-sigep#212]
Pessoal, me desculpem, talvez seja algo muito simples. Porém estou inciando e me surgiu uma dúvida. 
Fiz algumas alterações para homologar no correios conforme o manual deles solicita. Está postando a PLP normalmente no correios, porém alguns campos não estão gerando corretamente no XML de envio.
Existe alguma forma de salvar o XML gerado antes de postar no server do correios para verificar como foi gerado?

Obrigado

**Comment by stavarengo** [comment]
Nesta linha @micromart https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/FecharPreListaDePostagem.php#L35
