### ISSUE TITLE
fechaPlpVariosServicos demorando muito para processar

### ISSUE THREAD

**Issue by mateusff** [stavarengo/php-sigep#213]
Bom dia pessoal

O método fechaPlpVariosServicos tem demorado muito para processar. Isto é normal?

**Comment by andersonls** [comment]
Bom dia @mateusff , verifique as issues #158 e #144, ali tem uma discussão desse problema bem como alternativas para contorná-lo. Antes de abrir uma isssue, procure pelas já existentes no projeto!
