### ISSUE TITLE
Lentidão ao gerar etiquetas

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#214]
Boa tarde, gostaria de saber se tem como resolver o problema de lentidão ao gerar etiquetas. As vezes demora muito, e quando isto ocorre geralmente dá erro 404 ou então esses abaixo:

```
Warning: SoapClient::__doRequest(): SSL: Connection reset by peer in /home/lpwpw632/public_html/PhpSigep/Services/Real/SolicitaEtiquetas.php on line 75

Fatal error: Call to a member function getEtiquetaSemDv() on null in /home/lpwpw632/public_html/sigep.php on line 95
```

Alguém sabe o motivo e como resolver?

**Comment by lucaspaulino** [comment]
Me digam se estou fazendo corretamente...
Eu tenho 50 etiquetas. Eu separo os que são SEDEX de PAC, aí deu 40 PAC e 10 SEDEX, por exemplo, eu faço 2 solicitações, assim:
```
$dados_etiqueta -> setQtdEtiquetas(40); //PAC
e
$dados_etiqueta -> setQtdEtiquetas(10); //SEDEX
```

Aí depois de ter feito isto, eu crio um laço para pegar todas as etiquetas? Pq no momento eu faço um loop de todas as vendas, e faço de um em um a solicitação:
`$dados_etiqueta -> setQtdEtiquetas(1);`

Será por causa disto a lentidão?

**Comment by lucaspaulino** [comment]
?:

**Comment by lucaspaulino** [comment]
Alguém para tirar a minha dúvida?

**Comment by stavarengo** [comment]
Oi @lucaspaulino 
Estamos todos aqui :)
Se niquem respondeu é pq não entenderam ou pq não sabem responder 
A principio parece que está tudo certo com seu código.

**Comment by gustvao** [comment]
sempre eu solicito em poucas quantidades, nao tenho problemas dessa forma.. tente solicitar poucas várias vezes ao invés de muitas poucas vezes e veja se nao melhora a questao da lentidao
abs

**Comment by lucaspaulino** [comment]
Então, são geradas no mínimo 150 etiquetas por dia. Não dá para ir gerando de um em um, pois geramos também um relatório das etiquetas e aí o coletor assina. Imagina ficar assinando várias folhas, fora que vai perdendo mta folha.. então não tive tempo de testar ainda pq estamos com problemas nos correios. Mas ficou bem explicativo sim o tópico.

Eu coloquei para gerar todos as vendas PACs e SEDEXs em 2 arrays de acordo com o tipo. Então, peguei a quantidade de cada array e coloquei para solicitar a quantidade de etiquetas . Depois, só fiz um loop nos arrays e usei a função de modificar etiqueta. Fazendo isto, só fiz duas conexões (pac e sedex) no SOAP. Creio que a lentidão era por causa disto, pois para cada etiqueta era feito uma conexão SOAP.

Terça feira o problema com o contrato será resolvido, deu muitas vendas e o limite de 18k estourou kkk, e aí vamos testar se está tudo certo. Bom, fica a dica aí de como fiz. Se eu lembrar venho aqui falar se deu certo ou não, mas na teoria está tudo OK.
