### ISSUE TITLE
fechamento da PLP

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#215]
Ola pessoal ao executar o fechaPlpVariosServicos.php estou tendo retorno de erro

PhpSigep\Services\Result Object
(
    [isSoapFault:protected] => 1
    [errorCode:protected] => 0
    [errorMsg:protected] => Ocorreu um erro interno no Servidor.
    [result:protected] => 
    [soapFault:protected] => 
    [_failIfAtributeNotExiste:protected] => 1
)

Alguem pode me informar onde eu corrijo isso? Eh um problema no Soap? eu fi que ele esta habilitado no apache.

**Comment by andersonls** [comment]
@criacaosites Verifique se não há nenhum caracter especial no seu XML e se a codificação está correta.

Eu acabei sempre convertendo o XML para ISO-8859-1 e passando a codificação como parâmetro para o SOAP.

**Comment by criacaosites** [comment]
Onde eu faco essa conversao? no helper-criar-pre-lista? Eu estou usando os arquivos na integra com adaptacoes apenas para a minha aplicacao, o core do codigo do Stavarengo eu nao mudei.

**Comment by criacaosites** [comment]
Eu encontrei uma atualizacao no /src/PhpSigep/Services/Real/SolicitaXmlPlp.php mas estou resolvendo um outro erro de 404 ao chamar meu fechaplp,,, to vendo aqui vlw a dica

**Comment by criacaosites** [comment]
Resolvi o problema estava mesmo na minha aplicacao, o numero do endereco ia vazio no remetente o que gerou erro no fechamento da PLP.
[RESOLVIDO]
