### ISSUE TITLE
Dúvida: Comprimento + 10cm

### ISSUE THREAD

**Issue by ldseinhardt** [stavarengo/php-sigep#216]
alguém sabe porque têm esse + 10?

https://github.com/stavarengo/php-sigep/blob/1c28a24ca3b33309f742c16465f708d3b808c701/src/PhpSigep/Services/Real/FecharPreListaDePostagem.php#L282

**Comment by stavarengo** [comment]
Oi @ldseinhardt 
Experimenta tirar ele pra ver se a API do correios reclama alguma coisa.

**Comment by brunorthomaz** [comment]
Boa tarde,

Teoricamente não há problemas, desde que o pacote respeite as dimensões mínimas e máximas.

Comprimento: 16
Altura: 2
Largura: 11

Obs: Cada dimensão não pode passar de 105cm

C + A + L <= 200cm

**Comment by stavarengo** [comment]
Podemos fechar este issue?

**Comment by ldseinhardt** [comment]
Era uma dúvida só, obg.
