### ISSUE TITLE
Pergunta básica: como devo utilizar este software?

### ISSUE THREAD

**Issue by tonylampada** [stavarengo/php-sigep#217]
Exemplo: estou construindo um sistema de e-commerce em python e django.
Uma das coisas que preciso implementar é a impressão de etiquetas pra postagens.
Eu imaginava que esse imprimível era gerado pelo webservice dos correios, mas estou vendo olhando o código deste projeto (apesar de eu não saber p.n. sobre php) que não - é o próprio php-sigep que gera essas etiquetas.

Estou imaginando então que o melhor jeito de dar essa capacidade pro meu sistema seria subir uma instância do php-sigep do lado do meu backend em python, e implementar uma integração entre eles.

É isso mesmo? Eu tô pensando certo?

**Comment by ViLourenco** [comment]
Fala @tonylampada, tudo bem?
Primeira vez que estou usando esta API, mas conheço um pouco o sistema do Sigep Web de tanto meus clientes falaram, hehe. O Sigep Web é um programa dos correios para que os lojistas consigam ver suas encomendas, criar etiquetas, processar as listas de postagens e uma série de outras funcionalidades. E eles possuem um WebService de integração com este serviço, o manual é este: http://www.corporativo.correios.com.br/encomendas/sigepweb/doc/Manual_de_Implementacao_do_Web_Service_SIGEP_WEB.pdf

Este respositório aqui é da API é para integração usando PHP, você pode usar como mencionado ou integrar com Python pela documentação do link acima.

Abs.
