### ISSUE TITLE
solicitacao de etiqueta pac com codigo de sedex

### ISSUE THREAD

**Issue by criacaosites** [stavarengo/php-sigep#218]
Ola pessoal eu estou solicitando etiqueta com essa linha de comando no solicitaetiqueta que eu adaptei:

```php
if( $cod_servico == "PAC" ) {
    $params->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_CONTRATO_AGENCIA));
} else {
    $params->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_CONTRATO_AGENCIA));
}
```
Porem so obtenho etiquetas sedex mesmo forcando o $cod_servico...

**Comment by stavarengo** [comment]
Estranho @criacaosites. Pode ser alguma coisa com o contrato do seu cliente. Veja se consegue alguma pista usando o ambiente de homologação.
