### ISSUE TITLE
Dúvida: Utilização de frete reverso

### ISSUE THREAD

**Issue by amaurigabriel** [stavarengo/php-sigep#219]
Olá.

Como faço para gerar frete reverso com a lib? Tentei gerar uma etiqueta "comum" com o código dos serviços reversos, mas o cliente disse que não conseguiu postar na agência, pois alegaram que o código informado não era um código de autorização válido...

**Comment by andersonls** [comment]
Não é possível com os métodos para postagens comuns. Há um outro web service só para Logistica reversa (veja nos manuais). E acho que a bilbioteca ainda não tem implementado este webservice (pode confirmar @stavarengo?)

**Comment by stavarengo** [comment]
@andersonls é isso memso.

**Comment by afernandes** [comment]
Acredito que o webservice para logistica reversa seja este:
[https://cws.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl](https://cws.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl)
