### ISSUE TITLE
Impressão em impressora de etiqueta Elgin L42

### ISSUE THREAD

**Issue by rafaelsiqueira** [stavarengo/php-sigep#22]
Vocês já imprimiram as etiquetas nessa impressora Elgin L42 (recomendada pelos correios)? Foi tudo normal?

Eu fiz alguns testes, mas não rolou.

Os seguintes ajustes foram necessários:

1) Mudar o formato da página - Ao invés de usar uma folha A4 divida em 4 partes, precisei informar as dimensões corretas da impressora (no caso é 102mm por 152mm).

2) Reposicionar os elementos por conta da modificação do tamanho do papel

3) Fazer ajustes de posicionamento na chancela do Sedex.

Sugiro criar implementações diferentes da classe Chancela de acordo a impressora/papel a ser utilizado. O que acham?

Alguém passou por algum problema desse?

Abraços!

**Comment by stavarengo** [comment]
@rafaelsiqueira pelo jeito que vc falou parece que vc já implementou o código. É isso mesmo? Faz um PR que eu mesclo na master.

**Comment by rafaelsiqueira** [comment]
Sim, implementei, mas está hardcoded, ou seja, pode prejudicar quem utiliza
outro tipo de impressora, por exemplo.

Estou em processo de homologação junto aos Correios. Assim que tudo estiver
homologado, envio um PR.

Abraços!


*Rafael Siqueira*
*+55 (21) 98091-0023*

2016-01-04 11:26 GMT-02:00 Stavarengo <notifications@github.com>:

**Comment by stavarengo** [comment]
Ok Rafael. Vou esperar seu PR então. Valeu.

**Comment by rafaelsiqueira** [comment]
PR Enviado.
