### ISSUE TITLE
Entrega Interativa – Solicitação de suspensão da entrega

### ISSUE THREAD

**Issue by jonyw4** [stavarengo/php-sigep#220]
Pessoal tudo certo?

Estou com vários problemas aqui em meu ecommerce onde o Correios atrasa a entrega e o cliente solicita cancelamento do pedido. Procurando por soluções eu achei esse novo serviço web dos correios integrado ao SIGEP WEB chamado [ENTREGA INTERATIVA](https://www.correios.com.br/a-a-z/entrega-interativa-solicitacao-de-suspensao-da-entrega#tab-1). 
Esse serviço serve para suspender a entrega de qualquer envio.

[Na página 29 no manual do SIGEP WEB](http://www.corporativo.correios.com.br/encomendas/sigepweb/doc/Manual_de_Implementacao_do_Web_Service_SIGEP_WEB.pdf) já aparece como funciona e aparenta ser muito simples.

A minha dúvida é, alguém que usa aqui esse repositório, por acaso já implementou esse serviço? Ele funciona? Se sim compartilhem aqui pra gente. Eu vou tentar implementar por aqui e faço um pull request depois.

**Comment by stavarengo** [comment]
Legal. Olha que show @gustvao @andersonls

**Comment by jonyw4** [comment]
Gente, eu fiz aqui internamente na empresa pra testar e deu certo. Eu vou enviar o pull request mais tarde ai vocês revisam o código!

**Comment by jdgrieco** [comment]
@jonyw4, vi que o manual que você passou no link é atualizado, se puder acrescenta ele no PR

**Comment by stavarengo** [comment]
Maravilha @jonyw4 .
O manual vc coloca dentro [desta pasta](https://github.com/stavarengo/php-sigep/tree/master/manual)
Atualiza tbm o README.md falando que tbm temos essa função.

**Comment by jonyw4** [comment]
Acabei de mandar o PR com o link e atualizando o README, deem uma revisada #221
