### ISSUE TITLE
Erro 404

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#223]
Toda vez que tento gerar as etiquetas, as vezes da erro de Error Fetching http headers, é tempo limite de conexão. Aí oturas vezes da outro erro, mas aí ultimamente está dando o erro 404, e eu não sei o que é. Pq eu não mudo nada no código, só fico apertando F5 até gerar e baixar o PDF

**Comment by andersonls** [comment]
Acredito que seja instabilidade no WebService dos correios, nada que possa ser resolvido do lado do php-sigep.

**Comment by stavarengo** [comment]
@lucaspaulino 
Vc já viu [este](https://github.com/stavarengo/php-sigep/blob/master/exemplos/solicitarEtiquetas.php)?
