### ISSUE TITLE
Cartao de Postagem inexistente no ERP (Solução)

### ISSUE THREAD

**Issue by jonyw4** [stavarengo/php-sigep#227]
Tudo certo pessoal?

Hoje tive um problema que os Correios não estava achando o cartão de postagem no meu contrato. Era retornado o erro _"Cartao de Postagem inexistente no ERP"_. Depois de caçar erro descobri que o problema era no próprio cartão mesmo. **Todo cartão PRECISA ter 10 caracteres**, por algum motivo depois da atualização isso começou a rolar. Então tive que adicionar dois zeros a esquerda para dar os 10 caracteres. 

Caso alguém esteja com o mesmo problema fica ai a dica!

Abraços

**Comment by marlonassuncao** [comment]
Estou com o mesmo problema, coloquei os 00 mas não adiantou. Alguma dica?
