### ISSUE TITLE
Rastreamento de etiquetas

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#228]
Quando eu uso o usuário e senha padrão do manual (ECT e SRO), o rastreio vem normalmente, mas só o primeiro status do rastreio.
Mas quando configuro com os dados do contrato, não retorna nenhuma msg, etc:
`Array ( [*isSoapFault] => [*errorCode] => [*errorMsg] => [*result] => Array ( ) [*soapFault] => [*_failIfAtributeNotExiste] => 1 )`

Alguém sabe o pq?

obs.: eu consigo gerar normalmente as etiquetas.

**Comment by jdgrieco** [comment]
@lucaspaulino, o usuário e senha do SIGEP WEB e do SRO não são necessariamente iguais.

Solicite ao gerente da conta a criação de um usuário e senha para o sistema de rastreamento

**Comment by lucaspaulino** [comment]
@jdgrieco onde eu obtenho estes dados? Pra eu falar pra gerente aqui... esse SRO é login do portal, etc?

**Comment by jdgrieco** [comment]
@lucaspaulino, SRO = Sistema de Rastreamento de Objetos, vcs tem que pedir para os Correios criarem um usuário e senha para isso

**Comment by lucaspaulino** [comment]
@jdgrieco ela vai solicitar para mim. obrigado!
