### ISSUE TITLE
Inserção do Serviço Carta Comercial a Faturar Selo/SE (12556)

### ISSUE THREAD

**Issue by NeoGest** [stavarengo/php-sigep#231]
Precisamos fazer a inclusão do serviço "Carta Comercial a Faturar Selo/SE (12556)" e não estamos encontrando o ID do Serviço para fazer a atualização da lib com a inclusão deste.

Alguém poderia nos informar como conseguimos obter esse ID?

Já tentamos nos informar na agência e eles não souberam nos informar.

**Comment by Rwaldrighi** [comment]
Bom dia, @NeoGest, tudo bem?
Fiz uma consulta no método do buscaCliente dos correios e retornou pra mim o código.
<codigo>12556</codigo>
<dataAtualizacao>2018-05-24T15:58:41-03:00</dataAtualizacao>
<datajAtualizacao>118144</datajAtualizacao>
<descricao>CARTA COM A FATURAR SELO E SE</descricao>
<horajAtualizacao>155841</horajAtualizacao>

Espero que ajude.

**Comment by Rwaldrighi** [comment]
No projeto em exemplos tem o "buscaCliente.php", rodando ele o retorno será todas informações de serviços disponíveis para seu contrato, como o Código, Descrição e o Id.
