### ISSUE TITLE
Alteração do Código PAC Contrato

### ISSUE THREAD

**Issue by Fertusco** [stavarengo/php-sigep#232]
Prezados, boa tarde.

Minha agência dos correios informou que o código do PAC CONTRATO está incorreto, foi alterado para 004367.

Alguém poderia propor a alteração na branch master?

**Comment by Rwaldrighi** [comment]
@Fertusco Bom dia, tudo bem?
Esse código é utilizado para contrato com empresa de e-commerce que foi atribuído após uma liminar da ABCOMM, no projeto já esta implementado, no model ServicoDePostagem já existem os novos códigos.
// CODIGOS REFERENTES A LIMINAR ABCOMM
SERVICE_SEDEX_CONTRATO_GRANDES_FORMATOS_LM    = '04146';
SERVICE_SEDEX_CONTRATO_AGENCIA_LM             = '04154';
SERVICE_SEDEX_REVERSO_LM                      = '04243';
SERVICE_SEDEX_CONTRATO_UO_LM                  = '04278';
SERVICE_PAC_CONTRATO_GRANDES_FORMATOS_LM      = '04883';
SERVICE_PAC_CONTRATO_AGENCIA_LM               = '04367';
SERVICE_PAC_REVERSO_LM                        = '04375';
SERVICE_PAC_CONTRATO_UO_LM                    = '04332';
SERVICE_SEDEX_CONTRATO_AGENCIA_PAGAMENTO_NA_ENTREGA_LM    = '04151';
SERVICE_PAC_CONTRATO_AGENCIA_PAGAMENTO_NA_ENTREGA_LM      = '04308';

**Comment by stavarengo** [comment]
Podemos fechar a issue?
