### ISSUE TITLE
Help, ajuda com ambiente do Php-sigep

### ISSUE THREAD

**Issue by tonylampada** [stavarengo/php-sigep#235]
Eu sou programador python, tenho experiencia com desenvolvimento web, mas nada dessa experiência envolve php então preciso de ajuda com isso aqui.

Minha idéia é subir uma instância do php-sigep pra ver se consigo fazer meu e-commerce usar ele pra gerar etiquetas imprimiveis.

Não sei se a maneira que estou tentando rodar o php-sigep tah correta, ajuda é bem-vinda.

1) Estou tentando subir o php-sigep num docker com nginx e php-fpm. Meu Dockerfile contém o suficiente pra fazer o tal `composer update` funcionar sem problemas. Meu Dockerfile é assim:

```
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y libxml2-dev curl php-cli php-mbstring git unzip php-soap nginx php-fpm nano wget
WORKDIR /app
RUN cd && curl -sS https://getcomposer.org/installer -o composer-setup.php && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && cd /app
RUN mkdir /run/php
ADD . /app
RUN composer update
```

Em seguida eu inicio o container:

`docker run -it --rm -v $(pwd)/nginx/default:/etc/nginx/sites-enabled/default -v $(pwd):/app -w /app -p 80:80 phpsigep bash`

E esse cara usa uma configuração do nginx desse jeito:

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /app/src;
    index index.php index.html index.htm index.nginx-debian.html;
#    server_name domínio_do_servidor_ou_IP;
    location / {
        try_files $uri $uri/ =404;
    }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
    location ~ /\.ht {
        deny all;
    }
}   
```

Uma vez dentro do container eu posso subir o nginx e o php-fpm e... blz tá pé (meu browser consegue se conectar na porta 80) Mas como que eu testo? Como que eu gero uma etiqueta?

No demo online eu consigo ver que a etiqueta eh gerada fazendo um post assim:

![](https://image.ibb.co/iNCVaT/image.png)

Pra onde eu deveria fazer um post semelhante na minha aplicação? - Eu até tentei fazer um post semelhante pra cá `/PhpSigep/Pdf/CartaoDePostagem2016.php`, mas ele me retornou uma pagina em branco.

Bom, deu pra ver que eu to perdido ne :-)
Mas com um pouquinho de ajuda eu me acho. HELP! :D

**Comment by andersonls** [comment]
O PHP-Sigep é uma **API**, não tem nada pra você chegar dando POST e te retornar as etiquetas. Se você quiser usar dessa forma vai precisar implementar uma camada que recebe o POST, passa pras classes da API e retorna o resultado. Se quiser ir por esse caminho, os arquivos em exemplos podem ser um ponto de partida.

P.S.: já tentou procurar alguma coisa em python? Fazendo uma pesquisa rápida vi que tem projetos do sigep em python aqui no github (https://github.com/search?l=Python&q=sigep&type=Repositories).

**Comment by tonylampada** [comment]
Opa obrigado pela resposta rapida @andersonls !

> P.S.: já tentou procurar alguma coisa em python?
Ô, bastante! Até agora não encontrei algo que me ajude a gerar etiquetas imprimíveis (PDF) como a do screenshot acima.

> O PHP-Sigep é uma API, não tem nada pra você chegar dando POST e te retornar as etiquetas.

Mas então eu fiquei confuso agora. 
Quem tá gerando a etiqueta no screenshot que eu mandei acima? Não é o php-sigep?
Quando vc diz API, vc se refere à uma api do tipo "biblioteca"? Ou seja, eu teria que fazer uma aplicação em php e chamar as funções do PHP-sigep. Eh isso?

**Comment by tonylampada** [comment]
> Se você quiser usar dessa forma vai precisar implementar uma camada que recebe o POST, passa pras classes da API e retorna o resultado.

AH, então foi exatamente isso que o @stavarengo fez e botou no ar aqui --> http://phpsigep.stavarengo.com/?action=relatorios-pdf

Certo?! O mundo tá começando a fazer sentido de novo

Pô eu quero esse codigo dele, como eh q faz? hahaha
Alguma chance de liberar esse codigo adicional aih @stavarengo? (perguntar nao arranca pedaço)

**Comment by andersonls** [comment]
>  Quem tá gerando a etiqueta no screenshot que eu mandei acima? Não é o php-sigep?
é o php-sigep, mas tem uma página PHP que chama as classes ali.

>  Quando vc diz API, vc se refere à uma api do tipo "biblioteca"? Ou seja, eu teria que fazer uma aplicação em php e chamar as funções do PHP-sigep. Eh isso?

Isso mesmo. No teu ambiente, tenta acessar o arquivo exemplos/imprimirEtiquetas2016.php pelo navegador e vê se aparece a etiqueta. Esse arquivo é bem simples e vai ser tudo que você vai precisar se for apenas gerar as etiquetas (esse arquivo seria o modelo da tua "aplicação" em PHP). Se conseguir, alterar esse arquivo pra receber os parâmetros via POST e retornar o PDF em base64 pro python é moleza.

**Comment by tonylampada** [comment]
Melhorou :-)
Alguma dica pra esse erro aih?

![](https://image.ibb.co/kSuF9o/image.png)

**Comment by tonylampada** [comment]
Opa, resolvido com `apt-get install php-gd`

**Comment by tonylampada** [comment]
![](https://image.ibb.co/gheU28/image.png)

:+1: :+1: :+1: 

Valeu man! Vc eh o cara :-)

**Comment by andersonls** [comment]
Show! Só pegar os parâmetros agora com o $_GET ou $_POST e setar pra etiqueta sair com os dados que você quer.
