### ISSUE TITLE
cep de origem inválido

### ISSUE THREAD

**Issue by gustvao** [stavarengo/php-sigep#237]
pessoal, alguem sabe o que está acontecendo com nossos queridos correioos? aparentemente toda e qualuqer simulacao de frete está retornando o erro -2 de erro de cep de origem apesar de estar certo..

testei na pagina de demo e tambem acontece isso:

alguem enfrentando o mesmo problema?

![image](https://user-images.githubusercontent.com/5428331/41969879-43889f06-79df-11e8-8f3c-7e8b7fa21c82.png)

**Comment by andersonls** [comment]
Pois é, aqui também tá dando isso. Será que o Webservice tirou o dia de folga por causa da copa?

**Comment by brunorthomaz** [comment]
Bom dia,

Mesmo problema pra gente.

O que salvou a gente aqui foi um sistema de contingência que fizemos, até
agora está batendo com os valores do webservice.

Em qua, 27 de jun de 2018 08:53, Anderson Luiz Silvério <
notifications@github.com> escreveu:

**Comment by andersonls** [comment]
@brunorthomaz como é esse sistema de contingência, pode compartilhar conosco?

**Comment by dieguitoqueiroz** [comment]
Mesmo problema aqui, toda consulta retorna CEP inválido.

**Comment by gustvao** [comment]
eu tenho um sistema de contingência também.. mas mesmo assim é muito ruim..


será que todos ecommerces do brasil que nao tem continggência estao sofrendo? alguem tem contato com alguem dos correios para mandar email e avisar?

**Comment by brunorthomaz** [comment]
Mandamos email pros caras aqui, mas sem resposta por enquanto.

Em qua, 27 de jun de 2018 10:37, Gustavo Bobrow <notifications@github.com>
escreveu:

**Comment by jdgrieco** [comment]
Para mim também não está funcionando, e o pior é que o sistema **não** está gerando os códigos de rastreamento (etiqueta) também.

Além de ser praticamente impossível conseguir ter acesso ao suporte, o máximo que conseguimos fazer é comunicar o gerente da conta/agência, que via de regra não entendem nada de tecnologia para eles acionarem o suporte.

**Comment by gustvao** [comment]
parece que estão tentando consertar.. voltou a dar latência/ficar off

**Comment by gustvao** [comment]
aparentemente voltou.. acho que o estagiãrio dos correios deve ter feito merda.. mas corrigido

ainda com latencia gigante, mas corrigiram

![image](https://user-images.githubusercontent.com/5428331/41990837-f9319cec-7a19-11e8-8d12-74f7da86bae8.png)

**Comment by gustvao** [comment]
down ainda... os caras sao MTO ruins, pqp!

**Comment by gustvao** [comment]
parece que voltou.
