### ISSUE TITLE
Geração de Etiquetas em Homologação

### ISSUE THREAD

**Issue by walber-teixeira** [stavarengo/php-sigep#241]
Bom dia senhores!

Mais alguém está com problema em gerar etiquetas no ambiente de homologação ou só nós?

Está retornando o erro para nós:

> A PLP não será fechada, o(s) objeto(s) [EC37381620BR] já estão vinculados em outra PLP!

Tentamos mais de 100 etiquetas e nada. Alguém sabe quando se dá esse erro? E como resolver?

**Comment by andersonls** [comment]
O erro é exatamente o que está na mensagem! A etiqueta EC37381620BR já está vinculada com alguma PLP.

Verifique se a etiqueta que está passando no método fechaPlpVarioServicos está sendo obtida via webservice e não é uma etiqueta antiga, ou se o método fechaPlpVarioServicos não está sendo chamado mais de uma vez.

**Comment by walber-teixeira** [comment]
Obrigado pelo retorno @andersonls.

Desculpa a minha ignorância, me expressei mal rs.

Sim, as etiquetas foram obtidas pelo webservice mesmo, através do php-sigep.

Entendi sobre estar vinculado, etc... Mas isso para as todas as quase 100 etiquetas que tentamos é o X da questão.

Certificamos que está sendo chamado um a um, pois a maioria dos testes na tentativa de gerar, foram manuais.

**Comment by andersonls** [comment]
As vezes que apareceu esse erro pra mim era pq estava usando alguma etiqueta velha, fora isso não sei oq pode ser. Se puder postar o código que está usando talvez dê pra ajudar melhor.

**Comment by walber-teixeira** [comment]
Obrigado pelo retorno @andersonls.

Tudo indica que hoje voltou a funcionar normalmente, mas na última sexta-feira não estava sendo possível tanto com etiquetas velhas quanto as novas.

Detalhe: não mexemos em nada no código.

Vamos continuar monitorando e qualquer coisa posto aqui novamente.
