### ISSUE TITLE
Campo obrigatório não informado

### ISSUE THREAD

**Issue by jrmaia** [stavarengo/php-sigep#245]
Galera estou com problema na postagem na agência dos correios, eu gero a etiqueta pelo sistema sem nenhum problema, mas na hora de postar, o ERP dos correios retorna o seguinte erro:

Campo obrigatório não informado. (codigo_servico_adicional)

Meu código está assim:

        $_etiqueta = Mage::getModel('juniormaia_correios/sigep')->getEtiqueta($_data);
        $dimensao = new \PhpSigep\Model\Dimensao();
        $dimensao->setAltura(18);
        $dimensao->setLargura(27);
        $dimensao->setComprimento(36);
        $dimensao->setDiametro(0);
        $dimensao->setTipo(\PhpSigep\Model\Dimensao::TIPO_PACOTE_CAIXA);
        
        $destinatario = new \PhpSigep\Model\Destinatario();
        $destinatario->setNome($senderName);
        $destinatario->setLogradouro($address->getStreet(1));
        $destinatario->setNumero($address->getStreet(2));
        $destinatario->setComplemento($address->getStreet(3));
        
        $destino = new \PhpSigep\Model\DestinoNacional();
        $destino->setBairro($address->getStreet(4));
        $destino->setCep($digits->filter($address->getPostcode()));
        $destino->setCidade($address->getCity());
        $destino->setUf($this->getStateCode($address->getRegion()));
        $destino->setNumeroPedido($order->getIncrementId());
        $destino->setValorACobrar(0);

        $etiqueta = new \PhpSigep\Model\Etiqueta();
        $etiqueta->setEtiquetaComDv($_etiqueta);

        $servicoAdicional = new \PhpSigep\Model\ServicoAdicional();
        $servicoAdicional->setValorDeclarado(0); //coloquei como zero e mesmo assim não passa

        $encomenda = new \PhpSigep\Model\ObjetoPostal();
        $encomenda->setServicosAdicionais(array($servicoAdicional));
        $encomenda->setDestinatario($destinatario);
        $encomenda->setDestino($destino);
        $encomenda->setDimensao($dimensao);
        $encomenda->setEtiqueta($etiqueta);

A etiqueta é gerada certinha, mas na postagem dá isso:

[Erro ERP Postagem](https://prntscr.com/kbq61e)

Alguém sabe o que pode ser?

**Comment by jrmaia** [comment]
Opa @andersonls 

$servicoAdicional = new \PhpSigep\Model\ServicoAdicional();
$servicoAdicional>setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_REGISTRO);

Apenas isso?

**Comment by andersonls** [comment]
É pra ser isso.

**Comment by walber-teixeira** [comment]
@jrmaia achei muito pertinente seu problema, pode ser que mais pessoas tenham o problema e nós não tenhamos conhecimento desses acontecimentos por falta de contato (pecado grave) com o usuário final do sistema. @andersonls amigo, você acredita que devamos todos adicionar este método ao gerar as PLPs? ou é algo específico para o caso do @jrmaia?

**Comment by jrmaia** [comment]
Segundo os Correios:

```
<servico_adicional>
<codigo_servico_adicional>025</codigo_servico_adicional> //Registro obrigatório
<codigo_servico_adicional>001</codigo_servico_adicional> //AR opcional
<codigo_servico_adicional>019</codigo_servico_adicional> //Valor Declarado opcional
<valor_declarado>200,00</valor_declarado> //Se inserido código 019, valor é obrigatório, ex: 200,00
</servico_adicional>
```
Nesse caso que o contrato não utiliza AR e nem Valor declarado, o seguinte código resolveu o problema:

```
$servicoAdicional = new \PhpSigep\Model\ServicoAdicional();
$servicoAdicional>setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_REGISTRO);
```
O código acima manda o código 025 obrigatório na integração.

**Comment by andersonls** [comment]
@walber-teixeira Até onde eu sei esse código é obrigatório para todas as postagens, mesmo tendo os outros serviços adicionais (AR ou valor declarado).

Você tem alguma integração rodando sem informar esse código?

**Comment by walber-teixeira** [comment]
@andersonls desculpa pela demora em te responder, mas sim. Até eu ver essa issue, minha integração funcionava sem informar o código como padrão mesmo estando como obrigatório no manual. @Rwaldrighi valeu pela dica também.
