### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by gustvao** [stavarengo/php-sigep#246]
Galera, utimamente tenho recebido muitos warnigns de connection reset by peer dos correios.

Alguem passando por isso?

```php
ERROR: [2] SoapClient::__doRequest(): SSL: Connection reset by peer
REMOTE_ADDR: 35.239.27.7
HTTP_X_FWD: 
Warning on line 21 in file /home/.../php-sigep/src/PhpSigep/Services/Real/ConsultaCep.php
```

**Comment by arthr** [comment]
@gustvao estou passando pelo mesmo problema cara.
Alguns clientes já me ligaram para reportar o problema. Eu suponho que os correios estão passando por mais um problema de estabilidade de servidores, acho que esse problema se da quando ocorre a falha na autenticação nos servidores dos correios. O jeito é esperar normalizar.
Correios SIGEP 👎
