### ISSUE TITLE
Códigos de serviço atualizados?

### ISSUE THREAD

**Issue by vitor-veras** [stavarengo/php-sigep#249]
Olá galera,
Estava calculando o preço em alguns serviços(especificamente SEDEX e PAC) e comparando com o valor calculado pelo site dos [correios](http://www2.correios.com.br/sistemas/precosPrazos/) para ter certeza se correspondia. Porém o valor calculado pelo site e pelo php-sigep não correspondia.

Então fui inspecionar os códigos de serviço utilizados no site e eles estão diferentes.
Códigos de serviço do site:

![codigos_servico_site_correios](https://user-images.githubusercontent.com/20798819/45380031-0bc7b180-b5d8-11e8-9a89-5600b82c3003.PNG)

Será que os códigos de serviço foram atualizados?

**Comment by stavarengo** [comment]
OI @vitor-veras 
Como está trabalhando com os códigos?
Conseguiu alguma informação nova desde de quando cadastrou esse issue?

**Comment by vitor-veras** [comment]
Em nosso projeto, nós modificamos os códigos de serviço para estes que mandei na foto [acima](https://user-images.githubusercontent.com/20798819/45380031-0bc7b180-b5d8-11e8-9a89-5600b82c3003.PNG) para que o projeto continuasse. Depois do merge citado em #250 não cheguei a testar.
