### ISSUE TITLE
não consigo rodar o projeto no meu ambiente

### ISSUE THREAD

**Issue by rafaelrocha01** [stavarengo/php-sigep#251]
Boa tarde, estou com problema para rodar o projeto no meu ambiente, fiz a instalação pelo composer conforme manual, mas esta dando problema com configuração, gera a exceção falando pra eu setar as configurações antes de usar o php-sigep, e a variavel $config esta undefined, e em baixo fala de outro erro
FPDF ERROR: Some data has already been output, can't send PDF file.

Alguem pode me ajudar?

**Comment by stavarengo** [comment]
Oi @rafaelrocha01 
Pode colocar o log de erro para ver se consigo entender melhor?

**Comment by rafaelrocha01** [comment]
Bom dia @stavarengo, consegui resolver o problema obrigado, só tenho outra duvida, para eu gerar a etiqueta para imprimir no ambiente de produção, o que eu preciso alterar?, vi que no manual fala para executar alguns métodos antes mas não entendi muito bem, pode me ajudar?
