### ISSUE TITLE
Pegar código da Etiqueta

### ISSUE THREAD

**Issue by Moisa** [stavarengo/php-sigep#255]
Boa tarde Galera, preciso de uma ajuda. Como pego  o código da etiqueta retornar pelo \PhpSigep\Model\SolicitaEtiquetas();  não estou conseguindo extrar o codigo deste objeto abaixo.

object(PhpSigep\Services\Result)#14 (6) {
  ["isSoapFault":protected]=>
  bool(false)
  ["errorCode":protected]=>
  NULL
  ["errorMsg":protected]=>
  NULL
  ["result":protected]=>
  array(1) {
    [0]=>
    object(PhpSigep\Model\Etiqueta)#16 (4) {
      ["etiquetaComDv":protected]=>
      NULL
      ["etiquetaSemDv":protected]=>
      string(12) "SZ42852157BR"
      ["dv":protected]=>
      NULL
      ["_failIfAtributeNotExiste":protected]=>
      bool(true)
    }
  }
  ["soapFault":protected]=>
  NULL
  ["_failIfAtributeNotExiste":protected]=>
  bool(true)
}

**Comment by andersonls** [comment]
Tenta: `$objeto->getResult()[0]->getEtiquetaSemDv()` para pegar o código sem o dígito verificador
ou `$objeto->getResult()[0]->getEtiquetaComDv()` para pegar o código com o dígito verificador

**Comment by Moisa** [comment]
Obrigado andersonls, me ajudou muito!

> Tenta: `$objeto->getResult()[0]->getEtiquetaSemDv()` para pegar o código sem o dígito verificador
> ou `$objeto->getResult()[0]->getEtiquetaComDv()` para pegar o código com o dígito verificador

Obrigado andersonls, me ajudou muito!

**Comment by Moisa** [comment]
Obrigado andersonls, me ajudou muito!
