### ISSUE TITLE
Existe como relatar que pac/sedex/etc está em atraso?

### ISSUE THREAD

**Issue by jaymeproni** [stavarengo/php-sigep#256]
Existe como relatar que pac/sedex/etc está em atraso? Exemplo, supondo uma loja virtual que precisa diariamente de um relatório dos pedidos de deveriam ter sidos entregues no dia de ontem, ou seja, dia de chegada + 1 permite abertura de chamado para auxílio da logística e sac.

**Comment by andersonls** [comment]
Via webservice acredito que não exista a opção(e também acho que não seja de interesse do correio facilitar isso) O que existe é via [http://www2.correios.com.br/sistemas/falecomoscorreios/](site). Mas na minha experiência, para questão de atrasos, é só se você precisar enviar para o cliente que abriu o chamado, pq não ajuda em nada em agilizar a entrega ou receber uma posição do correio de onde está a mercadoria.
