### ISSUE TITLE
alguem já viu a nova página dos correios de components?

### ISSUE THREAD

**Issue by gustvao** [stavarengo/php-sigep#257]
https://apps.correios.com.br/componentes

Parece que eles estão melhorando as APIs/WebServices mas o negócio ainda me parece bastante confuso e burocrático.

Alguém sabe quando eles vão virar a chave e se todos os serviços seguirão o mesmo padrão? Inclusive acredito que o php-sigep seja afetado quando isso ocorrer..

Alguém está sabendo de algo? Tenho medo de uma hora pra outra eles resolverem não aceitar mais o método antigo e de repente nada funcionar... Bem a carinha deles com lack de comunicação etc...

Inclusive já viraram a chave para consulta internacional de precificação.. O modelo antigo não funciona mais, só pela forma nova.. Imagina se virarem a chave de uma vez para a consulta nacional? Vai ser o CAOS!

**Comment by brunorthomaz** [comment]
Bom dia,

Entrei em contato com os correios para saber sobre a nova API Rest de precificação.

Eles me informaram que por enquanto essa API é só interna e ainda não tem previsão de liberação para uso externo.

Att.

**Comment by gustvao** [comment]
Oi @brunorthomaz , obrigado.

Você pode nos falar qual meio entrou contato? Email, telefone? E qual?

Chegou a perguntar da precificação de envio internacional? Aparentemente removeram o acesso do webservice antigo e só funciona agora por esse novo. Parece então que não é tão interno assim rs

**Comment by brunorthomaz** [comment]
Boa tarde,

Nós temos um consultor na empresa que tem contato por email com o pessoal do time técnico dos correios.

Não cheguei a perguntar sobre envio internacional (**292**), perguntei somente a consultas nacionais (**275**) (Temos contrato de intermediação nacional).

Se você tentar fazer uma consulta no **275** através do link abaixo, você obterá a seguinte mensagem de erro: "Perfil de acesso não autorizado. Disponibilização de acesso é INTERNA e a credencial é EXTERNA"

https://apps.correios.com.br/componentes/home/index.html#/documentacao/rest/192/275

Att.
