### ISSUE TITLE
PHP Sigep WEB - Gerar XML da PLP

### ISSUE THREAD

**Issue by mateusf97** [stavarengo/php-sigep#261]
Olá!

Estou implementando no meu sistema um sistema de postagem que utiliza a API dos correios para postagem utilizando o SIGEP WEB

Estou com problemas para gerar o XML de uma PLP para levar para o gerente dos correios realizar a  validação

   ```
   require_once 'php-sigep/src/PhpSigep/Bootstrap.php';

      $accessDataParaAmbienteDeHomologacao = new \PhpSigep\Model\AccessDataHomologacao();

      $config = new \PhpSigep\Config();
      $config->setAccessData($accessDataParaAmbienteDeHomologacao);
      $config->setEnv(\PhpSigep\Config::ENV_PRODUCTION);
      $config->setCacheOptions(array('storageOptions' => array('enabled' => false,'ttl' => 10,'cacheDir' => sys_get_temp_dir(),)));

      \PhpSigep\Bootstrap::start($config);

      $accpSigep = new PhpSigep\Services\SoapClient\Real();
      //$response = $phpSigep->SolicitaXmlPlp($plp_number);
      $response = $phpSigep->SolicitaXmlPlp(163779926);

      echo "<pre>";
      print_r($response);essData = new \PhpSigep\Model\AccessDataHomologacao();
      $phpSigep = new PhpSigep\Services\SoapClient\Real();
      //$response = $phpSigep->SolicitaXmlPlp($plp_number);
      $response = $phpSigep->SolicitaXmlPlp(163779926);

      echo "<pre>";
      print_r($response);
```
O código funciona bem, não tenho problemas com a implementação do código essa é só mais uma das várias funções implementadas, o problema é a resposta que estou tendo

Sempre tenho como resposta:

```
PhpSigep\Services\Result Object
(
    [isSoapFault:protected] => 1
    [errorCode:protected] => 0
    [errorMsg:protected] => Resposta do Correios: Plp ainda não atualizada pelo Sara.
    [result:protected] => 
    [soapFault:protected] => 
    [_failIfAtributeNotExiste:protected] => 1
)

```
Parece que não consigo gerar o XML da PLP que acabei de gerar e fechar, enquanto eu não postar a encomenda, porém eu preciso do XML para levar nos gerente dos correios para validação

como proceder mediante a isso? alguém já passou por algo parecido? estou realizando algo de forma errada?

**Comment by andersonls** [comment]
@mateusf97 Você pode explicar melhor qual o teu fluxo? De onde você tirou esse número de PLP (163779926)?

**Comment by mateusf97** [comment]
Esse número da PLP é o número que é retornado no fechaPlpVariosServicos()

 ```
  $phpSigep = new PhpSigep\Services\SoapClient\Real();
   $result = $phpSigep->fechaPlpVariosServicos(unserialize($plp));

```
Ele é o Id da PLP que resulta de:

`   $result->getResult()->getIdPlp();
`
Este id é o que tem que ser utilizado para chamar o SolicitaXmlPlp();

```
   $phpSigep = new PhpSigep\Services\SoapClient\Real();
   $response = $phpSigep->SolicitaXmlPlp(163779926);
```

**Comment by mateusf97** [comment]
Isto está definido no arquivo SolicitaXMLPlp.php na linha 19
```

class SolicitaXmlPlp
{
    /**
     * @param integer $idPlpMaster
     *
```

**Comment by andersonls** [comment]
Então, no método fechaPlpVariosServicos o XML já é enviado pros correios. 

Verifique com o seu gerente, pois na minha experiência o que eles pedem é uma etiqueta para testar a postagem. Nesse caso você já fez o primeiro passo que é enviar a PLP para o correio via webservice, agora é só imprimir a etiqueta do objeto dessa PLP e levar pro gerente.

O método SolicitaXmlPlp é pra ser chamado somente após a postagem mesmo, pois esse método o correio retorna o XML com alguns campos preenchidos referentes a postagem. De acordo com a documentação do Sigep-Web: **Este  método  retorna o mesmo xml  da  PLP que  foi  anteriormente  enviada pelo cliente no  fechamento  da  PLP, sendo  atualizado no  ato  da postagem dos  objetos  nos  Correio**

Se for o caso deles querem realmente o XML, acho que vai precisar fazer alteração no projeto.

**Comment by plusites** [comment]
Pessoal, estou com um problema neste tema.

Quando chamo o fechaPlpVariosServicos.php
Apresenta o seguinte erro:
Fatal error: Call to undefined method PhpSigep\Config::getXmlEncode() in /public_html/loja2/Sigep/src/PhpSigep/Services/Real/FecharPreListaDePostagem.php on line 85

Alguem sabe o que pode estar ocorrendo?

**Comment by plusites** [comment]
Pessoal,
Estou tentando implantar esta integração, e realmente a gerente do Correios pede o XML de fechamento da PLT que é transmitida. Como posso capturar ?
Pois quando chamo o arquivo fechaPlpVariosServicos.php ele somente exibe este resultado:
Array
(
    [*isSoapFault] => 
    [*errorCode] => 
    [*errorMsg] => 
    [*result] => PhpSigep\Model\FechaPlpVariosServicosRetorno Object
        (
            [idPlp:protected] => 20175782
            [_failIfAtributeNotExiste:protected] => 1
        )

    [*soapFault] => 
    [*_failIfAtributeNotExiste] => 1
)

Precisava do XML que foi transmitido

**Comment by andersonls** [comment]
Você precisa inserir uma linha dentro do `fechaPlpVariosServicos.php` para salvar o XML.
