### ISSUE TITLE
código interno correio para serviços de postagem

### ISSUE THREAD

**Issue by gustvao** [stavarengo/php-sigep#263]
PEssoal,

Alguem sabe como eu consigo o código dos correios de modalidade? Conforme exemplo abaixo que está no arquivo:
https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Model/ServicoDePostagem.php

Queria saber a forma de conseguir esse número 109819 a partir do 41068

```php
self::SERVICE_PAC_41068                     => array('Pac 41068', 109819),
```

**Comment by brunorthomaz** [comment]
Boa noite,

Se estiver vinculado ao seu contrato, acredito que consultando o cartão de postagem você conseguirá essa informação.

Att.

**Comment by gustvao** [comment]
Obrigado. Sabe se tem algum método que devolve as informações do cartao de postagem aqui nesse repositório?

**Comment by brunorthomaz** [comment]
Se eu não me engano, esse aqui deve retornar:

https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/BuscaCliente.php

**Comment by gustvao** [comment]
Era isso mesmo.

Mto obrigado, @brunorthomaz
