### ISSUE TITLE
Class PhpSigepFPDF not found

### ISSUE THREAD

**Issue by vitorini** [stavarengo/php-sigep#266]
Joguei ele em um projeto codeigniter para usar e fica dando esse erro. Já tentei dar um require na classe, mas dá outro erro doido. Alguém sabe o que pode ser?

Fatal error: Class 'PhpSigepFDPF' not found in /home/suporte/Documentos/projetos/nxd/rebens-tim/src/php/lib/PhpSigep/Pdf/ImprovedFPDF.php on line 10

**Comment by Jack184** [comment]
Olá amigo!

Instale a dependência https://github.com/stavarengo/php-sigep-fpdf via composer ou baixe manualmente. Você precisa ter as 2 para funcionar. Exemplo composer.json:

`{
    "require": {
        "stavarengo/php-sigep-fpdf": "dev-master",
        "stavarengo/php-sigep": "dev-master"
    }
}`

No CMD rode o comando: 
> composer update


Depois faça o include:

include 'seu-caminho-relativo/php-sigep-fpdf/PhpSigepFPDF.php';

Espero ter ajudado.

**Comment by vitorini** [comment]
Olá. Consegui resolver de outro jeito. Obrigado pela atenção.

Em Qui, 22 de nov de 2018 09:33, Jack184 <notifications@github.com escreveu:

**Comment by relpcam** [comment]
@vitorini  e qual outro jeito você conseguiu resolver?

Eu estou tendo o mesmo problema e não consigo solucionar.
