### ISSUE TITLE
Ciclo de vida da plp

### ISSUE THREAD

**Issue by Jack184** [stavarengo/php-sigep#268]
Olá. Primeiramente gostaria de agradecer por essa maravilhosa biblioteca. Estou com uma dúvida e gostaria de saber se alguém pode clarear um pouco as coisas para mim.

Estou desenvolvendo uma aplicação em que eu seleciono alguns pedidos do meu ecommerce  para gerar 1 PLP. Para isso, eu utilizo a classe PhpSigep\Model\PreListaDePostagem(). Até aí ok. Eu consigo enviar a PLP e salvar o id da mesma em minha base de dados. O que eu realmente preciso saber é se existe uma forma de acessar essa PLP através do ID para gerar o PDF de impressão em um arquivo separado onde não tenho mais o objeto gerado pela classe PhpSigep\Model\PreListaDePostagem(). Existe alguma documentação sobre isso. Agradeço desde já.

**Comment by andersonls** [comment]
Bom dia, o webservice dos correios não possui métodos para geração de PDF, nem de etiquetas nem de PLP. A bilbioteca tem classes para geração de ambas, porém você precisa montar e passar os mesmos parâmetros utilizados quando fecha a PLP.

Veja o exemplo [mprimirPlp.php](https://github.com/stavarengo/php-sigep/blob/master/exemplos/fechaPlpVariosServicos.php)

**Comment by Jack184** [comment]
Então preciso monta-la novamente. Obrigado por esclarecer @andersonls !
