### ISSUE TITLE
Configuração

### ISSUE THREAD

**Issue by rabelorp** [stavarengo/php-sigep#27]
Bom dia pessoal, essa é uma dúvida muito primaria, mas faz tempo que não programo. Espero que compreendam isso.

Preciso pegar a etiqueta gerada no .../exemplos/solicitarEtiquetas.php e envia-lá para ...exemplos/geraDigitoVerificadorEtiquetas.php para depois imprimir a etiqueta e plp, igual segue nesse link: http://stavarengo.github.io/php-sigep/

Só geramos etiquetas c/ DV, por isso tenho que seguir essa sequência.

Eu teria acesso ao código dessa página? Seria ideal pra pegar ideia 
http://phpsigep.stavarengo.com/?action=relatorios-pdf

Muito obrigado pela atenção!

(17)981410907 whats
rabelo_rp@hotmail.com

**Comment by stavarengo** [comment]
@rabelorp O código dessa página vc econtra aqui https://github.com/stavarengo/php-sigep/blob/master/exemplos/imprimirEtiquetas.php
