### ISSUE TITLE
Problema ao usar "consultaCep" ou "listarAgenciaCliqueRetire"

### ISSUE THREAD

**Issue by marcosdourado** [stavarengo/php-sigep#270]
Olá, a todos. Antes de mais nada, obrigado por essa biblioteca maravilhosa, li o manual dos correios e fiquei pasmo, li a biblioteca de vocês e fiquei feliz.

Ao tentar executar alguns exemplos, tenho obtido o seguinte erro:

```
Notice: Undefined property: stdClass::$complemento in .../php-sigep/src/PhpSigep/Services/Real/ConsultaCep.php on line 38

Notice: Undefined property: stdClass::$id in .../php-sigep/src/PhpSigep/Services/Real/ConsultaCep.php on line 41

```
Os exemplos que tentei executar foram: 
[consultaCep](https://github.com/stavarengo/php-sigep/blob/master/exemplos/consultaCep.php)
[listar-agencias-clique-retire](https://github.com/stavarengo/php-sigep/blob/master/exemplos/listar-agencias-clique-retire.php)

É bem provável que eu esteja cometendo algum erro bobo, mas não consigo saber qual. Se alguém souber me responder ou me direcionar, serei imensamente grato :)

**Comment by marcosdourado** [comment]
Comentando as linhas, entendi o problema.
A resposta que vem dos correios vem assim:
```
object(stdClass)[12]
  public 'return' => 
    object(stdClass)[13]
      public 'bairro' => string 'Setor Central' (length=13)
      public 'cep' => string '74015120' (length=8)
      public 'cidade' => string 'Goiania' (length=7)
      public 'complemento2' => string '' (length=0)
      public 'end' => string 'Rua 23' (length=6)
      public 'uf' => string 'GO' (length=2)
```

Então no método `ConsultaCep` ele tenta buscar elementos que não existem na reposta em **_r_**.
Devo desconsiderar estes erros ? E uma última dúvida, deveria existir uma verificação prévia dos elementos na resposta, para evitar isso ?

**Comment by andersonls** [comment]
@marcosdourado Não é um erro, apenas um notice que não afeta no funcionamento do código. Mas sim, seria interessante ter esse tipo de verificação.

Se quiser contribuir, pode fazer um PR com este tipo de verificação para os campos que não são obrigatórios no retorno (Acredito que seja os campos de complemento, rua e bairro).

**Comment by marcosdourado** [comment]
@andersonls  Entendi, vou verificar no manual dos Correios e descobri quais são obrigatórios e quais não são, no meu caso o Id também está com problema. Obrigado :)
