### ISSUE TITLE
VerificaDisponibilidadeServico Timeout

### ISSUE THREAD

**Issue by avlima** [stavarengo/php-sigep#271]
App: Laravel
Php: 7.2

Olá amigos e mantenedores,

Estou com problema de timeout no serviço de verificação de disponibilidade. Os demais serviços quem tenho utilizado estão ok apenas o de disponibilidade que estou com problema de timeout.

Alguém está enfrentando o mesmo problema?

Grato.

**Comment by avlima** [comment]
Realizando testes pude reparar que ao verificar a disponibilidade de apenas um (1) serviço a api retorna ok, mas ao consultar três (3) ou mais já começa a ficar muito lento e não utilizável.

Alguma ideia do que possa ser?

**Comment by mauroagr** [comment]
@avlima dá uma olhada neste cometário, foi feito uma atualização do codigo, depende te ajuda 
#280 
Roda um update no composer, e testa novamente.

**Comment by avlima** [comment]
> @avlima dá uma olhada neste cometário, foi feito uma atualização do codigo, depende te ajuda
> #280
> Roda um update no composer, e testa novamente.

Muito obrigado, deu certo aqui.

Fiz a mesma implementação no soap de rastreio.
