### ISSUE TITLE
Controle de versão no packagist

### ISSUE THREAD

**Issue by diegosurita** [stavarengo/php-sigep#272]
Olá.
Eu gostaria de saber se existe a possibilidade de ser feito o controle de versão (vi que na issue #121 já foi discutido sobre isto), no packagist. Eu vi que as tags de versionamento estão sendo feitas aqui no repositório, mas no README.md ainda tem instruções de que seja utilizado através da branch `dev-master` no composer.

Tive um problema em um sistema antigo que tive que reconfigurá-lo em outro servidor. Provavelmente teve alguma alteração no php-sigep que gerou a quebra do meu código. No caso se eu tivesse limitado no composer.json a versão mais antiga do php-sigep, não quebraria.

Não sei se fui claro.
Obrigado.

**Comment by stavarengo** [comment]
Sim.
Podemos tentar.
