### ISSUE TITLE
Uncaught SoapFault exception [HTTP] Not Found VerificaDisponibilidadeServico

### ISSUE THREAD

**Issue by avlima** [stavarengo/php-sigep#273]
Boa tarde,

Até ontem o serviço estava normal, mas hoje me deparei com o seguinte erro:

`Fatal error: Uncaught SoapFault exception: [HTTP] Not Found in /Projetos/git/php-sigep-master/src/PhpSigep/Services/Real/VerificaDisponibilidadeServico.php:39 Stack trace: #0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://apphom.c...', '', 1, 0) #1 /Projetos/git/php-sigep-master/src/PhpSigep/Services/Real/VerificaDisponibilidadeServico.php(39): SoapClient->__call('verificaDisponi...', Array) #2 /Projetos/git/php-sigep-master/src/PhpSigep/Services/SoapClient/Real.php(26): PhpSigep\Services\Real\VerificaDisponibilidadeServico->execute(Object(PhpSigep\Model\VerificaDisponibilidadeServico)) #3 /Projetos/git/php-sigep-master/exemplos/verificaDisponibilidadeServico.php(12): PhpSigep\Services\SoapClient\Real->verificaDisponibilidadeServico(Object(PhpSigep\Model\VerificaDisponibilidadeServico)) #4 {main} thrown in /Projetos/git/php-sigep-master/src/PhpSigep/Services/Real/VerificaDisponibilidadeServico.php on line 39`

Alguém já passou por isso?

Obrigado.

**Comment by devtas** [comment]
Olá .. Também estou tendo o mesmo erro hoje!

Aparentemente é um erro temporário, visto que ontem também estava funcionando para mim!

**Comment by avlima** [comment]
> Olá .. Também estou tendo o mesmo erro hoje!
> 
> Aparentemente é um erro temporário, visto que ontem também estava funcionando para mim!

Então acabei utilizando a ferramente SoapUI e está funcionando o Soap dos correios, provavelmente é alguma coisa aqui na biblioteca do php-sigep mesmo.
![screen shot 2018-12-04 at 4 00 11 pm](https://user-images.githubusercontent.com/13434925/49462660-c1705e00-f7dd-11e8-8f3a-badceb276bc9.png)

**Comment by devtas** [comment]
Eu estou obtendo o erro no método:

PhpSigep\Services\SoapClient\Real()->solicitaEtiquetas()

O restante dos métodos, aparentemente, estão funcionando normalmente.

**Comment by devtas** [comment]
E a sua requisição está retornando 0 / false, então teoricamente o serviço não está disponível, correto?

**Comment by avlima** [comment]
> E a sua requisição está retornando 0 / false, então teoricamente o serviço não está disponível, correto?
 
É o retorno correto segundo: http://www.corporativo.correios.com.br/encomendas/sigepweb/doc/Manual_de_Implementacao_do_Web_Service_SIGEP_WEB.pdf.

Returno false / true era em uma versão antiga.
Já testou o serviço de disponibilidade no ambiente de development?

**Comment by devtas** [comment]
Eu estava com a documentação antiga… :/
Então, estou testando no ambiente de dev mesmo.

Vou aguardar algumas horas, pois assim como parou de funcionar de repente, pode voltar da mesma forma.

Qualquer coisa, aviso aqui.

**Comment by avlima** [comment]
Blz, fico no aguardo.

Obrigado.

**Comment by devtas** [comment]
Olá @stavarengo 

Tem alguma ideia do que possa estar acontecendo?

Obrigado.

**Comment by stavarengo** [comment]
Só com o a mensagem de erro resumida é dificil dizer, mas tem uma pista ali.
A mensagem começa dizendo `Fatal error: Uncaught SoapFault exception: [HTTP] Not Found`.
Esse `[HTTP] Not Found` pode indicar que a API deles mudou o endereço de algum endpoint ou até mesmo da API como um todo.

@avlima, você consegue o conteúdo da resposta desta requisição? (Body, headers, etc. O que estiver disponível) Talvez isso ajude.

**Comment by avlima** [comment]
Galera tentei pegar o erro do SoapFault e desses possíveis retornos:
`
public $faultcode;
public $faultstring;
public $faultactor;
public $detail;
public $faultname;
public $headerfault;
`

Somente retornaram:
$faultcode = HTTP;
$faultstring = Not Found;

Não consegui pegar nada especifico pois todo o erro é genérico.
@devtas @stavarengo conseguem me ajudar nesse assunto? Pelo menos dar uma luz do que fazer para que eu teste aqui.

Obrigado.

**Comment by avlima** [comment]
@devtas Pois é, realmente é um erro muito vago.

Vou continuar tentando depurar.

**Comment by devtas** [comment]
Eu também .. Estou conectando vai SOAPUI e conferindo todos os campos..

**Comment by devtas** [comment]
@avlima O código para de executar no arquivo **/PhpSigep/Services/Real/SolicitaEtiquetas.php**

$request = SoapClientFactory::getSoapClient()->solicitaEtiquetas($soapArgs);

**Comment by avlima** [comment]
@devtas Depurando esse serviço ele me retorna o seguinte:
`
Result {#417
  #isSoapFault: true
  #errorCode: 0
  #errorMsg: "Resposta do Correios: Not Found"
  #result: null
  #soapFault: null
  #_failIfAtributeNotExiste: true
}
`

**Comment by devtas** [comment]
Sim..

Me parece que o método getSoapClient() não está retornando a interface de solicitaEtiquetas() em \PhpSigep\Model\SolicitaEtiquetas

**Comment by avlima** [comment]
> Sim..
> 
> Me parece que o método getSoapClient() não está retornando a interface de solicitaEtiquetas() em \PhpSigep\Model\SolicitaEtiquetas

Pois é, parece que ele não está retornando o VerificaDisponibilidadeServico também.
Vou tentar fazer alguns testes aqui.

**Comment by devtas** [comment]
O getSoapClient retorna o model de Soap do AtendeCliente. Não estou conseguindo identificar porque não traz a classe inteira do AtendeCliente.

=(

**Comment by avlima** [comment]
Atualizando...

Testamos em Ruby e tivemos o mesmo problema.
![screen shot 2018-12-05 at 16 41 37](https://user-images.githubusercontent.com/13434925/49538829-6f017100-f8b3-11e8-95b0-f9736e07eee8.png)

Por tanto não se limita ao Soap do PHP.

Entrei em contato com o suporte técnico dos correios e estou aguardando uma resposta.

Atualizo assim que tiver um contato da parte deles, por favor me ajudem a resolver esse problema se tiverem um contato técnico dos correios mais eficaz.

Obrigado

**Comment by andresnjr** [comment]
Apenas atualizando...

Fiz um teste do mesmo Código em Ambiente de Produção e deu certo, mas se mudar para 

Homologação não funciona.

Creio eu que houve alguma mudança nos correios.

**Comment by stavarengo** [comment]
Essa parte da mensagem postada pelo @avlima  deixa bem claro que a resposta `Not Found` está sendo enviada pelo servidor do Correidos. Ao meu ver, a requisição está chegando na Api deles, mas a URL requisitada não existe mais. Em outra palavras, a URL mudou, e quem está dizendo isso é a própria API do Correios.

![image](https://user-images.githubusercontent.com/816369/49595617-8302ac80-f95f-11e8-80db-1079b3b13676.png)

**Comment by MatheusAriel** [comment]
Algum posicionamento por parte dos correios? Testei usando o SoapUI e o wsdl de teste deles, apesar de listar todas as funções, está retornando not Found.

**Comment by avlima** [comment]
> Algum posicionamento por parte dos correios? Testei usando o SoapUI e o wsdl de teste deles, apesar de listar todas as funções, está retornando not Found.

Ainda estou trocando e-mails com os correios sobre o problema, mas está complicado :(

**Comment by MatheusAriel** [comment]
Existe alguma solução temporária para esse problema? Estou com um projeto parado por conta disso, n sei o que fazer já, estou um pouco preocupado

**Comment by avlima** [comment]
Nada ainda galera, a única novidade que eu tenho é sobre uma alteração de código de um SEDEX que está no documento mais atualizado.

Assim que tiver uma solução para o problema real eu mando um pull request com as atualizações.

**Comment by brunorthomaz** [comment]
Olá, Bom dia

Tenho um contato bom lá dentro dos correios, vou ver se consigo agilizar uma resposta.

Valeu.

**Comment by avlima** [comment]
Bom dia,

Galera parece que normalizaram os serviços, porém alguns deles estão dando falha como por exemplo verificaDisponibilidadeServico e solicitarEtiquetas.

Provavelmente porque alguns serviços mudaram os seus códigos e precisam ser atualizados.

Eu conseguirei trabalhar nisto somente amanhã, se alguém puder atualizar os serviços com os novos códigos seria ótimo se não amanha eu começo a trabalhar nisto.

Obrigado @brunorthomaz e todos que nos ajudaram.

Peço para que esse issue continue aberto até os serviços estarem funcionando normalmente.

Vlw.

**Comment by MatheusAriel** [comment]
Posso tá fazendo confusão mas no método buscaServicos() não estou achando sobre o Sedex 40096, será q o mesmo foi removido?

**Comment by avlima** [comment]
> Posso tá fazendo confusão mas no método buscaServicos() não estou achando sobre o Sedex 40096, será q o mesmo foi removido?

Não existe mais este serviço `40096` por isso a necessidade de atualizar a lista de serviços, como comentei acima.

**Comment by brunorthomaz** [comment]
> Bom dia,
> 
> Galera parece que normalizaram os serviços, porém alguns deles estão dando falha como por exemplo verificaDisponibilidadeServico e solicitarEtiquetas.
> 
> Provavelmente porque alguns serviços mudaram os seus códigos e precisam ser atualizados.
> 
> Eu conseguirei trabalhar nisto somente amanhã, se alguém puder atualizar os serviços com os novos códigos seria ótimo se não amanha eu começo a trabalhar nisto.
> 
> Obrigado @brunorthomaz e todos que nos ajudaram.
> 
> Peço para que esse issue continue aberto até os serviços estarem funcionando normalmente.
> 
> Vlw.

Boa tarde,

Consegui pegar rastreios com o 04669 e 04162.
Quais os códigos de serviço que você está utilizando ?

Abraço

**Comment by avlima** [comment]
São vários, mas para os mais comuns eu deixo eles aqui para não travarem vocês até todos estarem atualizados.

Por favor utilizem esses:
![screen shot 2018-12-12 at 3 29 13 pm](https://user-images.githubusercontent.com/13434925/49887178-c73ff200-fe22-11e8-90f1-cc39741bc66f.png)

**Comment by MatheusAriel** [comment]
> > Posso tá fazendo confusão mas no método buscaServicos() não estou achando sobre o Sedex 40096, será q o mesmo foi removido?
> 
> Não existe mais este serviço `40096` por isso a necessidade de atualizar a lista de serviços, como comentei acima.

Pela lista de serviços disponíveis, não achei um serviço q se assemelhe com o SEDEX 40096

> São vários, mas para os mais comuns eu deixo eles aqui para não travarem vocês até todos estarem atualizados.
> 
> Por favor utilizem esses:
> ![screen shot 2018-12-12 at 3 29 13 pm](https://user-images.githubusercontent.com/13434925/49887178-c73ff200-fe22-11e8-90f1-cc39741bc66f.png)

Pra saber qual código se assemelha mais com aquele antigo 40096 seria verificando o preço pelo método calcPrecoPrazo() ?

**Comment by brunorthomaz** [comment]
> > > Posso tá fazendo confusão mas no método buscaServicos() não estou achando sobre o Sedex 40096, será q o mesmo foi removido?
> > 
> > 
> > Não existe mais este serviço `40096` por isso a necessidade de atualizar a lista de serviços, como comentei acima.
> 
> Pela lista de serviços disponíveis, não achei um serviço q se assemelhe com o SEDEX 40096
> 
> > São vários, mas para os mais comuns eu deixo eles aqui para não travarem vocês até todos estarem atualizados.
> > Por favor utilizem esses:
> > ![screen shot 2018-12-12 at 3 29 13 pm](https://user-images.githubusercontent.com/13434925/49887178-c73ff200-fe22-11e8-90f1-cc39741bc66f.png)
> 
> Pra saber qual código se assemelha mais com aquele antigo 40096 seria verificando o preço pelo método calcPrecoPrazo() ?

Cara, eu usava o 40096 e passei a usar o 04162, veja se te atende.

**Comment by MatheusAriel** [comment]
> > > > Posso tá fazendo confusão mas no método buscaServicos() não estou achando sobre o Sedex 40096, será q o mesmo foi removido?
> > > 
> > > 
> > > Não existe mais este serviço `40096` por isso a necessidade de atualizar a lista de serviços, como comentei acima.
> > 
> > 
> > Pela lista de serviços disponíveis, não achei um serviço q se assemelhe com o SEDEX 40096
> > > São vários, mas para os mais comuns eu deixo eles aqui para não travarem vocês até todos estarem atualizados.
> > > Por favor utilizem esses:
> > > ![screen shot 2018-12-12 at 3 29 13 pm](https://user-images.githubusercontent.com/13434925/49887178-c73ff200-fe22-11e8-90f1-cc39741bc66f.png)
> > 
> > 
> > Pra saber qual código se assemelha mais com aquele antigo 40096 seria verificando o preço pelo método calcPrecoPrazo() ?
> 
> Cara, eu usava o 40096 e passei a usar o 04162, veja se te atende.

Acho q é esse mesmo q mais se assemelha, muito obrigado pessoal pela ajuda

**Comment by avlima** [comment]
Exatamente pessoal, estou colocando o print aqui do ultimo e-mail recebido pela equipe técnica dos correios:

![screen shot 2018-12-12 at 4 49 46 pm](https://user-images.githubusercontent.com/13434925/49891616-193a4500-fe2e-11e8-86b7-a9195e01238e.png)

É isso mesmo!

Qualquer dúvida estamos a disposição.

**Comment by avlima** [comment]
Solução da issue: #278 

Obrigado a todos, principalmente @stavarengo
