### ISSUE TITLE
RastrearObjeto retorna apenas o primeiro evento de cada etiqueta/objeto

### ISSUE THREAD

**Issue by GEnghusen** [stavarengo/php-sigep#274]
Ao tentar efetuar um rastreio de objeto utilizando `exemplos/rastreamentoDeObjetos.php`, ele apenas retorna o primeiro evento da etiqueta/objeto.

Utilizando como exemplo a etiqueta **"DZ 087 632 119 BR"**, que consta como _"Objeto entregue ao destinatário"_ pelo rastreamento de objetos no site dos Correios, espera-se que o retorno do rastreamento utilizando a classe seja um array de eventos ou o último evento relacionado à etiqueta, porém o retorno é de _"Objeto postado"_.

Segue a resposta do exemplo para esta etiqueta.

```
array(6) {
    ["*isSoapFault"]=> bool(false)
    ["*errorCode"]=> NULL
    ["*errorMsg"]=> NULL
    ["*result"]=> array(1) {
        [0]=> object(PhpSigep\Model\RastrearObjetoResultado)#19 (3) {
            ["etiqueta":protected]=> object(PhpSigep\Model\Etiqueta)#20 (4) {
                ["etiquetaComDv":protected]=> string(13) "DZ087632119BR"
                ["etiquetaSemDv":protected]=> NULL
                ["dv":protected]=> NULL
                ["_failIfAtributeNotExiste":protected]=> bool(true)
            }
            ["eventos":protected]=> array(1) {
                [0]=> object(PhpSigep\Model\RastrearObjetoEvento)#21 (12) {
                    ["tipo":protected]=> string(2) "PO"
                    ["status":protected]=> string(2) "01"
                    ["dataHora":protected]=> string(16) "2018-10-29 15:14"
                    ["descricao":protected]=> string(14) "Objeto postado"
                    ["recebedor":protected]=> string(0) ""
                    ["detalhe":protected]=> string(0) ""
                    ["local":protected]=> string(40) "AC HAMBURGO VELHO "
                    ["codigo":protected]=> string(8) "93511970"
                    ["cidade":protected]=> string(13) "NOVO HAMBURGO"
                    ["uf":protected]=> string(2) "RS"
                    ["error":protected]=> NULL
                    ["_failIfAtributeNotExiste":protected]=> bool(true)
                }
            }
            ["_failIfAtributeNotExiste":protected]=> bool(true)
        }
    }
    ["*soapFault"]=> NULL
    ["*_failIfAtributeNotExiste"]=> bool(true)
}
```

**Comment by arthurlauck** [comment]
+1

**Comment by jdgrieco** [comment]
@arthurlauck e @GEnghusen, para o usuário ECT e senha SRO (padrões dos testes) o retorno será somente da última interação mesmo.

E para se ter o histórico completo do objeto é necessário o usuário que os Correios libera no contrato para usar o SigepWeb

**Comment by avlima** [comment]
Estou com o mesmo problema, pode me confirmar se para o usuário ECT e senha SRO o serviço buscaEventosLista também só retorna apenas o primeiro código de rastreio?

estou passando uma lista de códigos e só está retornando apenas o primeiro e com apenas um evento.

Grato.

**Comment by avlima** [comment]
> Ao tentar efetuar um rastreio de objeto utilizando `exemplos/rastreamentoDeObjetos.php`, ele apenas retorna o primeiro evento da etiqueta/objeto.
> 
> Utilizando como exemplo a etiqueta **"DZ 087 632 119 BR"**, que consta como _"Objeto entregue ao destinatário"_ pelo rastreamento de objetos no site dos Correios, espera-se que o retorno do rastreamento utilizando a classe seja um array de eventos ou o último evento relacionado à etiqueta, porém o retorno é de _"Objeto postado"_.
> 
> Segue a resposta do exemplo para esta etiqueta.
> 
> ```
> array(6) {
>     ["*isSoapFault"]=> bool(false)
>     ["*errorCode"]=> NULL
>     ["*errorMsg"]=> NULL
>     ["*result"]=> array(1) {
>         [0]=> object(PhpSigep\Model\RastrearObjetoResultado)#19 (3) {
>             ["etiqueta":protected]=> object(PhpSigep\Model\Etiqueta)#20 (4) {
>                 ["etiquetaComDv":protected]=> string(13) "DZ087632119BR"
>                 ["etiquetaSemDv":protected]=> NULL
>                 ["dv":protected]=> NULL
>                 ["_failIfAtributeNotExiste":protected]=> bool(true)
>             }
>             ["eventos":protected]=> array(1) {
>                 [0]=> object(PhpSigep\Model\RastrearObjetoEvento)#21 (12) {
>                     ["tipo":protected]=> string(2) "PO"
>                     ["status":protected]=> string(2) "01"
>                     ["dataHora":protected]=> string(16) "2018-10-29 15:14"
>                     ["descricao":protected]=> string(14) "Objeto postado"
>                     ["recebedor":protected]=> string(0) ""
>                     ["detalhe":protected]=> string(0) ""
>                     ["local":protected]=> string(40) "AC HAMBURGO VELHO "
>                     ["codigo":protected]=> string(8) "93511970"
>                     ["cidade":protected]=> string(13) "NOVO HAMBURGO"
>                     ["uf":protected]=> string(2) "RS"
>                     ["error":protected]=> NULL
>                     ["_failIfAtributeNotExiste":protected]=> bool(true)
>                 }
>             }
>             ["_failIfAtributeNotExiste":protected]=> bool(true)
>         }
>     }
>     ["*soapFault"]=> NULL
>     ["*_failIfAtributeNotExiste"]=> bool(true)
> }
> ```

@GEnghusen Boa tarde, realmente foi validado com os correios que os dados completos só retornam com usuário de produção, tanto para o numero de eventos quanto para a numero de itens a serem rastreados.

Por favor considere essa discussão resolvida e fecha assim que possível.

Obrigado.

**Comment by GEnghusen** [comment]
Obrigado, @avlima.

**Comment by chags** [comment]
Estou tentando acessar os dados desse array de retorno  mas não consegui de nehuma forma algum pde me ajudar? como acessar esse array dos correios?
ex; print_r($result["*result"][0]["eventos":protected]["codigo":protected])
