### ISSUE TITLE
504 Gateway Time-out  - Na primeira requisição.

### ISSUE THREAD

**Issue by avlima** [stavarengo/php-sigep#280]
Tenho notado que toda primeira requisição do dia aos correios ela retorna 504 Gateway Time-out.

Depois de um minuto mais ou menos o serviço passa a funcionar.

É como se tivesse que esquentar a API (acordar o servidor).

Mai alguém notou isso?

Grato.

**Comment by stavarengo** [comment]
@avlima 
Talvez o cache possa te ajudar. Veja https://github.com/stavarengo/php-sigep/issues/279

**Comment by mauroagr** [comment]
Aqui também, a primeira requisição é lenta. 
Quero tentar criar uma requisição para consultar o cartão  e depois fazer as etiquetas.
Tentar 'enganar' o sistema.

**Comment by jdgrieco** [comment]
@mauroagr e @avlima, deem uma olhada no meu comentário na issue https://github.com/stavarengo/php-sigep/issues/158#issuecomment-307561579

**Comment by mauroagr** [comment]
@jdgrieco vou testar esta sugestão https://github.com/stavarengo/php-sigep/issues/158#issuecomment-309517284 e retorno quando tiver resultado

**Comment by mauroagr** [comment]
Coloquei no src/PhpSigep/Services/Real/SoapClientFactory.php, os parametros sugerido, no $opt e na primeira conexão foi muito rapido.
```
$opts = array(
                'ssl' => array(
                    //'ciphers'           =>'RC4-SHA', // comentado o parâmetro ciphers devido ao erro que ocorre quando usado dados de ambiente de produção em um servidor local conforme issue https://github.com/stavarengo/php-sigep/issues/35#issuecomment-290081903
                    'verify_peer'       =>false,
                    'verify_peer_name'  =>false
                ),
                'http' => array(
                    'protocol_version'=>'1.1',
                    'header' => 'Connection: Close'
                )
            );
```

**Comment by jdgrieco** [comment]
@mauroagr, inclusive tem esse comentário na issue #158, mas ninguém, inclusive eu, mexeu nisso.

Você consegue fazer um PR, seria legal verificar se precisa dessa opção também nas outras chamadas

**Comment by mauroagr** [comment]
@jdgrieco feito se puder testar, e aceitar o PR, já resolvemos este problema.
