### ISSUE TITLE
Autorização de acesso negada para o sistema

### ISSUE THREAD

**Issue by andrecampioni** [stavarengo/php-sigep#281]
Boa tarde, pessoal. 

Depois de implementar o WebService em minha aplicação, qualquer chamada ao webservice me retorna o erro:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <soap:Fault>
            <faultcode>soap:Server</faultcode>
            <faultstring>IWS101 - Autorização de acesso negada para o sistema.</faultstring>
            <detail>
                <ns2:WebServiceFaultInfo xmlns:ns2="http://service.logisticareversa.correios.com.br/">
                    <mensagem>IWS101 - Autorização de acesso negada para o sistema.</mensagem>
                    <excecao>br.com.correios.infraws.exception.AutorizacaoException</excecao>
                    <classificacao>TECNICA</classificacao>
                </ns2:WebServiceFaultInfo>
            </detail>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>
```

Poderiam me tirar essa duvida do que se trata?

**Comment by andrecampioni** [comment]
Rafael, consegui sim.

Existe um procedimento que tem que ser realizado para a autorização de acesso a esta funcionalidade do WebService. Estou anexando uma documentação que encontrei mais atualizada, que demonstra passo como devemos proceder para solicitar a permissão.

Link para acesso
[https://www.4shared.com/s/ftVO1eJdngm](url)

**Comment by igorgaelzer** [comment]
Olá @andrecampioni ! Estamos com o mesmo problema, porém o seu link não funciona mais. Poderia mandar novamente? Obrigado! Estamos trancados nisso também :/

**Comment by andersonls** [comment]
@stavarengo Será que não seria interessante colocar isso no FAQ do projeto? Explicar que antes de usar a biblioteca em modo produção é necessário solicitar a habilitação juntamente com os correios...

@andrecampioni Não consegue anexar o PDF diretamente aqui no github?

**Comment by stavarengo** [comment]
Muito interessante, @andersonls.
Você consegue colocar? Se vc conseguir, seria interessante tbm atualizar o readme como um todo.

**Comment by andrecampioni** [comment]
Pessoal desculpe a ausência.
Vou compartilhar novamente.
