### ISSUE TITLE
AcessHomologacao

### ISSUE THREAD

**Issue by JoaoVictorSarzi** [stavarengo/php-sigep#286]
Eu tenho que usar sempre o $params->setAccessData(new \PhpSigep\Model\AccessDataHomologacao());
Estou usando par calculo de frete para um cliente sem Contrato, porem os valores que retornam muitas vezes vem abaixo do valro minimo do correio.. Por que será?

**Comment by mauroagr** [comment]
@JoaoVictorSarzi 
Podem ser várias causas:
- Peso incorreto (preste atenção se é gramas ou kg)
- CEP de Origem e CEP de destino, cuide que as vezes alguns cep começam com 08500000, e ai se tu converter para inteiro ele vira 850000 e isto muda tudo.
- Volume passado incorretamente;
