### ISSUE TITLE
Como gerar código de postagem?

### ISSUE THREAD

**Issue by pedrost** [stavarengo/php-sigep#287]
Olá gostaria de saber como faço pra gerar o número (código) que o vendedor leva ao correios para despachar a encomenda. É uma PLP que me retorna esse número? como obtenho o idPlpMaster? Preciso gerar etiquetas antes de abrir uma PLP? Tenho já o numero de contrato, e o login/senha do id correios, mas ainda encontro dificuldades pra proceder com esse método.

**Comment by andersonls** [comment]
Boa tarde @pedrost, a primeira coisa que você precisa fazer é solicitar acesso ao webservice junto dos correios (não é o login e senha do ID correios).

Você pode dar uma olhada no manual de implementação dos correios ([aqui](https://github.com/stavarengo/php-sigep/tree/master/manual)), lá explica o fluxo das chamadas necessárias ao webservice para fazer a postagem e depois tem os [exemplos](https://github.com/stavarengo/php-sigep/tree/master/exemplos) dessas chamas dentro do projeto.
