### ISSUE TITLE
parametro idPlpCliente

### ISSUE THREAD

**Issue by pedrost** [stavarengo/php-sigep#289]
pessoal, no método fechaPlpVariosServicos, existe um parametro "idPlpCliente", como faço pra obter esse id? não veio com os dados do cliente (contrato, cartaoPostagem, etc...)
Na documentação diz "Código gerado pelo cliente para identificação da PLP."

se alguém souber e puder me ajudar agradeço desde já :)

**Comment by andersonls** [comment]
@pedrost Este parâmetro você passa vazio, é o webservice que gera e retorna no retorno da chamada do método.

Este valor é utilizado posteriormente no método solicitaXmlPLP, que o webservice te retorna o XML com todos os dados preenchidos (como valor cobrado por cada postagem).

**Comment by jhonatangalante** [comment]
@andersonls estou implementando aqui na empresa e quando tento passar o <idPlpCliente> vazio ele dá erro no envio.

Já tentei <idPlpCliente></idPlpCliente>, <idPlpCliente,> e até mesmo sem essa tag. Quando coloco seis dígitos 0, por exemplo, ele diz que a etiqueta já está vinculada a outro PLP. E agora estou parado aqui nesse problema. Saberia me dizer como proceder nesse caso? (Depois de tanto tempo rs).

**Comment by andersonls** [comment]
@jhonatangalante quando implementei passava vazio mesmo. Não tenho mais acesso para ver o XML que é gerado, mas acredito que ainda esteja o mesmo código rodando em produção rs
