### ISSUE TITLE
Problema ao fechar PLP

### ISSUE THREAD

**Issue by pedrost** [stavarengo/php-sigep#290]
Pessoal, estou tentando usar o método fechaPlpVariosServicos e estou com problemas

Se eu não passo o idPlpCliente ele volta esse erro:
`"<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unmarshalling Error: For input string: \"\" </faultstring></soap:Fault></soap:Body></soap:Envelope>",`

Se eu passo o idPlpCliente como **102030** (peguei esse número da documentação, pois não sei como conseguir esse número) ele me volta esse outro erro 

`<ns2:SigepClienteException xmlns:ns2=\"http://cliente.bean.master.sigep.bsb.correios.com.br/\">Ocorreu um erro ao interpretar os dados do XML gerado pelo Cliente. &#xd;\n</ns2:SigepClienteException>`

Aqui está o meu fluxo
 solicitaEtiquetas->geraDigitoVerificadorEtiquetas-> fechaPlpVariosServicos(etiquetasSemDV, 102030, xml)

O meu xml está assim (igual o da documentação, só muda o número da etiqueta, no XML eu coloco a etiqueta com DV)

> let xml =  `
>                  <?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>
>                  <correioslog>
>                      <tipo_arquivo>Postagem</tipo_arquivo>
>                      <versao_arquivo>2.3</versao_arquivo>
>                      <plp>
>                          <id_plp/>
>                          <valor_global/>
>                          <mcu_unidade_postagem/>
>                          <nome_unidade_postagem/>
>                          <cartao_postagem>${config.default.dadosCliente.numeroCartaoPostagem}</cartao_postagem>
>                      </plp>
>                      <remetente>
>                          <numero_contrato>${config.default.dadosCliente.numeroContrato}</numero_contrato>
>                          <numero_diretoria></numero_diretoria>
>                          <codigo_administrativo>${config.default.dadosCliente.numeroAdministrativo}</codigo_administrativo>
>                          <nome_remetente><![CDATA[${config.default.dadosCliente.nomeEmpresa}]]></nome_remetente>
>                          <logradouro_remetente><![CDATA[${config.default.dadosCliente.endereco.rua}]]></logradouro_remetente>
>                          <numero_remetente>${config.default.dadosCliente.endereco.numero}</numero_remetente>
>                          <complemento_remetente><![CDATA[${config.default.dadosCliente.endereco.complemento}]]></complemento_remetente>
>                          <bairro_remetente><![CDATA[${config.default.dadosCliente.endereco.bairro}]]></bairro_remetente>
>                          <cep_remetente>${config.default.dadosCliente.endereco.CEP}</cep_remetente>
>                          <cidade_remetente><![CDATA[${config.default.dadosCliente.endereco.cidade}]]></cidade_remetente>
>                          <uf_remetente>${config.default.dadosCliente.endereco.UF}</uf_remetente>
>                          <telefone_remetente></telefone_remetente>
>                          <fax_remetente></fax_remetente>
>                          <email_remetente><![CDATA[${config.default.dadosCliente.email}]]></email_remetente>
>                      </remetente>
>                      <forma_pagamento/>
>                      <objeto_postal>
>                          <numero_etiqueta>${etiquetasComDV[0]}</numero_etiqueta>
>                          <codigo_objeto_cliente/>
>                          <codigo_servico_postagem>41068</codigo_servico_postagem>
>                          <cubagem>0,00</cubagem>
>                          <peso>2500</peso>
>                          <rt1/><rt2/>
>                          <destinatario>
>                              <nome_destinatario><![CDATA[Cliente2]]></nome_destinatario>
>                              <telefone_destinatario><![CDATA[6232339644]]></telefone_destinatario>
>                              <celular_destinatario><![CDATA[62991239321]]></celular_destinatario>
>                              <email_destinatario><![CDATA[cli2@mail.com.br]]></email_destinatario>
>                              <logradouro_destinatario><![CDATA[Avenida Central2]]></logradouro_destinatario>
>                              <complemento_destinatario><![CDATA[Qd: 102 ALt:04]]></complemento_destinatario>
>                              <numero_end_destinatario>865</numero_end_destinatario>
>                          </destinatario>
>                          <nacional>
>                              <bairro_destinatario><![CDATA[SetorIndustrial]]></bairro_destinatario>
>                              <cidade_destinatario><![CDATA[Goiânia]]></cidade_destinatario>
>                              <uf_destinatario>GO</uf_destinatario>
>                              <cep_destinatario><![CDATA[74503100]]></cep_destinatario>
>                              <codigo_usuario_postal/>
>                              <centro_custo_cliente/>
>                              <numero_nota_fiscal>112233</numero_nota_fiscal>
>                              <serie_nota_fiscal/>
>                              <valor_nota_fiscal/>
>                              <natureza_nota_fiscal/>
>                              <descricao_objeto><![CDATA[]]></descricao_objeto>
>                              <valor_a_cobrar>0,0</valor_a_cobrar>
>                          </nacional>
>                          <servico_adicional>
>                              <codigo_servico_adicional>001</codigo_servico_adicional>
>                              <codigo_servico_adicional>019</codigo_servico_adicional>
>                              <valor_declarado>3000,00</valor_declarado>
>                          </servico_adicional>
>                          <dimensao_objeto>
>                              <tipo_objeto>002</tipo_objeto>
>                              <dimensao_altura>50,00</dimensao_altura>
>                              <dimensao_largura>30,00</dimensao_largura>
>                              <dimensao_comprimento>60,00</dimensao_comprimento>
>                              <dimensao_diametro>0,00</dimensao_diametro>
>                          </dimensao_objeto>
>                          <data_postagem_sara/>
>                          <status_processamento>0</status_processamento>
>                          <numero_comprovante_postagem/>
>                          <valor_cobrado/>
>                      </objeto_postal>
>                  </correioslog>
>                  `;

**Comment by andersonls** [comment]
@pedrost Você está mexendo no código do projeto para colocar esse **102030**?? Pq na chamada do método fechaPlpVariosServicos só é passado um parâmetro que é um objeto.

O XML que você informou está cheio de tags com valor no estilo: **${config.default.dadosCliente.numeroCartaoPostagem}**. Se isso tá indo pro correio vai dar erro mesmo. Acho que está faltando você estar alguns dados antes de fazer a chamada do método.

Você já rodou o fechaPlpVariosServicos.php dos exemplos? Tenta ver no exemplo como estão sendo feitas as chamadas e vê se vc não esqueceu de alguma.

**Comment by pedrost** [comment]
Vou testar mais aqui, obrigado! 
Também, te mandei invite no linkedin @andersonls, queria agradecer pelo suporte aqui essa lib de vocês é realmente fantástica.

**Comment by pedrost** [comment]
@andersonls consegui!!
Sabe me dizer se o número que o vendedor leva o objeto a ser postado no correios é o número da PLP? ou o da etiqueta?

**Comment by pedrost** [comment]
O problema que eu estava tendo era que o xml que estava sendo enviado estava mal formatado, a declaração do arquivo <?xml> estava uma linha após o começo do arqvuivo, foi só tirar esse espaço em branco que resolveu!

**Comment by andersonls** [comment]
Aqui na agência da minha cidade eles pedem os dois.
