### ISSUE TITLE
Service Temporarily Unavailable

### ISSUE THREAD

**Issue by limabibi** [stavarengo/php-sigep#291]
Olá,

Estou usando os métodos  e os mesmos estão retornando "Service Temporarily Unavailable", tenho que ficar atualizando a página diversas vezes para poder funcionar.

Está ocorrendo algum problema?

Desde já grata.

**Comment by andersonls** [comment]
Bom dia,

é problema no lado do correio, tive esse problema ontem também com todos os
métodos! Depois de alguns minutos voltou a funcionar.
