### ISSUE TITLE
Plp ainda não atualizada pelo Sara

### ISSUE THREAD

**Issue by pedrost** [stavarengo/php-sigep#292]
Ao solicitar a o xml da PLP passando o idPlpMaster recebo esse erro: 

`<ns2:SigepClienteException xmlns:ns2=\"http://cliente.bean.master.sigep.bsb.correios.com.br/\">Plp ainda não atualizada pelo Sara.</ns2:SigepClienteException>`

Alguém sabe me dizer o que pode ser?
Tentei levar a etiqueta impressa junto com o numero da PLP e quando a agencia escaneou disse que era invalido.

**Comment by luiz-merante** [comment]
Estou com esse mesmo problema, e o fluxo de fechamento está correto, poderiam me ajudar?
