### ISSUE TITLE
calcPrecoPrazo fora do ar

### ISSUE THREAD

**Issue by jdgrieco** [stavarengo/php-sigep#297]
Pessoal, alguém está com problema na rotina calcPrecoPrazo, está dando erro

> A resposta do Correios não está no formato esperado. Detalhes do problema: "A resposta recebida é um objeto, mas este objeto não possui todos as entradas necessárias."

**Comment by jdgrieco** [comment]
Pelo que notei está dando timeout na consulta do WSDL 
http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL

**Comment by mauroagr** [comment]
Sim, está muito instavel ultimos dias.
