### ISSUE TITLE
Etiqueta Cancelada

### ISSUE THREAD

**Issue by mauroagr** [stavarengo/php-sigep#298]
Pessoal,
Consegui gerar as etiquetas, tudo tranquilo.
Num teste que fiz, tenho uma plp, com dois PAC e um deles ao consultar na agência, consta como cancelada.
Não sei como debugar isto, pensei em gravar o xml que é enviado ao ws, mas nao achei como, para ver se tem algo errado.
Alguem tem sugestão para debugar?
Obrigado.
Mauro

**Comment by mauroagr** [comment]
Acho que deve ser pq no nome do cliente tinha um acento e na hora de passar ele bugou o caractere.
Amnha vou conferir novamente e reabro caso seja necessário.

**Comment by mauroagr** [comment]
Não funcionou, tanto que a etiqueta gerada apareceu como não encontrado.
Alguem sabe algum motivo para dar etiqueta cancelada, mesmo com plp gerando OK?

**Comment by andersonls** [comment]
@mauroagr Eu tive esse problema na semana passada. Tinha uma PLP com alguns objetos e um deu esse erro de etiqueta cancelada e os outros foram postados normalmente.

No dia seguinte eu gerei uma nova PLP apenas com o objeto que deu problema e passou na agência.

Se continuar com o problema sugiro tentar entrar em contato com alguém da área técnica dos correios, pois esses erros que dão na agência são quase impossíveis de debugar do nosso lado.

**Comment by mauroagr** [comment]
O engraçado é que tenho um outro sistema, que fiz na unha, que faz o mesmo processo e uso a mais de 2 anos, e nunca tive este tipo de cancelamento, dentro de uma PLP. To imaginando que seja algo relacionado à montagem do XML com algum caractere inválido, que o sara nao 'colete' ele, mas é uma merda.
Vou tentar ver com um cara dos correios, da TI deles, pra achar o motivo.

**Comment by jdgrieco** [comment]
O único "senão" é conseguir falar com a área técnica deles



> @mauroagr Eu tive esse problema na semana passada. Tinha uma PLP com alguns objetos e um deu esse erro de etiqueta cancelada e os outros foram postados normalmente.
> 
> No dia seguinte eu gerei uma nova PLP apenas com o objeto que deu problema e passou na agência.
> 
> Se continuar com o problema sugiro tentar entrar em contato com alguém da área técnica dos correios, pois esses erros que dão na agência são quase impossíveis de debugar do nosso lado.

**Comment by mauroagr** [comment]
É um pequeno detalhe

**Comment by jdgrieco** [comment]
Vdd, :laughing::laughing:

**Comment by mauroagr** [comment]
O pequeno detalhe se resolveu.
Meu XML tá sendo passado como utf8, mesmo pelo que vi no codigo estar como ISO-8859-1.
Vou tentar achar no codigo do projeto onde ele faz isto. 
Possivelmente algumas etiquetas sem caracteres acentuados estejam passando. 
Vou testar e aviso

**Comment by mauroagr** [comment]
Resultados do análise:
Na linha 84 do arquivo: Services/Real/FecharPreListaDePostagem.php, está assim:
```
        $writer->startDocument('1.0', 'UTF-8');
```
modifiquei ele para:
```
        $writer->startDocument('1.0', 'ISO-8859-1');
```
O Manual recomenda usar ISO.
Porém, no meu destinatário tem acento, e ai o xml nao foi gerado (coloquei uma linha para salvar o xml que é enviado ao webservice) ai ele gravou vazio.
Tente converter para utf8_encode() o destinatário e salvou um ?, tentei vários opcoes não tive sucesso.
Preciso de ajuda, para tentar identificar o que fazer para passar corretamente valores com acentos.
Aceito sugestões para poder ajustar, @andersonls @jdgrieco tem alguma mágica?
abraço,
Mauro

**Comment by mauroagr** [comment]
Continuei os teste, consegui gerar a PLP, porém o nome do destinatário na etiqueta em pdf e na lista da plp, o nome carregou branco. Acredito que foi por causa da codificação.
O que fiz foi
```
    private function _($str, $maxLength, $cdata = true, $trim = true)
    {
        if ($str === null) {
            return $str;
        }
        if ($trim) {
            $str = trim($str);
        }
        if ($maxLength) {
            $str = mb_substr($str, 0, $maxLength, 'UTF-8');
        }
        $str = utf8_encode($str);
        return $str;
    }
```
adicionei a linha 
```
$str = utf8_encode($str);
```
Vou entrar em contato com o cliente e ai vamos ver se foi recebi com sucesso.

**Comment by andersonls** [comment]
@mauroagr Verifique em qual codificação estão os teus dados. Você utiliza linux ou windows?

O que pode estar acontecendo é que os teus dados não estejam em UTF-8 e a biblioteca trabalha apenas com UTF-8. Eu uso tudo em UTF-8 e com o XML sendo gerado em ISO-8859-1 e funciona tudo normal.

Se os teus dados não estiverem em UTF-8 você temq passar pra biblioteca já convertido ou ver se o @stavarengo acha interessante tentar tratar isso no código da biblioteca. Eu uso [esta](https://github.com/neitanod/forceutf8) biblioteca pra tratar de codificações, ela é quase mágica hehe

**Comment by mauroagr** [comment]
@andersonls, uso servidor linux. 
Parece ser problema de codifcação sim, mas pelo que vi a biblioteca tá gerando o xml do fechamento da plp, com UTF-8, os correios recomendam ISO-8859-1, obviamente, por algum motivo o @stavarengo deixou assim.
Fiz um teste ontem a noite, estou aguardando resposta dos correios se deu OK.
Vou ver a sugestao de biblioteca.

**Comment by andersonls** [comment]
@mauroagr A alteração no startDocument para ISO-8859-1 está correta mesmo. Talvez ficou assim pq ninguém percebeu. Comentei da verificar a codificação dos teus dados pelo fato de não estar aparecendo caracteres com acentuação nos PDFs.

**Comment by mauroagr** [comment]
@andersonls Então vamos lá, tentar criar uma linha de teste.
1. mudei para iso e bugou a geração do xml
2. O dado vinha do banco de dados, e eu aplicava utf8_encode() e bugava a geração do xml.
3. Removi o utf8, lá do inicio do codigo e mudei ele para aplicar no metodo _, que aplica em todas as variáveis que vem do meu código. Resultado: gerou o XML e o id da PLP;
4. Consultei o TI dos correios e eles me informaram que aquela plp gerou 100%;
5. Problema: Ao gerar a etiqueta da PLP, o 'nome' do destinatário que tinha acento, nao mostrou, nem no pdf da plp. (ps: serializo a PLP e jogo no banco e depois puxo ela para gerar a etiqueta).

- Acredito que o problema possa estar em algum tratamento ao gerar o pdf de caracteres, mas nao consegui testar.

**Comment by lucaspaulino** [comment]
@mauroagr tenta usar função que remove todos os acentos, no google tem vários.. acho q tivesse esse problema tbm, aí hje faço tudo assim.. fazemos dezenas de envios diários e vai tudo ok..

**Comment by mauroagr** [comment]
@lucaspaulino Boa idéia, é que to pensando em algo que já solucione isto no phpsigep.
@stavarengo, @andersonls , o que acham da possibilidade de colocar um 'ativar' e 'desativar' a funcionalidade sugerida de limpar os caracteres com acentos e tal?

**Comment by andersonls** [comment]
@mauroagr Remover acentuação é uma opção, temq ver se vale a pena tratar caracteres especiais também, que podem dar problema de uma codificação para outra.

Outra alternativa, porém adiciona uma dependência no projeto, é utilizar a biblioteca que mencionei no outro comentário e, no lugar do `$str = utf8_encode($str);` colocar `$str = Encoding::fixUTF8(Encoding::toUTF8($str));` (só não tenho certeza quanto ao FixUTF8, precisa testar se é necessário mesmo)

E no improvedFPDF colocar o inverso `$str = Encoding::toLatin1($str);`

Dessa forma fica totalmente transparente dentro da lib, pode mandar qualquer string que a biblioteca se vira em converter na codificação correta. O que acha @stavarengo? Qual tua política para dependências dentro do projeto?

Eu já uso essa biblioteca num módulo que tenho que lê emails, pois tenho um "mini cliente" dentro do meu software e ela consegue manter em UTF8 emails enviados por qualquer cliente de email.

**Comment by stavarengo** [comment]
@andersonls 
De uma olhada nesse método `Encoding::toLatin1($str);` as vezes a gente pode conseguir o mesmo resultado com uma solução mais simples, feitas por nós mesmo, sem precisar depender de outra library.

É sempre preferivel não depender de mais nada, principalmente quando é algo para resolver apenas um problema muito pontual.

Veja se podemos fazer o nosso próprio "toLatin1" ou não. Acatarei o que vc decidir.

**Comment by andersonls** [comment]
@mauroagr Você pode fazer esse tratamento de remover a acentuação ou converter para utf8 antes de passar os dados para a biblioteca?

Nesse caso eu coloco essa solução apenas no FAQ caso alguém venha a ter o mesmo problema.

**Comment by mauroagr** [comment]
@andersonls Não consegui testar ainda. Quando testar posiciono.

**Comment by mauroagr** [comment]
Para histórico:
Código da biblioteca forceutf8/Encoding.php
```
 static function toWin1252($text, $option = self::WITHOUT_ICONV) {
    if(is_array($text)) {
      foreach($text as $k => $v) {
        $text[$k] = self::toWin1252($v, $option);
      }
      return $text;
    } elseif(is_string($text)) {
      return static::utf8_decode($text, $option);
    } else {
      return $text;
    }
  }
  static function toISO8859($text, $option = self::WITHOUT_ICONV) {
    return self::toWin1252($text, $option);
  }
  static function toLatin1($text, $option = self::WITHOUT_ICONV) {
    return self::toWin1252($text, $option);
  }
```

**Comment by mauroagr** [comment]
Testei agora, tive que pegar o arquivo inteiro e puxar para meu modulo e ai aplicar o tolatin1, gerou o xml correto, com os acentos, e mantive o utf-8 na tag xml, acredito que nao terá problemas nos correios, manha tenho a confirmação.
Já na hora de gerar os pdf (etiqueta e plp), deu pau, nao mostrou, vou analisar uma solucao mais prática.

**Comment by mauroagr** [comment]
Para o pdf da etiqueta gerar corretamente tive que mexer no pdf/CartaoDepostagem2018.php, adicionando no nome do remetente o metodo \ForceUTF8\Encoding::toUTF8(), porém teria de fazer isto em todas as variáveis, acredito que exista uma maneira mais pratica para isto.
Se tiver alguma sugestão, agradeço.

**Comment by andersonls** [comment]
@mauroagr A idéia é que você faça isso antes de passar os dados pra biblioteca. Por exemplo

```php
$destinatario = new \PhpSigep\Model\Destinatario();
$destinatario->setNome('Google Belo Horizonte');
$destinatario->setLogradouro('Av. Bias Fortes');
```

 ficaria

```php
$destinatario = new \PhpSigep\Model\Destinatario();
$destinatario->setNome(
\ForceUTF8\Encoding::toUTF8('Google Belo Horizonte'));
$destinatario->setLogradouro(
\ForceUTF8\Encoding::toUTF8('Av. Bias Fortes'));
```

E o mesmo para todo método que você possa passar alguma coisa com acentuação e/ou caractere especial. Dessa forma você não precisa manipular o XML e o PDF será gerado corretamente.

**Comment by mauroagr** [comment]
@andersonls O 'problema' é que eu recupero ela do banco de dados. Eu serializo a plp toda a jogo no banco, e depois puxo ela para gerar o pdf, que ai tenho em qualquer tempo ela.
Vou ter que pensar em como tratar ela ao puxar do banco, com um while na array ou algo assim.
Se tiver ideia, de um contorno me avisa.

**Comment by mauroagr** [comment]
Desisto.
O Iconv com o funciona para o xml, mas na hora de recuperar do banco de dados e gerar a etiqueta, nao tem jeito, parece que ele se perde no encode.
Bom parti para a força bruta, já investi tempo demais.
```
    public static function removeAcentos($text) {
        return transliterator_transliterate('Any-Latin; Latin-ASCII;',utf8_encode($text));
    }
```
Isto aqui resolveu, to gerando tudo sem acentos, e ai vamos ver.

**Comment by mauroagr** [comment]
Bom, pensando bem, vai dar errado, por exemplo "1º andar", ele vai tirar o º dando problema.
Vou precisar repensar. Aguardo ideias.

**Comment by mauroagr** [comment]
@andersonls @stavarengo Desisti de achar um metodo inteligente, para resolver, para mim, tudo que tentei não funcionou.
Para descrever o meu problema. Na hora de serializar a plp para gravar no banco de dados, usando utf8_encode(), funciona direitinho a geração do xml, porém quando recupero esta informação do banco de dados, por meio de unserialize(), ele nao escreve os nomes no pdf. 
Seguindo a recomendação do @stavarengo , decido nao mexer na biblioteca e depois de horas tentando, decidi partir para força bruta/gambiarra.
Como meu problema era no imprimir a etiqueta e alista da plp, fiz um metodo que trata o retorno do banco de dados, reecrevendo o dados com utf8_encode(), e ai passo para o pdf, e funcionou.
Para quem interessar, abaixo a função.
```
    public function setUtf8Pdf($objetoPostal){
        $nomeDestinatario = utf8_encode($objetoPostal->getDestinatario()->getNome());
        $logradouro = utf8_encode($objetoPostal->getDestinatario()->getLogradouro());
        $numero = utf8_encode($objetoPostal->getDestinatario()->getNumero());
        $complemento = utf8_encode($objetoPostal->getDestinatario()->getComplemento());
        $bairro = '';
        $cidade = '';
        $uf = '';
        $cep = '';
        $destino = $objetoPostal->getDestino();

        if ($destino instanceof \PhpSigep\Model\DestinoNacional) {
            $bairro = utf8_encode($destino->getBairro());
            $cidade = utf8_encode($destino->getCidade());
            $uf = utf8_encode($destino->getUf());
            $cep = utf8_encode($destino->getCep());
        }
        $d = new \PhpSigep\Model\Destinatario();
        $d->setNome($nomeDestinatario);
        $d->setLogradouro($logradouro);
        $d->setNumero($numero);
        $d->setComplemento($complemento);

        $n = new \PhpSigep\Model\DestinoNacional();
        $n->setBairro($bairro);
        $n->setCidade($cidade);
        $n->setUf($uf);
        $n->setCep($cep);
        $objetoPostal->setDestinatario($d);
        $objetoPostal->setDestino($n);
        return $objetoPostal;
    }
```

Como usar: 
```
public function gerarListaDePostagem()
{
        $plp = $this->getPlpFromDb();
        $id_plp = $plp->id_plp;
        $p = unserialize($plp->plp);
        $acc = $p->getAccessData();
        $enc = $p->getEncomendas();
        foreach ($enc as $key => $objetoPostal) {
            $enc[$key] = $this->setUtf8Pdf($objetoPostal);
        }
        $pdf = new \PhpSigep\Pdf\ListaDePostagem($p, $plp->id_plp);
        $pdf->render("I");

}
```
@andersonls @stavarengo  se tiver alguma sugestão, comenta ai, caso contrário, podemos fechar.

**Comment by andersonls** [comment]
@mauroagr Que bom que conseguisse resolver, problema de codificação é complicado, eu achava que o _serialize_ e _unserialize_ não afetavam a codificação. Vou fechar a _issue_, caso mais pessoas venham a ter o problema podemos reabrir a discussão sobre integrar alguma solução dentro do php-sigep.

**Comment by mauroagr** [comment]
@andersonls La vamos nos novamente, recebi o retorno do suporte dos correios, da area de TI.
Eles recomendam mesmo usar iso-8859-1, vou ter que criar um fork e atualizar isto.
![image](https://user-images.githubusercontent.com/5348884/53919688-87fff680-4049-11e9-8144-069f96fdc2ed.png)

**Comment by andersonls** [comment]
@mauroagr Tente resolver os outros problemas de validação primeiro. Pela janela abaixo você está com problemas em duas tags. Tente corrigir estes erros e ver se passa

**Comment by stavarengo** [comment]
Amigos, isso agui resolveria? 
@mauroagr caso resolva, acho que podemos modificar o seu PR para incluir está função.
A ideia seria que o php-sigep poderia identificar se a string é UTF-8 (que funciona numa boa) e se não for, usaria esta função para converter.

```php
public static function removeAccents($string)
    {
        $array1 = array(
            'á', 'à', 'â', 'ã', 'ä', 'é', 'è', 'ê', 'ë', 'í', 'ì', 'î', 'ï', 'ó', 'ò', 'ô', 'õ', 'ö', 'ú', 'ù', 'û',
            'ü', 'ç', 'Á', 'À', 'Â', 'Ã', 'Ä', 'É', 'È', 'Ê', 'Ë', 'Í', 'Ì', 'Î', 'Ï', 'Ó', 'Ò', 'Ô', 'Õ', 'Ö', 'Ú',
            'Ù', 'Û', 'Ü', 'Ç'
        );
        $array2 = array(
            'a', 'a', 'a', 'a', 'a', 'e', 'e', 'e', 'e', 'i', 'i', 'i', 'i', 'o', 'o', 'o', 'o', 'o', 'u', 'u', 'u',
            'u', 'c', 'A', 'A', 'A', 'A', 'A', 'E', 'E', 'E', 'E', 'I', 'I', 'I', 'I', 'O', 'O', 'O', 'O', 'O', 'U',
            'U', 'U', 'U', 'C'
        );
        $string  = str_replace($array1, $array2, $string);
        
        //remove os ascentos
        $string = iconv('UTF-8', 'US-ASCII//TRANSLIT', $string);
        
        return $string;
    }
```

**Comment by mauroagr** [comment]
Teoricamente sim. 
O problema é que ai por exemplo endereços de empresas fulano & ciclano, ou 1º andar, 1ª quadra, eu terei problemas no endereçamento (só os que eu lembrei), obviamente poderia colocar ali, porém, deve ter outras variantes que nao lembraremos.
Tentei usar o translit e nos testes que fiz, eu desisti, ou tinha caracteres que dava problema.
Meu problema específicamente está no serializado que vai para o banco de dados, e quando recupero ele, os carateres ao imprimir o pdf da etiqueta, nao são mostrados e que todas os testes que fiz usando UTF-8 e consultei o TI dos correios, disseram: encode errado...hehehe.
Se não der para fazer o PR, manterei o fork de boa.
Abraço

**Comment by stavarengo** [comment]
@mauroagr estou achando o PR https://github.com/stavarengo/php-sigep/pull/317 uma solução muito específica, principalmente quando você diz que o problema ocorre quando vc recupera os valores do seu banco de dados. Do jeito que estou entendendo isto não é um problema do php-sigep, mas sim uma peculiaridade do seu sistema. 
Meu raciocínio está certo? 

Acho que poderíamos conseguir o mesmo resultado com listeners. Assim vc poderia conectar seus listeners para modificar o encoding sem precisar deixar isso dentro do php-sigep (uma vez que assumiremos isso como uma peculiaridade do seu sistema).

O que acha?

**Comment by mauroagr** [comment]
@stavarengo sim, teu raciocinio está certo, pode ser que tenha algo no meu banco, no meu php, etc., que pode ser específica, porém mais gente pode estar tendo problema de codificação e não relatando. 

Se tu olhar a documentação dos correios, ela recomenda usar ISO e não UTF, por isto que testei usar ISO e meus problemas de con parei de ter problemas. 
![image](https://user-images.githubusercontent.com/5348884/54131267-b8041c80-43f0-11e9-9647-5c477f050a43.png)

Se puder, me fala como tu faz o workflow ai, se tu grava a PLP no banco, e recupera ela depois ou outra maneira, quem sabe posso alterar aqui.

Abraço

**Comment by andersonls** [comment]
@stavarengo Esse PR eu acho válido, pois não está apenas tratando o problema dele, está fazendo uma alteração para deixar de acordo com o manual do webservice.

Se tivesse pouco uso da biblioteca eu seria mais hardcore e deixaria fixo o ISO-8859-1, mas como tem bastante gente usando, acho que manter essa opção com o padrão UTF-8 (não muda nada pra quem já tá funcionando) é uma boa.
