### ISSUE TITLE
Aviso de recebimento

### ISSUE THREAD

**Issue by rabelorp** [stavarengo/php-sigep#30]
Olá, bom dia. Talvez não tenha procura muito bem no código, mas em que parte do sistema tenho a impressão de aviso de recebimento(AR)???

Além da etiqueta e plp, também preciso do aviso, aí sim o sistema ficaria completo aqui pra mim.

Muito obrigado!

**Comment by stavarengo** [comment]
Oi Rabel.
Não temos essa impressão ainda.
Gostaria de fazer e colaborar com o projeto?

​

**Comment by stavarengo** [comment]
@rabelorp ?

**Comment by rabelorp** [comment]
@stavarengo desculpe a demora. Ainda estou vendo com o outro programador, mas vamos desenvolver sim. Alguma novidade?

**Comment by stavarengo** [comment]
Não @rabelorp.
Só estou aguardando seu PR para atualizar a master.

**Comment by stavarengo** [comment]
https://github.com/stavarengo/php-sigep/issues/49

**Comment by entchucs** [comment]
Alguma novidade?
