### ISSUE TITLE
Obter preço de envio

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#300]
Boa tarde, primeiramente gostaria de agradecer quem criou todo o código, parabéns!

Hoje preciso fazer um relatório de custos (é necessário, pois o responsável não vai ter acesso ao gerenciamento das etiquetas), e queria tirar a dúvida se aquela calculadora de preço e prazo dá as informações reais. 

Ou se é possível puxar o preço direto do sistema dos correios.

**Comment by mauroagr** [comment]
@lucaspaulino acho que pela funcao getxmlPlp() tu consegue puxar a informação da PLP, porém ela só é possivel puxar depois de validada pelos correios.
PS: não testei.
Eu to desenvolvendo um script para azer upload do xml que é gerado pelo financeiro dos correios ao final do mês.

**Comment by andersonls** [comment]
É isso mesmo, só chamar método getxmlPlp informando o IdPLP retornado pelos correios no momento do fechamento da PLP. O único detalhe é que os objetos já devem estar postados.

@mauroagr Quando tiver uma versão funcional compartilha com a gente :)

**Comment by lucaspaulino** [comment]
@mauroagr @andersonls vocês tem um exemplo de como se usa?? Não entendi mto bem.. É esta classe né? PhpSigep/Model/SolicitaXmlPlpResult.php

**Comment by andersonls** [comment]
@lucaspaulino Esta classe vai ter o retorno da chamada. A chamda você faz da seguinte forma:

`
$phpSigep = new PhpSigep\Services\SoapClient\Real();
$result = $phpSigep->SolicitaXmlPlp($idPlp);
`

**Comment by lucaspaulino** [comment]
@mauroagr @andersonls entendi.. então, fiz aqui e retornou:
PhpSigep\Services\Result Object ( [isSoapFault:protected] => 1 [errorCode:protected] => 0 [errorMsg:protected] => Resposta do Correios: Plp não encontrada. [result:protected] => [soapFault:protected] => [_failIfAtributeNotExiste:protected] => 1 )

Sendo que tem várias PLPs enviadas...

**Comment by mauroagr** [comment]
1. O numero que tu tá passando da PLP ela é valida?
2. Esta PLP 'andou', o correios lá deu OK, e as postagens andaram?

**Comment by lucaspaulino** [comment]
É válida sim, é o número que preencho quando solicito quantas etiquetas preciso..  
Tenho dezenas de PLP já geradas e enviadas, testei quase 10 e nenhuma deu..

**Comment by mauroagr** [comment]
Tu tem algum rastreio destas PLP, ele aparece como 'postado'?

**Comment by lucaspaulino** [comment]
Aparecem postados, entregue, saiu para entrega etc.. fazemos dezenas de envios todo dia..

**Comment by andersonls** [comment]
@lucaspaulino Pode postar o trecho do teu código? Testei com uma minha aqui e retornou o XML.

Você está testando com uma PLP de produção no ambiente de produção certo? Não sei se esse método funciona no ambiente de homologação.

**Comment by lucaspaulino** [comment]
@andersonls Então, vê se é isso que vc quer entender:

`/************************/
	$accessDataDeHomologacao = new \PhpSigep\Model\AccessDataHomologacao();

	$accessData = new \PhpSigep\Model\AccessData();
	$accessData -> setUsuario($accessDataDeHomologacao -> getUsuario());
	$accessData -> setSenha($accessDataDeHomologacao -> getSenha());
	$accessData -> setCnpjEmpresa($accessDataDeHomologacao -> getCnpjEmpresa());
	$accessData -> setCodAdministrativo($accessDataDeHomologacao -> getCodAdministrativo());
	$accessData -> setNumeroContrato($accessDataDeHomologacao -> getNumeroContrato());
	$accessData -> setCartaoPostagem($accessDataDeHomologacao -> getCartaoPostagem());
	$accessData -> setAnoContrato($accessDataDeHomologacao -> getAnoContrato());
	$diretoria = new \PhpSigep\Model\Diretoria(\PhpSigep\Model\Diretoria::DIRETORIA_DR_BRASILIA);
	$accessData -> setDiretoria($diretoria);

	/************************/

	$config = new \PhpSigep\Config();
	$config -> setAccessData($accessData);
	$config -> setEnv(\PhpSigep\Config::ENV_PRODUCTION);

	$real = new \PhpSigep\Services\SoapClient\Real();`

No caso, eu configurei direto no Model/AccessDataHomologacao.php

**Comment by andersonls** [comment]
@lucaspaulino Acho que seria da última linha do que você postou pra baixo. Quero ver a parte que você faz a chamada para o webservice e qual o parâmetro que está sendo passado, que é onde tá o problema,

**Comment by lucaspaulino** [comment]
@andersonls perdão.. segue o código que obtive a resposta informada:

`<?php
use PhpSigep\Model\ServicoAdicional;

include ("engine/mysql.php");

require_once __DIR__ . '/engine/PhpSigep/Bootstrap.php';

$accessDataDeHomologacao = new \PhpSigep\Model\AccessDataHomologacao();

$accessData = new \PhpSigep\Model\AccessData();
$accessData -> setUsuario($accessDataDeHomologacao -> getUsuario());
$accessData -> setSenha($accessDataDeHomologacao -> getSenha());
$accessData -> setCnpjEmpresa($accessDataDeHomologacao -> getCnpjEmpresa());
$accessData -> setCodAdministrativo($accessDataDeHomologacao -> getCodAdministrativo());
$accessData -> setNumeroContrato($accessDataDeHomologacao -> getNumeroContrato());
$accessData -> setCartaoPostagem($accessDataDeHomologacao -> getCartaoPostagem());
$accessData -> setAnoContrato($accessDataDeHomologacao -> getAnoContrato());
$diretoria = new \PhpSigep\Model\Diretoria(\PhpSigep\Model\Diretoria::DIRETORIA_DR_BRASILIA);
$accessData -> setDiretoria($diretoria);

$config = new \PhpSigep\Config();
$config -> setAccessData($accessData);
$config -> setEnv(\PhpSigep\Config::ENV_PRODUCTION);

$real = new \PhpSigep\Services\SoapClient\Real();

$config -> setCacheOptions(array('storageOptions' => array(
// Qualquer valor setado neste atributo será mesclado ao atributos das classes
// "\PhpSigep\Cache\Storage\Adapter\AdapterOptions" e "\PhpSigep\Cache\Storage\Adapter\FileSystemOptions".
// Por tanto as chaves devem ser o nome de um dos atributos dessas classes.
'enabled' => false, 'ttl' => 60, // "time to live" de 10 segundos
'cacheDir' => sys_get_temp_dir(), // Opcional. Quando não inforado é usado o valor retornado de "sys_get_temp_dir()"
), ));

\PhpSigep\Bootstrap::start($config);

$result = $real -> SolicitaXmlPlp(1546444380);
print_r($result);
?>`

**Comment by andersonls** [comment]
Daonde você tirou esse **1546444380**? As PLPs que eu gero estão com apenas 9 digitos.

**Comment by lucaspaulino** [comment]
@andersonls pelo que entendi, o número da PLP é um número qualquer que a gente cria.. eu apenas soltei um time()
assim:
`$pdf = new \PhpSigep\Pdf\CartaoDePostagem2016($plp, time(), $logoFile, $layoutChancela);`

**Comment by andersonls** [comment]
Não, o número da PLP é o que é retornado pelo webservice quando fecha a PLP.

**Comment by lucaspaulino** [comment]
E como obtenho esse número? Mds sempre fiz errado KKKKKK

**Comment by andersonls** [comment]
é o retorno do método fechaPlpVariosServicos! Daí salva no banco no lugar desse que você tá gerando aleatóriamente.

**Comment by lucaspaulino** [comment]
@andersonls vou testar, aí em 3 dias eu retorno;.. valeu cara!!!

**Comment by mauroagr** [comment]
@lucaspaulino eu salvo todo o retorno da PLP, e o numero da PLP no banco para usar depois para gerar as estiquetas sem precisar consultar.
Detalhe, para salvar toda a plp uso serialize($plp), e jogo no banco.

**Comment by lucaspaulino** [comment]
Deu certo, valeu aí.. agora partir pro próximo passo!
