### ISSUE TITLE
URL de desenvolvimento fora do ar?

### ISSUE THREAD

**Issue by pedrost** [stavarengo/php-sigep#301]
Pessoal, hoje mais cedo vi que a URL de desenvolvimento
[https://apphom.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl](url)
Estava dando 404, alguém sabe se eles trocaram?

**Comment by MatheusAriel** [comment]
Percebi q tá fora do ar desde semana passada, liguei pro pessoal do sigep web e não souberam me informar o motivo, pra variar....

**Comment by arthursoas** [comment]
Mesma coisa aqui. Desde semana retrasada não é possível acessar esse wsdl.

**Comment by gfernandescs** [comment]
Alguma novidade quanto a isto?

**Comment by mauhk** [comment]
Liguei para o número 3003-0888 e simplesmente me falaram que eles não dão suporte para isso.

**Comment by MatheusAriel** [comment]
Liguei e me deram a mesma resposta, lá não dão suporte pra web service.

https://apphom.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl

voltou mesmo
