### ISSUE TITLE
Registrar ocorrência nos correios

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#302]
Boa tarde,
com intuito de melhorar sempre esta comunidade... gostaria de saber se já há desenvolvido alguma classe que registra reclamações com os correios.

Vi que esta funcionalidade já acontece no Mercado Livre... Seria bem bacana, um formulário bem simples,melhor do que ficar abrindo formulário dos correios preenchendo várias informações, etc..

**Comment by walrt** [comment]
Boa tarde pessoal!
@lucaspaulino a ideia é boa mesmo. Irá agregar ainda mais à biblioteca.

Atualmente é necessários que os clientes entram no site dos Correios, preencha [o formulário com a opção de "Reclamação"](http://www2.correios.com.br/sistemas/falecomoscorreios/) e informe o Código de Rastreio a ser reclamado.

Já vi soluções na internet que conseguem abrir e acompanhar a manifestação de reclamação automaticamente, mas não faço ideia como pode é feito. Uma vez que para acompanhar, é necessário passar pelo captcha do Google para acessar.

Segundo [um manual dos Correios](http://www2.correios.com.br/sistemas/falecomoscorreios/docs/TermoDeUsoFaleComOsCorreios.pdf), informa quais são os requisitos e prazos para abertura e acompanhamento das manifestações.

**Comment by lucaspaulino** [comment]
Exatamente, o impasse fica nesse captcha. Mas se empresas estão fazendo,  é pq tem como.. e acredito que seja através de requisições
