### ISSUE TITLE
Tempo de validade da etiqueta

### ISSUE THREAD

**Issue by MatheusAriel** [stavarengo/php-sigep#304]
Galera to com um problema de como proceder, não é com o código em si.
Fui informado pelos correios, q ao gerar uma etiqueta, ela tem o tempo máximo de 10 minutos pra entrar em uma plp, caso contrário, ela será inutilizada pelos correios. 
O meu problema é que, eu gerava uma etiqueta por uma compra individual (no meu sistema, há uma tabela q lista todas as vendas) e existe um botão q gera a etiqueta para aquela venda em si; havia feito um outro botão q pegava todas essas etiquetas e colocava na plp (q seria utilizado após gerar todas as etiquetas do dia). Só q ao saber dessa informação hj pelos correios, essa minha ideia meio q cai por água abaixo. Queria saber se alguém tem alguma sugestão de como contornar esse problema, espero ter sido claro com a dúvida, desde já, agradeço a todos.

**Comment by lucaspaulino** [comment]
No meu sistema, eu listo todas as vendas com um campo checkbox, e aí eu marco todas ou quais eu desejo enviar. 

Eu faço a solicitação da quantidade de etiquetas de acordo com a quantidade que selecionei, e aí na hora de puxar as etiquetas.. eu já jogo na PLP, já envio os dados de destino, etc.

Aí essas informações ficam gravadas no banco de dados, e eu posso baixar o PDF sempre que necessário.

Espero que seja isso...

**Comment by MatheusAriel** [comment]
Foi justamente oq eu pensei em fazer, gerar as etiquetas das vendas selecionadas juntas e já gerar a plp.
Vlw mano, muito obrigado

**Comment by lucaspaulino** [comment]
@MatheusAriel é pq esse servidor dos correios é um lixo, as vezes vc passa um tempão tentando gerar etiquetas... Então quanto mais vc conseguir fazer de uma vez só melhor.. E quanto mais armazenar no seu banco de dados, melhor ainda tbm, pq não precisa fazer requisições.. Flw

**Comment by MatheusAriel** [comment]
Quando soube do tempo máximo de vida da etiqueta era 10 minutos, fiquei sem entender o pq de tão pouco tempo, se n fosse isso, meu fluxo seguia normalmente do modo como eu estava fazendo, mas, correios é correios, infelizmente
