### ISSUE TITLE
Nomenclatura da etiqueta 2018

### ISSUE THREAD

**Issue by MatheusAriel** [stavarengo/php-sigep#305]
Quando uso o serviço carta comercial à faturar na etiqueta 2018, tá saindo com a nomenclatura PAC. Mas quando uso qualquer outro tipo de carta, sai como Carta, alguém sabe me dizer se isso é um erro?
Já aproveito e pergunto oq iria nesse setNumeroPedido, seria um id da minha venda?

$encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_CARTA_COMERCIAL_A_FATURAR));

![pac](https://user-images.githubusercontent.com/9145799/53092935-ca2b2300-34f4-11e9-80df-b76c79a8e080.PNG)

**Comment by mauroagr** [comment]
Tens o numero do Serviço da Carta comercial?

**Comment by MatheusAriel** [comment]
Tenho sim, é 10065, sabe me informar se é um erro na programação ou sai mesmo como PAC?

**Comment by mauroagr** [comment]
@MatheusAriel Vendo o codigo do projeto, este código tá anexado ao 
```
const SERVICE_PAC_CONTRATO_10065 = '10065';
```
Dá uma olhada nesta conversa #192  e na #231 , ali tem como consultar os codigos corretos do teu contrato. 
Se puder conferir, que acho que tem algo trocado no codigo fonte.

**Comment by MatheusAriel** [comment]
Acabei de olhar o código, talvez seja isso mesmo, há dois itens com o código 10065.

    const SERVICE_PAC_CONTRATO_10065 = '10065';
    const SERVICE_CARTA_COMERCIAL_A_FATURAR = '10065';

Como só vou usar carta comercial à faturar no meu projeto, será q eu alterando o valor do PAC para outro qualquer q n seja 10065 resolverei isso para mim?

**Comment by mauroagr** [comment]
Tu precisa descobrir o codigo correto do teu carta_comercial, possivelmente um deles tá errado. Não é trocar por qualquer código. É um codigo específico dos correios.

**Comment by MatheusAriel** [comment]
Pelo método buscaCliente o carta comercial à faturar retorna 10065

**Comment by mauroagr** [comment]
Tá estranho, pq tem uma constante específica para este 10065, depende comentar aquela linha da constante do PAC, resolveria. Testa ai, acho que mais para baixo tem uma citacao novamente.

@andersonls @stavarengo consegue me ajudar ai, se trocar a constant, resolve o problema do Matheus?

**Comment by MatheusAriel** [comment]
Verifiquei q até os serviços estão iguais, 109480 para ambos            
 self::SERVICE_PAC_CONTRATO_10065                         => array('Pac 10065', self::SERVICE_CARTA_COMERCIAL_A_FATURAR                  => array('Carta Comercial a Faturar', 109480),

Eu consegui resolver comentando o pac_contrato_10065, mas não sei se é a solução mais correta, de qualquer forma, a etiqueta tá saindo como CARTA agora

**Comment by andersonls** [comment]
Boa tarde, essa constante do PAC foi adicionada no PR #278, porém foi um PR grande com várias modificações. 

@stavarengo o que acha de remover a constante referente ao PAC e deixar somente a da Carta?

**Comment by stavarengo** [comment]
Por mim ok Anderson.

**Comment by andersonls** [comment]
Resolvido no commit  5e3711cb0bb11dde76d45ecbd796474cd18c188a.
