### ISSUE TITLE
Adicionar release v0.0.2 no Packagist

### ISSUE THREAD

**Issue by GusAntoniassi** [stavarengo/php-sigep#306]
Bom dia!

Seria possível adicionar a [release v0.0.2](https://github.com/stavarengo/php-sigep/releases/tag/v0.0.2) no Packagist para ela ser instalada via Composer?

Estou com um projeto na versão 7.3 do PHP e não consigo utilizar a 0.0.1 pois ela usa a biblioteca `setasign/fpdi` na versão 1.6, e precisamos desta biblioteca na versão 2.2.

Consegui contornar o problema usando a tag `dev-master` do Packagist, mas gostaria de usar uma versão fixa no composer.json para evitar divergência do código entre os desenvolvedores e o servidor de produção.

Agradeço desde já!

**Comment by stavarengo** [comment]
Oi @GusAntoniassi .
Não entendi muito bem. Porque vc não faz a alteração e submete como PR pra gente avaliar?

**Comment by GusAntoniassi** [comment]
Olá @stavarengo, dei uma pesquisada sobre o Packagist e pelo que encontrei ele deveria subir as tags automaticamente com base nas releases que são postadas aqui no GitHub.

Encontrei [essa issue](https://github.com/composer/packagist/issues/649) sugerindo remover a chave `version` do composer.json. Fiz a alteração e enviei no PR https://github.com/stavarengo/php-sigep/pull/310. Não sei se isso resolverá o problema, mas acho que teria que mergear o PR com a master pra gente testar.

**Comment by stavarengo** [comment]
Cofirmado @GusAntoniassi.
Também encontrei essa sugestão para rever o `version` na [documentação oficial](https://getcomposer.org/doc/04-schema.md#version).
