### ISSUE TITLE
Resposta do Correios: Não foi possível obter as etiquetas solicitadas.

### ISSUE THREAD

**Issue by avlima** [stavarengo/php-sigep#307]
Ambiente: Produção

Problema em solicitar etiquetas:
SERVICE_PAC_41068             
SERVICE_SEDEX_10              
SERVICE_SEDEX_10_PACOTE       
SERVICE_SEDEX_HOJE_40878

Mais alguém está tendo este problema?

O SERVICE_SEDEX_CONTRATO_AGENCIA gera a etiqueta normalmente, o problema ocorre apenas com esses outros serviços acima.

Desde já agradeço.

**Comment by lucaspaulino** [comment]
Talvez estes serviços não estejam no contrato..

**Comment by luiz-merante** [comment]
Estou com esse mesmo problema, mas diferente do amigo acima, eu estou tendo problema com TODAS as etiquetas, todas retornam "Não é possível solicitar as etiquetas"

**Comment by webesistemas** [comment]
estou tendo o mesmo retorno, alguem descobriu um motivo que pode ser?

**Comment by webesistemas** [comment]
acabei intanciando dados de prod na classe de homologação!! deu certinho agora que corrigi isso
