### ISSUE TITLE
Cancelar envio

### ISSUE THREAD

**Issue by lucaspaulino** [stavarengo/php-sigep#309]
Bom dia, existe possibilidade de fazer cancelamento do envio? No nosso painel gerenciador há um botão pra fazer a encomenda voltar de onde está.. Essa implementação é possível? Não vi nada no manual dos correios tbm...

**Comment by andersonls** [comment]
@lucaspaulino Existe sim, mas acho que não está implementado ainda. Se conseguir implementar, depois é só criar um PR que nós aprovamos.

O nome da chamada ao webservice é bloquearObjeto e os parâmetros que precisam ser passados são:

'numeroEtiqueta'   => 'OG12345678BR', //Código de rastreio
'idPlp'            => '123456789', //Número da PLP
'tipoBloqueio'     => 'FRAUDE_BLOQUEIO', //Atualmente só existe esta opção
'acao'             => 'DEVOLVIDO_AO_REMETENTE', //Atualmente só existe esta opção

**Comment by jonyw4** [comment]
Ta implementado sim @andersonls. Deram merge aqui: #221
