### ISSUE TITLE
Ajuda para instalação do plugin

### ISSUE THREAD

**Issue by felipe-tanure-rocha** [stavarengo/php-sigep#311]
Estou tentando instalar a versão "0.0.2" de forma manual, pois não sei trabalhar com o Composer, e ao enviar o arquivo tenho a seguinte mensagem de erro: "O pacote não pôde ser instalado. Nenhum plugin válido foi encontrado.".

Estou utilizando a versão 5.1 do Wordpress e a versão 7.1 do PHP.

Vi a seguinte instrução de instalação "Para usar as classe do php-sigep, você só precisa carregar o arquivo "php-sigep/src/PhpSigep/Bootstrap.php". Isso fara com que o loader seja registrado." mas não entendi muito bem. Seria upar o arquivo no servidor? Eu fiz isso, mas não surtiu efeito.

Agradeço qualquer ajuda!

**Comment by andersonls** [comment]
@felipe-tanure-rocha Eu nunca trabalhei com wordpress, mas este projeto não foi feito como um plugin, acredito que não seja possível instalar como plugin mesmo.
