### ISSUE TITLE
Problemas com a maioria dos exemplos

### ISSUE THREAD

**Issue by SabrinaProexDigital** [stavarengo/php-sigep#312]
Olá,

O exemplo de rastreio fica carregando infinito e depois da erro de tempo de carregamento pra mim.
E o exemplo imprimirPlp.php gera o seguinte erro:

Fatal error: Uncaught Error: Undefined class constant 'SERVICE_SEDEX_40096' no arquivo php-sigep-master\exemplos\helper-criar-pre-lista.php

E no exemplo imprimirEtiquetas2018.php a tela fica toda em branco.

Alguém poderia me ajudar por favor?

**Comment by luiz-merante** [comment]
no imprimir etiquetas2018 é só ir no render do exemplo e tirar os parametros que tao sendo passados, lá na classe já esta sendo passado o parametro e sendo inicializado de vazio

**Comment by SabrinaProexDigital** [comment]
> no imprimir etiquetas2018 é só ir no render do exemplo e tirar os parametros que tao sendo passados, lá na classe já esta sendo passado o parametro e sendo inicializado de vazio

Sabe me dizer qual dos exemplos eu consigo pegar o código de rastreio de uma encomenda?

**Comment by luiz-merante** [comment]
em uma aplicação real você precisaria solicitar a etiqueta, e depois em rastreio você usaria para rastrea-la

**Comment by SabrinaProexDigital** [comment]
> em uma aplicação real você precisaria solicitar a etiqueta, e depois em rastreio você usaria para rastrea-la

Desculpe a burrice, mas é que nunca usei o Sigep... quando eu solicito a etiqueta como eu sei de qual encomenda é? Porque aqui no exemplo só me retorna o código de rastreio mesmo, mais nada. Ou isso só gera um código pra eu usar em uma encomenda depois?

**Comment by jdgrieco** [comment]
@SabrinaProexDigital, você solicita os códigos de rastreio (etiquetas), e quando for gerar a plp você informa remetentse, o tamanho do pacotes, se tem serviços adicionais, destinatários, endereços de entrega, o códigos de rastreio que você gerou antes, os códigos dos serviços (PAC, SEDEX, etc)

**Comment by SabrinaProexDigital** [comment]
> @SabrinaProexDigital, você solicita os códigos de rastreio (etiquetas), e quando for gerar a plp você informa remetentse, o tamanho do pacotes, se tem serviços adicionais, destinatários, endereços de entrega, o códigos de rastreio que você gerou antes, os códigos dos serviços (PAC, SEDEX, etc)

Agora entendi! Muito obrigada!
