### ISSUE TITLE
Novos códigos de serviços (contrato) 06/03/2019

### ISSUE THREAD

**Issue by t8rafa** [stavarengo/php-sigep#314]
Os Correios criaram novos pacotes de serviço, e houve alteração no código de serviços.

**SEDEX Contrato**:
Até 05/03      : 04162
A partir 06/03: 04553

**SEDEX Reverso**:
Até 05/03       : 04170
A partir 06/03: 04928

**PAC Contrato**:
Até 05/03       : 04669
A partir 06/03: 04596

**PAC Reverso**:
Até 05/03       : 04677
A partir 06/03: 04936

[Comunicado Correios - novos códigos pacote ENC 2.0.pdf](https://github.com/stavarengo/php-sigep/files/2936074/Comunicado.Correios.-.novos.codigos.pacote.ENC.2.0.pdf)

**Comment by andersonls** [comment]
@t8rafa consegue criar um PR com esses novos códigos?

**Comment by t8rafa** [comment]
@andersonls feito a PR.

**Comment by luiz-merante** [comment]
onde modificaria no código do sigep?

**Comment by t8rafa** [comment]
pessoal, estou entrando em contato com os Correios, recebi a informação de que todos haviam sido migrados. Vou confirmar e volto com mais detalhes

**Comment by jdgrieco** [comment]
Pessoal, a modificação já foi feita anteriormente no PR #264 do @willian-rosa

**Comment by andersonls** [comment]
@t8rafa Acho interessante confirmar com os correios, mas hoje eu já fiz postagem com os códigos atuais, se todos tivessem sido migrados eu não teria conseguido fazer essa postagem.

**Comment by andersonls** [comment]
@jdgrieco realmente, só faltou os códigos do Sedex e PAC reverso neste PR. @t8rafa pode usar esse PR como base e adicionar apenas os códigos de sedex e pac reverso?

**Comment by jdgrieco** [comment]
@andersonls, eu fiz uma busca pelos códigos cadastrados no contrato de um dos meus clientes e não aparecem os códigos novos para PAC e SEDEX, mas não sei se são os Correios que tem que alterar isso.

Também não sei se nesse caso eles se enquadram no pacote ENCOMENDA BÁSICO - ENC 2.0 (sem valor mínimo
mensal)

**Comment by mauroagr** [comment]
Estes codigos só vale para enc2.0. Não é Geral.

**Comment by walrt** [comment]
@mauroagr, estou entendendo que seriam aplicados à novos contratos, certo? Ou até mesmo a clientes que tiverem seus contratos atualizados.

Se sim, acredito que a lib já está pronta para atender. Só utilizar os serviços que estão como "TA".

**Comment by t8rafa** [comment]
Então, olha o que aconteceu na nossa empresa, conversamos hoje pela manhã com o comercial.
Nosso contrato foi migrado automaticamente para o ENC 2.0, sem nenhuma solicitação nossa.
E eles enfatizaram para usar os novos códigos.

Eu entendo que todos os clientes que usam o PAC_AGENCIA 04669 agora são 04596 (esse é o nosso exemplo).

Conforme vocês comentaram acima, vou passar a utilizar as constantes "TA", que já me atendem.
E faço a adição dos REVERSO @andersonls.

só uma dúvida, qual o significado do TA?

**Comment by willian-rosa** [comment]
Pessoal, tomem cuidado e não façam a alteração de códigos a cegas. Pois nem todos os contratos que se encaixam nas novas regras tem esse código de serviço habilitado.

Aqui na minha empresa estamos utilizando o método 'buscaCliente' para verificar se o contrato tem esse código de serviço.

**Comment by walrt** [comment]
@willian-rosa concordo. Acredito que devemos utilizar o serviços "TA" já existentes.

Também realizei buscas com 2 cartões de postagem aqui da empresa pelo _buscaCliente_ e os serviços antigos ainda permanecem inalterados.
