### ISSUE TITLE
Voucher de Postagem / Pré lista de postagem

### ISSUE THREAD

**Issue by plusites** [stavarengo/php-sigep#319]
Pessoal, no manual de integração dos correios SIGEPWEB, tem um relatório denominado Voucher de Postagem / Pré lista de postagem, não achei ele nos exemplemos. Gostaria de saber se foi desenvolvido

**Comment by andersonls** [comment]
é o exemplo [imprimirPlp.php](https://github.com/stavarengo/php-sigep/blob/master/exemplos/imprimirPlp.php).

**Comment by plusites** [comment]
> é o exemplo [imprimirPlp.php](https://github.com/stavarengo/php-sigep/blob/master/exemplos/imprimirPlp.php).

**Comment by plusites** [comment]
Segundo manual dos correis, são dois relatórios distintos:
Pelo que percebi, o imprimirPlp.php corresponde a listagem 2 do manual dos correios pagina 54.
Na página 53 tem um outro modelo bem parecido, porém tem código de barras, é este que não encontrei exemplo.

**Comment by andersonls** [comment]
Este modelo não tem implementado.
