### ISSUE TITLE
Formato de Etiqueta

### ISSUE THREAD

**Issue by viebig** [stavarengo/php-sigep#32]
No processo de homologação enviaram o formato abaixo, que difere bastante do que fazemos hoje.

Procede? Alguém já fez? Faz sentido?

![selection_001](https://cloud.githubusercontent.com/assets/356510/12648665/31bba72e-c5c2-11e5-9231-3fb4a0e43a85.png)

**Comment by rafaelsiqueira** [comment]
O correios é uma piada. Cada um fala e orienta uma coisa.

De fato, o modelo que você colocou é o mais próximo da documentação. Há 15 dias eu homologuei o sistema aqui da empresa usando o modelo em anexo.

[130822.pdf](https://github.com/stavarengo/php-sigep/files/108428/130822.pdf)

**Comment by viebig** [comment]
Homologou em São Paulo, conversou com quem? Tem o contato?

**Comment by rafaelsiqueira** [comment]
Sim, foi em São Paulo, com o Daniel Teixeira: (11) 2102-2493


*Rafael Siqueira*
*+55 (21) 98091-0023*

2016-01-28 14:52 GMT-02:00 Guilherme Viebig <notifications@github.com>:

**Comment by viebig** [comment]
Os técnicos do correio informaram que vão homologar agora, nas em breve onnovo formato será obrigatório. Estou disposto a na medida da possibilidade adaptar o que temos hoje para o novo formato conforme manual junto a ajuda dos correios para garantir que próximos a usar este pacote tenham menos dificuldade na homologação. 

Ele também atentou a alguns itens no XML, vou forjar e criar pull request na medida do progresso.

**Comment by stavarengo** [comment]
Pessoal, posso fechar esse bug ou ainda precisa ser feito alguma coisa?

**Comment by viebig** [comment]
Pode fechar.

Em ter, 2 de fev de 2016 14:52, Stavarengo <notifications@github.com>
escreveu:
