### ISSUE TITLE
wsdl não encontrada

### ISSUE THREAD

**Issue by tonylampada** [stavarengo/php-sigep#323]
O README faz menção a um arquivo que deve ser baixado daqui
https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl

Mas essa URL tá dando 404. Os correios tão sacaneando a gente mesmo?

Outro problema relacionado é que eu tô tentando rodar um exemplo semelhante ao `solicitarEtiquetas.php` (estou usando o código da tag 0.0.2), só que usando a api de produção, e obtendo um erro que parece relacionado a esse 404

![image](https://user-images.githubusercontent.com/218821/55501793-924dea00-5621-11e9-9544-8c01403710e6.png)

![image](https://user-images.githubusercontent.com/218821/55502040-1607d680-5622-11e9-98b2-bef49af1868b.png)

Alguma dica?

**Comment by tonylampada** [comment]
Mas o quê... é só criar a issue que o serviço do correio volta! ôPôra :-)

**Comment by andersonls** [comment]
@tonylampada Pode se acostumar, o webservice do correio tem umas instabilidades mesmo, hehe. Acho que é o assunto que mais gera issue aqui!
