### ISSUE TITLE
verificaDisponibilidadedeServicos sempre True

### ISSUE THREAD

**Issue by 20in** [stavarengo/php-sigep#325]
Estava testando a função e percebi que só estava dando  'disponivel":protected]=> bool(true)', fui então para o site dos correios verificar se os serviços realmente estavam disponível, porém não estavam, mas o retorno diz que está.

Código:
public function verificaDisponibilidadeServico($cepOrigem, $cepDestino, $servicos){
            
            foreach($servicos as $servico){
                $i_servico = new ServicoDePostagem($servico);
                $arr_servicos[] = $i_servico;
            }
            $cep = self::consultaCep($cepOrigem);
                    print_r($cep);echo"<BR><BR>";
            $cep = self::consultaCep($cepDestino);
                    print_r($cep);echo"<BR><BR>";
            $params = new verificaDisponibilidadeServico;
            $params -> setCepOrigem($cepOrigem);
            $params -> setCepDestino($cepDestino);
            $params -> setServicos($arr_servicos);
                    print_r($params -> getServicos());echo"<BR><BR>";
            $retorno = $this->real->verificaDisponibilidadeServico($params);
                    var_dump($retorno);

        }

Retorno:
Array ( [cep] => 95760000 [uf] => RS [cidade] => São Sebastião do Caí [bairro] => [endereco] => [complemento1] => [complemento2] => ) 

Array ( [cep] => 22451368 [uf] => RJ [cidade] => Rio de Janeiro [bairro] => Rocinha [endereco] => Rua Antônio Simão de Araújo [complemento1] => [complemento2] => ) 

Array ( [0] => PhpSigep\Model\ServicoDePostagem Object ( [codigo:protected] => 40169 [idServico:protected] => 115218 [nome:protected] => Sedex 12 [_failIfAtributeNotExiste:protected] => 1 ) ) 

object(PhpSigep\Services\Result)#17 (6) { ["isSoapFault":protected]=> bool(false) ["errorCode":protected]=> NULL ["errorMsg":protected]=> NULL ["result":protected]=> object(PhpSigep\Model\VerificaDisponibilidadeServicoResposta)#16 (2) { ["**disponivel":protected]=> bool(true)** ["_failIfAtributeNotExiste":protected]=> bool(true) } ["soapFault":protected]=> NULL ["_failIfAtributeNotExiste":protected]=> bool(true) }

**Comment by 20in** [comment]
Corrigi o erro já

**Comment by mydanilows** [comment]
Boa tarde, como você corrigiu isso estou tentado o mesmo problema
