### ISSUE TITLE
erro ao converter para json

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#326]
pode ser que seja algo simples, mas estou com dificuldade por ainda ser trainee, quero converter o obj php que o calcPreçoPrazo retorna para json, porém não consigo pois as variaveis sao protected, alguem poderia me ajudar?

**Comment by andersonls** [comment]
@luiz-merante Pega o valor das variáveis com os gets da classe e monta a string do json. Ou monta um array e depois passa ele para o json_encode

**Comment by luiz-merante** [comment]
eu preciso do valor, prazo da entrega, entrega domiciliar, entrega sabado, e não está dando certo, quando chamo o get desses valores vem sempre vazio, devo criar uma função dentro de alguma classe pra retornar isso ou posso chamar diretamente numa model ou controller?

**Comment by andersonls** [comment]
Pode colocar o trecho do teu código que tá pegando esses valores?

**Comment by luiz-merante** [comment]
![erro correios](https://user-images.githubusercontent.com/48022324/55744871-56919680-5a0c-11e9-95e8-4d15cfba600e.png)
está marcado ai, quando eu chamo o getValor por exemplo, ele vem vazio(talvez seja pq nao estou sabendo como e onde invocar esse metodo também)

**Comment by andersonls** [comment]
Substituia a linha 60 por:

```php
$result->getResult();
$result = $result[0]; //Se for calcular para mais de um serviço temq iterar o $result ao invés de usar o [0]

$array = array(
    'valor' => $result->getValor(),
    'prazoEntrega' => $result->getPrazoEntrega(),
    //E o que mais você precisar de informações
);

$json = json_encode($array);

print_r($json);
```

**Comment by luiz-merante** [comment]
![erro correios](https://user-images.githubusercontent.com/48022324/55746121-4fb85300-5a0f-11e9-8164-eb7def09064d.png)
ainda sim não deu :(

**Comment by andersonls** [comment]
Opa, na primeira linha faltou código! é $result = $result->getResult();

**Comment by luiz-merante** [comment]
$result = $result-> getResult(); //Se for calcular para mais de um serviço temq iterar o $result ao invés de usar o [0]
                $array = array(
                    'valor' => $result->getValor(),
                    'prazoEntrega' => $result->getPrazoEntrega(),
                    //E o que mais você precisar de informações
                ); 
                $json = json_encode($array);
                print_r($json);
                
                exit();
esse é o código atual, e deu o mesmo problema que está dando no postman, diz que eu não posso acessar uma propriedade vazia

**Comment by andersonls** [comment]
Você fez alguma alteração no código da biblioteca? Se você der um print_r($phpSigep->calcPrecoPrazo($params)); retorna o que?

Veja também se você consegue rodar o calcPrecoPrazo.php que tem na pasta exemplos

**Comment by luiz-merante** [comment]
![erro correios](https://user-images.githubusercontent.com/48022324/55751100-3fa67080-5a1b-11e9-95b8-4220ea95ab5e.png)
esse é o retorno do que vc pediu acima

**Comment by luiz-merante** [comment]
única alteração que fiz foi a de fazer apenas para um determinado tipo de entrega, antes fazia para todas as entregas disponiveis. n sei se isso realmente influenciaria em algo

**Comment by luiz-merante** [comment]
Consegui agora, thanks @andersonls

**Comment by andersonls** [comment]
Show de bola @luiz-merante
