### ISSUE TITLE
permissão negada para geração de etiquetas em pdf

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#328]
![erro correios](https://user-images.githubusercontent.com/48022324/55904855-2f230100-5ba7-11e9-9125-2b540d7e1191.png)
estou com esse erro, não faço ideia do porque, se alguem puder me ajudar agradeceria muito, tenho que entregar esse sistema até sexta!!! :(

**Comment by luiz-merante** [comment]
@andersonls @stavarengo

**Comment by 20in** [comment]
verificou se o caminho do helvetica.php está correto?

**Comment by luiz-merante** [comment]
Resolvida.
