### ISSUE TITLE
Etiqueta e ListaDePostagem

### ISSUE THREAD

**Issue by 20in** [stavarengo/php-sigep#329]
Após o desenvolvimento das funções de criar a etiqueta e a lista de postagem, me deparei com um problema, para utilizar essas funções eu utilizo os parametros da função 'fechaPlpVariosServicos' já que eles são da classe PreListaDePostagem, porém não consigo montar etiqueta e lista de postagem, pois quando uso o render() ele não executa mais o codigo, então não cria o proximo, e se eu fizer um de cada vez, é criado um novo idPlp.

Alguém teria alguma solução, algum modo de guardar a PLP ou algo assim, para que eu abrir o mesmo PLP diversas vezes.

**Comment by 20in** [comment]
Resolvido com base no #293 
> @mauroagr, eu consigo imprimir somente as etiquetas que desejo "remontando" a PLP:
> 
> ```
>         $plp = new \PhpSigep\Model\PreListaDePostagem();
>         $plp->setAccessData($accessData);
>         $plp->setEncomendas($encomendas);
>         $plp->setRemetente($remetente);
>         $pdf = new \PhpSigep\Pdf\CartaoDePostagem2016($plp, '', $logoFile); 
>         $pdf->render('D', 'Etiquetas da PLP ' . $plpID . ' - ' . date('Y-m-d H:i') . '.pdf');
> ```
> Colocando na variável "$encomendas" somente os dados das etiquetas.
> Funciona inclusive para PLP ainda não transmitidas e PLP fechadas (transmitidas para os Correios)

**Comment by luiz-merante** [comment]
estou com esse mesmo problema, como solucionou?

**Comment by silvavitor** [comment]
Salvei no banco todas as informações pra construir uma nova PLP antes de pedir a etiqueta novamente
