### ISSUE TITLE
WSDL de produção não funciona em PHP 5.3+

### ISSUE THREAD

**Issue by xjaco222x** [stavarengo/php-sigep#33]
ola,

O meu sistema parou de funcionar sem prévios motivos, depois de vários testes constatei que o webservice de desenvolvimento funciona em todas as versões do PHP, porem o webservice em produção só funciona no PHP 5.2, no 5.3 + da um looping infinito.

Alguém está com o mesmo problema?

**Comment by viebig** [comment]
Loop infinito em getEtiquetaSemDv? Pode postar o dump?

**Comment by xjaco222x** [comment]
<?

$client = new SoapClient("https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl");
 
$function = 'buscaCliente';
 
$arguments= array('ConvertTemp' => array(
						'idContrato' => "dados do contrato",
						'idCartaoPostagem' => "dados do cartao",
                        'usuario'   => "dados do usuario",
                        'senha'      => "dados da senha"
                ));
$options = array('location' => "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente");
 echo "aqui";
$result = $client->__Call($function, $arguments, $options);
 
echo 'Response: ';

foreach($result as $row){
	foreach((object)$row->contratos->cartoesPostagem->servicos as $row2){
		echo $row2->codigo;
		echo "<br/>";
	}
}
?>


Aqui segue um script que fiz só para testar, e sempre tenho o mesmo erro de tempo limite exedido no php 5.3 ou maior.

O link como pode ser visto está em produção, mas seu eu trocar para desenvolvimento funciona normalmente.

Obs: tenho dados validos para conexão.

**Comment by xjaco222x** [comment]
não sei exatamente se o que vc quer é o var_dump mas se for não é possivel enviar pois o erro que ocorre é um erro 500, como se não enviasse os dados.

**Comment by rafaelsiqueira** [comment]
Eu tive esse problema tb.

Pelo que pude perceber, o SoapClient não consegue baixar o WSDL (não
consegui investigar a fundo). Pra resolver o problema aqui, eu baixei o
WSDL e salvei local no meu servidor.

Na criação do SoapClient você passa um path local e tudo funciona. Não sei
se é alguma questão de certificado ssl.

Abraços,
*Rafael Siqueira*

2016-02-01 10:19 GMT-02:00 xjaco222x <notifications@github.com>:

**Comment by xjaco222x** [comment]
Obrigado rafael, não manjo muito disso mas vou tentar fazer isso. vlw.

**Comment by xjaco222x** [comment]
@rafaelsiqueira não consegui achar nada, sera que vc pode me dar uma explicação melhor de como vc fez?

**Comment by xjaco222x** [comment]
consegui, estava cometendo um erro no momento de passar o link. grato novamente.
