### ISSUE TITLE
 Resposta do Correios: Não foi possível obter as etiquetas solicitadas.

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#330]
$etiqueta = new \PhpSigep\Model\Etiqueta();
                $accessData = new \PhpSigep\Model\AccessDataHomologacao();
		$params = new \PhpSigep\Model\SolicitaEtiquetas();
		$params->setQtdEtiquetas(1);
		$params->setAccessData($accessData);
		$params->setServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068);

		$phpSigep = new \PhpSigep\Services\SoapClient\Real();
		$codEtiqueta = $phpSigep->solicitaEtiquetas($params);
                
                print_r($codEtiqueta);
                exit();
toda vez me da o retorno = " Resposta do Correios: Não foi possível obter as etiquetas solicitadas." isso pra toda e qualquer etiqueta, estou fazendo algo errado?(eu ja estou setando na mão o accessdataHomologação com os parametros que o cara dos correios me passou)

**Comment by luiz-merante** [comment]
[idCorreiosUsuario:protected] => 
            [idCorreiosSenha:protected] => 
 [anoContrato:protected] => 
acabei de ver, e esses 3 campos estão vazios, há algum problema nisso? @stavarengo

**Comment by humbcezar** [comment]
@luiz-merante Estou com o mesmo problema. Você conseguiu resolver?

**Comment by luiz-merante** [comment]
Consegui, na vdd essa api é maluca kkkkkk não estava pegando e voltou do nada
Resolvido aqui.
