### ISSUE TITLE
Consultar ID da PLP

### ISSUE THREAD

**Issue by jdgrieco** [stavarengo/php-sigep#331]
Olá a todos.

Em um de meus clientes, com frequência, no fechamento da PLP dá algum erro e não retorna o ID da PLP.

Quando se tenta repetir o processo de fechamento o webservice retorma: A PLP não será fechada, o(s) objeto(s) .....  já estão vinculados em outra PLP!

Alguém conhece alguma maneira de recuperar o ID da PLP nesse caso? Pelo idPlpCliente ou código de uma etiqueta

**Comment by 20in** [comment]
Eu estou guardando cada plp no meu bd, pois não consegui pensar em nenhuma outra maneira

**Comment by jdgrieco** [comment]
@20in eu também faço isso, o problema é que esse erro está ocorrendo antes de eu receber o ID da PLP. 

Esperava encontrar uma maneira de conseguir consultar esse ID de alguma maneira

**Comment by andersonls** [comment]
Até onde sei não tem como obter o ID da PLP, pois essa é a chave pra você obter qualquer outra informação.

Será que não tem algum erro no teu código entre o fechamento da PLP e quando você salva/mostra na tela o ID? Acho estranho, pq se tá dizendo que já tá vinculado a uma PLP não deveria ter dado erro no lado do correio (mas se tratando de webservice de órgão público vai saber como eles tratam lá dentro).

**Comment by jdgrieco** [comment]
@andersonls, eu estou desconfiado que alguma coisa com timeout, apesar de já ter colocado set_time_limit(0).

Vou colocar um log para registrar as etapas.

O sistema deles realmente é uma porcaria
