### ISSUE TITLE
Etiqueta vindo em branco 

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#332]
quando faço a requisição no postman, a etiqueta vem certinho, mas quando faço a requisição de download no navegador, as paginas do pdf vem todas vazias, alguém sabe pq?

**Comment by HenriqueCRodrigues** [comment]
poste o trecho do código utilizado.
de antemão vc esta finalizando a função de impressão com $pdf->render(); ?

**Comment by webesistemas** [comment]
Estou tendo o mesmo problema
