### ISSUE TITLE
Logo esticado no CartaoDePostagem2018

### ISSUE THREAD

**Issue by lipemesquita** [stavarengo/php-sigep#333]
Boa tarde, notei que o comportamento do logotipo foi alterado da etiqueta 2016 para a 2018. Agora é informada uma altura fixa de 25mm, ou seja, é esperado um logo quadrado

Código do CartaoDePostagem2016:
`$this->pdf->Image($this->logoFile, 66, $this->pdf->GetY() + 3, 25);`

Código do CartaoDePostagem2018:
`$this->pdf->Image($this->logoFile, 5, ($this->pdf->GetY() + 2), 25, 25);`

Alguém com alguma sugestão de um workaround?

**Comment by andersonls** [comment]
@lipemesquita O espaço destinado para o logo no layout do correio é quadrado. O logo que você informar deveria encolher para caber no espaço, caso seja retangular.

Você já tentou utilizar a etiqueta com a sua logo?

**Comment by lipemesquita** [comment]
Sim, no caso, ela fica esticada para cobrir toda a área quadrada, distorcida. Se eu remover o parâmetro de altura ela fica encolhida, como acontecia no CartaoDePostagem2016

**Comment by andersonls** [comment]
Pode ser o caso de apenas remover o último parâmetro. Você consegue testar com algumas imagens diferentes de logo? Se o resultado ficar certo, pode criar um PR com essa correção ou me avisa que eu posso fazer a alteração também.

**Comment by lipemesquita** [comment]
Imagino que tenha sido feito dessa maneira para não quebrar com logotipos no formato retrato, com a altura maior que a largura..  Se for esse o caso, nem acho bom alterar.. eita..

**Comment by lipemesquita** [comment]
Agradeço a resposta imediata, mas resolvi por fora, informando uma logo quadrada.. Se não for interessante a discussão, eu dou a Issue como fechada.. valeu!

**Comment by andersonls** [comment]
@lipemesquita Se você tiver interesse em fazer um tratamento na classe para aceitar qualquer tipo de logo (quadrada, retrato e paisagem), as alterações serão bem vindas!
