### ISSUE TITLE
validações da mercadoria

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#337]
Alguém que já tenha o sistema bem amadurecido, pode me passar TODAS  as validações que devem ser feitas para os fretes? 
Exemplo: a largura não pode passar de 105cm
Preciso dessas validações para poder fazer mais de 1 frete, caso passe de 105 cm por exemplo, eu estarei criando uma nova requisição para um novo frete. Agradeço desde já!

**Comment by HenriqueCRodrigues** [comment]
https://www.correios.com.br/a-a-z/limites-de-dimensoes-e-peso
