### ISSUE TITLE
Tamanho da Etiqueta de Impressão

### ISSUE THREAD

**Issue by JhonatanGarcia92** [stavarengo/php-sigep#339]
Boa tarde Galera,
Alguém já passou por esse problema de quebra de Layout da Etiqueta?

![Captura de Tela 2019-04-30 às 15 01 51](https://user-images.githubusercontent.com/12009571/56983163-5b53f100-6b59-11e9-931b-481bfb911d3c.png)

**Comment by luiz-merante** [comment]
Comigo até agora não aconteceu isso, você modificou algo nas classes de impressão? talvez seja isso

**Comment by JhonatanGarcia92** [comment]
> Comigo até agora não aconteceu isso, você modificou algo nas classes de impressão? talvez seja isso

pior que não amigo. Esse tamanho fixo do layout atual que esta dando essa dor de cabeça. Estou verificando a possibilidade de aumentar esse tamanho, senão vou barrar na aplicação o tamanho do complemento do endereço.

**Comment by barreirinha** [comment]
Observe que o Completento do Endereço ficou muito grande, acho que foi planejado para apenas 1 linha

**Comment by JhonatanGarcia92** [comment]
> Observe que o Complemento do Endereço ficou muito grande, acho que foi planejado para apenas 1 linha

então cara, terei de barrar essa situação aqui na aplicação, porque hoje esta limitado em 255 caracteres, e estive analisando melhor os detalhes dessa API, e vi que pedem uma limitação de 30 caracteres para etiqueta.

Agradeço o apoio galera. Obrigado
