### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach() in src/PhpSigep/Services/Real/RastrearObjeto.php on line 128

### ISSUE THREAD

**Issue by prhost** [stavarengo/php-sigep#34]
Ola, estou recebendo esse erro quando rastreio o objeto. De alguma forma, os objetos retornados, alguns deles vem completamente NULL em sua posição, coloquei um `if($objeto)` antes do `foreach($objeto->evento as $evento)` e aparentemente funcionou, só não sei se é a melhor forma de consertar este bug.

**Comment by stavarengo** [comment]
Bug antigo e sem interações.
