### ISSUE TITLE
Erro WDSL em ambiente de desenvolvimento

### ISSUE THREAD

**Issue by HenriqueCRodrigues** [stavarengo/php-sigep#340]
Bom dia pessoal, estou tendo um problema com essa biblioteca, gostaria de saber se alguém consegue me ajudar.
Imagem 1- Erro que estou recebendo no momento que solicito qualquer informação com a biblioteca.
Imagem 2 - Erro que estou recebendo no momento que solicito qualquer informação com a biblioteca, quando eu utilizo a solução do php < 5.2, (MEU PHP é o 7.2).
Imagem 3 - Meus parâmetros, está igual ao de acesso de homologação.
Imagem 4 - Configuração do bootstrap
Imagem 5 - Iniciando o sigep e invocando a função. 

O $result está vindo com erro, ontem eu tinha feito o teste com o mesmo código e estava funcionando.

![image](https://user-images.githubusercontent.com/23089194/57140282-c980f980-6d8d-11e9-9bcd-3ef7809e3e44.png) **Imagem 1**

![image](https://user-images.githubusercontent.com/23089194/57140344-ec131280-6d8d-11e9-8a5c-db8cbf0c31f4.png) **Imagem 2**

![image](https://user-images.githubusercontent.com/23089194/57140534-5d52c580-6d8e-11e9-975e-1cffba86f5cb.png) **Imagem 3**

![image](https://user-images.githubusercontent.com/23089194/57140615-91c68180-6d8e-11e9-88c1-6cb7f70476cd.png) **Imagem 4**

![image](https://user-images.githubusercontent.com/23089194/57140693-b9b5e500-6d8e-11e9-9212-0abae85c4fb2.png) **Imagem 5**

**Comment by andersonls** [comment]
@HenriqueCRodrigues é o webservice de homologação do correio que está fora do ar ou com problema, não tem relação com a biblioteca.

**Comment by HenriqueCRodrigues** [comment]
Obrigado pela a informação!

**Comment by mauroagr** [comment]
@HenriqueCRodrigues remove aquela imagem com o usuario e senha, melhor não deixar estes dados publicos
