### ISSUE TITLE
Erro de "Busca CEP"

### ISSUE THREAD

**Issue by HenriqueCRodrigues** [stavarengo/php-sigep#341]
Bom dia estava testando a biblioteca, notei que a a função busca esta dando problema na variável $complemento, eu inspecionei a o retorno do SOAP, e o retorno do SOAP esta sendo sendo de acordo com a imagem 1.
Na função da biblioteca, **imagem 2**, esta referenciando uma variável que não esta retornando dos correios.
Recomendo colocar um isset nas variáveis.
Ex:. $r->return->complemento ? $consultaCepResposta->setComplemento1(SoapClientFactory::convertEncoding($r->return->complemento)); : '';
Ou 
IF ($r->return->complemento) {
$consultaCepResposta->setComplemento1(SoapClientFactory::convertEncoding($r->return->complemento));
}

![image](https://user-images.githubusercontent.com/23089194/57147108-364fc000-6d9d-11e9-860f-29a8fc262d29.png)
**Imagem 1**

![image](https://user-images.githubusercontent.com/23089194/57147176-58e1d900-6d9d-11e9-93f9-17a3c783f3bc.png)
**Imagem 2**

**Comment by andersonls** [comment]
Já tem um PR para este problema (#334). Só não foi feito merge pq foi excluida uma linha e o autor ainda não corrigiu. 

Dá uma olhada nele, se quiser fazer um novo PR pra corrgir o problema eu dou merge no teu e fecho o outro!

**Comment by HenriqueCRodrigues** [comment]
@andersonls Acabei de fazer um pull na master
