### ISSUE TITLE
Possível bug no fechaPlpVariosServicos

### ISSUE THREAD

**Issue by HenriqueCRodrigues** [stavarengo/php-sigep#343]
Estou utilizando a biblioteca, na hora que fui implementar o fechaPlpVariosServicos notei que o campo 'idPlpCliente' esta sendo passado valor (''), gostaria de saber se estão ciente e se precisar faço PR para da a opção de passar o idPlpCliente para ser enviado

**Comment by andersonls** [comment]
@HenriqueCRodrigues Até onde sei esse campo não tem utilizadade, pois o webservice armazena nem faz nada com ele.

**Comment by luiz-merante** [comment]
o meu fechaPlpVariosServicos também está bugado, ele sempre me da o mesmo retorno pra toda e qualquer etiqueta 
"errorMsg": "A PLP não será fechada, o(s) objeto(s) [PU37920569BR] já estão vinculados em outra PLP!"
Alguém sabe como resolver?

**Comment by HenriqueCRodrigues** [comment]
@luiz-merante esse "problema" acontece, pq a sua etiqueta já pertence a uma lista PLP.
Cada etiqueta só pode pertencer a uma lista PLP.
Só vc gerar uma nova etiqueta e testar, que irá gerar o seu idPlp
