### ISSUE TITLE
Problemas em fazer consultas 2 dias! 

### ISSUE THREAD

**Issue by tiagobatistaa** [stavarengo/php-sigep#344]
Alguém esta com problemas no WS? estou a 2 dias parado. 

504 Gateway Time-out
nginx/1.6.2

preparo todos os paramentros quando faço envio $phpSigep->calcPrecoPrazo($params); 
erro  Time-out

Parms: 

> object(PhpSigep\Model\CalcPrecoPrazo)#21 (9) {
  ["accessData":protected]=>
  object(PhpSigep\Model\AccessDataHomologacao)#22 (11) {
  ["servicosAdicionais":protected]=>
  NULL
  ["ajustarDimensaoMinima":protected]=>
  bool(true)
  ["_failIfAtributeNotExiste":protected]=>
  bool(true)
}

**Comment by jdgrieco** [comment]
@tiagobatistaa, também está acontecendo para mim.

Infelizmente é o padrão de qualidade dos Correios

**Comment by tiagobatistaa** [comment]
> @tiagobatistaa, também está acontecendo para mim.
> 
> Infelizmente é o padrão de qualidade dos Correios

Ufa hehe ja estava começando a fazer do 0 no xml kkk

**Comment by AlexMacha** [comment]
Querendo me livrar dessas APIs, já é a 3 ou 4 vez nesses últimos 2 anos que tem problema por parte dos Correios. Não da pra confiar em deixar uma plataforma consultar nisso e ainda usa um meio de comunicação obsoleto de 2005. O jeito é usar tabela de cep x peso x preço.

**Comment by mathmarques** [comment]
O problema está em algumas portas dos servidores do Correios utilizados no wsdl: http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL
No final desse arquivo possui um: ``<wsdl:service name="CalcPrecoPrazoWS">`` que informa a URL da endpoint (ela varia entre as portas: 80, 8080, 8081 e 8082 `randomicamente`, atualize a página para ver) e somente a porta 80 está funcionando. Porém o Soap do PHP faz cache do wsdl e se ele pegou a porta incorreta, vai ficar dando erro.

A solução aqui foi implementar uma requisição POST direto para: ``http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo``

**Comment by jdgrieco** [comment]
@mathmarques, consegue detalhar o que você fez?

**Comment by tiagobatistaa** [comment]
> A solução aqui foi implementar uma requisição POST direto para: `http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo`

fale mais sobre?

**Comment by mathmarques** [comment]
@jdgrieco e @tiagobatistaa 
É possivel ver aqui: http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo os outros métodos que essa endpoint aceita.
Mas basicamente é enviar os mesmos [argumentos do SOAP](https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/CalcPrecoPrazo.php#L86-L101) via `POST` (lembrar do `Content-Type: application/x-www-form-urlencoded`) para `http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo`

Repare que o XML resultante é um pouco diferente, não possui o `soap:Envelope` e `soap:Body`. Retorna um `<cResultado>` com o `<Servicos>` como filho. Pode utilizar [essa mesma lógica para o parse](https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Services/Real/CalcPrecoPrazo.php#L142-L177).

**Comment by tiagobatistaa** [comment]
Pessoal achei uma solução bem simples: 
@jdgrieco e @AlexMacha 

Dentro do arquivo:
http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL
Conforme o @mathmarques falou tem as linhas:
 
```
<http:address location="http://ws.correios.com.br:8081/calculador/CalcPrecoPrazo.asmx"/>
<http:address location="http://ws.correios.com.br:8081/calculador/CalcPrecoPrazo.asmx"/>
```

**Minha solução temporária:** 
Salvei o xml http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL em um local do meu servidor, e alterei essas linhas para:
```
<http:address location="http://ws.correios.com.br:80/calculador/CalcPrecoPrazo.asmx"/>
<http:address location="http://ws.correios.com.br:80/calculador/CalcPrecoPrazo.asmx"/>  
```

Então no arquivo src\PhpSigep\Config.php
alterei a const WSDL_CAL_PRECO_PRAZO = "LOCAL_DO_MEU_SERVIDOR_COM_PORTA_80"

>_plin plin e a luz voltou a brilhar._

**Comment by jdgrieco** [comment]
@tiagobatistaa, não precisa mexer no código da classe pois existe $config->setWsdlCalPrecoPrazo().

Eu salvei o XML, fiz a modificação que nem vc indicou e usei o "set" acima para configurar, deu certo

**Comment by marcobraghim** [comment]
Com problema aqui também =/

**Comment by marcobraghim** [comment]
Alguém sabe me dizer se é possível desabilitar o cache para reduzir a ocorrencia desses erros?

**Comment by AlexMacha** [comment]
Galera aqui pra mim aparentemente voltou.
