### ISSUE TITLE
Cancelamento de etiqueta

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#346]
Tenho o seguinte cenário: foi gerada a etiqueta, porém o fornecedor não irá enviar mais o produto por N motivos, existe alguma maneira de eu cancelar essa etiqueta para não precisar pagar por ela?

**Comment by andersonls** [comment]
@luiz-merante Se a etiqueta não foi postada não há necessidade de cancelar A cobrança só é feita no momento da postagem.

**Comment by luiz-merante** [comment]
se somente gerar a etiqueta, não é cobrado nada?
