### ISSUE TITLE
Erro Cannot access protected property PhpSigep\Pdf\ImprovedFPDF::$w

### ISSUE THREAD

**Issue by diegosurita** [stavarengo/php-sigep#350]
Olá pessoal.

Eu estou recebendo uma exception (Cannot access protected property PhpSigep\Pdf\ImprovedFPDF::$w), no momento que o método \Sigep\Model\CartaoDePostagem::_render() é executado.

Não tenho ideia se o que pode ser, alguém poderia me dar um help?

Thanks!

**Comment by andersonls** [comment]
Diego, você está usando qual versão do FPDF? O projeto não é compatível com
a versão 1.8!

**Comment by diegosurita** [comment]
Oi Anderson.

Vi aqui que outra dependência do meu projeto está utilizando a versão 1.8.1.

Existe algum plano de upgrade da compatibilidade para a versão 1.8.* do FPDF?

**Comment by andersonls** [comment]
@diegosurita Se conseguir, pode fazer um PR com as alterações necessárias na classe _ImprovedFPDF_ para ser compatível com o FPDF 1.8

@stavarengo Acha que é seguro fazer o upgrade?
