### ISSUE TITLE
etiqueta gera em dev mas em prod não gera

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#353]
os dados do acess data de homologação está correto, com o usuario e senha que foi passado pelos correios, em ti gera a etiqueta normalmente, em ambiente de produção não gera, alguem sabe o motivo? não achei diferenças de codigo do meu ti com a de produção, e isso está me matando de tanto pensar kkkkk

**Comment by luiz-merante** [comment]
não entendi, a resposta dos correios quando ta em ti vem corretamente, em produção vem null

**Comment by luiz-merante** [comment]
resolvido aqui.

**Comment by tdias25** [comment]
Luiz merante, estou com o mesmo problema, o que foi?

**Comment by luiz-merante** [comment]
a resposta vinha certa, porém na hora de tratar o json tava sendo tratado errado, acho que era isso @tdias25

**Comment by luiz-merante** [comment]
uma dica, se a api que vc usa pra gerar a etiqueta é uma api separada da api da sua loja, tenta bater diretamente no web service dos correios que gera a etiqueta, assim verá se o erro ta no código da api separada, ou se ta errando no tratamento, ou até mesmo no curl que faz ligação das duas api

**Comment by tdias25** [comment]
Então, eu instalei esse pacote do php-sigep hoje pelo composer, seria o mais atual, eu só alterei o ENV_DEVELOPMENT pra ENV_PRODUCTION e alterei o setContrato, e começou a dar esse erro do SOAP, em qual parte do idCorreios eu habilito essa função?
