### ISSUE TITLE
plp inválida

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#354]
![etiqueta](https://user-images.githubusercontent.com/48022324/59217370-2b562f80-8b94-11e9-8721-2176d67f254e.jpg)
o cliente gerou a etiqueta, e quando chegou nos correios para poder postar, deu o seguinte erro de etiqueta invalida, alguém sabe o que pode ser?

**Comment by mauroagr** [comment]
Tua postagem nao tá encode errado? UTF8 em vez de ISO-8859-1 ou vice versa?

**Comment by luiz-merante** [comment]
$xml = utf8_encode($xmlDaPreLista->flush());

a linha do encode ai @mauroagr , eu ainda sou iniciante na empresa onde estou, está algo errado ai? se sim, me de mais detalhes por favor.

**Comment by brunogpires** [comment]
Passei por este problema, e no meu caso, e função abaixo estava comentada
`$result = $phpSigep->fechaPlpVariosServicos($plp);`

Por isso quando chegava nos Correios, enfrentava o mesmo problema que você, depois que descomentei essa função, tudo funcionou perfeitamente!
