### ISSUE TITLE
A PLP não será fechada, o(s) objeto(s) [PU37920569BR] já estão vinculados em outra PLP!

### ISSUE THREAD

**Issue by luiz-merante** [stavarengo/php-sigep#355]
sempre que uso o fecharPlpVariosServicos sempre me retorna isso, pra toda e qualquer etiqueta, como seria o fluxo para o fechamento da plp? preciso disso urgente pois o sistema de envio está parado por conta disso

**Comment by mauroagr** [comment]
Não tem um loop  duplicando o envio da plp que dá este erro?

**Comment by luiz-merante** [comment]
@mauroagr na verdade fecharPlpVariosServicos não necessita ser usado no fluxo de fechamento, eu gerando a lista de postagem já simultaneamente já estaria fechando a plp, certo? se for eu consegui arrumar
