### ISSUE TITLE
Serviço adicional - Valor Declarado

### ISSUE THREAD

**Issue by jonyw4** [stavarengo/php-sigep#36]
Hoje tive um problema com os correios e achei interessante compartilhar aqui 
Existe uma regra para utilizar o Serviço de Valor Declarado de um produto, ele precisa ter no mínimo: R$15,00.
Acho que seria interessante criar uma condição já no php-sigep para que ele não deixasse utilizar o serviço nesse caso.

**Comment by alamops** [comment]
+1

**Comment by stavarengo** [comment]
@jonyw4 Você não consegue fazer e nos mandar como pull request?
+1

**Comment by stavarengo** [comment]
Fechando o bug, pois não tive mais respostas e nenhum outro usuário reportou o problema.
