### ISSUE TITLE
Dúvida: rastreio

### ISSUE THREAD

**Issue by trialforce** [stavarengo/php-sigep#367]
Bom dia.

Isto não é um issue é uma dúvida.

Meu cliente usa um sistema externo para gerar as etiquetas e códigos do Correio.

Acontece que hoje uma pessoa tem que manualmente copiar esse código e preencher no meu sistema.

Existe a possibilidade via Sigep, de que eu leia a lista de encomendas enviadas e pegue o código de rastreio dela e então atualize minha base?

Obrigado pela atenção. 

Abraço.

**Comment by gustvao** [comment]
@trialforce o método SolicitaXmlPlp da classe Real vai te falar todas as etiquetas da PLP consultada:

```php
$phpSigep = new PhpSigep\Services\SoapClient\Real();
$result = $phpSigep->SolicitaXmlPlp($_GET['plp']);
```

**Comment by trialforce** [comment]
Obrigado amigo!
