### ISSUE TITLE
Xml Encode - Franquias x Agencias

### ISSUE THREAD

**Issue by mauroagr** [stavarengo/php-sigep#369]
Pessoal,
Estou tendo problema de acentos bugados ao postar na franquia..e não tenho problema ao postar na agência propria.
Quem sabe ai está o problema que tempo atras, alguns não tinham problema postando como ISO e outros tinha, e vice versa.
Postando como iso na agencia, não tenho problema.
Alguem passou por isto?

**Comment by gustvao** [comment]
@mauroagr o que resolveu para mim foi essa lib:
ForceUTF8\Encoding

**Comment by gutobenn** [comment]
Obrigado, @mauroagr!
Passei pelo mesmo problema. Na agência funcionava UTF-8, na franquia não. Troquei para ISO-8859-1 e funcionou na franquia.

**Comment by mauroagr** [comment]
Tu conseguiu resolver só trocando a codificação?
Eu tentei e não fui feliz,acho que devo ter feito algo errado.

**Comment by gustvao** [comment]
caso ajude alguem, para mim ficou assim:

`Services/Real/FecharPreListadePostagem.php`

```php
public function execute(\PhpSigep\Model\PreListaDePostagem $params)
    {
        $xmlDaPreLista = $this->getPlpXml($params);

        $listaEtiquetas = array();
        foreach ($params->getEncomendas() as $objetoPostal) {
            $listaEtiquetas[] = $objetoPostal->getEtiqueta()->getEtiquetaSemDv();
        }

        $xml = utf8_encode($xmlDaPreLista->flush());
//		$xml = utf8_encode($xml);
		$xml = iconv('UTF-8', 'ISO-8859-1', $xml);

        $soapArgs = array(
            'xml'            => $xml,
            'idPlpCliente'   => '',
            'cartaoPostagem' => $params->getAccessData()->getCartaoPostagem(),
            'listaEtiquetas' => $listaEtiquetas,
            'usuario'        => $params->getAccessData()->getUsuario(),
            'senha'          => $params->getAccessData()->getSenha(),
        );`

**Comment by gutobenn** [comment]
Fiz assim como o @gustvao e também coloquei 'ISO-8859-1' aqui: https://github.com/stavarengo/php-sigep/blob/b955b6bd759bbf27a6a0c4a61c8ab15ba35ffb31/src/PhpSigep/Services/Real/FecharPreListaDePostagem.php#L85

(Uso uma versão um pouco mais antiga, em que não tinha ainda a configuração de encoding no Bootstrap)

**Comment by gutobenn** [comment]
Uma correção: eu pensava que minhas clientes havia migrado de uma agência para uma franquia., mas na verdade elas migraram de uma franqueada para outra.
Ou seja, em uma franquia o UTF-8 funcionava, e em outra apenas ISO-8859-1.

**Comment by mauroagr** [comment]
Ai lascou, por que ai depende do software da franquia, que não deve ser padrão.
