### ISSUE TITLE
Código administrativo não encontrado na rotina calcPrecoPrazo no ambiente de homologação

### ISSUE THREAD

**Issue by jdgrieco** [stavarengo/php-sigep#379]
Quando tento usar o webservice calcPrecoPrazo em ambiente de homologação dá uma exceção
`'PhpSigep\Model\Exception' with message 'There is no service with the code "0".' in /var/www/html/vendor/stavarengo/php-sigep/src/PhpSigep/Model/ServicoDePostagem.php on line 151`

Debugando a chamada percebi que o erro é por causa de um problema no código administrativo, o resultado retornado pelo webservice é 0 no `$r->CalcPrecoPrazoResult->Servicos->cServico->Codigo`  e "Erro inesperado. Descrição: Código administrativo não encontrado." no `$r->CalcPrecoPrazoResult->Servicos->cServico->MsgErro`

Estou usando:
```
$accessData = new AccessDataHomologacao();
$config = new Config();
$config->setEnv(Config::ENV_DEVELOPMENT);
$config->setAccessData($accessData);

PhpSigep\Bootstrap::start($config);
$phpSigep = new PhpSigep\Services\SoapClient\Real();
```

Gostaria de saber se está ocorrendo para mais alguém, suponho que seja problema do ambiente dos Correios visto que em ambiente de produção com credenciais reais não dá problema

**Comment by Rafael-luiz** [comment]
Estou com o mesmo problema

**Comment by ochetski** [comment]
Caso alguém encontre esse problema, provavelmente é referente a falta de código administrativo válido.
 Os dados de teste não servem para isso e na classe CalcPrecoPrazo o erro acaba sendo omitido por um cast.
