### ISSUE TITLE
Errona leitura da Etiquetas - imprimirEtiquetas2016.php

### ISSUE THREAD

**Issue by andrecrorazim** [stavarengo/php-sigep#380]
Pessoal,
Tudo bem?

Alguém já passou por esse problema na geração das etiquetas

“Erro na validação do arquivo. Quantidade de caracteres maior que a permitida ou preenchimento incorreto (numero. End. Destinatário)”.

Estou usando o imprimirEtiquetas2016.php, mas quando a leitura é feita na agencia do correio apresenta esse aviso!

Se alguém poder ajudar?

Obrigado.

**Comment by loja5combr** [comment]
Este erro geralmente ocorre quando o numero do endereço esta sendo enviado maior que o suportado na api do sigep, verifique esta detalhe e faça o tratamento do limite de caracteres para os campos em seu sistema.

**Comment by andrecrorazim** [comment]
Olá Loja5, muito obrigado pelo seu feedback!

Fiz algumas melhorias no tratamento dos dados, aparentemente resolveu, porem agora me apresenta este aviso :

"“A sigla da etiqueta não é valida para o serviço informado”."

Estou procurando na web para ver se encontro alguma informação do erro!
