### ISSUE TITLE
["errorMsg":protected]=> string(72) "Resposta do Correios: Não foi possível obter as etiquetas solicitadas.

### ISSUE THREAD

**Issue by lucasmfusco** [stavarengo/php-sigep#381]
Boa noite,

Já alterei uma série de parâmetros em meu Script, porém sempre é retornado o erro abaixo:

> object(PhpSigep\Services\Result)#19 (6) { ["isSoapFault":protected]=> bool(true) ["errorCode":protected]=> int(0) ["errorMsg":protected]=> string(72) "Resposta do Correios: Não foi possível obter as etiquetas solicitadas." ["result":protected]=> NULL ["soapFault":protected]=> NULL ["_failIfAtributeNotExiste":protected]=> bool(true) }

Estou utilizando o seguinte código:

```
require_once __DIR__ . '../../../sigep/src/PhpSigep/Bootstrap.php';

$usuario = trim('1234');
$senha = trim('1234');
$cnpjEmpresa = trim('1234');
$numcontrato = trim('1234');
$cartaopostagem = trim('1234');
$codigoadm = trim('1234');

$accessData = new \PhpSigep\Model\AccessData();
$accessData->setUsuario($usuario);
$accessData->setSenha($senha);
$accessData->setCnpjEmpresa($cnpjEmpresa);
$accessData->setCodAdministrativo($codigoadm);
$accessData->setNumeroContrato($numcontrato);
$accessData->setCartaoPostagem($cartaopostagem);
$accessData->setAnoContrato(null);
$accessData->setDiretoria(new \PhpSigep\Model\Diretoria(\PhpSigep\Model\Diretoria::DIRETORIA_DR_SAO_PAULO));

$config = new \PhpSigep\Config();
$config->setAccessData($accessData);
$config->setEnv(\PhpSigep\Config::ENV_PRODUCTION);
$config->setWsdlAtendeCliente('https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl');
$config->setCacheOptions(
    array(
        'storageOptions' => array(
            // Qualquer valor setado neste atributo será mesclado ao atributos das classes 
            // "\PhpSigep\Cache\Storage\Adapter\AdapterOptions" e "\PhpSigep\Cache\Storage\Adapter\FileSystemOptions".
            // Por tanto as chaves devem ser o nome de um dos atributos dessas classes.
            'enabled' => false,
            'ttl' => 10,// "time to live" de 10 segundos
            'cacheDir' => sys_get_temp_dir(), // Opcional. Quando não inforado é usado o valor retornado de "sys_get_temp_dir()"
        ),
    )
);

\PhpSigep\Bootstrap::start($config);

    // Solicita as etiquetas
     $etiqueta = new \PhpSigep\Model\Etiqueta();
    $dados_etiqueta = new \PhpSigep\Model\SolicitaEtiquetas();
    $dados_etiqueta->setAccessData($config->getAccessData());
    $dados_etiqueta->setQtdEtiquetas(1);
    $dados_etiqueta->setServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068);


    // Envia e recupera o número da etiqueta
    $real = new \PhpSigep\Services\SoapClient\Real();
   /* $result = $real->solicitaEtiquetas($dados_etiqueta);
    $result = $result->getResult();

    $etiqueta->setEtiquetaSemDv($result[0]->getEtiquetaSemDv());
    $sigep_codigo_postal = $etiqueta->getEtiquetaComDv(); */

 var_dump($real->solicitaEtiquetas($dados_etiqueta)); 
```

**Comment by mathleite** [comment]
Boa tarde amigo, estou querendo colaborar com este projeto e descobri algo interessante haha.
Existe um método chamado `findMultRequest()` da classe `SolicitaEtiquetas` e nela há algumas chamadas de métodos que não existem, conforme mostro neste print:
![image](https://user-images.githubusercontent.com/34130446/72537314-ae421580-385a-11ea-98a0-2ce53aaa740f.png)
Possivelmente, na minha opnião, esta (e não só isso, toda a arquitetura deste projeto é falha) é a causa do seu problema.
Espero ter ajudado!

**Comment by rodrigojob** [comment]
> Boa tarde amigo, estou querendo colaborar com este projeto e descobri algo interessante haha.
> Existe um método chamado `findMultRequest()` da classe `SolicitaEtiquetas` e nela há algumas chamadas de métodos que não existem, conforme mostro neste print:
> ![image](https://user-images.githubusercontent.com/34130446/72537314-ae421580-385a-11ea-98a0-2ce53aaa740f.png)
> Possivelmente, na minha opnião, esta (e não só isso, toda a arquitetura deste projeto é falha) é a causa do seu problema.
> Espero ter ajudado!

Realmente não ajudou.
Verifique se o seu arquivo Model/SolicitaEtiquetas.php está correto, pois ele possui parte da classe.

A mensagem pode ter 2 ou três origens:
1 - a falta de autorização de uso do webservices
1.1 - a falta de homologação do sistema 
2 - tentativa de emissão de uma etiqueta com o código de serviço inválido para o contrato.
Tente dar mais de 10 segundos
