### ISSUE TITLE
imprimirPlp.php erro para ler o retorno

### ISSUE THREAD

**Issue by guganakada** [stavarengo/php-sigep#383]
Olá!!

Por favor, alguém pode me ajudar, referente ao arquivo imprimirPlp.php. Não estou sabendo ler o retorno.

```
<?php
require_once __DIR__ . '/bootstrap-exemplos.php';
$params = include __DIR__ . '/helper-criar-pre-lista-a4.php';

$pdf  = new \PhpSigep\Pdf\ListaDePostagem($params, time());
$pdf->render('I');
```

Estou enviando um post para o arquivo e não estou sabendo ler o retorno. Como faço para ler esse pdf?

```
$.post(
	'../assets/php-sigep-master/lista_plp/imprimirPlp.php',
	{encomendas: select},
	function(result){
		var $modal = $('#imprime_plp_pdf');
		var $btnSelect = $modal.find('#envia_Plp');
		$btnSelect.data('dados', select);
		$modal.modal('show');
		$('#modal-body').html(result);
})
```

**Comment by andersonls** [comment]
O método render('I') é para mostrar o PDF direto no navegador. render('S') retorna o PDF como string e render('F', 'nomeArquivo.pdf') salva o PDF em arquivo.

Veja qual funciona melhor pra você e altere o imprimirPlp de acordo.

**Comment by guganakada** [comment]
Deu certo... Muito obrigado!!
