### ISSUE TITLE
Gera Plp com serviço de postagem vazio

### ISSUE THREAD

**Issue by guganakada** [stavarengo/php-sigep#386]
Olá

Estou gerando e fechando a Plp pelo arquivo imprimirPlp.php e o helper-criar-pre-lista-a4.php, esta gerando o arquivo pdf e enviando para o correio normalmente, porem na agência informa que o código do serviço esta vazio.

Desde já agradeço.

**Comment by guganakada** [comment]
Acredito que seja nessa linha, não estou sabendo, como alterar o Serviço. 

$encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068));

**Comment by andersonls** [comment]
Você está fazendo a chamada para o método fechaPlpVariosServicos? Se não estiver, este é o motivo.

**Comment by guganakada** [comment]
Sim, estou e é exatamente no fechaPlpVariosServicos.php junto com helper-criar-pre-lista.php que acho que não estou sabendo incluir o serviço de postagem.

Acredito que seja nesta linha:
$encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41068));

não estou sabendo como alterar o serviço de postagem (SERVICE_PAC_41068).

**Comment by andersonls** [comment]
Você editou a linha 33 do herlper-criar-pre-lista.php: `    $etiqueta->setEtiquetaSemDv('PD73958096BR');`?

Se não editou, o método fechaPlpVariosServicos deveria estar retornando erro! Olha o exemplo solicitarEtiquetas.php, basicamente você precisa passar o retorno desse exemplo no método setEtiquetaSemDv.

Sobre o serviço de postagem, vai depender do contrato que você está usando, todos são constantes da classe \PhpSigep\Model\ServicoDePostagem. Você pode ver com a própria agência quais os serviços de postagem que são permitidos para o teu contrato.

**Comment by guganakada** [comment]
Blz, acho que entendi... pode fechar.
Muito obrigado!
