### ISSUE TITLE
Problema na execução dos métodos em ambiente de produção

### ISSUE THREAD

**Issue by islimn** [stavarengo/php-sigep#388]
Bom dia a todos!

Este problema que estou enfrentando já deve ter sido reportado aqui alguma vez, mas vamos lá.

Estou executando os métodos da maneira como indica nos exemplos em ambiente de produção com os dados que recebi dos correios, mas sempre acaba excedendo o tempo máximo de execução e não retorna os dados necessários, apenas a mensagem `Maximum execution time of 60 seconds exceeded` (isto apenas em ambiente de produção, em ambiente de homologação está funcionando sem problemas). Isso está acontecendo nos exemplos de:

- `verificaDisponibilidadeServico()`
- `buscaCliente()`
- `consultaCep()`
- `getStatusCartaoPostagem()`

Já os métodos restantes (principalmente o de `solicitarEtiquetas()`) não funcionam tanto em ambiente de produção quanto de homologação. Segui as instruções como indica nos exemplos e na documentação oficial do web service, mas não obtive sucesso.

Alguém que tenha enfrentado algum desses problemas e conseguiu solucionar, pode me ajudar?

**Comment by rodrigojob** [comment]
Você percebeu se isso ocorre seguidamente, ou se esperar uns 3 minutos, depois da primeira tentativa, ele executa corretamente?
