### ISSUE TITLE
Problemas com a integração

### ISSUE THREAD

**Issue by rafaelquality** [stavarengo/php-sigep#39]
Boa tarde pessoal,

Precisei fazer uma integração com o SIGEP para um cliente, e optei por esta plataforma, porém, o correios está apontando vários erros no layout das etiquetas, e da PLP...
Corrigi alguns problemas no layout das etiquetas, porém estou com alguns outros...

O que está acontecendo é que o sistema do cliente é muito antigo, e não possui nem dimensões dos produtos, e me tomaria muito tempo implementando o mesmo.

Gostaria de saber se consigo enviar as informações dos pedidos para o SIGEP do cliente, para que lá ele imprima as etiquetas e as PLPs, pois hoje é enviado direto para o SARA (no qual aponta erro, dizendo que não é informado o tamanho nem o tipo do objeto).

Att,
Rafael

**Comment by CassianoCarraro** [comment]
Olá @rafaelquality ,
Você pode informar as dimensões básicas, como no [schema XSD da PLP](https://github.com/stavarengo/php-sigep/blob/master/src/PhpSigep/Support/xsd/plp_schema.xsd), no XML de envio para o SARA, sendo que quando o cliente realizar a postagem os Correios realizam a pesagem e o dimensionamento dos objetos. Quanto ao tipo de objeto, acredito que você possa identificar se o serviço utilizado é referente a carta ou referente a outros serviços postais, assim é possível selecionar o tipo de objeto, se é envelope ou pacote/caixa.

**Comment by rafaelquality** [comment]
@CassianoCarraro ,
Acabei realizando um cadastro para as dimensões, visto que o cliente possui poucos produtos.

Mesmo assim, obrigado!
