### ISSUE TITLE
Falha no tratamento de dados em geraDigitoVerificadorEtiquetas()

### ISSUE THREAD

**Issue by renesul** [stavarengo/php-sigep#390]
src/PhpSigep/Services/Real/GeraDigitoVerificadorEtiquetas.php

Na linha 38 há no if a condição "&& $soapReturn->return" que falha quando return é 0.

        $result = new Result();
        try {
            $soapReturn = SoapClientFactory::getSoapClient()->geraDigitoVerificadorEtiquetas($soapArgs);
            if ($soapReturn && is_object($soapReturn) && $soapReturn->return) {
                if (!is_array($soapReturn->return)) {
                    $soapReturn->return = (array)$soapReturn->return;
                }

**Comment by NewtonMan** [comment]
Olá @renesul pode fazer a atualização do projeto para a versão atual e verificar a correção implementada e feche este Issue por favor

**Comment by renesul** [comment]
Feito
