### ISSUE TITLE
Geração de Etiquetas

### ISSUE THREAD

**Issue by andrecrorazim** [stavarengo/php-sigep#391]
Pessoal,
Boa tarde!

Alguém já passou por isso?

A AGR (agencia) dos correios em que enviamos os produtos, nos informa que as etiquetas ao serem lidas pelo sistema dos correios apresenta a seguinte mensagem de erro!

**“Erro na validação do arquivo quantidade de caracteres maior que a permitida ou preenchimento incorreto (complemento. Numero. End destinatário)”.**

Eu já olhei o manual, adaptei os campos para o padrão solicitado na documentação, mesmo assim o problema continua a acontecer.

Será que pode me dar uma ajuda?

Obrigado Galera.

**Comment by andersonls** [comment]
Verifique o tamanho dos campos complemento, Numero e endereço, se estão obedecendo o tamanho máximo permitido pelo Correio. Outra sugestão é remover acentuação e caracteres especiais.

**Comment by andrecrorazim** [comment]
@andersonls obrigado pelo retorno, quanto aos tamanhos eu já verifiquei e esta certinho com o manual do SIGEP Web, não tinha me atentado sobre os caracteres especiais, vou dar uma olhada nisso também! Obrigado!
