### ISSUE TITLE
Peso dos objetos na PLP e Postagem

### ISSUE THREAD

**Issue by lukasdev** [stavarengo/php-sigep#394]
Boa noite. Me deparei com um problema:
Consigo criar tudo como esperado utilizando o seu pacote php-sigep.
Porém informo um peso para a plp e esta sendo possivel efetuar a postagem com peso a mais doq o informado.

Existe algum modo de evitar que isso aconteça, talvez com alguma configuração na propria plp que informe a pessoa do caixa para não deixar postar nada além do peso informado?

**Comment by andersonls** [comment]
@lukasdev não existe nada nesse sentido na API do correio, a sua aplicação que deve fazer o controle.
