### ISSUE TITLE
Novos códigos de serviço

### ISSUE THREAD

**Issue by JoaoVictorSarzi** [stavarengo/php-sigep#397]
Como posso adicionar novos serviços, tipo envio normal, impresso normal, módico para livros?

**Comment by NewtonMan** [comment]
É preciso saber o código e o id do serviço, se você usar o buscaCliente e debugar o objeto de resposta vai poder observar que os serviços liberados na conta SIGEP do cliente serão listados, caso tenha dificuldade, copie e cole o debug neste issue (não esqueça de nullar dados privados e as chancelas), com os dados que mencionei você pode implementar igualmente eu mesmo fiz no pull request #399
