### ISSUE TITLE
Erro de Tempo de Execução

### ISSUE THREAD

**Issue by guilhermeassuncao** [stavarengo/php-sigep#403]
Alguem ja passou por esse problema Fatal error: Maximum execution time of 120 seconds exceeded in C:\Xampp\htdocs\sigep\vendor\stavarengo\php-sigep\src\PhpSigep\Services\Real\SoapClientFactory.php?. Ao executar esse trecho de código $result = $phpSigep->calcPrecoPrazo($params);.

**Comment by andersonls** [comment]
O Webservice de cálculo de frete é bem instável, provavelmente ele só está fora do ar.
