### ISSUE TITLE
Solicitar Postagem Reversa

### ISSUE THREAD

**Issue by FabioS82** [stavarengo/php-sigep#406]
Olá, boa tarde, estava tentando aqui configurar o código, mas ele nunca vai em modo de produção, já tenho conta no idCorreios, configurei lá no ficheiro de Exemplo o Contrato e o Codigo_Servico, mas ele sempre retorna um código de postagem que não existe, reparei também que no novo manual pede Cod_Administrativo e cartao, onde eu posso configurar isso ou o que falta configurar para o sistema ficar funcional?

**Comment by rodrigojob** [comment]
Olá Fábio, isso é CodAdminitrativo e cartaoPostagem são configurados no AccessData, 
Eu tinha esta função inteiramente desenvolvida, mas o meu o PhpSigep não estava rodando direito, então eu reinstalei. Nem percebi que não estava atualizando.
Como já tinha esta funcionalidade no script eu não mexi ainda, mas estou vendo que não deve estar completa.
Os dados de Destinatário, Remetente e Objeto são diferentes da Remessa normal.
