### ISSUE TITLE
Erro após último commit

### ISSUE THREAD

**Issue by luizgdi** [stavarengo/php-sigep#419]
Após a atualização da sdk pra última versão (commit "Caractere illegal, não imprime informações na etiqueta", #94069d7ef41c57242379e4783ce9613f7e1713ed) não consigo mais gerar etiquetas e não retorna nenhum erro, a aplicação apenas morre. Após muito debug, acabei chegando a esse erro: "Recoverable fatal error: Object of class PhpSigep\Pdf\CartaoDePostagem2018 could not be converted to string in ../vendor/stavarengo/php-sigep/src/PhpSigep/Pdf/CartaoDePostagem2018.php on line 678", onde linha 678 = "$$this->multiLines($w, utf8_decode($address1), 'L');", então vim aos ultimos commits, abri esse mais recente e alterei manualmente pra o que era anteriormente, após isso a geração de etiquetas voltou a funcionar normalmente, peço que revisem pois acho que tem algo de errado nesse commit... Ou se puderem dar uma luz se o problema for aqui...

**Comment by stavarengo** [comment]
@Suporte-MKT

**Comment by NewtonMan** [comment]
Estou respondendo com um commit com as devidas correções e instruções @Suporte-MKT se tiver dúvidas e os problemas que havia reportado voltarem a aparecer por favor fale comigo.

**Comment by luizgdi** [comment]
@NewtonMan Muito obrigado! Verifiquei a PR e é exatamente o que fiz aqui manualmente pra voltar a funcionar (exceto a alteração no GeraDigitoVerificadorEtiquetas.php, nesse não toquei), então deve corrigir assim que aceitarem, enfim, grato!

**Comment by Suporte-MKT** [comment]
Obrigado @NewtonMan pela correção e @luizgdi por reportar.

**Comment by luizgdi** [comment]
Não conseguiram aceitar o PR ainda pelo jeito...

**Comment by stavarengo** [comment]
Oi pessoal. O PR https://github.com/stavarengo/php-sigep/pull/420 ainda está conflitando com a master por isso não consigo mesclar.
Se alguém conseguir resolver os conflitos eu posso mesclar as alterações.

**Comment by NewtonMan** [comment]
Olá @luizgdi pode fazer a atualização do projeto para a versão atual e verificar a correção implementada e feche este Issue por favor
