### ISSUE TITLE
Problema com acesso a ambiente de homologação de logística reversa

### ISSUE THREAD

**Issue by KokeroO** [stavarengo/php-sigep#423]
A um tempo atrás comecei a implementar na minha aplicação a rotina de logística reversa e dei uma pausa, retornando atualizei a biblioteca e a autenticação do ambiente de homologação parou de funcionar retornando a seguinte msg:

`SoapClient::SoapClient(https://apphom.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized`

Somente atualizei a biblioteca, testando pelo SoapUI o acesso ao link e solicitado o usuário (empresacws) e senha(123456) antes de consumir o webservice e aparentemente está validação não está ocorrendo.

models/AcessDataHomologcaoReversa.php:

`    
public function __construct()
``
    {
        parent::__construct(
            array(
                'usuario' => 'empresacws',
                'senha' => '123456',
                'codAdministrativo' => '17000190',
                'numeroContrato' => '9992157880',
                'cartaoPostagem' => '0067599079',
                'cnpjEmpresa' => '34028316000103', // Obtido no método 'buscaCliente'.
                'anoContrato' => null, // Não consta no manual.
                'diretoria' => new Diretoria(Diretoria::DIRETORIA_DR_BRASILIA), // Obtido no método 'buscaCliente'.
            )
        );
    }
`

**Comment by samirortiz** [comment]
Estranho, pelo erro parece problema de usuário e senha mesmo... tenho uma
integração aqui, acabei de testar essas mesmas configurações que tu ta
usando e tá funcionando...

Em qua, 23 de set de 2020 às 00:42, KokeroO <notifications@github.com>
escreveu:

**Comment by inegrao** [comment]
Comigo eu tive que incluir mais duas keys. **idCorreiosusuario** e **idCorreinhosSenha**. Então o array ficou assim:
array(
                'usuario' => 'SEU_USUARIO',
                'senha' => 'SUA_SENHA',
		'idCorreiosUsuario' =>'SEU_USUARIO',
		'idCorreiosSenha' => 'SUA_SENHA',
                'codAdministrativo' => 'SEU_COD_ADM',
                'numeroContrato' => 'SEU_NUM_CONTRATO',
                'cartaoPostagem' => 'SEU_NUM_CARTAO',
                'cnpjEmpresa' => 'CNPJ_SUA_EMPRESA', // Obtido no método 'buscaCliente'.
                'anoContrato' => null, // Não consta no manual.
                'diretoria' => new Diretoria(Diretoria::DIRETORIA_DR_SAO_PAULO), // Obtido no método 'buscaCliente'.
            )

Sobre a DIRETORIA, procurar no seu contrato qual que é.

**Comment by samirortiz** [comment]
Eu tb tive que botar esses 2 parâmetros, mas só pra produção. Homologação
não precisa.

**Comment by KokeroO** [comment]
> Comigo eu tive que incluir mais duas keys. **idCorreiosusuario** e **idCorreinhosSenha**. Então o array ficou assim:
> array(
> 'usuario' => 'SEU_USUARIO',
> 'senha' => 'SUA_SENHA',
> 'idCorreiosUsuario' =>'SEU_USUARIO',
> 'idCorreiosSenha' => 'SUA_SENHA',
> 'codAdministrativo' => 'SEU_COD_ADM',
> 'numeroContrato' => 'SEU_NUM_CONTRATO',
> 'cartaoPostagem' => 'SEU_NUM_CARTAO',
> 'cnpjEmpresa' => 'CNPJ_SUA_EMPRESA', // Obtido no método 'buscaCliente'.
> 'anoContrato' => null, // Não consta no manual.
> 'diretoria' => new Diretoria(Diretoria::DIRETORIA_DR_SAO_PAULO), // Obtido no método 'buscaCliente'.
> )
> 
> Sobre a DIRETORIA, procurar no seu contrato qual que é.

Resolveu meu problema na homologação. Agora está dando certinho. Obrigado.
