### ISSUE TITLE
Erro ao fechar PLP - java.lang.nullPointerException

### ISSUE THREAD

**Issue by samirortiz** [stavarengo/php-sigep#425]
Pessoal, todas as funcionalidades estão ok na minha intregração, exceto o fechamento da PLP, que me retorna  java.lang.nullPointerException, ou seja, esse erro vem do lado dos Correios. Todos os parâmetros estão bem configurados mas não há jeito aqui...

Alguém está conseguindo fechar??

**Comment by mauroagr** [comment]
Conseguiu resolver?
- Faz um teste com um endereço, nomes etc, sem uso de caracteres como Çé...etc....para eliminar erros de utf8;

**Comment by mauroagr** [comment]
Estou tendo problema com valor declarado, acima de 0.
ele dá erro
