### ISSUE TITLE
Erro Logistica reversa: solicitarPostagemReversa error: SoapFault Object (     [message:protected] => Not Found

### ISSUE THREAD

**Issue by caresolutions** [stavarengo/php-sigep#436]
Durante o final de semana começou a aparecer o erro na logistica reversa SoapFault Object (     [message:protected] => Not Found
no  endereço https://cws.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl, alguém esta passando por isso?

**Comment by mathmarques** [comment]
Passando pelo mesmo problema... ainda não encontrei a solução.

**Comment by caresolutions** [comment]
sim, em contato com algumas fontes, estão com problema la

**Comment by samirortiz** [comment]
Bom dia galera.
Segue o problema aqui, alguém já sabe oq é ou já resolveu de alguma outra
forma?

**Comment by mathmarques** [comment]
Entrei em contato com a TI dos correios mas não obtive nenhuma resposta.

Porém, voltou a funcionar aqui hoje.
