### ISSUE TITLE
Codigo do VALOR_DECLARADO

### ISSUE THREAD

**Issue by renan-arrieiro** [stavarengo/php-sigep#439]
Entramos em contato com o Correio parece que o código do VALOR_DECLARADO agora é 025 ao invés de 019.
agradeço.

**Comment by rodrigojob** [comment]
> Entramos em contato com o Correio parece que o código do VALOR_DECLARADO agora é 025 ao invés de 019.
> agradeço.

Vai depender do serviço, de qual modalidade você está enviando. É um inferno.
