### ISSUE TITLE
Armazenar PDFs gerados no servidor

### ISSUE THREAD

**Issue by blumtech** [stavarengo/php-sigep#44]
Pessoal,
Estou com uma PR pronta para flexibilizar a forma como os PDFs são gerados. Em vez de sempre mostrar o PDF no navegador, se passarmos um parâmetro com o nome do arquivo, o PDF é salvo no servidor.
Não quebra nada (quem não quiser salvar é só não passar nenhum parâmetro para o método render).

Minha dúvida é em relação ao stream_wrapper_register

Para poder gerar 2 PDFs na mesma requisição *parece* que tem que chamar stream_wrapper_unregister antes de iniciar o segundo PDF.

Isso pode ser feito logo depois de chamar o método render, mas acho que não é "competência" desse trecho de código chamar o unregister.

Já que o register é chamado no construct da classe ImprovedFPDF , eu acho que o ideal seria chamar o unregister ali.

A minha ideia era sobrescrever o método Output do FPDF da sequinte forma:
```
  function Output($name='', $dest='')
    {
        $result = parent::Output($name,$dest);
        stream_wrapper_unregister("var");//isso permite que seja gerado dois PDFs na mesma requisição, útil se você quiser gerar a PLP e as etiquetas de uma só vez.
        return $result;
    }
```

O problema disso é que o método output não está definido no parent do ImprovedFPDF mas sim no "avô" dele.
Para isso funcionar eu teria que criar uma outra pull request no PhpSigepFPDF , o que implicaria que isso só funcionaria para quem atualizasse os dois pacotes. 

O que é melhor:
- chamar stream_wrapper_unregister fora da classe ImprovedFPDF 
- criar uma pull request em cada pacote

Só quero deixar claro que, independente da opção, nada vai mudar para quem não quer usar essa funcionalidade.

abraços!

**Comment by stavarengo** [comment]
fixed: https://github.com/stavarengo/php-sigep/pull/46
