### ISSUE TITLE
Function ("solicitarPostagemReversa") is not a valid method for this service

### ISSUE THREAD

**Issue by seapvnk** [stavarengo/php-sigep#440]
# Erro ao solicitar postagem reversa
**short**: Não existe documentação disponível para tratar esse tipo de erro

Ao enviar o SOAP com os dados preenchidos conforme os exemplos sugerem, utilizando os mesmos dados usados ao fazer esse tipo de solicitação manualmente, recebo do SOAP esse tipo de mensagem. É um erro do php-sigep ou é problema do correios?

**Comment by rodrigojob** [comment]
O sistema funciona, pois eu o uso. Pode ser que você não está incluindo os dados de usuário
