### ISSUE TITLE
Timeout e lentidão no calculo de prazos

### ISSUE THREAD

**Issue by prhost** [stavarengo/php-sigep#444]
Olá pessoal,

Estou tendo um problema recentemente que é timeout nos calculos, está dando mais de 1 minuto no processamento e meu servidor ta matando o processo sem saber o que retorna. Alguem mais ta com esse problema?

Minha dúvida é saber se o problema ta no Correios ou no meu servidor, por ser algo recente.

**Comment by jdgrieco** [comment]
@prhost, eu tive problemas com isso, a primeira consulta demora muito tempo e acaba dando timeout, depois fica "normal".

Acredito que possa ser algo relacionado a algum tipo de cache da autenticação no ambiente dos Correios

O que fiz para contorna foi criar uma rotina que roda no cron/agendador de tarefas consultando os dados do contrato, ação que é suficente para dar um "warm-up" no ambietne.

Algo do tipo: 
```
require_once __DIR__ . '/bootstrap_sigep.php';
$result = $phpSigep->buscaCliente($accessData);

**Comment by andersonls** [comment]
Duplicate of #158
