### ISSUE TITLE
Consultar PI

### ISSUE THREAD

**Issue by wagnerjaccoud** [stavarengo/php-sigep#446]
Estou tentando consultar a PI, mas na documentação, o método para consulta pede um campo chamado CANAL, mesmo preenchendo com qualquer valor tenho retorno de tipo de consulta inválido. Chegou a testar efetuar consultas?

**Comment by wagnerjaccoud** [comment]
@gustavovendramini você já chegou a ver algo do tipo?

**Comment by rodrigojob** [comment]
"canal" => "FALECONOSCO"

**Comment by gustavovendramini** [comment]
O que é PI? PLP?
Estou por fora.

**Comment by rodrigojob** [comment]
PI é Pedido de Informação, reclamação, Fale Conosco
