### ISSUE TITLE
Autorizacao de Postagem

### ISSUE THREAD

**Issue by gustvao** [stavarengo/php-sigep#45]
Quem ja utiliza essa lib em producao ja deve ter percebido que o Pedido nao aparece no sistema de correios pois nao tem a parte de Autorizacao de Postagem.

@stavarengo vc pretende colocar esse modulo na lib? Seria muito util.

Acredito que deva ser relativamente simples, uma vez que ja existe o model imprimirPlp com todas as infos necessarias para gerar a Autorizacao de Postagem dentro dos correios..

**Comment by gustvao** [comment]
Acabei de olhar o README e voce menciona o seguinte:

- Gerar e enviar o XML da pre-lista de postagem (PLP) para o Correios.
- Gerar novos números de etiquetas de postagem.

'E exatamente isso que eu preciso fazer.. Nao achei esses exemplos no codigo.. Aonde estao?

**Comment by stavarengo** [comment]
@gustvao esse exemplo faz isso
https://github.com/stavarengo/php-sigep/blob/master/exemplos/fechaPlpVariosServicos.php

**Comment by gustvao** [comment]
obrigado @stavarengo  pode fechar
