### ISSUE TITLE
Duvida - Documentação

### ISSUE THREAD

**Issue by IgorPC** [stavarengo/php-sigep#450]
Olá pessoal, muito bacana o projeto de vocês.

Estou precisando integrar o SIGEP em um sistema de um cliente, mas não sou muito familiarizado com a arquitetura SOAP, por isso estou estudando a possibilidade de integrar esse pacote ao projeto, mas não encontrei uma documentação de como instanciar, ou os métodos para executar as funções necessárias.

Podem me auxiliar em relação a isso?

**Comment by gustavovendramini** [comment]
@IgorPC tem uma pasta no projeto chamada exemplos, vai explorando  ela e debugando https://github.com/stavarengo/php-sigep/tree/master/exemplos

Mas no geral vc precisa disso no seu composer.json

`
    "require": {
         ...
        "stavarengo/php-sigep": "dev-master",
        "stavarengo/php-sigep-fpdf": "dev-master",
        ...
`

Sempre de chamar algum serviço vc deve inicializar a lib

`Bootstrap::start($config);`

E no geral vc calcula preco, gera etiqueta, e fecha plp e pronto. Fuça nos exemplos ae.
