### ISSUE TITLE
Envio modico

### ISSUE THREAD

**Issue by ViniciosOliveira** [stavarengo/php-sigep#452]
é possivel criar etiquetas e PLP para envio modico? 
Parabéns desde já pelo projeto

**Comment by gustavovendramini** [comment]
Eu perguntei isso no [fale conosco](https://apps2.correios.com.br/faleconosco/app/cadastro/suporte/index.php) de cliente com contrato e eles disseram que na integração é somente PAC, SEDEX e carta.
Mas já vi relatos de gente com integração que tinha impresso módico, então se souber de algo e funcionar avise-nos aqui também kkk

**Comment by rodrigojob** [comment]
Use o MiniEnvios, o PacMini. Este dá para usar.
Envio módico é para despacho de objetos não mercantis, ou o que não é mercadoria, não tem seguro e é proibido enviar mercadorias.
