### ISSUE TITLE
Gerar varios Etiquetas(PDF)

### ISSUE THREAD

**Issue by pvpzaum** [stavarengo/php-sigep#47]
Olá pessoal, estou tentando gerar varias etiquetas de uma vez, porém consigo gerar varios códigos, mas na hora de imprimir varios PDF's ele só retorna um. Estou alterando a função "$params->setQtdEtiquetas(1)", gostaria de saber se estou alterando no local errado ou esquecendo de alguma coisa.

Obrigado, pela ajuda se possível.
Att,

**Comment by stavarengo** [comment]
@pvpzaum, as entiquetas são geradas com base nos dados
da \PhpSigep\Model\PreListaDePostagem.
Para imprimir varias etiquetas vc pode fazer um loop para imprimir todas
que vc precisa.
​

**Comment by etevaofelipe** [comment]
não sei se fiz alguma coisa errada, mas quando tento gerar mais de uma etiqueta, acaba saindo uma por página, diferente do http://stavarengo.github.io/php-sigep/, alguma sugestão?

**Comment by pvpzaum** [comment]
@estevaofelipe , fiz o loop, mas para mim não funcionou, como você fez?

Poderia postar para mim o seu exemplo?

Obrigado pela ajuda.

**Comment by estevaofelipe** [comment]
crie um array vazio no helper-criar-pre-lista.php, faça um foreach nos seus pedidos e no final de cada looping incremente o array:
$encomendas = array();
foreach ($pedidos as $value) {
    $encomenda = new \PhpSigep\Model\ObjetoPostal();
    $encomenda->setServicosAdicionais(array($servicoAdicional));
    $encomenda->setDestinatario($value->destinatario);
    $encomenda->setDestino($value->destino);
    $encomenda->setDimensao($value->dimensao);
    $encomenda->setEtiqueta($value->etiqueta);
    $encomenda->setPeso($value->peso);
    $encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_CARTA_REGISTRADA));
    $encomendas[] = $encomenda;
}

troque no final $plp->setEncomendas(array($encomenda)); pelo array que você incrementou, ficando assim: $plp->setEncomendas($encomendas);

**Comment by estevaofelipe** [comment]
@pvpzaum , você consegue gerar em formato a4?

Att.

**Comment by pvpzaum** [comment]
@estevaofelipe consigo sim, para você não esta gerando no formato A4?

**Comment by pvpzaum** [comment]
@estevaofelipe obrigado pela ajuda, tinha esquecido do array la em baixo na $plp, por isso não estava funcionando, agora estou tentando chegar ao resultado que você também procura, imprimir 4 em uma mesma página.

**Comment by stavarengo** [comment]
Posso fechar esse pessoal?

**Comment by estevaofelipe** [comment]
@stavarengo , se puder me ajudar com a questão da impressão de várias etiquetas em papel a4 agradeço. pois hoje se gerar mais de uma, acabam sendo geradas duas páginas no pdf.

**Comment by gustvao** [comment]
@estevaofelipe a ideia é voce configurar a impressão diretamente na sua impressora,  na minha opiniao o jeito que existe hoje é o ideal, 1 etiqueta por folha e se você quiser imprimir mais de uma etiqueta por folha é só configurar pra imprimir X páginas por folha...

**Comment by estevaofelipe** [comment]
@gustvao , a minha ideia seria já gerar o pdf com várias etiquetas já no formato a4 como no site do projeto http://stavarengo.github.io/php-sigep/. De qualquer forma isso seria apenas configuração do fpdf, vou desenvolver um módulo pra Prestashop e se ficar bom disponibilizo.

**Comment by gustvao** [comment]
@estevaofelipe o site do projeto está com o código antigo.. se voce der uma olhada no history de código vc acha a versão que tinha 4 etiquetas por página.. isso foi resultado de um PR há alguns meses

**Comment by pvpzaum** [comment]
@stavarengo pode fechar, o problema foi resolvido.

Att.

**Comment by gustvao** [comment]
@pvpzaum como vc fez?

**Comment by pvpzaum** [comment]
@gustvao , para gerar varias etiquetas? Se for isso, criei um array exatamente como o @estevaofelipe disse, mas reparei que tenho um problema, o PLP como é gerado em outro lugar, não gera outro número para os restantes das etiquetas. Ficando o mesmo para todas.

**Comment by estevaofelipe** [comment]
@gustvao, o número do plp é a função time(), resolvi fazendo o seguinte, quando gero as etiquetas gravo no banco o json com todas elas e em outra tabela gravo apenas o plp, pra gerar o plp, faço a consulta no banco pelas etiquetas, não sei se fui claro.

**Comment by pvpzaum** [comment]
@estevaofelipe fiquei um pouco confuso, você gera a etiqueta primeiro para depois gerar um plp para cada uma?

**Comment by gustvao** [comment]
@pvpzaum a ideia é vc gerar as etiquetas antes e depois associar um plp a varias etiquetas.. vc vai precisar de um bd pra guardar depois a relação de etiquetas e plps

**Comment by pvpzaum** [comment]
@gustvao , @estevaofelipe entendi, o que eu gostaria de saber é se quando eu gero varias etiquetas, necessáriamente eles devem possuir o mesmo plp por que foram geradas ao mesmo tempo?

Att,

**Comment by estevaofelipe** [comment]
@pvpzaum, pelo que vi no sistema do sigep, no lugar da plp que vai na etiqueta tem a NF, o número fica apenas na plp, então imagino que isso seja indiferente, servirá apenas para controle.

**Comment by gustvao** [comment]
@pvpzaum vc pode ter 1 plp por etiqueta ou varias etiquetas por plp.. vc nao precisa gerar a etiqueta junto com o plp, no entando, uma vez que vc associar as etiquetas ao plp e mandar pro servidor dos correios, nao tem mais volta, nao da pra editar...

**Comment by estevaofelipe** [comment]
@pvpzaum, apenas pra confirmar sua pergunta, o número da plp deve ser o mesmo que consta na etiqueta sim, pois a leitura é feita pela plp e não pela etiqueta.

**Comment by guimunarolo** [comment]
Bom dia, seguindo a lógica do Correios, se eu gero a etiqueta eu preciso necessariamente gerar a plp também ou posso gerar só a etiqueta?

**Comment by estevaofelipe** [comment]
@guimunarolo, a PLP também deve ser gerada, pois os correios usam ela pra cadastrar  os códigos de rastreio no sistema.
