### ISSUE TITLE
Vários Itens (Cubagem)

### ISSUE THREAD

**Issue by meciasbueno** [stavarengo/php-sigep#470]
Como eu passaria as medidas para calcular o preço/prazo quando eu tenho vários itens (produtos diferentes) no carrinho de compras?

**Comment by webesistemas** [comment]
creio que a lib nao faça isso, vc deveria calcular na sua loja e enviar para lib as dimensões finais de sua 'caixa'

**Comment by rodrigojob** [comment]
Também entendo que a cubagem deve partir do seu sistema, pois só você sabe qual é a caixa/embalagem que vai usar e como irá acondicionar os produtos.
