### ISSUE TITLE
Mini Envios Valor Declarado (065)

### ISSUE THREAD

**Issue by daviddgm** [stavarengo/php-sigep#473]
Olá... Não consigo gerar PLP com o SERVICE_VALOR_DECLARADO_MINI_ENVIOS (065), quando incluo ele não gera a tag do valor no XML, apenas do serviço... Com PAC (064) e Sedex (019) funciona normalmente... inclusive para o Mini Envios consegui adicionar o serviço (019), mas obviamente deu erro na agência. Alguém tem alguma dica? Seria limitação do contrato?

**Comment by gustavovendramini** [comment]
@daviddgm Eu uso Mini Envios com valor declarado aqui, funciona normal.

Tente verificar esses itens:
- Se o Mini Envios está no seu contrato (ele é exclusivo para clientes com contrato), método buscaCliente da lib retorna isso.
- Verifique se o valor declarado máximo é 100 reias (para Mini Envio) [Quanto Custa? > Valor Declarado](https://www.correios.com.br/enviar/servicos-adicionais/servicos-adicionais)
- Verifique se o valor mínimo declarado é 21 reais qualquer serviço.

Se ainda assim não estiver indo tem que debugar a lib, qualquer coisa posta o retorno que vc está recebendo.

**Comment by daviddgm** [comment]
Olá! Obrigado pelas dicas que me ajudaram a char o problema, minha versão tem algumas customizações e não é a versão master, o problema estava writeServicoAdicional() que só escrevia quando fosse PAC ou Sedex.

**Comment by lucaspaulino** [comment]
> @daviddgm Eu uso Mini Envios com valor declarado aqui, funciona normal.
> 
> Tente verificar esses itens:
> 
> * Se o Mini Envios está no seu contrato (ele é exclusivo para clientes com contrato), método buscaCliente da lib retorna isso.
> * Verifique se o valor declarado máximo é 100 reias (para Mini Envio) [Quanto Custa? > Valor Declarado](https://www.correios.com.br/enviar/servicos-adicionais/servicos-adicionais)
> * Verifique se o valor mínimo declarado é 21 reais qualquer serviço.
> * Verifique qual código de serviço você está usando, hoje temos cadastrado esses 3 na lib 04227, 04235, 04391 para Mini Envios, caso não tiver o que vc está usando mande um pull request adicionando.
> 
> Se ainda assim não estiver indo tem que debugar a lib, qualquer coisa posta o retorno que vc está recebendo.

Boa tarde @gustavovendramini , estou tentnado gerar etiquetas mini envio e estão com problemas. Talvez possa até ser validação dos dados, mas é só eu inserir um destes 3 códigos de serviços e mandar para a agencia?
Mandamos e deu o erro adicional 2, só que não sabemos o que é isso.

O serviço que colocamos foi o numero 04227 (159982), esse apareceu qunado listamos os serviços para o contrato.

**Comment by gustavovendramini** [comment]
@lucaspaulino Esses três códigos de MiniEnvios pelo que sei são respectivamente ao MiniEnvios em contrato Bronze, Prata e Ouro.

Nunca vi esse erro, eu tentaria primeiro confirmar com seu contato comercial dos correios se esse código (04227) está no seu contrato, pelo telefone eles devem saber informar também 3003-0888 no ramal SigepWeb.

Vou deixar como estou usando aqui, talvez ajude:

Pra gerar faço assim:

```

            $params = new SolicitaEtiquetas();
            $params->setQtdEtiquetas(1);
            $params->setServicoDePostagem($codigoservico);
            $params->setAccessData($accessData);

            $phpSigep = new \PhpSigep\Services\SoapClient\Real();

            $result = $phpSigep->solicitaEtiquetas($params);

            /** @var \PhpSigep\Model\Etiqueta $etiqueta */
            $etiqueta = $result->getResult()[0];
            $etiquetaCompleta = $etiqueta->getEtiquetaComDv();
 ```



Pra imprimir as etiquetas eu uso assim:


```
        $pdf = new CartaoDePostagem2018($plp, $idplpmaster, $logoFile);

        $pdf->render('I', "etiquetas-{$idplpmaster}.pdf");
```


Ah e um detalhe mais tarde quando você estiver montando sua PLP pra enviar lembra de passar o serviço de registro sempre;


```
        $srvAdcionalRegistro = new ServicoAdicional();
        $srvAdcionalRegistro->setCodigoServicoAdicional(ServicoAdicional::SERVICE_REGISTRO);

        $codigoValorDec = ServicoAdicional::SERVICE_VALOR_DECLARADO_MINI_ENVIOS;
        $srvAdicionalValorDec = new ServicoAdicional();       
        $srvAdicionalValorDec->setCodigoServicoAdicional($codigoValorDec);
        $srvAdicionalValorDec->setValorDeclarado($valorDeclarado);


        $encomenda = new ObjetoPostal();
        $encomenda->setServicosAdicionais([$srvAdcionalRegistro, $srvAdicionalValorDec]);
```
