### ISSUE TITLE
Problema em servidor compartilhado

### ISSUE THREAD

**Issue by estevaofelipe** [stavarengo/php-sigep#48]
Fatal error: Aborting! The New Relic imposed maximum PHP function nesting level of '500' has been reached. This limit is to prevent the PHP execution from catastrophically running out of C-stack frames. If you think this limit is too small, adjust the value of the setting newrelic.special.max_nesting_level in the newrelic.ini file, and restart php. Please file a ticket at https://support.newrelic.com if you need further assistance. in /home/warfare/www/modules/sigep/models/PhpSigep/Model/Etiqueta.php on line 65

**Comment by stavarengo** [comment]
Wow! Como isso aconteceu @estevaofelipe

Enviado de dispositivo móvel.
Rafael Stavarengo

**Comment by estevaofelipe** [comment]
@stavarengo, acontece quando tento solicitar etiquetas, a kinghost tem uma diretiva newrelic.special.max_nesting_level setada como 500, o problema é que não temos acesso as configurações do php pra desativar isso ou aumentar o valor. Por enquanto aconteceu apenas no método SolicitaEtiquetas.

**Comment by stavarengo** [comment]
@estevaofelipe me parece que isso está fora do nosso contexto. Vou fechar o bug, mas caso tenha mais alguma consideração pode reabrir.
