### ISSUE TITLE
Criação de AR (Aviso de Recebimento)

### ISSUE THREAD

**Issue by pvpzaum** [stavarengo/php-sigep#49]
Boa tarde pessoal,

nessa API existe a criação da AR? Por que minha cliente tem essa necessidade, se caso não existir estarei criando e irei subir para ajudar a comunidade.

Att,

**Comment by stavarengo** [comment]
Não lêmbro de ter implementado isso. Vou ver durante o final de semana e te
aviso. Se vc souber antes de mim me avise pf.

On Wednesday, April 20, 2016, pvpzaum <notifications@github.com> wrote:

> Boa tarde pessoal,
>
> nessa API existe a criação da AR? Por que minha cliente tem essa
> necessidade, se caso não existir estarei criando e irei subir para ajudar a
> comunidade.
>
> Att,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stavarengo/php-sigep/issues/49>
>


-- 
*Rafael Stavarengo*
reminds.co
Skype: rafael.stavarengo

**Comment by pvpzaum** [comment]
@stavarengo eu dei uma olhada e realmente, apenas vi que você apenas envia a informação para os correios, mas a "etiqueta" que é gerada não tem. Estou fazendo aqui, qualquer coisa eu subo.

**Comment by pvpzaum** [comment]
@stavarengo peço desculpas, pelos inúmeros "apenas" citados acima hehe...

**Comment by pvpzaum** [comment]
@stavarengo uma pergunta, não estou achando aonde no documento do pdf, você gera o QRCode, poderia me falar onde ele esta?

Att,

**Comment by rafaelsiqueira** [comment]
É gerado no CartaoDePostagem.php, linha 364.

*Rafael Siqueira*

**Comment by guimunarolo** [comment]
Boa tarde, alguém chegou a fazer o modulo de impressão do AR?

**Comment by stavarengo** [comment]
@guimunarolo, como vc resolveu isto? Chegou a criar a impressão do AR?

**Comment by carlosfilho88** [comment]
Eu fiz a implementação do AR com outra biblioteca, utilizo Zend 1.12 com essa lib pra solicitar etiquetas, mas não pra fazer as impressões.

Acho o projeto muito bacana, até comecei a fazer a integração do AR por aqui, mas não prossegui porque as classes estão um pouco acopladas e prefiro o mPDF ao fPDF. Em um futuro próximo, vou pegar o layout dos Correios e implementar com o Zend_Pdf, que é mais trabalhoso mas consideravelmente mais rápido.

No mais, parabéns pela ideia, pelas contribuições e pela atividade contínua da comunidade. Se alguém quiser ver o modelo, posso postar o código no gist, é só me marcar aqui na thread.

**Comment by stavarengo** [comment]
Oi @carlosfilho88 
Pq não juntamos força para fazer dessa lib algo melhor, ao invés de começar outro?

**Comment by carlosfilho88** [comment]
@stavarengo precisaríamos de um roadmap pra depois pensar em refatorar algumas classes. Atualmente não é possível acoplar outras fontes de impressão senão o fPDF. Meu problema atualmente é gerar algumas centenas de ARs convertendo de html pra pdf, além de custoso é insano...

Por isso a ideia de usar o Zend_Pdf ou algum similar que tenha algo nativo pra gerar pdf com mais rapidez e que seja robusto!

**Comment by stavarengo** [comment]
@carlosfilho88, adoraria usar o ZF.
Quando essa lib foi feita o ZF era um único repositório e não era possível usar apenas o componente PDF.
Hoje podemos fazer isso, já que o ZF PDF foi extraído para https://github.com/zendframework/ZendPdf

**Comment by carlosfilho88** [comment]
Pois vamos cair pra cima, cara! E outra, corrigi o pr que tinha feito, dei um vacilo besta e subi código errado. Quando der, faz o merge aí.

**Comment by stavarengo** [comment]
Show de bola @carlosfilho88 
Aguardamos seu PR com o ZF. Vai ser lindo de ver!

**Comment by entchucs** [comment]
PessoALL,
Alguma novidade sobre este assunto?
Preciso gerar o AR para um cliente e estou com pouco tempo para diagramar o PDF.

**Comment by stavarengo** [comment]
@entchucs podemos fechar esse ?

**Comment by carlosfilho88** [comment]
Bom, eu peguei [esse modelo aqui](http://www2.correios.com.br/enderecador/cartas/act/gerarAR.cfm) e adaptei pra minha necessidade. Criei um HTML com tabela e CSS inline pra evitar problemas na conversão pra PDF. Usei o mPDF com a seguinte configuração e consegui imprimir 3 ARs por página:

 ```
$mpdf = new mPDF('UTF-8', 'A4', 0, '', 10, 10, 5, 5, 0, 0);
$mpdf->SetDisplayPreferences('NoPrintScaling');
$mpdf->useSubstitutions = true;
$mpdf->simpleTables = false;
$mpdf->showImageErrors = false;
$mpdf->packTableData = true;
```

[Fiz um gist](https://gist.github.com/carlosfilho88/bdc1e605c777b40c65c00fb3e1e695cf#file-aviso_recebimento-html) que **precisa ser adaptado** pra sua necessidade, como por exemplo, passar as variáveis pra página e carregar os valores dinamicamente.

**Comment by stavarengo** [comment]
@carlosfilho88 caso tenha alguma colaboração, mande pra gente via PR. 
Vou fechar o issue por hora.

**Comment by carlosfilho88** [comment]
@stavarengo eu até tentei fazer nesse modelo de vocês, mas não rolou porque é muita volta pra imprimir com fpdf. Do jeito que foi pensado, ficou um pouco acoplado. Deixei o que a lib faz sendo feito e gerei o AR por fora usando o que já tinha disponível. Mesma coisa pra lista de postagem.

**Comment by willian-rosa** [comment]
@stavarengo e @carlosfilho88 a única coisa que falta o AR ficar pronto é a geração dom pdf?

**Comment by stavarengo** [comment]
Sim

**Comment by carlosfilho88** [comment]
@willian-rosa pega lá o gist que enviei que é o modelo que uso em produção. Não tem me dado problema.

**Comment by willian-rosa** [comment]
@carlosfilho88 mas lá é mpdf, certo?
O mpdf eu acho muito pesado.

Estava pensando em fazer em fpdf, e ai da para compartilhar para todos. Não parece ser muito complexo fazer fpdf (assim espero).

Vou dar inicio em alguns testes aqui. E se der certo, vou fazer um PR.

**Comment by stavarengo** [comment]
Aguardamos ansiosos :)

**Comment by willian-rosa** [comment]
Estava fazendo o layout da documentação até ver que o correios tem 2 layout =/   (eles nunca tem um padrão)

Que esta na documentação
![image](https://user-images.githubusercontent.com/17603785/29927854-e712b8b6-8e3d-11e7-8950-07f79c794df7.png)
 
e a que esta no gerador de AR deles
![image](https://user-images.githubusercontent.com/17603785/29927905-0b395b8c-8e3e-11e7-8a2e-78694adc4713.png)

Vou continuar com o da documentação, afinal só muda as ordens dos campos.
Ou será que tem algum problema?

**Comment by carlosfilho88** [comment]
A diferença é que um é o layout do SIGEP e o outro não. Na prática, eles trabalham com os dois modelos porque os campos são iguais. O importante é adotar um padrão, @willian-rosa. Não faça um por conta própria porque terá problemas. 

O melhor mesmo é procurar um gerente dos Correios e imprimir seus layouts pra validar com ele, especialmente se você adotar o modelo de cartas com o CEPNet. Faça isso e evitará dores de cabeça gigantescas, porque eles testam na máquina franqueada. Se ela estiver lendo tudo direitinho, você será um grande amigo dos Correios...

O modelo do SIGEP é o mais confiável, porque é uma plataforma que eles usam e cobram por esse serviço.

**Comment by willian-rosa** [comment]
Entendi...
Valeu

**Comment by MatheusAriel** [comment]
Existe essa ferramenta de imprimir o AR hoje no sistema? Caso seja possível, onde eu encontro um exemplo? Obrigado desde já

**Comment by andersonls** [comment]
@MatheusAriel Dá uma olhada no exemplos/imprimirAvisoRecebimento.php se é o que você procura.

**Comment by MatheusAriel** [comment]
Muito obrigado
