### ISSUE TITLE
AccessDataHomologacaoReversa (dados de acesso)

### ISSUE THREAD

**Issue by AndreXori** [stavarengo/php-sigep#495]
idCorreiosUsuario' => 'XXXXX',
'idCorreiosSenha' => 'XXXXX',
**'usuario' => 'XXXXX',
'senha' => 'XXXXX',**
'codAdministrativo' => 'XXXXX',
'numeroContrato' => 'XXXXX',
'cartaoPostagem' => 'XXXXX',
'cnpjEmpresa' => 'XXXXX', // Obtido no método 'buscaCliente'.
'anoContrato' => null, // Não consta no manual.
'diretoria' => new Diretoria(Diretoria::DIRETORIA_DR_BRASILIA), // Obtido no método 'buscaCliente'.

O que colocar em usuário em senha? De onde vem esses dados?
Já tentei os dados do Sigep e nada. Criei um usuário dentro do idCorreios (Meu Correios) e nada.

Poderiam dar uma luz?

**Comment by AndreXori** [comment]
Tbm tentei o usuário e senha que uso no webservice dos Correios para consultar objetos.
Tbm não funcionou. Quando tento cadastrar uma autorização de postagem, recebo:

PhpSigep\Services\Result Object
(
    [isSoapFault:protected] => 1
    [errorCode:protected] => 0
    [errorMsg:protected] => Unauthorized
    [result:protected] => 
    [soapFault:protected] => 
    [_failIfAtributeNotExiste:protected] => 1
)

**Comment by andersonls** [comment]
Eu não utilizo o serviço de logística reversa, mas acredito que seja necessário solicitar ao correio habilitação para utilizar este Webservice. Talvez seja o mesmo processo de habilitação para utilizar o Sigep.

**Comment by AndreXori** [comment]
Consegui!
Pedi para o gestor do meu contrato autorizar.
Pelo MEU CORREIOS a gente não consegue fazer.
Precisa ser no [ws.correios.com.br](https://cws.correios.com.br/)
Lá tem um link no menu para gestão de API's.
