### ISSUE TITLE
Número da PLP

### ISSUE THREAD

**Issue by estevaofelipe** [stavarengo/php-sigep#50]
A função que gera o número da PLP é time(), porém está gerando com 10 dígitos, e com isso não registra no sistema. Os Correios orientaram criar com 8 dígitos, resolvi da seguinte maneira: substr(time(), 0, 8), então gravou com sucesso, mas a plp foi salva como fechada, impossibilitando os correios editar informações de volume e peso. Não encontrei nada sobre esse status.

**Comment by pvpzaum** [comment]
@estevaofelipe , reparei que no PLP, ele tem que enviar o tamanho e o peso, de cada produto, entretanto não estou achando aonde esta registrado esse envio. Poderia me ajudar?

**Comment by estevaofelipe** [comment]
@pvpzaum, na verdade não é o peso de cada produto, mas sim das embalagens. você pode usar o Model\Dimensao(). No helper-criar-pre-lista.php tem o exemplo logo no começo do código.

**Comment by pvpzaum** [comment]
@estevaofelipe verdade, deixei passar aqui. Obrigado.

**Comment by gustvao** [comment]
@estevaofelipe o número do PLP é retornado pelos correios quando você fecha a PLP.

o time() é meramente ilustrativo, você tem que substituir o time() pelo PLP retornado quando fechar a PLP.

**Comment by estevaofelipe** [comment]
@gustvao, pacei despercebido pelo método que fecha as plp's, obrigado pela ajuda.

**Comment by estevaofelipe** [comment]
@gustvao, informando um erro no método FecharPreListaDePostagem\writeRemetente(),

Fatal error: Call to a member function getNumero() on a non-object in /PhpSigep/Services/Real/FecharPreListaDePostagem.php on line 115

O getNumero() pertence a classe getAccessData e não getRemetente. "$data->getAccessData()->getDiretoria()->getNumero()"

**Comment by gustvao** [comment]
@estevaofelipe eu consegui fechar a PLP direitinho.. vc precisa autenticar com todos os dados.. inclusive o diretoria etc... tá faltando dado na sua autenticacao

**Comment by estevaofelipe** [comment]
Depois que fiz a alteração que citei acima também consegui fechar tudo certinho, inclusive homologuei lá nos correios. Abaixo segue meu código.

class AccessDataHomologacao extends AccessData
{
    /**
     * Atalho para criar uma {@link AccessData} com os dados do ambiente de homologação.
     */
    public function __construct()
    {
        parent::__construct(
            array(
                'usuario'           => '99XXXX634',
                'senha'             => '8XXX40',
                'codAdministrativo' => '132XXX85',
                'numeroContrato'    => '99XXXXX047',
                'cartaoPostagem'    => '00XXXXX042',
                'cnpjEmpresa'       => '07XXXXX7000126', // Obtido no método 'buscaCliente'.
                'anoContrato'       => '2013', // Não consta no manual.
                'diretoria'         => new Diretoria(Diretoria::DIRETORIA_DR_SANTA_CATARINA), // Obtido no método 'buscaCliente'.
            )
        );
        try {\PhpSigep\Bootstrap::getConfig()->setEnv(\PhpSigep\Config::ENV_PRODUCTION);} catch (\Exception $e) {}
    }
}

**Comment by marcelomaeda** [comment]
Alterei o arquivo /PhpSigep/Services/Real/FecharPreListaDePostagem.php

na linha: $writer->writeElement('numero_diretoria', $data->getRemetente()->getDiretoria()->getNumero());

para: $writer->writeElement('numero_diretoria', $data->getAccessData()->getDiretoria()->getNumero());

Funcionou corretamente o fechamento de plp.

**Comment by jdgrieco** [comment]
@marcelomaeda eu resolvi acrescentando a diretoria no remetente:
$remetente->setDiretoria(new \PhpSigep\Model\Diretoria(\PhpSigep\Model\Diretoria::DIRETORIA_DR_BRASILIA));
no arquivo helper-criar-pre-lista.php do exemplo

Eu instalei via composer e como eu copiei a pasta de exemplos, o "vendor" não tem nenhuma alteração

**Comment by stavarengo** [comment]
@marcelomaeda e @jdgrieco tudo certo?
Eu não entendi muito bem, este problema necessita de alguma alteração no nosso projeto?

**Comment by jdgrieco** [comment]
@stavarengo Ao tentar rodar o exemplo fechaPlpVariosServicos.php dá o erro que o @estevaofelipe reportou acima:

Fatal error: Call to a member function getNumero() on a non-object in /var/www/html/vendor/stavarengo/php-sigep/src/PhpSigep/Services/Real/FecharPreListaDePostagem.php on line 115

E o @marcelomaeda reportou que tem que alterar o arquivo /PhpSigep/Services/Real/FecharPreListaDePostagem.php

Eu resolvi o problema acrescentando a diretoria no remetente no arquivo helper-criar-pre-lista.php  na pasta exemplo.

Agora não sei qual solução faz mais sentido. Se for a do @marcelomaeda vai ter que alterar a classe propriamente dita, se for a minha (@jdgrieco) vai ter que alterar o exemplo.

De qualquer maneira vai ter que fazer um PR

**Comment by stavarengo** [comment]
O que acham?
https://github.com/stavarengo/php-sigep/commit/df56b7e88b8118db93cba48a732da6ae36274cbe

**Comment by jdgrieco** [comment]
Perfeito
