### ISSUE TITLE
Envio de mais de um serviço adicional por etiqueta na plp

### ISSUE THREAD

**Issue by furtado3g** [stavarengo/php-sigep#500]
Quando tento enviar mais de um serviço adicional acaba me retornando que o xml está invalido conforme mensagem retornada do correio (Ocorreu um erro ao interpretar os dados do XML gerado pelo Cliente.), Segue trecho de código onde eu defino o array de serviços adicionais na etiqueta, Os valores estão salvos em uma String implodidos no próprio banco de dados

$servicosAdicionais = [];
$adicionais = explode(',', $v->adicional);
foreach($adicionais as $adicional){
    $servicoAdicional = new \PhpSigep\Model\ServicoAdicional();
    if($adicional == '019' || $adicional == '064' || $adicional == '065'){
        $servicoAdicional->setCodigoServicoAdicional($adicionais[0]);
        $servicoAdicional->setValorDeclarado(floatval(moedaPhp($v->valor_produto)));
        $servicosAdicionais[] = $servicoAdicional;
    }elseif($adicional == '01'){
        $servicoAdicional->setCodigoServicoAdicional($adicional);
        $servicosAdicionais[] = $servicoAdicional;
    }
}

**Comment by andersonls** [comment]
Pelo teu código, pode estar acontecendo de o mesmo serviço estar sendo adicionado várias vezes.

Essa linha ` $servicoAdicional->setCodigoServicoAdicional($adicionais[0]);`
Não deveria ser ` $servicoAdicional->setCodigoServicoAdicional($adicional);`?

Veja no XML se esse não é o caso, se tiver vários serviços com o mesmo código vai retornar erro mesmo. Além disso, o código de serviço adicional de valor declarado deve estar de acordo com o tipo de serviço (Sedex, PAC, etc).

**Comment by furtado3g** [comment]
@andersonls Bom dia, 
Mesmo com a correção apontada o que realmente acabava causando um erro o resultado é o mesmo, e ao gerar a plp de uma etiqueta que contenha apenas um serviço adicional a mesma é gerada normalmente, Mas ao enviar mais de um serviço adicional o erro se mantem,
`$servicosAdicionais = [];
$adicionais = explode(',', $v->adicional);
foreach($adicionais as $adicional){
    $servicoAdicional = new \PhpSigep\Model\ServicoAdicional();
    if($adicional == '019' || $adicional == '064' || $adicional == '065'){
        $servicoAdicional->setCodigoServicoAdicional($adicional);
        $servicoAdicional->setValorDeclarado(floatval(moedaPhp($v->valor_produto)));
        $servicosAdicionais[] = $servicoAdicional;
    }elseif($adicional == '01'){
        $servicoAdicional->setCodigoServicoAdicional($adicional);
        $servicosAdicionais[] = $servicoAdicional;
    }
}`

segue xml que foi gerado 

`<?xml version="1.0" encoding="UTF-8"?>
<correioslog>
   <tipo_arquivo>Postagem</tipo_arquivo>
   <versao_arquivo>2.3</versao_arquivo>
   <plp>
      <id_plp />
      <valor_global />
      <mcu_unidade_postagem />
      <nome_unidade_postagem />
      <cartao_postagem>0076404080</cartao_postagem>
   </plp>
   <remetente>
      <numero_contrato>21169632</numero_contrato>
      <numero_diretoria>36</numero_diretoria>
      <codigo_administrativo>9912532939</codigo_administrativo>
      <nome_remetente><![CDATA[Lucas Furtado]]></nome_remetente>
      <logradouro_remetente><![CDATA[Rua Ara��]]></logradouro_remetente>
      <numero_remetente><![CDATA[43]]></numero_remetente>
      <complemento_remetente />
      <bairro_remetente><![CDATA[Jardim Morumbi]]></bairro_remetente>
      <cep_remetente><![CDATA[86035050]]></cep_remetente>
      <cidade_remetente><![CDATA[Londrina]]></cidade_remetente>
      <uf_remetente>PR</uf_remetente>
      <telefone_remetente />
      <fax_remetente />
      <email_remetente />
      <celular_remetente />
      <cpf_cnpj_remetente />
      <ciencia_conteudo_proibido>S</ciencia_conteudo_proibido>
   </remetente>
   <forma_pagamento />
   <objeto_postal>
      <numero_etiqueta>QJ931357485BR</numero_etiqueta>
      <codigo_objeto_cliente />
      <codigo_servico_postagem>04227</codigo_servico_postagem>
      <cubagem>0</cubagem>
      <peso>300</peso>
      <rt1 />
      <rt2 />
      <restricao_anac>0</restricao_anac>
      <destinatario>
         <nome_destinatario><![CDATA[Lucas Furtado]]></nome_destinatario>
         <telefone_destinatario />
         <celular_destinatario />
         <email_destinatario />
         <logradouro_destinatario><![CDATA[Jardinete Terezinha Schlivinski]]></logradouro_destinatario>
         <complemento_destinatario />
         <numero_end_destinatario><![CDATA[43]]></numero_end_destinatario>
         <cpf_cnpj_destinatario />
      </destinatario>
      <nacional>
         <bairro_destinatario><![CDATA[Cristo Rei]]></bairro_destinatario>
         <cidade_destinatario><![CDATA[Curitiba]]></cidade_destinatario>
         <uf_destinatario>PR</uf_destinatario>
         <cep_destinatario><![CDATA[80050590]]></cep_destinatario>
         <codigo_usuario_postal />
         <centro_custo_cliente />
         <numero_nota_fiscal>0</numero_nota_fiscal>
         <serie_nota_fiscal />
         <valor_nota_fiscal />
         <natureza_nota_fiscal />
         <descricao_objeto />
         <valor_a_cobrar>0</valor_a_cobrar>
      </nacional>
      <servico_adicional>
         <codigo_servico_adicional>025</codigo_servico_adicional>
         <codigo_servico_adicional>065</codigo_servico_adicional>
         <valor_declarado>100</valor_declarado>
         <codigo_servico_adicional>01</codigo_servico_adicional>
         <valor_declarado />
      </servico_adicional>
      <dimensao_objeto>
         <tipo_objeto>002</tipo_objeto>
         <dimensao_altura>1</dimensao_altura>
         <dimensao_largura>10</dimensao_largura>
         <dimensao_comprimento>15</dimensao_comprimento>
         <dimensao_diametro>0</dimensao_diametro>
      </dimensao_objeto>
      <data_postagem_sara />
      <status_processamento>0</status_processamento>
      <numero_comprovante_postagem />
      <valor_cobrado />
   </objeto_postal>
</correioslog>`

**Comment by andersonls** [comment]
Notei duas coisas no teu XML:

* na tag _logradouro_remetente_, tem uns caracteres estranhos. Precisa cuidar com a codificação, pois o correio aceita apenas a ISO 8859-1. Eu removo toda a acentuação para não ter dor de cabeça. Se para você está funcionando, pode ignorar esse comentário.
* O código do último servico está com apenas dois caracteres, eu sempre uso com 3. Veja se não é isso!  `<codigo_servico_adicional>01</codigo_servico_adicional>`, para `<codigo_servico_adicional>001</codigo_servico_adicional>`. 
* Não sei se influencia também, mas eu informo primeiro o AR (001) e depois o do valor declarado (065)

**Comment by furtado3g** [comment]
@andersonls Muito obrigado pela ajuda consegui resolver o erro, 
O mesmo era causado pelo formato do valor informado no vd e ordem
