### ISSUE TITLE
Consulta das PLP fechadas

### ISSUE THREAD

**Issue by Thiago-Rizzo** [stavarengo/php-sigep#510]
Tem alguma forma depois de fechar as PLPs, consulta-las ou ter algum detalhamento delas??

**Comment by willian-rosa** [comment]
Sim, é possível buscar a PLP a partir do método `solicitaXmlPlp`:

```php
$phpSigep = new PhpSigep\Services\SoapClient\Real();
var_dump($phpSigep->solicitaXmlPlp('XXX''));
```
