### ISSUE TITLE
Erro na impressão de etiqueta

### ISSUE THREAD

**Issue by guimunarolo** [stavarengo/php-sigep#52]
Estou rodando o script de exemplo imprimirEtiquetas.php e recebendo o seguinte erro:

Warning: strtoupper() expects parameter 1 to be string, object given in /Applications/MAMP/htdocs/php-sigep/vendor/stavarengo/php-sigep-fpdf/fpdf.php on line 988
FPDF error: Some data has already been output, can't send PDF file (output started at /Applications/MAMP/htdocs/php-sigep/vendor/stavarengo/php-sigep-fpdf/fpdf.php:988)

Alguém teve o mesmo problema?

**Comment by gustvao** [comment]
o erro diz que você não pode ter dado nenhum ECHO/PRINT_R ou jogado qualquer tipo de texto antes de chamar o output...

**Comment by guimunarolo** [comment]
Sim, o error ocorre por conta do warning que é printado anteriormente. Porém o warning ocorre porque está sendo usado um strtoupper em um objeto, correto?

**Comment by gustvao** [comment]
@guimunarolo não vi seu código, mas sua conclusão me parece fazer sentido

**Comment by guimunarolo** [comment]
Pelo que vi o $dest está chegando um objeto no fpdf e isso está causando o problema. Se você testar com o próprio código de exemplo de impressão da etiqueta você vai acabar no mesmo problema que eu estou tendo.

**Comment by gustvao** [comment]
se eu nao me engano o exemplo está desatualizado com o master, anyways, aqui ta funcionando direitinho..

**Comment by guimunarolo** [comment]
@gustvao encontrei o problema, foi feito um merge com uma alteração sua onde a função render da classe CartaoDePostagem espera o $dest, e no exemplo estava sendo passado um objeto de PLP.

Valeu.

**Comment by gustvao** [comment]
@guimunarolo boa! faz um PR pra consertar o script de exemplo, acho que é uma boa, nao?

**Comment by guimunarolo** [comment]
@gustvao sim, vou fazer ainda hoje!
