### ISSUE TITLE
Prefixo do Código Gerado

### ISSUE THREAD

**Issue by pvpzaum** [stavarengo/php-sigep#54]
Boa noite pessoal,

gostaria de tirar uma dúvida, minha cliente alegou que cade tipo de entrega tem um prefixo diferente, gostaria de saber se isto é verdade? Por que não consegui achar nada na documentação e se for se esse sistema já esta implementado na API.

Obrigado.

Att,

**Comment by guimunarolo** [comment]
Você solicitando a etiqueta com a api, o código já é gerado com os prefixos de cada tipo de serviço.

**Comment by pvpzaum** [comment]
@guimunarolo estranhamente, eu faço isso mas ele só esta gerando com o prefixo do Sedex. Você imagina aonde pode ser esse problema?

**Comment by guimunarolo** [comment]
@pvpzaum você está utilizando o código de exemplo?

**Comment by pvpzaum** [comment]
@guimunarolo Sim, estou utilizando o código de exemplo.

**Comment by guimunarolo** [comment]
@pvpzaum arquivo solicitarEtiquetas.php linha 16:
$params->setServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_E_SEDEX_STANDARD);

o meu ficou assim, passando no get o código do serviço:
$params->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem($_GET['service']));

**Comment by pvpzaum** [comment]
@guimunarolo o meu ficou assim.

` if(isset( $value['tipo_envio'] ) && $value['tipo_envio'] == 'PAC' ) { 
                $encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_PAC_41106));
            }`

Eu faço "if" e "else" para saber qual é o serviço escolhido, a chancela muda, como deveria realmente mudar, mas o prefixo sempre continua o mesmo.

**Comment by guimunarolo** [comment]
@pvpzaum isso na quando gera a etiqueta?

**Comment by pvpzaum** [comment]
@guimunarolo Exatamente, muito estranho, o mais estranho é ele mudar a chancela, mas não mudar o código, por que um esta atrelado ao outro, então logo ele deveria mudar.

**Comment by guimunarolo** [comment]
@pvpzaum vixi, cara... precisava dar uma olhada no seu código pra eu conseguir te ajudar melhor, porque o meu está funcionando aqui e eu também utilizei os códigos de exemplo como base.

Tem como criar um repositório e compartilhar comigo?

**Comment by pvpzaum** [comment]
Claro, vou criar aqui e compartilho.

**Comment by pvpzaum** [comment]
@guimunarolo desculpa não ter respondido com o repositório mas tive um problema com a Net(operadora) e fiquei até agora sem conexão, então tive bastante tempo para pensar em possíveis erros e descobri que apenas o "Sedex" e o "PAC" não estão funcionais, quando coloco como opção de pagamento.

Coloquei o meu código do helper-criar-pre-lista.php no pastbin para você dar uma olhada.

[http://pastebin.com/LShcnrYN](url)

O erro que ele me retorna quando tento uma das opções é esse.

`Fatal error: Call to a member function getEtiquetaSemDv() on a non-object in /caminho/helper-criar-pre-lista.php on line 57`

**Comment by pvpzaum** [comment]
Fui dar uma olhada no "solicitarEtiquestas" e o retorno que recebo quando tento imprimir um do tipo PAC é esse.

`O Serviço 41106                     PAC À VISTA                    não está liberado para solicitação de etiquetas.`

**Comment by pvpzaum** [comment]
@guimunarolo Descobri, não tinha prestado atenção no retorno, ele já diz qual é o problema, meu cliente tinha me passado o PAC e o Sedex errados, então logo não iria funcionar, então como ela n sabia fui na base da tentativa e erro e achei os corretos.

Obrigado por tudo, me ajudou muito.

@stavarengo Pode fechar se assim quiser.

Att,

**Comment by guimunarolo** [comment]
@pvpzaum que isso! Precisando, só chamar!!
