### ISSUE TITLE
Sistema Validador de Postagens.

### ISSUE THREAD

**Issue by pvpzaum** [stavarengo/php-sigep#55]
Pessoal, estou com um outro problema, estou gerando os códigos das etiquetas, minha cliente foi testar em um programa dos proprios correios, "Sistema Validador de Postagens",  quando ela coloca a  etiqueta ele retorna que o "Objeto postal não pertence ao SIGEPWEB", alguém saberia me dizer o motivo?

Att,

**Comment by pvpzaum** [comment]
Descobri, por que esta dando essa mensagem, por que ela esta tentando verificar um PLP que não esta no servidor dos correios ainda. Mas estou tentando fechar a PLP e esta dando erro.

`Array
(
    [*isSoapFault] => 1
    [*errorCode] => 0
    [*errorMsg] => Ocorreu um erro interno no Servidor.
    [*result] => 
    [*soapFault] => 
    [*_failIfAtributeNotExiste] => 1
)`

Entendo o problema esta em algum atributo, ou na falta dele, basicamente é isso, não consigo identificar qual é? Alguém saberia, obrigado.

**Comment by pvpzaum** [comment]
@stavarengo , @gustvao , vocês conseguiram fechar a PLP, como fizeram pq estou tentando mas ele da a mensagem da resposta acima e não me retorna mais nada então estou as escuras. 

Att,

**Comment by gustvao** [comment]
ocorreu um erro interno no servidor é meio dificil de debugar, vc autenticou antes com todos os dados? contrato, cod adm, cod diretoria etc etc?

**Comment by pvpzaum** [comment]
@gustvao sim, esse é o problema estou com os dados todos preenchidos e o erro que da é muito vago, como disse na mensagem acima estou nas escuras mesmo.

**Comment by gustvao** [comment]
coloca seu codigo aqui.. depois se quiser posso por o meu pra vc comparar

**Comment by stavarengo** [comment]
Todos pararam de interagir com este bug: posso fechar?
@pvpzaum se vc encontrou uma solução, deixa postado aqui!

**Comment by arthrmrs** [comment]
Estranhamente esse erro voltou a ocorrer. Estou enfrentando o mesmo problema ao fechar uma PLP com vários serviços, simplesmente recebo a mensagem de Erro interno no servidor.
Alguém ainda esta com esse problema?

**Comment by luiz-merante** [comment]
Estou recebendo este mesmo erro "Ocorreu um erro interno no Servidor."
{
    "return": true,
    "msg": "",
    "data": {
        "isSoapFault": true,
        "errorCode": 0,
        "errorMsg": "Ocorreu um erro interno no Servidor.",
        "result": null,
        "soapFault": null
    },
    "time_start": 1560343700.9531,
    "time_end": 1560343701.4475,
    "time": 0.49444198608398
}

**Comment by victorarielgarcia** [comment]
Estou com o mesmo problema, alguém sabe como resolver?
