### ISSUE TITLE
Problema com input de solicitação de postagem reversa

### ISSUE THREAD

**Issue by bbenatti** [stavarengo/php-sigep#56]
Boa tarde, tenho um problema com a implementação do método solicitarPostagemReversa. Tenho como retorno: 

`DADOS DE VALIDAÇÃO DA COLETA INCOMPLETOS . ( coletas_solicitadas.coleta.remetente ) Obrigatório.`

Não resolve estruturar o `$soapArgs` como manda a documentação dos correios ou colocar o remetente dentro de uma array "coleta" por sua vez dentro de "coletas_solicitadas". 

Sinto que é um problema mais com a documentação do que com o código em si. Alguém sabe como resolver esse problema?

**Comment by stavarengo** [comment]
@bbenatti, tbm me parece ser mais um problema de integração com o Correios do que com o projeto em si.
Vou fechar este erro por ser muito antigo e ninguém deu um feedback, mas se você tiver alguma consideração extra, por favor deixe o seu cometário aqui tbm.
