### ISSUE TITLE
1166006 - A tarifa deste serviço não foi encontrada

### ISSUE THREAD

**Issue by estevaofelipe** [stavarengo/php-sigep#58]
Alguém imagina o que seja esse erro? Ocorre sempre que fecho uma PLP.

**Comment by stavarengo** [comment]
@estevaofelipe não sei o que pode ser.
Vou fechar este erro por ser muito antigo e ninguém deu um feedback, mas poste a sua solução caso tenha encontrado por favor.

**Comment by estevaofelipe** [comment]
encontrei a solução sim, o código do serviço adicional são 3 caracteres, ao passar 019 por exemplo, por algum motivo o zero não ia no xml, então coloquei entre aspas passando como string e funcionou.
