### ISSUE TITLE
Layout Etiquetas e Gerar Código etiqueta. 

### ISSUE THREAD

**Issue by r0drigocarvalho** [stavarengo/php-sigep#59]
Fala pessoal beleza?

Fiz a instalação via Composer, o Layout das etiquetas está diferente do que está na versão atual. E quanto ao gerar o código da etiqueta alguém poderia me ajudar acabei não entendendo a documentação.

**Comment by gustvao** [comment]
@r0drigocarvalho a documentacao está velha vs o código do master... voce poderia aproveitar o assunto e atualizar a documentacao e fazer um PR.. o que acha da ideia @stavarengo ? :)

**Comment by r0drigocarvalho** [comment]
Alguém teria a versão mais atualizada? Pois trabalhar com a versão desatualizada é retrabalho.

**Comment by gustvao** [comment]
Esse é justamente o ponto Rodrigo. Voce atualizar a documentacao e contribuir

**Comment by r0drigocarvalho** [comment]
Sim, Gustavo mais a versão que está como modelo está mais atualizada que a versão do git. Só precisava dessa versão para dar continuidade no projeto.

**Comment by gustvao** [comment]
A versao do master do repositorio do codigo é a mais atualizada. voce precisa rodar no seu pc, gerar os exemplos e atualizar os codigos e exemplos e imagens da documentacao para elas ficarem em fase, faz sentido?

**Comment by r0drigocarvalho** [comment]
desculpa Gustavo não entendi o que você quis dizer.

**Comment by stavarengo** [comment]
Oi pessoal. Desculpa a demora pra responder.
Como ficou esse bug? Posso fechar? Ficou tudo esclarecido @r0drigocarvalho ?
