### ISSUE TITLE
Como conseguir - Login e Senha

### ISSUE THREAD

**Issue by rafanake** [stavarengo/php-sigep#61]
Olá,
Gostaria de saber se mais alguém teve dificuldades em conseguir essas informações para o acesso!

Falei com a gerente e ela não sabe absolutamente nada sobre o Web Service, pediu para ligar no 3003-0888 e lá eles dizem que não dão suporte ao Web Service e pedem para falar com o Gerente...

Ai fico em um loop infinito e não consigo a informação que preciso.
Alguém mais teve este tipo de dificuldade e conseguiu uma solução? Obrigado!

**Comment by gustvao** [comment]
minha dica é não falar vocabulario complexo ou webservice. fala que voce quer usar o SIGEP e eles vao te fazer o cadastro e passar login e senha. as informacoes vao ser as mesmas do webservice
