### ISSUE TITLE
Problema no processamento da PLP na agência dos Correios

### ISSUE THREAD

**Issue by youzoom** [stavarengo/php-sigep#62]
Pessoal, estou com um problema na validação da PLP na agência dos Correios. A PLP é gerada normalmente via Webservice, mas quando levo na agência para a efetivação da postagem, é exibido o erro no sistema Sara "Não é possível interpretar o conteúdo do arquivo. Verifique se o arquivo está correto".

Verifiquei todos os campos do XML, e os dados estão seguindo o padrão exigido pelo manual de integração.

Alguém já passou por esse tipo de problema ou tem ideia do que pode ser? Pois nem mesmo o pessoal dos Correios sabem dizer qual o problema.

Obrigado!

**Comment by gustvao** [comment]
@youzoom como vc resolveu? poderia compartilhar?

**Comment by youzoom** [comment]
@gustvao Era apenas problema de codificação do arquivo XML, fiz alguns ajustes na montagem do XML e resolveu o problema.

**Comment by AndreCalza92** [comment]
@youzoom Estou com o mesmo problema aqui, você poderia me dizer quais ajustes você fez na montagem do xml ? Valeu!

**Comment by youzoom** [comment]
@AndreCalza92 No meu caso era problema de codificação do XML, estava concatenando os dados com codificações diferentes, o que gerava um erro processar o XML.

**Comment by gustvao** [comment]
@youzoom poderia dar um exemplo pra nós? estou enfrentando isso de vez em quando também.

**Comment by stavarengo** [comment]
@AndreCalza92 @gustvao @youzoom 
Esse bug vale um PR?

**Comment by lucianoalbis** [comment]
Olá, estou passando pelo mesmo problema, o xml é enviado corretamente, o código Plp é gerado, porém na validação na agencia ocorre problema na validação.

**Comment by gnrbrasil** [comment]
Bem, vamos lá!

O interpretador de XML dos Correios é sensível a qualquer tipo de "caractere estranho", então qualquer lixo (por exemplo problema de codificação) que tenha no XML, irá gerar esse erro de interpretação.

O que se deve evitar nos dados do XML (e na string do próximo XML):
- Espaços no início e fim;
- Caracter para quebra de linha "\r\n" ou "\n" (esse é o mais comum ao montar o XML);
- Caracter "lixo" resultante de erro na conversão de codificação (ISO => UTF8 ou UTF8 => ISO);

Basicamente após realizar o tratamento do XML com as regras descritas acima, não tive mais problemas com geração de PLP.

Espero ter ajudado e boa sorte!

PS.: Meu nick antigo era o @youzoom

**Comment by lucianoalbis** [comment]
Olá,
muito obrigado pela observação! Você sabe me informar como consigo verificar os erros no meu xml, pois a responsável da agencia dos correios estava intermediando minhas dúvidas, em uma das respostas me foi enviado exatamente alguns erros, como saber esses erros?

att,

**Comment by gustvao** [comment]
@gnrbrasil fabio, acho que o que vai ajudar é você mostrar como você tratou as variáveis que pega para gerar a PLP.. ex. usou alguma funcao ou algum outro projeto no github para corrigir codificacao? etc etc..

**Comment by gustvao** [comment]
outra coisa, como você debuga isso? pq o pessoal que me manda não consegue falar por que nao funcionou, por exemplo... só falam que nao da pra ler lá..

**Comment by AndreCalza92** [comment]
No meu caso, a PLP não era validada na agencia dos correios pois o código do centro de distribuição estava incorreto, estava utilizando o código referente ao Paraná e o correto para mim deveria ser o codigo de Sao Paulo. Tive também que tratar do maxlength dos campos seguindo aquele manual que eles fornecem. Após isso a PLP foi validada.

Para validação da estrutura do XML, eles fornecem no manual, um Schema. Eu utilizei o site http://www.utilities-online.info/xsdvalidation/#.WCYiafowjDc para validar o xml que estava gerando com o schema correto.

Obs.: esse metodo que eles utilizam é horrível, passar informações via Xml é um caos para ficar tratando..se fosse com json, seria tudo mais simples..mas como esse webservice deve ser bem antigo, ficamos limitados.

Abraço.

**Comment by lucianoalbis** [comment]
Entendi! Com relação à validacao, a responsável da agência dos correios enviou os dados para alguém dos correios e esse alguém me envio os problemas. Corrigi e mandei pra agencia, porém ainda não funcionou. Tá osso isso!

**Comment by gustvao** [comment]
eu olhei o creator do XML e aparentemente o maxlenght é validado lá, @AndreCalza92 você pode falar quais validações de maxlenght colocou para fazermos um PR?

gente, é super importante qeu quando alguem consiga achar um bug e corrigir, que mande um PR pra isso melhorar o repositorio e nao termos que ficar reabrindo issues antigos

**Comment by lucianoalbis** [comment]
Olá, 
muito obrigado pelas dicas! Seguindo esse esquema de utilizar esse validador online "http://www.utilities-online.info/xsdvalidation/#.WCYiafowjDc" consegui verificar meus erros. A única observação que faço é com relação ao campo "dimensao_diametro", ao rodar o validador (seu xml e wsdl plp) o resultado final é um erro;

Not valid.
Error - Line 2, 2470: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 2470; cvc-minInclusive-valid: Value '0' is not facet-valid with respect to minInclusive '5' for type '#AnonType_dimensao_diametro'.
Error - Line 2, 2470: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 2470; cvc-type.3.1.3: The value '0' of element 'dimensao_diametro' is not valid.

No meu caso achei estranho o erro, pois vi no documento do SIGEP que na documentação é informado que para tipo de objeto igual a 2, basta preencher com 0, porém ao validar via "XML Schema (XSD) Validation" o xml é reprovado, porém se colocar um valor igual ou maior que 5 o mesmo é aprovado, porém essa informação é validada lá no webservice, então não tem problema.

A título de curiosidade segue meus erros;
Tag <codigo_servico_adicional> com valor vazio
Tag dimensao_altura, dimensao_largura, dimensao_comprimento com valores errados.

att,

**Comment by andersonls** [comment]
@lucianoalbis O que eu costumo fazer é validar o XML com o PHP no momento da geração.

```PHP
$xml = new \DOMDocument('1.0', 'ISO-8859-1');

// gera o XML...

$validSchema = $xml->schemaValidateSource($this->_getSigepPlpXMLSchema());

if ($validSchema === false) {
   //trata o erro. Mostra msg para o usuário e não envia o XML, por exeplo
} else {
    $xmlPlp = $xml->saveXML();
    // Envia PLP...
}
```
O parâmetro do schemaValidateSource é uma string do XSD.

**Comment by jdgrieco** [comment]
@lucianoalbis, @andersonls 
No manual do Sigep tem o XSD.

**Comment by gustvao** [comment]
@lucianoalbis eu tinha lido na socumentacao do SIGEP que o dimensao só precisa quando é formato ROLO, e no caso eu uso sempre caixa... esse erro de validação eu estou ignorando e já tive diversos PLPs que passaram nos correios com esse setup

**Comment by andersonls** [comment]
@gustvao, @lucianoalbis Eu também somente uso caixa. No meu caso, como não deixo passar se tiver erro de validação do XML, o que eu fiz foi alterar o XSD para o mínimo ser 0 ao invés de 5. A linha do XSD é:

```XML
    <xs:element name="dimensao_diametro">
        <xs:simpleType>
            <xs:restriction base="xs:int">
                <xs:minInclusive value="0"/> <!-- Essa linha no XSD do manual o do projeto está 5 -->
                <xs:maxInclusive value="105"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
```

**Comment by jdgrieco** [comment]
@andersonls, isso está ok na validação do XML na sua aplicação, mas imagino que os Correios façam a validação lá no sistema deles e vão usar o XSD original, sem essa alteração

**Comment by gustvao** [comment]
@jdgrieco vc usa dimensao mesmo no pacote_caixa? qual valor que usa?

**Comment by jdgrieco** [comment]
@gustvao, meu cliente não está controlando tamanho da caixa então estou colocando 20 para altura, largura e comprimento.
E, apesar dos Correios já ter homologado, o sigep ainda não está sendo usado em produção, então não sei ao certo se teremos problemas de validação do XML da PLP

**Comment by andersonls** [comment]
@jdgrieco Pela minha experiência, o webService não valida o XML em si. Eles devem fazer alguma validação campo a campo. Tanto é que no exemplo que eu dei, de alterar o XSD na mão, o WebService não retorna erro.

Com relação as medidas, você não vai ter problema no envio para o webservice. O problema vai aparecer quando o pacote for postado na agência. Pelo menos na agência daqui o funcionário sempre confere a medida do pacote com a medida informada na PLP.

**Comment by jdgrieco** [comment]
@andersonls, obrigado pela informação. Realmente não tenho experiência quanto a isso, é meu primeiro projeto que necessita o uso do sigep.

Sobre as medidas, já alertei meu cliente.

**Comment by AndreCalza92** [comment]
@gustvao Cara, eu não usei o seu projeto aqui do git para implementar o meu, eu fiz em .Net e baixei o seu apenas para ver como fazia as chamadas do WS dos correios, por isso não fiz o PR.

O maxlength que fiz foi basicamente nos campos de string.

Não sei se o seu código fonte esta (ou estava) com esse mesmo problema, como eu disse, fiz o meu em .Net

Abraço.

**Comment by stavarengo** [comment]
Pessoal, pelo que percebi essa é uma melhoria simples e bem interessante para maturidade do projeto.
Estou certo? Vale a pena fazer?

**Comment by gustvao** [comment]
@stavarengo acho que é uma validação a mais e vale a pena, infelizmente não resolve 100% o problema por que só o fato de validar o scheme não garante que não vai ter problemas..

se você for mexer nisso, acho que vale a pena colocar uma uniformização de codificação antes de enviar o plp.. eu estou fazendo isso via essa biblioteca que tem um método interessante fixUTF8;

https://github.com/neitanod/forceutf8

**Comment by stavarengo** [comment]
Legal @gustvao.
Quando puder manda pra gente suas alterações.

**Comment by brunorthomaz** [comment]
Boa tarde,

Eu vi que no wsdl dos correios, existe um método chamado "validaPlp", será que esse método não seria pra validar a plp ?

Não consegui testar aqui ainda.

**Comment by luiz-merante** [comment]
eu também estou com problemas na plp, ela me retorna sempre esse erro
A PLP não será fechada, o(s) objeto(s) [PU37920569BR] já estão vinculados em outra PLP!
