### ISSUE TITLE
Imprimir 4 etiquetas na mesma pagina

### ISSUE THREAD

**Issue by jlhaas** [stavarengo/php-sigep#63]
Olá.
No exemplo do site http://phpsigep.stavarengo.com/, a impressão de etiquetas divide a página em 4, para que sejam impressas 4 etiquetas na mesma folha, porém ao baixar o projeto, os testes imprimem somente uma etiqueta por página. 
Gostaria de imprimir 4 etiquetas por página....
Perdi algo? Alguem pode me dar alguma dica?

Desde já muito obrigado.
José Luís

**Comment by jlhaas** [comment]
Opa, vi agora que tem uma issue fechada dizendo que a quantidade de etiquetas por página foi alterada para somente uma e que eu deveria configurar na hora da impressão para imprimir X páginas por folha...

Desculpem
Obrigado
José Luís

**Comment by mozgbrasil** [comment]
Ola

Boa Noite meus amigos

Tenho a necessidade de imprimir 4 etiquetas na mesma pagina

Você informa para configurar na hora da impressão para imprimir X páginas por folha

Veja nas imagens a seguir que no processo para impressão não tenho essa possibilidade

Você tem alguma informação para essa necessidade ? 

![captura de tela de 2017-02-10 20-13-03](https://cloud.githubusercontent.com/assets/17202780/22846170/5f2359b0-efcd-11e6-8658-d39eb31b8ba5.png)
![captura de tela de 2017-02-10 20-13-05](https://cloud.githubusercontent.com/assets/17202780/22846172/5f4a5290-efcd-11e6-81b7-239258d66a40.png)
![captura de tela de 2017-02-10 20-13-07](https://cloud.githubusercontent.com/assets/17202780/22846173/5f645f96-efcd-11e6-9181-d0a303bb352d.png)

**Comment by jlhaas** [comment]
Ali na aba "Configurar Página", na opção "Frente e Verso" pra mim aparece "um lado" e na opção "Páginas por Lado" eu escolho o numero de páginas... Não sei porque pra você aparece "não disponivel", já tentou em outra impressora?

**Comment by mozgbrasil** [comment]
Ola Boa Tarde

Eu não estou com a impressora instalada aqui na minha maquina no momento

Não sei se isso tem relação na exibição desse recurso usando o visualizador de PDF nativo do Ubuntu o Evince

Eu interagi no seguinte ticket e demonstro que pelo Adobe Acrobat aparece esse recurso

https://github.com/stavarengo/php-sigep/issues/111

Obrigado pelas informações
