### ISSUE TITLE
Erro ao rastrear objeto

### ISSUE THREAD

**Issue by jlhaas** [stavarengo/php-sigep#64]
Quando chamo a classe rastrearObjeto ocorre o erro "String could not be parsed as XML".

Debugando o código parece que quando o curl acessa a pagina dos correios da página Not Found e diz que o documento foi movido, pois a página dos correios mudou o link do rastreio.

Alguém está com este erro também?

**Comment by youzoom** [comment]
Provavelmente a URL do Webservice está desatualizada. O correto é: http://webservice.correios.com.br/service/rastro

**Comment by jlhaas** [comment]
A url que o curl busca é "http://websro.correios.com.br/sro_bin/sroii_xml.eventos", alterei para esta que você comentou e também não funcionou....
Criei uma função separada que faz um curl e passa a etiqueta via get, mas de qualquer forma obrigado pela ajuda.
