### ISSUE TITLE
Warning: include(StaLib/Logger.php)

### ISSUE THREAD

**Issue by IuryChristmas** [stavarengo/php-sigep#65]
Eae galera,
Então... Estou fazendo integração com o sigep, utilizando o Magento como framework... Fiz alguns testes com os métodos do php-sigep e notei que apenas os métodos que não fazem referência ao "StaLib" estão funcionando, qualquer outro gera o seguinte erro:
Warning: include(StaLib/Logger.php): failed to open stream: No such file or directory  in /var/www/html/projeto/lib/Varien/Autoload.php on line 93
A causa pode ser alguma configuração que não estou fazendo?

**Comment by stavarengo** [comment]
Estranho @IuryChristmas. 
O código exite um teste verificando se a classe existe antes de carregar, por isso não deveria gerar este warning.
Veja: https://github.com/stavarengo/php-sigep/search?q=Logger&type=Code&utf8=%E2%9C%93

De qualquer forma, você pode remover essas instruções, e se quiser pode fazer um PR.

**Comment by mozgbrasil** [comment]
Ola Boa Noite meu amigo

Estou tendo o mesmo problema em uso com o Magento

![captura de tela de 2017-01-18 20-16-46](https://cloud.githubusercontent.com/assets/17202780/22085404/19509656-ddbb-11e6-8090-0b28cc56bd4d.png)



Vemos na imagem que Isolei o script em um controller do Magento onde caso eu venha a usar somente o trecho 

        if (class_exists('\StaLib_Logger')) {

        }

Já é disparado o erro

![captura de tela de 2017-01-18 20-19-33](https://cloud.githubusercontent.com/assets/17202780/22085492/79af0cbc-ddbb-11e6-9e72-ff42e81783be.png)

![captura de tela de 2017-01-18 20-19-46](https://cloud.githubusercontent.com/assets/17202780/22085501/80431f8c-ddbb-11e6-963e-e26b78e2800e.png)

**Comment by mozgbrasil** [comment]
Acabo de descobrir o motivo do erro

Ao editar o arquivo .htaccess e adicionar 

SetEnv MAGE_IS_DEVELOPER_MODE "true"

é disparado esse erro

![captura de tela de 2017-01-18 20-37-26](https://cloud.githubusercontent.com/assets/17202780/22086057/0d245d1a-ddbe-11e6-9485-b03512a96de8.png)
![captura de tela de 2017-01-18 20-37-32](https://cloud.githubusercontent.com/assets/17202780/22086059/0d250b66-ddbe-11e6-9515-64c2bef73b77.png)
![captura de tela de 2017-01-18 20-37-44](https://cloud.githubusercontent.com/assets/17202780/22086061/0d277626-ddbe-11e6-84f2-d1ed1d7380dd.png)
![captura de tela de 2017-01-18 20-37-49](https://cloud.githubusercontent.com/assets/17202780/22086058/0d24d27c-ddbe-11e6-9c9e-315d098cac99.png)
![captura de tela de 2017-01-18 20-38-01](https://cloud.githubusercontent.com/assets/17202780/22086060/0d268630-ddbe-11e6-8ad5-8f1952bc8ca4.png)

**Comment by andersom-rfd** [comment]
@stavarengo onde consegue a classe **StaLib_Logger**?

**Comment by stavarengo** [comment]
@andersom-rfd está classa eh algo legacy dentro do projeto. Hoje em dia temos a [PSR-3](http://www.php-fig.org/psr/psr-3/).

Respondendo sua pergunta: não consegue mais. Se estiver atrapalhando, ou se tiver precisando de mensagens de log, pode remover e usar PSR-3 no lugar.
