### ISSUE TITLE
Novas regras para Valor Declarado

### ISSUE THREAD

**Issue by andersonls** [stavarengo/php-sigep#70]
Os correios alteraram o código do serviço adicional de valor declarado. Segue o texto enviado pelos correios com as novas regras:

“Prezados colegas, boa noite.

Segunda-Feira, dia 19 de setembro de 2016, será disponibilizada a versão 1.1.22 do Sigep Web.

Contará com as seguintes correções:

1) Correção da perda do endereço WSDL, Banco Compartilhado e do Proxy;

2) Correção (desmembramento) da Tabela de Valor Declarado, que ficará assim:

Para os serviços PAC, de acordo com a Regra de Negócio, conforme a seguir:

è O valor declarado para os serviços 4106-8, 4107-6, 4108-4, 4109-2, 4110-6, 4120-3, 4121-1, 4122-0, 4123-8, 4124-6, 4125-4, 4126-2, 4130-0, 4145-9, 4149-1, 4153-0, 4160-2, 4166-1, 4172-6, 4173-4, 4176-9, 4161-0, 4162-9, 4139-4.

Terão como limite mínimo R$17,00 (dezessete Reais) e  máximo R$3.000,00 (Três mil Reais).

Para esta regra o serviço adicional ?Valor Declarado? deverá ser identificado pelo código ?064.

Para os demais serviços o valor declarado de um objeto deverá estar compreendido entre R$17,00 (dezessete Reais) e R$ 10.000,00 (dez mil Reais). 

Para esta regra o serviço adicional ?Valor Declarado? deverá ser identificado pelo código ?019.

**Comment by stavarengo** [comment]
Temos alguém no grupo que já implementou estas alterações?
