### ISSUE TITLE
Correios não encontra código da PLP e da Etiqueta

### ISSUE THREAD

**Issue by felipez3r0** [stavarengo/php-sigep#72]
Olá pessoal,

Estou enfrentando um problema já tem algumas semanas, eu gero a etiqueta e posteriormente fecho a PLP porém algumas vezes a agência dos Correios aqui informa que não encontra a PLP e em outras informa que não encontra o código da etiqueta.

Alguém já passou por isso? Em nenhum dos casos o sistema apresentou erros, ele gerou normalmente o cóigo da etiqueta e o ID da Plp;

**Comment by stavarengo** [comment]
Nunca passei @felipez3r0, ja vi outras pessoas comentando sobre isso tempos atras.
Você tem certeza que está gerando as etiquetas no ambiente correto?

**Comment by felipez3r0** [comment]
Como o PHP no servidor é aquela versão que eventualmente da problema estou usando a seguinte configuração:

`// Configurações para consultas
$accessData = new \PhpSigep\Model\AccessData();
$accessData->setUsuario(USUARIO_SIGEP);
$accessData->setSenha(SENHA_SIGEP);
$accessData->setCodAdministrativo(COD_ADM);
$accessData->setNumeroContrato(CONTRATO_SIGEP);
$accessData->setCartaoPostagem(CARTAO_POSTAGEM);
$accessData->setCnpjEmpresa(CNPJ);
$accessData->setAnoContrato(null);
$diretoria = new \PhpSigep\Model\Diretoria(\PhpSigep\Model\Diretoria::DIRETORIA_DR_SAO_PAULO);
$accessData->setDiretoria($diretoria);

$config = new \PhpSigep\Config();
$config->setAccessData($accessData);
$config->setEnv(\PhpSigep\Config::ENV_PRODUCTION);
$config->setWsdlAtendeCliente('http://URL_COMPLETA/classes/CorreiosWSDL/AtendeCliente.xml?wsdl');`

**Comment by stavarengo** [comment]
@felipez3r0 , olha este bug https://github.com/stavarengo/php-sigep/issues/50
Principalmente o primeiro comentário do @estevaofelipe

**Comment by felipez3r0** [comment]
@stavarengo o meu código de fechar a PLP:

```
$plp = new \PhpSigep\Model\PreListaDePostagem();
$plp->setAccessData($config->getAccessData());

$plp->setEncomendas($encomendas);
$plp->setRemetente($remetente); 

$real = new \PhpSigep\Services\SoapClient\Real();
$resultC = $real->fechaPlpVariosServicos($plp);
$result = $resultC->getResult();

if($result == null){
      echo "Ocorreu um erro ao gerar a PLP com os pedidos selecionados.<br />";
      var_dump($resultC);
      exit();
}

$idPLP = $result->getIdPlp();
```

O estranho é que não ocorre erro, ele retorna o ID da PLP, porém algumas vezes o pessoal da agência não encontra o código no sistema. Em outras eles encontram, porém o código da Etiqueta não

**Comment by estevaofelipe** [comment]
Coloquei um tratamento quando houver erro:

if($erro = $result->getErrorMsg())
     die('<h3>'.$erro.'</h3>');

**Comment by felipez3r0** [comment]
Pode acontecer de retornar erro e mesmo assim retornar o ID da PLP?

**Comment by estevaofelipe** [comment]
Aconteceu de retornar erro apenas uma vez, quando enviei uma cidade com acentuação, retornou erro dizendo que o xml não foi processado e não veio o id.

**Comment by felipez3r0** [comment]
Entendi, aqui o problema na verdade é que ele me retorna ID e retorna as etiquetas porém a agência de correios não consegue encontrar a PLP e em alguns casos não consegue encontrar o código da etiqueta

**Comment by felipez3r0** [comment]
Existe alguma forma de consultar uma PLP pelo número ou somente o Correios pode fazer isso?

**Comment by felipez3r0** [comment]
Outra coisa interessante é que se eu tento realizar novamente o fechamento da PLP ele me informa:
A PLP não será fechada, o(s) objeto(s) [DW58109962BR] já estão vinculados em outra PLP!

Ou seja, de alguma forma a PLP anterior e os objetos foram encaminhados, porém a agência daqui não consegue encontrar o ID da PLP e nem o código da etiqueta.

**Comment by estevaofelipe** [comment]
Depois que a PLP é fechada não pode mais enviar as mesmas etiquetas em outra PLP, nem mesmo editar. Você está usando o método correto pra solicitar etiquetas?

**Comment by felipez3r0** [comment]
Sim, eu sei. Comentei que é estranho o Correios não encontrar na agência se ali o sistema me retorna o erro que está em outra PLP.

Para solicitar o código das etiquetas estou usando:
```
    // Envia e recupera o número da etiqueta
    $real = new \PhpSigep\Services\SoapClient\Real();
    $result = $real->solicitaEtiquetas($dados_etiqueta);
    $result = $result->getResult();

    $etiqueta->setEtiquetaSemDv($result[0]->getEtiquetaSemDv());

    $sigep_codigo_postal = $etiqueta->getEtiquetaComDv();
```

**Comment by felipez3r0** [comment]
Pessoal,

O Correios me informou o seguinte:

Erros na estrutura  do XML:
Erro na Posição da Tag: </codigo_servico_adicional>, do objeto: DW581129216BR
- A mesma tem que vir Antes da Tag: valor_declarado
Erro na Estrutura do Objeto: DW581129216BR
- As seguintes TAGs estam faltando: <valor_declarado> e </valor_declarado>

Erros nos dados do XML:
- Código do serviço adicional Incorreto! Deve conter 3 Caracteres!
- Identificação do Tipo do Objeto Incorreto! Deve conter 3 Caracteres!
- Altura do Objeto Inválida, Permitido 2 a 105!

O estranho que isso não impede de gerar o ID da PLP, vou checar aqui e ver o que preciso ajustar

**Comment by Vitorspk** [comment]
Me tire uma duvida felipez3r0,

Você entrou em contato com os correios via e-mail ? ou tem algum telefone deles para contato?
Pois estou com alguns erros em um desenvolvimento que estou fazendo referente ao método SolicitaEtiquetas e não consigo contato com eles.... ninguém no suporte helpdesk consegue me orientar como obter ajuda.

**Comment by felipez3r0** [comment]
Vitor, eu entrei em contato através de um e-mail que o pessoal de Bauru me
forneceu.
O e-mail é esse aqui: spisigepweb@correios.com.br

Em 3 de outubro de 2016 16:30, Vitor <notifications@github.com> escreveu:

**Comment by felipez3r0** [comment]
@stavarengo Consegui resolver os problemas e agora aparentemente tudo está ok.
Tive que alterar o seguinte nos meus arquivos:

```
class Dimensao extends AbstractModel
{
    const TIPO_ENVELOPE      = "001";
    const TIPO_PACOTE_CAIXA  = "002";
    const TIPO_ROLO_CILINDRO = "003";
```

E também mudei:

```
class ServicoAdicional extends AbstractModel
{
    const SERVICE_AVISO_DE_RECEBIMENTO = '001';
    const SERVICE_MAO_PROPRIA          = '002';
    const SERVICE_VALOR_DECLARADO      = '019';
    const SERVICE_REGISTRO             = '025';
```

Além disso mesmo não utilizando o valor declarado eu setei ele como zero e também setei o Diâmetro como zero (mesmo usando o tipo CAIXA)

**Comment by gustvao** [comment]
@felipez3r0 tive problemas parecidos com alguns casos também... mas não acontece com todo mundo, só com 1 ou outro como você falou..

fantástico que você conseguiu resolver o problema.. poderia criar um PR para o @stavarengo dar o merge urgente? acredito que isso deva estar afetando outros também

**Comment by felipez3r0** [comment]
Estou aguardando a primeira encomenda ser despachada com sucesso junto ao
Correio para enviar um PR.
O cliente ficou de enviar uma encomenda entre hoje e amanhã, confirmando o
envio sem problemas eu já faço.

Em 4 de outubro de 2016 19:35, Gustavo Bobrow <notifications@github.com>
escreveu:

**Comment by gustvao** [comment]
o correios deve estar fazendo algum roll out nas agencias e as PLPs lentamente estão ficando problemáticas.. segundo cliente menos de dois dias reclamando que não estão mais conseguindo puxar as PLPs no sistema..

![image](https://cloud.githubusercontent.com/assets/5428331/19120443/1e1ac536-8af9-11e6-8995-e03ad39c3508.png)

**Comment by gustvao** [comment]
@felipez3r0  alguma novidade da postagem?

**Comment by felipez3r0** [comment]
Até agora o pessoal lá ainda não fez os testes para me retornar se está tudo ok.
Segundo meu contato com os correios aquelas mudanças que falei corrigiram os problemas no XML, mas seria interessante alguma encomenda ser despachada confirmando.

Pelo que o Correios me informou, caso a agência não encontrasse a etiqueta mesmo após essas mudanças eles deveriam entrar em contato com o Suporte do Sistema de Postagem para verificarem o motivo da não incorporação.

**Comment by gustvao** [comment]
oi @felipez3r0 , entendi... você pode fazer um PR temporário então, o @stavarengo não aceita o PR, só pra eu ver exatamente os arquivos que você mudou?

Me ajudaria bastante,
Obg

**Comment by felipez3r0** [comment]
@gustvao Pessoal testou e disse que agora foi! Vou enviar um PR com o que precisei mudar ;)
