### ISSUE TITLE
Problemas com rastreio de objeto

### ISSUE THREAD

**Issue by messiahh** [stavarengo/php-sigep#74]
Alguém está conseguindo usar ?

Aqui nem no exemplo faz.

Warning: SimpleXMLElement::__construct() [simplexmlelement.--construct]: Entity: line 1: parser error : Space required after the Public Identifier in ***/php-sigep/src/PhpSigep/Services/Real/RastrearObjeto.php on line 117

**Comment by stavarengo** [comment]
@messiahh , qual o conteúdo deste XML?

**Comment by messiahh** [comment]
Rodeio no arquivo de exemplo. com um codigo real : RD966939915BR e com um que estava no manual de rastreio: SQ458226057BR;

Fui tentar ver o retorno do xml ele esta vindo um html.

Devem ter mudado a api de rastreio. Esse é o retorno:


<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>302 Found</TITLE>
</HEAD><BODY>
<H1>Found</H1>
The document has moved <A HREF="http://www2.correios.com.br/sistemas/rastreamento/">here</A>.<P>
<HR>
<ADDRESS>Apache/1.3.41 Server at 127.0.0.1 Port 80</ADDRESS>
</BODY></HTML>

**Comment by stavarengo** [comment]
Então é isso. Como vc pode ver o servidor do Correios está te respondendo com um 302.
Sabe dizer o porque?

**Comment by gustvao** [comment]
parece que a URL de lá está velha, troquei para a nova que é http://webservice.correios.com.br/service/rastro/Rastro.wsdl e nao funcionou também..

na verdade acho que ela está fora do ar hj pq nem tentando acessar ela via POST direto está retornando algo diferente de 404

```Error 404: java.io.FileNotFoundException: WSWS7147E: O sistema não pôde localizar o terminal para /rastro/Rastro.wsdl.```

Alguem sabe se essa url de rastreio costuma sair do ar?

**Comment by davidalves1** [comment]
Eu também estou tentando via POST e dá o mesmo erro do @gustvao. Creio que o problema seja no WS deles, que não está conseguindo processar a requisição.

**Comment by davidalves1** [comment]
Enviei a correção e um exemplo de uso:
https://github.com/stavarengo/php-sigep/pull/85

**Comment by gustvao** [comment]
@davidalves1 fiz update depois do seu PR e estou recebendo agora erro 500 ao tentar fazer o rastreio..

tá funcionando ceritnho pra voce? alguem mais teve probelmas?

**Comment by davidalves1** [comment]
@gustvao você utilizou o código de teste que eu enviei? Fiz outras correções, então pode atualizar e testar novamente. Tenta com o código que enviei também. Aqui está funcionando.

**Comment by gustvao** [comment]
@davidalves1 não to conseguindo usar ainda. qual arquivo eu uso para restar? rastreamentoDeObjetos.php ou voce tem algum outro exemplo de código para testar?


poderia me passar, por favor?

**Comment by gustvao** [comment]
@davidalves1 ?

**Comment by gustvao** [comment]
@davidalves1 por algum motivo meu servidor nao ta funcionando, da timeout ou 500.. mas rodou local!! orbigado , pode fechar @stavarengo

**Comment by gustvao** [comment]
na verdade, nao consigo configurar nenhum servidor pra nao dar timeout, por algum motivo local nao da// alguem tem algum palpite do que possa ser?

**Comment by gustvao** [comment]
@davidalves1 qual servidor você usa?

**Comment by davidalves1** [comment]
@gustvao Hospedamos a nossa aplicação na Locaweb. Estranho não funcionar no seu servidor, sendo que localmente funciona. Pode ser alguma configuração do PHP.
