### ISSUE TITLE
Melhoria na classe AccessData

### ISSUE THREAD

**Issue by jdgrieco** [stavarengo/php-sigep#75]
@stavarengo cometi um erro básico quando estava setando a classe AccessData para o ambiente de produção:
```php
$accessData = new AccessData();
$accessData->setDiretoria(Diretoria::DIRETORIA_DR_SAO_PAULO);
```
Ai quando tentava gerar etiqueta dava o erro:
Fatal error: Call to a member function getSigla() on a non-object in /var/www/html/vendor/stavarengo/php-sigep/src/PhpSigep/Pdf/Chancela/Sedex2016.php on line 94

Dá para resolver isso fazendo:
```php
public function setDiretoria(\PhpSigep\Model\Diretoria $diretoria)
```
Posso fazer um PR, a não ser que haja alguma objeção

**Comment by stavarengo** [comment]
Com certeza. Ótima ideia.
Precisamos apenas garantir que não vamos quebrar a compatibilidade com versões anteriores.
Sugiro então que seja assim: se receber um inteiro nós criamos o objeto diretoria e se receber um objeto então não faz nada pq já está tudo certo.

Acha que faz sentido?

**Comment by jdgrieco** [comment]
Fica legal, mas aí não dá para fazer por typehinting

Vai ter q fazer a validação no código 

Vou fazer o PR

José D. Grieco

**Comment by stavarengo** [comment]
O type hint a gente coloca no DocBlock do method tipo /* @param
Diretoria|int $diretoria

**Comment by jdgrieco** [comment]
Sim, blz.

É que quando se coloca na chamada do método o PHP já valida.


*José D. Grieco*
11 99294-9636

Em 07-10-2016 12:00, Stavarengo escreveu:
> O type hint a gente coloca no DocBlock do method tipo /* @param
> Diretoria|int $diretoria
>
