### ISSUE TITLE
Chancela e-Sedex sai como Sedex

### ISSUE THREAD

**Issue by jdgrieco** [stavarengo/php-sigep#77]
Finalizei o processo de homologação com os Correios, mas eles fizeram uma ressalva:
Ao gerar etiqueta para o serviço e-Sedex a chancela que aparece é a do Sedex.

Verifiquei no método "_render" das classes PhpSigep\Pdf\CartaoDePostagem2016.php e PhpSigep\Pdf\CartaoDePostagem.php e a geração de chancela está:

```php
case ServicoDePostagem::SERVICE_E_SEDEX_STANDARD:
    $tPosChancela = 3;
    if ($this->layoutSedex === CartaoDePostagem::TYPE_CHANCELA_SEDEX) {
        $chancela = new Sedex($lPosChancela, $tPosChancela, $nomeRemetente, Sedex::SERVICE_SEDEX, $accessData);
    } else {
        $chancela = new Sedex2016($lPosChancela, $tPosChancela, $nomeRemetente, Sedex::SERVICE_SEDEX, $accessData);
    }
    break;
```
acredito que nesse caso deveria ser:

```php
case ServicoDePostagem::SERVICE_E_SEDEX_STANDARD:
    $tPosChancela = 3;
    if ($this->layoutSedex === CartaoDePostagem::TYPE_CHANCELA_SEDEX) {
        $chancela = new Sedex($lPosChancela, $tPosChancela, $nomeRemetente, Sedex::SERVICE_E_SEDEX, $accessData);
    } else {
        $chancela = new Sedex2016($lPosChancela, $tPosChancela, $nomeRemetente, Sedex::SERVICE_E_SEDEX, $accessData);
    }
    break;
```

Então fiz um PR para acertar isso, e também, os serviços Sedex 10, Sedex 12 e Sedex Hoje

**Comment by jdgrieco** [comment]
@stavarengo desculpe lhe incomodar com isso, mas o prazo final para colocar o SIGEP em produção é até 14/10 e preciso que as chancelas esteja de acordo com o que os Correios pediram.

Quando você pode fazer o merge desse PR?

**Comment by stavarengo** [comment]
Pronto.
