### ISSUE TITLE
Fatal error: Class 'FPDF'

### ISSUE THREAD

**Issue by Fertusco** [stavarengo/php-sigep#8]
Estamos tentando usar o sigep porém estamos obtendo erros em relação ao FPDF.

Já baixei a versão 1.7 do FPDF, porém como fazemos para configurar o carregamento automático da classe?

Obrigado.

**Comment by stavarengo** [comment]
Se você usar o composer o autoload será configurado automáticamente, caso
contraŕio, use este código.

> set_include_path(implode(PATH_SEPARATOR, array(
>     realpath('paht-to-fpdf'),
>     get_include_path(),
> )));


2014-12-30 12:54 GMT-02:00 Fertusco <notifications@github.com>:

> Estamos tentando usar o sigep porém estamos obtendo erros em relação ao
> FPDF.
>
> Já baixei a versão 1.7 do FPDF, porém como fazemos para configurar o
> carregamento automático da classe?
>
> Obrigado.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stavarengo/php-sigep/issues/8>.
>



-- 
*Rafael Stavarengo*
stapi.com.br - Linkedin
<http://br.linkedin.com/pub/rafael-stavarengo/1a/338/2a1/>
Skype: rafael.stavarengo

**Comment by Fertusco** [comment]
Isto dentro do Loader.php correto?

Iniciei a homologação, porém coloquei o path para o fpdf dentro do Loader manualmente para que conseguisse realizar os testes. Vou mudar para o seu código.

Outra coisa que estamos com dificuldade é que vamos fechar uma PLP varios servicos, com diversos serviços adicionais estamos obtendo o seguinte erro:

Fatal error: Call to undefined method PhpSigep\Model\ServicoAdicional::SERVICE_VALOR_DECLARADO() in /Applications/XAMPP/xamppfiles/htdocs/sigep/src/PhpSigep/Services/Real/FecharPreListaDePostagem.php on line 267

Segue o código de teste:
```
$servicoAdicional = new \PhpSigep\Model\ServicoAdicional();
    $servicoAdicional->setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_REGISTRO);

    $servicoAdicional2 = new \PhpSigep\Model\ServicoAdicional();
    $servicoAdicional2->setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_AVISO_DE_RECEBIMENTO);

    $servicoAdicional3 = new \PhpSigep\Model\ServicoAdicional();
    $servicoAdicional3->setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_REGISTRO);

    $encomenda = new \PhpSigep\Model\ObjetoPostal();
    $encomenda->setServicosAdicionais(array($servicoAdicional,$servicoAdicional2));
    $encomenda->setDestinatario($destinatario);
    $encomenda->setDestino($destino);
    $encomenda->setDimensao($dimensao);
    $encomenda->setEtiqueta($etiqueta2);
    $encomenda->setPeso(0.500);// 500 gramas
    $encomenda->setServicoDePostagem(new \PhpSigep\Model\ServicoDePostagem(\PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_40096));
```

Se adicionamos apenas o primeiro serviço adicional, a plp fecha sem problemas. Porém, ao colocar mais de um como no exemplo acima, obtemos o erro mencionado.

Isso é problema no WebService de homologação ou estou fazendo algo errado no código?

**Comment by mjescandell** [comment]
Boa tarde, estou passando por um problema parecido, eu instalei atraves do composer, mas ai quando tenho entrar no exemplo de imprimir aparece a seguinte mensagem:

Fatal error: Class 'FPDF' not found in C:\xampp\htdocs\facilitador\vendor\stavarengo\php-sigep\src\PhpSigep\Pdf\ImprovedFPDF.php on line 5

Ai não sei o que pode ser. 

Obrigado!

**Comment by stavarengo** [comment]
​Oi Marcos.
Com o composer você não deveria ter problema de autoload.
Mas caso seu load não esteja funcionando corretamente, você pode usar este
código;
Se você usar o composer o autoload será configurado automáticamente, caso
contraŕio, use este código.

> set_include_path(implode(PATH_SEPARATOR, array(
>     realpath('paht-to-fpdf'),
>     get_include_path(),
> )));

Substitua "paht-to-fpdf" pelo caminho correto para onde está o FDPF.
