### ISSUE TITLE
Meu primeiro codigo não funciona

### ISSUE THREAD

**Issue by WiltonNunes** [stavarengo/php-sigep#89]
Baixei o projeto php-sigep-master aqui no github, descompactei o projeto dentro da pasta '/opt/lampp/htdocs/SigepIntegration' no no servidor local 'xampp' e escrevi a seguinte classe:

<?php
require('php-sigep-master/src/PhpSigep/Bootstrap.php');
require('php-sigep-fpdf-master/PhpSigepFPDF.php');

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
ini_set('error_reporting', 'E_ALL|E_STRICT');
error_reporting(E_ALL);

header('Content-Type: text/html; charset=utf-8');

$autoload = __DIR__ . '/../vendor/autoload.php';
if (file_exists($autoload)) {
    require_once $autoload;
}
if (!class_exists('PhpSigepFPDF')) {
    throw new RuntimeException(
        'Não encontrei a classe PhpSigepFPDF. Execute "php composer.phar install" ou baixe o projeto ' .
        'https://github.com/stavarengo/php-sigep-fpdf manualmente e adicione a classe no seu path.'
    );
}

class SigepConexao {

    function __construct() {
        $accessDataParaAmbienteDeHomologacao = new \PhpSigep\Model\AccessDataHomologacao();

        $config = new \PhpSigep\Config();
        $config->setAccessData($accessDataParaAmbienteDeHomologacao);
        /* $config->setEnv(\PhpSigep\Config::ENV_PRODUCTION); */
        $config->setEnv(\PhpSigep\Config::ENV_DEVELOPMENT);
        /* $config->setWsdlAtendeCliente('AtendeCliente'); */
        $config->setCacheOptions(
            array(
                'storageOptions' => array(
                    'enabled' => false,
                    'ttl' => 10,
                    'cacheDir' => sys_get_temp_dir(),
                ),
            )
        );

        \PhpSigep\Bootstrap::start($config);
    }

    public function calcPrecoPrazo($sCepOrigem, $sCepDestino, $nVlPeso, $nVlAltura, $nVlComprimento, $nVlLargura) {
        $dimensao = new \PhpSigep\Model\Dimensao();
        $dimensao->setTipo(\PhpSigep\Model\Dimensao::TIPO_PACOTE_CAIXA);
        $dimensao->setAltura($nVlAltura);
        $dimensao->setComprimento($nVlComprimento);
        $dimensao->setLargura($nVlLargura);

        $params = new \PhpSigep\Model\CalcPrecoPrazo();
        $params->setAccessData(new \PhpSigep\Model\AccessDataHomologacao());
        $params->setCepOrigem($sCepOrigem);
        $params->setCepDestino($sCepDestino);
        $params->setServicosPostagem(\PhpSigep\Model\ServicoDePostagem::getAll());
        $params->setAjustarDimensaoMinima(true);
        $params->setDimensao($dimensao);
        $params->setPeso($nVlPeso);

        $phpSigep = new PhpSigep\Services\SoapClient\Real();
        $result = $phpSigep->calcPrecoPrazo($params);

        var_dump((array)$result);
    }
}

depois testei ela com o seguinte arquivo:

<?php
require('SigepConexao.php');

$nCdServico = 'SEDEX Varejo';
$sCepOrigem = '59280000';
$sCepDestino = '09760640';
$nVlPeso = 30;
$nCdFormato = 1;
$nVlComprimento = 105;
$nVlAltura = 105;
$nVlLargura = 105;
$nVlDiametro = 200;
$sCdMaoPropria = 'Sim';
$nVlValorDeclarado = 0;
$sCdAvisoRecebimento = 'Sim';

$sigepConexao = new SigepConexao();
$sigepConexao->calcPrecoPrazo($sCepOrigem, $sCepDestino, $nVlPeso, $nVlAltura, $nVlComprimento, $nVlLargura);
?>

dei start no xampp abrir a url 'http://localhost/SigepIntegration/CalcPrecosPrazos.php' e apareceu o seguinte erro:

Fatal error: Call to a member function calcPrecoPrazo() on null in /opt/lampp/htdocs/SigepIntegration/php-sigep-master/src/PhpSigep/Services/Real/CalcPrecoPrazo.php on line 111

executei também o exemplo 'http://localhost/php-sigep-master/exemplos/calcPrecoPrazo.php', e deu o mesmo erro.

Tenho que fazer alguma coisa antes? Me ajudem nessa.

**Comment by stavarengo** [comment]
@WiltonNunes, duplicado com https://github.com/stavarengo/php-sigep/issues/90?
