### ISSUE TITLE
BUG: Fatal error SERVICE_VALOR_DECLARADO()

### ISSUE THREAD

**Issue by Fertusco** [stavarengo/php-sigep#9]
Prezados estou relatando um BUG e forma de corrigí-lo.

Quando solicitamos o método fechaPlpVariosServicos() com o serviço adicional Valor Declarado dentro do objeto, está retornando o seguinte erro:

Fatal error: Call to undefined method PhpSigep\Model\ServicoAdicional::SERVICE_VALOR_DECLARADO() in /Applications/XAMPP/xamppfiles/htdocs/sigep/src/PhpSigep/Services/Real/FecharPreListaDePostagem.php on line 267

No arquivo FecharPreListaDePostagem.php linha 267 o código está assim:
```
                if ($servicoAdicional->getCodigoServicoAdicional() == ServicoAdicional::SERVICE_VALOR_DECLARADO()) {
```

Deve ser alterado para:
```
                if ($servicoAdicional->getCodigoServicoAdicional() == ServicoAdicional::SERVICE_VALOR_DECLARADO) {
```
Com esta correção o serviço adicional AR funcional perfeitamente, mas o Valor declarado continua gerando problema. Segue o array de resposta quando o serviço de valor declarado é passado para no objeto:

```
Array
(
    [*isSoapFault] => 1
    [*errorCode] => 0
    [*errorMsg] => Ocorreu um erro ao interpretar os dados do XML gerado pelo Cliente.
    [*result] => 
    [*soapFault] => 
    [*_failIfAtributeNotExiste] => 1
)
```

**Comment by stavarengo** [comment]
Fertusco, faça um pull request por favor.

**Comment by Fertusco** [comment]
@stavarengo bom dia.

Conseguimos colocar em produção há um mês o SIGEP utilizando sua classes, porém a homologação foi extremamente complicada. Gerou diversos erros durante a homologação o que demandou diversas alterações nos códigos.

Não sei como fazer um PullRequest, portanto vou agrupar todas as alterações que foram necessárias e encaminho para você.

**Comment by stavarengo** [comment]
Obrigado Fertusco.
Pull request é bem mas simples do que agrupar tudo e me mandar ;)
Alem disso vc vai apareceer na lista de colaboradores do projeto.
Se tiver dúvida esse link vai te ajudar
<http://t.signaletre.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1p7-ZxW7gs8101pNv9jW7fsFDW56dKw1f2bXyYM02?t=https%3A%2F%2Fwww.google.com%2Fwebhp%3Fsourceid%3Dchrome-instant%26ion%3D1%26espv%3D2%26ie%3DUTF-8%23q%3Dpull%2520request%2520github&si=6484137984655360&pi=bc9c0fae-d89d-4e1c-dc12-5c539a3d12bd>
.

2015-02-21 4:54 GMT-08:00 Fertusco <notifications@github.com>:

> @stavarengo <https://github.com/stavarengo> bom dia.
>
> Conseguimos colocar em produção há um mês o SIGEP utilizando sua classes,
> porém a homologação foi extremamente complicada. Gerou diversos erros
> durante a homologação o que demandou diversas alterações nos códigos.
>
> Não sei como fazer um PullRequest, portanto vou agrupar todas as
> alterações que foram necessárias e encaminho para você.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stavarengo/php-sigep/issues/9#issuecomment-75370419>.
>



-- 
*Rafael Stavarengo*
stapi.com.br
<http://t.signaletre.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1p7-ZxW7gs8101pNv9jW7fsFDW56dKw1f2bXyYM02?t=http%3A%2F%2Fstapi.com.br%2F&si=6484137984655360&pi=bc9c0fae-d89d-4e1c-dc12-5c539a3d12bd>
-
Linkedin
<http://t.signaletre.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1p7-ZxW7gs8101pNv9jW7fsFDW56dKw1f2bXyYM02?t=http%3A%2F%2Fbr.linkedin.com%2Fpub%2Frafael-stavarengo%2F1a%2F338%2F2a1%2F&si=6484137984655360&pi=bc9c0fae-d89d-4e1c-dc12-5c539a3d12bd>
Skype: rafael.stavarengo

**Comment by endel** [comment]
Hey @Fertusco,

Já rolou pull-request desse problema aqui: https://github.com/stavarengo/php-sigep/pull/10/files

**Comment by stavarengo** [comment]
Verdade @endel. 
Estou fechando esse bug.
Obrigado pessoal.
