### ISSUE TITLE
Erro ao executar o projeto no xampp.

### ISSUE THREAD

**Issue by WiltonNunes** [stavarengo/php-sigep#90]
Acabei de baixar o projeto, descompactei ele na pasta htdocs do meu servidor local xampp, executei o exemplo calcPrecoPrazo.php, e ocorreu o seguinte erro:

Fatal error: Call to a member function calcPrecoPrazo() on null in /opt/lampp/htdocs/php-sigep-master/src/PhpSigep/Services/Real/CalcPrecoPrazo.php on line 111

Tenho que fazer alguma coisa antes?

**Comment by davidalves1** [comment]
@WiltonNunes acho que este problema tem relação com [este pull request.](https://github.com/stavarengo/php-sigep/pull/88 "https://github.com/stavarengo/php-sigep/pull/88") 
Temporariamente você pode tentar corrigir este problema alterando o arquivo src/PhpSigep/Services/Real/SoapClientFactory.php na linha 85, onde está ```self::$_soapClient``` você coloca  ```self::$_soapCalcPrecoPrazo```. Isso deve resolver.

**Comment by stavarengo** [comment]
PR mesclado. Isso fecha este erro?

**Comment by davidalves1** [comment]
Eu utilizo o WAMP, mas estava com o mesmo erro. Nos testes que realizei aqui resolveu o problema sim.

**Comment by davidalves1** [comment]
@WiltonNunes após a atualização seu problema foi resolvido?

**Comment by WiltonNunes** [comment]
Sim foi ressolvido, obrigado.
