### ISSUE TITLE
Erro ao tentar criar a PLP em PDF.

### ISSUE THREAD

**Issue by WiltonNunes** [stavarengo/php-sigep#92]
Seguir os exemplos do projeto e escrevi o codigo abaixo:

$plp = new \PhpSigep\Model\PreListaDePostagem();
$plp->setAccessData(new \PhpSigep\Model\AccessDataHomologacao());
$plp->setEncomendas(array($encomenda));
$plp->setRemetente($remetente);

$pdf  = new \PhpSigep\Pdf\ListaDePostagem($plp, time());
$pdf->render($plp);

Porem ele retorna o seguinte erro:

Warning: strtoupper() expects parameter 1 to be string, object given in /opt/lampp/htdocs/SigepIntegration/php-sigep-fpdf-master/fpdf.php on line 988
FPDF error: Some data has already been output, can't send PDF file

**Comment by gustvao** [comment]
tenta assim:
```php
$pdf  = new \PhpSigep\Pdf\ListaDePostagem($params, $last_plp);
$pdf_string = $pdf->render('S');      
```

**Comment by mozgbrasil** [comment]
Ola

Boa Tarde meus amigos

-

Na execução do script

https://github.com/stavarengo/php-sigep/blob/master/exemplos/imprimirPlp.php

Vemos conforme imagens o erro

FPDF error: Some data has already been output, can't send PDF file

![captura de tela de 2017-02-01 18-46-47](https://cloud.githubusercontent.com/assets/17202780/22525809/f748fea4-e8af-11e6-85e8-8749da5d40a9.png)
![captura de tela de 2017-02-01 18-47-33](https://cloud.githubusercontent.com/assets/17202780/22525810/f74d1eda-e8af-11e6-8d44-4c23c0750263.png)


-

Isolei o seguinte script

https://github.com/mozgbrasil/php-sigep/blob/master/exemplos/stavarengo_php_sigep_relatorios_pdf.php

Com base no script

https://github.com/stavarengo/php-sigep/blob/gh-pages/site/php/actions/relatorios-pdf.php

Veja que a geração da etiqueta funciona como esperado

Caso eu altere no script a variavel "$relatorio=" para tentar gerar a PLP é retornado o erro

Warning: fopen(): Filename cannot be empty in /vendor/stavarengo/php-sigep-fpdf/fpdf.php on line 1025

FPDF error: Unable to create output file: 

![captura de tela de 2017-02-01 18-47-37](https://cloud.githubusercontent.com/assets/17202780/22525817/fd0c2bea-e8af-11e6-9de1-6a953ef77e2d.png)
![captura de tela de 2017-02-01 18-49-24](https://cloud.githubusercontent.com/assets/17202780/22525818/fd0d7af4-e8af-11e6-830d-dfdc0aefa778.png)


-

**Comment by stavarengo** [comment]
@mozgbrasil acredito que o problemas são os warnings. Eles estão sendo impresso antes de vc tentar enviar o PDF para o buffer, causando o erro que vc mostrou. 

Quando ao segundo erro "Warning: fopen(): Filename cannot be empty in /vendor/stavarengo/php-sigep-fpdf/fpdf.php on line 1025"

Vc colcou o nome da variavel vazia eh isso? Se for, esse é o problema.
Caso queira, coloque uma validação que estoura uma exceção caso o nome do arquivo seja vazio e suba como PR que eu faço o merge.

**Comment by mozgbrasil** [comment]
Bom dia

-

Veja nas imagens o passo a passo que estou usando para uso da biblioteca

-

Veja que estou usando o composer

-

Sobre o uso do exemplo "/vendor/stavarengo/php-sigep/exemplos/imprimirEtiquetas2016.php"

Na execução do exemplo via browser, vemos que é gerado erro relativo ao apontamento do autoload

Fiz a correção, alterando para a seguinte variavel

	$autoload = dirname(dirname(dirname(dirname(__FILE__)))) . '/autoload.php';

Na execução do exemplo via browser, foi gerado erro de perimissão

Fiz a correção

Na execução do exemplo via browser, foi exibido uma tela branca, onde temos o devido arquivo de etiqueta na pasta do exemplo, 

Funcionando como esperado

-

Sobre o uso do exemplo "/vendor/stavarengo/php-sigep/exemplos/imprimirPlp.php"

Na execução do exemplo via browser, vemos que é gerado o seguinte erro 


Warning: strtoupper() expects parameter 1 to be string, object given in /home/marcio/dados/public_html/test/03022017/vendor/stavarengo/php-sigep-fpdf/fpdf.php on line 988

FPDF error: Some data has already been output, can't send PDF file


-

Veja que alterei no arquivo "/vendor/stavarengo/php-sigep/exemplos/imprimirPlp.php" para

	$pdf->render('I');

Que funcionou

Tentei outra opção como

	$pdf->render('F', 'etiquetas.pdf');

Mas é gerado erro usando essa ultima

-

Acabo de enviar um PR sobre essa alteração no arquivo "/vendor/stavarengo/php-sigep/exemplos/imprimirPlp.php" 

https://github.com/stavarengo/php-sigep/pull/106

-

![animation_2017-02-03_11-26-49](https://cloud.githubusercontent.com/assets/17202780/22593324/17348b38-ea05-11e6-9e9a-b16a490e0c47.gif)
