### ISSUE TITLE
Erro ao tentar enviar o xml da PLP para os correios.

### ISSUE THREAD

**Issue by WiltonNunes** [stavarengo/php-sigep#93]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /opt/lampp/htdocs/SigepIntegration/php-sigep-master/src/PhpSigep/Model/Etiqueta.php on line 65

**Comment by andersonls** [comment]
@WiltonNunes Você setou a etiqueta (método setEtiquetaComDv ou setEtiquetaSemDv)? A execução tá demorando? Me parece que teu código entrou em loop.

@stavarengo Será que não vale um ticket pra corrigir isso? A implementação pode gerar um loop se a etiqueta não for setada antes de chamar o get, já que o getEtiquetaComDv chama o getEtiquetaSemDv e o getEtiquetaSemDv chama o getEtiquetaComDv.

**Comment by WiltonNunes** [comment]
Já resolvi esse erro, obrigado.
Postei outro erro logo acima, se puder ajudar.

**Comment by stavarengo** [comment]
@WiltonNunes vc pode mandar sua correção como PR?

**Comment by criacaosites** [comment]
WilsonNunes como você resolveu esse problema
