### ISSUE TITLE
Erro ao tentar rastrear objeto

### ISSUE THREAD

**Issue by WiltonNunes** [stavarengo/php-sigep#94]
Rodei o exemplo de rastreamentoDeObjetos.php, e ocorreu o erro abaixo:

Notice: Trying to get property of non-object in /opt/lampp/htdocs/php-sigep-master/src/PhpSigep/Services/Real/RastrearObjeto.php on line 95

Notice: Trying to get property of non-object in /opt/lampp/htdocs/php-sigep-master/src/PhpSigep/Services/Real/RastrearObjeto.php on line 96

Notice: Trying to get property of non-object in /opt/lampp/htdocs/php-sigep-master/src/PhpSigep/Services/Real/RastrearObjeto.php on line 97

Notice: Trying to get property of non-object in /opt/lampp/htdocs/php-sigep-master/src/PhpSigep/Services/Real/RastrearObjeto.php on line 97

Catchable fatal error: Argument 1 passed to PhpSigep\Model\RastrearObjetoEvento::setDataHora() must be an instance of DateTime, boolean given, called in /opt/lampp/htdocs/php-sigep-master/src/PhpSigep/Services/Real/RastrearObjeto.php on line 97 and defined in /opt/lampp/htdocs/php-sigep-master/src/PhpSigep/Model/RastrearObjetoEvento.php on line 93

O mesmo erro está ocorrendo no codigo que escrevi, a etiqueta que usei funciona no rastreamento do site dos correios, logo o problema não é com a etiqueta.

**Comment by davidalves1** [comment]
Boa tarde @WiltonNunes. Enviei uma correção, creio que pode resolver o seu problema. Dá uma olhada na descrição do pull request.
