### ISSUE TITLE
Serviço adicional

### ISSUE THREAD

**Issue by entchucs** [stavarengo/php-sigep#97]
Como faço para adicionar múltiplos serviços adicionais?

Por exemplo:

$servicoAdicional->setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_AVISO_DE_RECEBIMENTO);
$servicoAdicional->setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_MAO_PROPRIA);

**Comment by gustvao** [comment]
@entchucs você respondeu sua própria pergunta?

**Comment by entchucs** [comment]
Me expressei mal/.
Eu tentei dessa forma mas não funciona.

**Comment by gustvao** [comment]
eu fiz assim:

```php
$servicoAdicional = new \PhpSigep\Model\ServicoAdicional();
  $servicoAdicional->setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_REGISTRO);
  
  $servicoAdicional->setCodigoServicoAdicional(\PhpSigep\Model\ServicoAdicional::SERVICE_VALOR_DECLARADO);
$servicoAdicional->setValorDeclarado($valor_declarado);
```

**Comment by entchucs** [comment]
Agora tenta adicionar o AR e o MP...
Só vai pegar o último que você declarar.

Eu resolvi declarando a variável como array e modificando a leitura dessas variáveis nas integrações.

Grato pela atenção.

**Comment by gustvao** [comment]
@entchucs faz um PR com sua sugestão de código que pode ajudar alguém no futuro, pode ser?

**Comment by relpcam** [comment]
Queria saber como o @wcm3web  resolveu essa questão. Atualmente estou tendo o mesmo problema onde sempre pega o último valor inserido na variável.
