### ISSUE TITLE
Logistica reversa

### ISSUE THREAD

**Issue by Cadselfs** [stavarengo/php-sigep#99]
Boa tarde! 

Qual o endereço correto do webservice de logistica reversa? No manual disponível o usuario de teste indicado não funciona!

E em outro manual que os correios me disponibilizaram o endereço está diferente do seu manual veja:
http://webservicescolhomologacao.correios.com.br/ScolWeb/WebServiceScol?wsdl

com o mesmo usuario que também não funciona! Poderia me ajudar?

Obrigado , Feliz 2017!
Edgard

**Comment by Cadselfs** [comment]
Qual o endereço correto do webservice de logística reversa?

1  -  http://webservicescolhomologacao.correios.com.br/ScolWeb/WebServiceScol?wsdl

ou 

2  -  https://apphom.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl

**Comment by joubertvasc** [comment]
Sei que a conversa é antiga, mas alguém já conseguiu fazer isso funcionar? Estou com problemas para conseguir informações sobre esse WS. Alguém sabe ao menos onde encontro a documentação oficial?

**Comment by luiz-merante** [comment]
@joubertvasc eu também estou com dificuldades, com o ws de homolog faz normalmente e gera o numero de coleta, já com o ws de produção, ele não gera e da o seguinte erro 
PhpSigep\Services\Result Object
(
[isSoapFault] => 1
[errorCode] => 0
[errorMsg] => SOAP-ERROR: Parsing WSDL: Couldn't load from
'https://cws.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl' : failed to load
external entity "https://cws.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl"

[result] =>
[soapFault] =>
[_failIfAtributeNotExiste:protected] => 1
)

**Comment by luiz-merante** [comment]
@stavarengo @gustvao poderíam nos ajudar quanto a isso?

**Comment by tdias25** [comment]
Também estou no mesmo barco, isso acontece quando eu altero para produção, eu só altero o contrato e isso:

`$config->setEnv(\PhpSigep\Config::ENV_PRODUCTION, 1);`

Seria assim mesmo?

**Comment by rodrigojob** [comment]
Lamento não ter lido isso antes.
Para mim está funcional. Se alguém precisar reative a discussão

**Comment by Daniellviana** [comment]
Pessoal,
pra mim está dando o problema ainda. Quando eu tento acessar a url pelo navegador pede usuário e senha.
Mais alguem com esse problema?

PhpSigep\Services\Result Object
(
    [isSoapFault:protected] => 1
    [errorCode:protected] => 0
    [errorMsg:protected] => SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://apphom.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl' : failed to load external entity "https://apphom.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl"

    [result:protected] => 
    [soapFault:protected] => 
    [_failIfAtributeNotExiste:protected] => 1
)

**Comment by rodrigojob** [comment]
> Pessoal,
> pra mim está dando o problema ainda. Quando eu tento acessar a url pelo navegador pede usuário e senha.
> Mais alguem com esse problema?
> 
> PhpSigep\Services\Result Object
> (
> [isSoapFault:protected] => 1
> [errorCode:protected] => 0
> [errorMsg:protected] => SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://apphom.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl' : failed to load external entity "https://apphom.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS?wsdl"
> 
> ```
> [result:protected] => 
> [soapFault:protected] => 
> [_failIfAtributeNotExiste:protected] => 1
> ```
> 
> )

É normal ele pedir o usuário e senha, na criação do objeto do php-sigep você deve passar estes parâmentros

**Comment by joaovds** [comment]
Alguém conseguiu??? Estou com o mesmo problema nesse web service 👀
